import { CATEGORIES, DESIGNS } from '@/catalog';
import { num, type Locale } from './i18n';

// The library's own words. Demo content lives in src/catalog/profiles.

type Noun = { one: string; two: string; few: string; many: string };
const designsAr: Noun = { one: 'تصميم', two: 'تصميمان', few: 'تصاميم', many: 'تصميمًا' };
const stylesAr: Noun = { one: 'صنف', two: 'صنفان', few: 'أصناف', many: 'صنفًا' };

/** An Arabic count, the noun in the form its number takes: ٣ تصاميم, ١٢ تصميمًا, ١٠٠ تصميم. */
export function arCount(n: number, noun: Noun): string {
  if (n === 1) return `${noun.one} واحد`;
  if (n === 2) return noun.two;
  const r = n % 100;
  return `${num(n, 'ar')} ${r >= 3 && r <= 10 ? noun.few : r >= 11 ? noun.many : noun.one}`;
}

const D = DESIGNS.length;
const S = CATEGORIES.length;

export const copy = {
  ar: {
    name: 'قالب',
    latin: 'Qalib',
    title: 'قالب · مكتبة تصاميم مواقع مع برومبت جاهز لـ Claude Code',
    description: `${arCount(D, designsAr)} للمواقع في ${arCount(S, stylesAr)}، بالعربية والإنجليزية. شاهد كل تصميم حيًا، صف مشروعك، وانسخ برومبت مفصّلًا يبني به Claude Code موقعك بالأسلوب نفسه.`,
    nav: { designs: 'التصاميم', styles: 'الأصناف', how: 'كيف يعمل' },
    switchTo: 'English',
    switchShort: 'EN',
    kicker: (d: string, s: string) => `مكتبة تصاميم مواقع · ${d} تصميمًا · ${s} صنفًا`,
    heroTitle: ['اختر', 'شكل', 'موقعك القادم'],
    heroLead: 'تصاميم حقيقية بالعربية والإنجليزية: كلاسيكي، قديم، عصري، متحرك، تراثي، رقمي وغيرها. اختر ما يعجبك، صف مشروعك في سطرين، وانسخ برومبت مفصّلًا يبني به Claude Code موقعك بالأسلوب نفسه.',
    search: 'ابحث: مطعم، فاخر، داكن، متحرك…',
    browse: 'تصفّح التصاميم',
    howCta: 'كيف يعمل؟',
    howTitle: 'من الفكرة إلى الموقع في ثلاث خطوات',
    how: [
      { t: 'اختر تصميمًا', d: 'تصفّح العروض الحية على الحاسوب والجوال، بالعربية والإنجليزية، حتى تجد الطابع الذي يناسب مشروعك.' },
      { t: 'صف مشروعك', d: 'اسم النشاط، نوعه، اللغات والتقنية التي تفضلها. نحفظها في متصفحك لتنتقل بها بين التصاميم.' },
      { t: 'انسخ البرومبت', d: 'برومبت مفصّل فيه الألوان والخطوط وبنية كل قسم والحركة وقواعد العربية، ورابط العرض المرجعي. ألصقه في Claude Code.' },
    ],
    stylesTitle: `${arCount(S, stylesAr)}، ولكل صنف شخصيته`,
    stylesLead: 'كل صنف أسلوب كامل بخطوطه وألوانه وأشكاله وحركته، وفيه تصاميم لأنشطة مختلفة.',
    designsCount: (n: number) => arCount(n, designsAr),
    allTitle: 'كل التصاميم',
    filters: { all: 'الكل', style: 'الصنف', type: 'نوع الموقع', anyType: 'كل الأنواع', scheme: 'الألوان', any: 'الكل', light: 'فاتح', dark: 'داكن', animated: 'متحرك فقط', favs: 'المفضلة', clear: 'مسح', results: (n: number) => `${n} تصميمًا` },
    empty: 'لا تصاميم تطابق هذا البحث. جرّب كلمة أخرى أو امسح الفلاتر.',
    fav: 'أضف إلى المفضلة',
    unfav: 'أزل من المفضلة',
    open: 'افتح',
    view: 'شاهد التصميم',
    fontsLabel: 'الخطوط',
    crumbsHome: 'قالب',
    demoOf: 'عرض لـ',
    openDemo: 'افتح العرض الحي',
    copyPrompt: 'انسخ البرومبت',
    preview: { desktop: 'حاسوب', tablet: 'لوحي', phone: 'جوال', language: 'لغة العرض', loading: 'يُحمَّل العرض…', newTab: 'في نافذة جديدة' },
    dna: { title: 'روح التصميم', palette: 'الألوان', copyHex: 'انقر لنسخ الرمز', copied: 'نُسخ', fonts: 'الخطوط', motion: 'الحركة', sections: 'الأقسام', radius: 'الزوايا' },
    roles: { bg: 'الخلفية', surface: 'البطاقات', ink: 'النص', muted: 'نص ثانوي', accent: 'الإبراز', accent2: 'إبراز ثانٍ', line: 'الخطوط', onAccent: 'نص فوق الإبراز' },
    motion: { calm: 'هادئة', subtle: 'خفيفة', lively: 'حيوية', rich: 'غنية' },
    prompt: {
      title: 'البرومبت',
      lead: 'صف مشروعك ويتحدّث البرومبت فورًا. ما تكتبه يُحفظ في متصفحك فقط.',
      brief: 'مشروعك',
      name: 'اسم النشاط أو المشروع',
      namePh: 'مثلًا: مطعم دار سلمى',
      type: 'نوع الموقع',
      typeNone: 'اختر…',
      typeOther: 'نوع آخر',
      typeOtherPh: 'مثلًا: حضانة أطفال',
      description: 'عن النشاط',
      descriptionPh: 'ماذا يقدّم، لمن، وأين؟',
      languages: 'اللغات',
      langAr: 'عربي', langEn: 'إنجليزي', langBoth: 'الاثنتان',
      pages: 'الصفحات',
      pagesOne: 'صفحة واحدة', pagesMulti: 'عدة صفحات',
      stack: 'التقنية',
      contact: 'بيانات التواصل',
      contactPh: 'الهاتف، واتساب، البريد، العنوان',
      assets: 'عندي شعار وصور في مجلد assets',
      notes: 'ملاحظات إضافية',
      notesPh: 'أي شيء آخر: ألوان العلامة، أقسام خاصة، حجز…',
      outLang: 'لغة البرومبت',
      css: 'أرفق CSS المرجعي كاملًا',
      cssHint: 'يطيل البرومبت، لكنه يعطي Claude كل القيم بدقة.',
      copy: 'انسخ البرومبت',
      copied: 'نُسخ ✓',
      chars: '{n} حرفًا',
      reset: 'مسح الحقول',
      pasteHint: 'ألصقه في Claude Code داخل مجلد مشروع جديد.',
    },
    prev: 'السابق',
    next: 'التالي',
    more: (s: string) => `تصاميم أخرى من «${s}»`,
    otherStyles: 'أصناف أخرى',
    styleDna: 'ما يميّز هذا الصنف',
    dnaLabels: { type: 'الخطوط', color: 'الألوان', layout: 'التخطيط', shape: 'الأشكال', imagery: 'الصور', motion: 'الحركة', details: 'التفاصيل', avoid: 'تجنّب' },
    footer: {
      about: 'مكتبة تصاميم مواقع بالعربية والإنجليزية، مع برومبت جاهز لـ Claude Code لكل تصميم.',
      by: 'صنعه',
      author: 'عمر الديك',
      photos: 'الصور من Unsplash عبر Lorem Picsum. كل الأنشطة في العروض وهمية.',
      more: 'من أعمالي أيضًا',
    },
    notFound: 'هذه الصفحة غير موجودة.',
    backHome: 'العودة إلى المكتبة',
  },
  en: {
    name: 'Qalib',
    latin: 'قالب',
    title: 'Qalib · a library of website designs with ready Claude Code prompts',
    description: `${D} website designs in ${S} styles, in Arabic and English. See every design live, describe your project and copy a detailed prompt that has Claude Code build your site in the same style.`,
    nav: { designs: 'Designs', styles: 'Styles', how: 'How it works' },
    switchTo: 'العربية',
    switchShort: 'ع',
    kicker: (d: string, s: string) => `Website design library · ${d} designs · ${s} styles`,
    heroTitle: ['Choose the', 'look', 'of your next website'],
    heroLead: 'Real designs in Arabic and English: classic, vintage, modern, animated, heritage, digital and more. Pick one you like, describe your project in two lines, and copy a detailed prompt that has Claude Code build your site in the same style.',
    search: 'Search: restaurant, luxury, dark, animated…',
    browse: 'Browse the designs',
    howCta: 'How does it work?',
    howTitle: 'From idea to website in three steps',
    how: [
      { t: 'Pick a design', d: 'Browse the live demos on desktop and phone, in Arabic and English, until you find the character your project needs.' },
      { t: 'Describe your project', d: 'Its name, type, languages and preferred stack. It stays in your browser and follows you from design to design.' },
      { t: 'Copy the prompt', d: 'A detailed prompt with the colours, fonts, every section\'s treatment, motion, Arabic rules and the reference demo. Paste it into Claude Code.' },
    ],
    stylesTitle: `${S} styles, each with its own character`,
    stylesLead: 'Every style is a complete language of type, colour, shape and motion, with designs for different kinds of business.',
    designsCount: (n: number) => `${n} designs`,
    allTitle: 'All designs',
    filters: { all: 'All', style: 'Style', type: 'Type of site', anyType: 'Any type', scheme: 'Colours', any: 'Any', light: 'Light', dark: 'Dark', animated: 'Animated only', favs: 'Favourites', clear: 'Clear', results: (n: number) => `${n} designs` },
    empty: 'No designs match. Try another word or clear the filters.',
    fav: 'Add to favourites',
    unfav: 'Remove from favourites',
    open: 'Open',
    view: 'View the design',
    fontsLabel: 'Fonts',
    crumbsHome: 'Qalib',
    demoOf: 'Demo for',
    openDemo: 'Open the live demo',
    copyPrompt: 'Copy the prompt',
    preview: { desktop: 'Desktop', tablet: 'Tablet', phone: 'Phone', language: 'Demo language', loading: 'Loading the demo…', newTab: 'In a new tab' },
    dna: { title: 'Design DNA', palette: 'Colours', copyHex: 'Click to copy the code', copied: 'Copied', fonts: 'Fonts', motion: 'Motion', sections: 'Sections', radius: 'Corners' },
    roles: { bg: 'Background', surface: 'Cards', ink: 'Text', muted: 'Muted', accent: 'Accent', accent2: 'Accent 2', line: 'Lines', onAccent: 'On accent' },
    motion: { calm: 'Calm', subtle: 'Subtle', lively: 'Lively', rich: 'Rich' },
    prompt: {
      title: 'The prompt',
      lead: 'Describe your project and the prompt updates as you type. What you write stays in your browser.',
      brief: 'Your project',
      name: 'Business or project name',
      namePh: 'e.g. Dar Salma restaurant',
      type: 'Type of site',
      typeNone: 'Choose…',
      typeOther: 'Something else',
      typeOtherPh: 'e.g. a nursery',
      description: 'What it does',
      descriptionPh: 'What it offers, for whom, and where?',
      languages: 'Languages',
      langAr: 'Arabic', langEn: 'English', langBoth: 'Both',
      pages: 'Pages',
      pagesOne: 'One page', pagesMulti: 'Several pages',
      stack: 'Stack',
      contact: 'Contact details',
      contactPh: 'Phone, WhatsApp, email, address',
      assets: 'I have a logo and photos in an assets folder',
      notes: 'Extra notes',
      notesPh: 'Anything else: brand colours, special sections, bookings…',
      outLang: 'Prompt language',
      css: 'Attach the full reference CSS',
      cssHint: 'Makes the prompt longer, but gives Claude every value exactly.',
      copy: 'Copy the prompt',
      copied: 'Copied ✓',
      chars: '{n} characters',
      reset: 'Clear the fields',
      pasteHint: 'Paste it into Claude Code inside a new project folder.',
    },
    prev: 'Previous',
    next: 'Next',
    more: (s: string) => `More ${s} designs`,
    otherStyles: 'Other styles',
    styleDna: 'What defines this style',
    dnaLabels: { type: 'Typography', color: 'Colour', layout: 'Layout', shape: 'Shapes', imagery: 'Imagery', motion: 'Motion', details: 'Details', avoid: 'Avoid' },
    footer: {
      about: 'A library of website designs in Arabic and English, with a ready Claude Code prompt for every design.',
      by: 'Made by',
      author: 'Omar Aldeek',
      photos: 'Photos from Unsplash via Lorem Picsum. Every business in the demos is fictional.',
      more: 'More of my work',
    },
    notFound: 'This page does not exist.',
    backHome: 'Back to the library',
  },
};

export type Copy = (typeof copy)['ar'];
export const t = (locale: Locale): Copy => copy[locale] as Copy;
