import type { Category, CategoryId, Layout } from './types';

// The styles. Each one's DNA is written to be pasted into a prompt
// as is, so it says concretely what to do and what to avoid.

const base: Layout = {
  nav: 'bar', hero: 'split', about: 'split', quotes: 'cards', contact: 'split', cta: 'band', footer: 'columns', stats: 'row',
  offer: 'cards', gallery: 'gallery', pricing: 'pricing', process: 'steps', schedule: 'timeline', extra: 'cards',
};
const layout = (overrides: Partial<Layout>): Layout => ({ ...base, ...overrides });

export const CATEGORIES: Category[] = [
  {
    id: 'classic',
    name: { ar: 'كلاسيكي', en: 'Classic' },
    tagline: { ar: 'وقار الخطوط المذيّلة والتماثل', en: 'Serif dignity and symmetry' },
    description: {
      ar: 'تصميم هادئ وواثق: خطوط مذيّلة، تكوينات متماثلة، خطوط فاصلة رفيعة وزخارف صغيرة. يناسب من يريد أن يبدو عريقًا وموثوقًا.',
      en: 'Calm and assured: serif type, symmetrical compositions, hairline rules and small ornaments. For businesses that want to look established and trustworthy.',
    },
    dna: {
      type: { ar: 'عناوين بخط مذيّل عالي التباين وبأحجام كبيرة، ونص بخط مذيّل للقراءة، وعناوين صغيرة فوق العناوين بأحرف لاتينية كبيرة متباعدة.', en: 'High-contrast serif headings set large, a readable serif for text, and small letter-spaced capitals for eyebrows (Latin only).' },
      color: { ar: 'خلفية عاجية أو ورقية، حبر داكن دافئ، ولون رئيسي عميق واحد (عنابي أو كحلي أو أخضر غامق) مع ذهبي خافت للخطوط.', en: 'Ivory or paper background, warm dark ink, one deep accent (burgundy, navy or forest green) and a muted gold for rules.' },
      layout: { ar: 'أقسام متمركزة بعرض محدود، مسافات سخية، عناوين في الوسط، وشبكة من عمودين على الأكثر.', en: 'Centred sections with a restrained measure, generous spacing, centred headings and at most two-column grids.' },
      shape: { ar: 'زوايا حادة، إطارات مزدوجة رفيعة حول الصور والبطاقات، أزرار مستطيلة بحدود رفيعة.', en: 'Square corners, thin double frames around images and cards, rectangular buttons with hairline borders.' },
      imagery: { ar: 'صور دافئة بإضاءة طبيعية داخل إطار بهامش داخلي (passe-partout).', en: 'Warm, naturally lit photographs inside a framed mat (passe-partout).' },
      motion: { ar: 'ظهور ناعم بالتلاشي عند التمرير فقط، بلا حركات لافتة.', en: 'Only soft fade-ins on scroll; nothing flashy.' },
      details: { ar: 'فواصل زخرفية صغيرة (❦) بين الأقسام، أرقام لاتينية قديمة الطراز، تواقيع بخط مائل.', en: 'Small fleuron dividers (❦) between sections, old-style numerals, italic signatures.' },
      avoid: { ar: 'التدرجات اللونية، الظلال الكبيرة، الزوايا الدائرية، الألوان الفاقعة.', en: 'Gradients, large shadows, rounded corners, saturated colours.' },
    },
    defaults: layout({ nav: 'center', hero: 'framed', about: 'quote', quotes: 'single', offer: 'list' }),
    motion: 'subtle', radius: 0,
    tile: { bg: '#F4EEE1', ink: '#2A1E17', accent: '#7A1F2B', font: 'cormorant-garamond', fontAr: 'amiri' },
  },
  {
    id: 'vintage',
    name: { ar: 'قديم', en: 'Vintage' },
    tagline: { ar: 'ورق معتّق وطباعة حروف وأختام', en: 'Aged paper, letterpress and stamps' },
    description: {
      ar: 'روح المحلات القديمة والمطابع: ورق معتّق، خطوط عرض كبيرة، شارات دائرية، تذاكر وملصقات، وصور بلون السيبيا.',
      en: 'The spirit of old shops and print houses: aged paper, big display type, round badges, tickets and labels, and sepia photographs.',
    },
    dna: {
      type: { ar: 'خط عرض عريض بطابع قديم للعناوين، وخط آلة كاتبة للتفاصيل الصغيرة، وخط مذيّل كلاسيكي للنص.', en: 'A heavy display face with period character for headings, a typewriter face for small details, a classic serif for text.' },
      color: { ar: 'ورق بلون الكريم أو البيج مع نسيج حبيبي، حبر بني داكن، وأحمر طباعة أو أزرق حبر كلون مميز.', en: 'Cream or beige paper with grain, dark brown ink, and a printer\'s red or ink blue as the accent.' },
      layout: { ar: 'تكوينات متمركزة كالملصقات، عناوين داخل شرائط وشارات، أقسام مفصولة بخطوط متقطعة.', en: 'Poster-like centred compositions, headings inside ribbons and badges, sections divided by dashed rules.' },
      shape: { ar: 'بطاقات كالتذاكر بزوايا مقصوصة، حدود متقطعة، شارات دائرية، صور بإطار أبيض كالصور القديمة مائلة قليلًا.', en: 'Ticket cards with notched corners, dashed borders, round badges, photos with white borders like old prints, slightly tilted.' },
      imagery: { ar: 'صور بلون السيبيا أو بالأبيض والأسود مع حبيبات وتعتيم للأطراف.', en: 'Sepia or black-and-white photographs with grain and a vignette.' },
      motion: { ar: 'أقل ما يمكن: ظهور هادئ، وختم يهبط على الصفحة مرة واحدة.', en: 'Minimal: quiet reveals and one stamp that lands on the page.' },
      details: { ar: 'نسيج ورق خفيف على الخلفية، أختام بتاريخ التأسيس، أرقام داخل دوائر، نجوم ✦ بين العناصر.', en: 'Light paper texture, "established" stamps, numbers in circles, ✦ stars between elements.' },
      avoid: { ar: 'الأبيض النقي، الزجاج والتدرجات العصرية، الخطوط الهندسية الحديثة.', en: 'Pure white, glass and modern gradients, geometric modern sans faces.' },
    },
    defaults: layout({ nav: 'center', hero: 'centered', contact: 'card', footer: 'simple', offer: 'list' }),
    motion: 'calm', radius: 2,
    tile: { bg: '#EADFC8', ink: '#3B2A1E', accent: '#B5452B', font: 'rye', fontAr: 'rakkas' },
  },
  {
    id: 'modern',
    name: { ar: 'عصري', en: 'Modern' },
    tagline: { ar: 'خطوط جريئة ومساحات واسعة وبطاقات ناعمة', en: 'Bold sans, wide space, soft cards' },
    description: {
      ar: 'الشكل الذي تتوقعه من شركة ناشئة واثقة: خطوط بلا تذييل جريئة، مساحات بيضاء واسعة، بطاقات بزوايا دائرية، ولون واحد قوي.',
      en: 'What you expect from a confident young company: bold sans-serif type, wide white space, rounded cards and one strong colour.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل هندسي أو إنساني بأوزان ثقيلة للعناوين وكبيرة جدًا، ووزن عادي للنص، مع تباعد أسطر مريح.', en: 'A geometric or humanist sans in heavy weights for very large headings, regular weight for text, comfortable line height.' },
      color: { ar: 'خلفية بيضاء أو رمادية فاتحة جدًا، حبر شبه أسود، ولون مميز واحد مشبع (أزرق، أخضر ليموني، تركواز) يستخدم بقلة.', en: 'White or very light grey background, near-black ink and one saturated accent (blue, lime, teal) used sparingly.' },
      layout: { ar: 'شبكة من 12 عمودًا، تكوينات غير متماثلة، شبكات بينتو، أقسام بعرض كامل تتناوب مع أقسام ضيقة.', en: '12-column grid, asymmetric compositions, bento grids, full-width sections alternating with narrow ones.' },
      shape: { ar: 'زوايا دائرية كبيرة (16–24px)، أزرار على شكل حبة، ظلال ناعمة جدًا أو حدود رفيعة.', en: 'Large radii (16–24px), pill buttons, very soft shadows or thin borders.' },
      imagery: { ar: 'صور نظيفة ساطعة بزوايا دائرية، أو رسومات بسيطة بألوان العلامة.', en: 'Clean bright photos with rounded corners, or simple illustrations in brand colours.' },
      motion: { ar: 'ظهور تدريجي عند التمرير، ارتفاع خفيف للبطاقات عند المرور، انتقالات قصيرة (200–300ms).', en: 'Staggered reveals on scroll, a slight lift on card hover, short transitions (200–300ms).' },
      details: { ar: 'شارات صغيرة فوق العناوين، أرقام كبيرة للإحصاءات، أيقونات خطية بسماكة موحدة.', en: 'Small pill labels above headings, big statistic numbers, line icons with a consistent stroke.' },
      avoid: { ar: 'الزخارف، الخطوط المذيّلة الثقيلة، الظلال القاسية، ازدحام الألوان.', en: 'Ornaments, heavy serifs, hard shadows, too many colours.' },
    },
    defaults: layout({ gallery: 'bento' }),
    motion: 'subtle', radius: 20,
    tile: { bg: '#EEF1F6', ink: '#0F172A', accent: '#2563EB', font: 'plus-jakarta-sans', fontAr: 'alexandria' },
  },
  {
    id: 'animated',
    name: { ar: 'متحرك', en: 'Animated' },
    tagline: { ar: 'الحركة هي التصميم', en: 'Motion is the design' },
    description: {
      ar: 'صفحات تتحرك مع التمرير: عناوين تصعد كلمة كلمة، أشرطة نصية تجري، صور بعمق متحرك، وأرقام تعدّ أمامك. الحركة هنا جزء من الهوية لا زينة.',
      en: 'Pages that move with the scroll: headings that rise word by word, running text bands, layered images, numbers that count up. Motion is part of the identity, not decoration.',
    },
    dna: {
      type: { ar: 'خط عرض ضخم جدًا للعنوان الرئيسي (حتى 10vw)، يقسم إلى كلمات تظهر بالتتابع، وخط بلا تذييل للنص.', en: 'A huge display face for the main heading (up to 10vw), split into words that appear in sequence, and a sans for text.' },
      color: { ar: 'تباين قوي: خلفية داكنة أو فاتحة جدًا مع لون مميز ناري واحد، وتدرجات متحركة في الخلفية عند الحاجة.', en: 'Strong contrast: very dark or very light background with one fiery accent, and animated gradients where useful.' },
      layout: { ar: 'أقسام بعرض كامل، أشرطة نصية متحركة بين الأقسام، شرائط أفقية للصور، أرقام ضخمة.', en: 'Full-width sections, moving text bands between sections, horizontal image strips, giant numbers.' },
      shape: { ar: 'زوايا دائرية متوسطة، أزرار مغناطيسية تتبع المؤشر، دوائر نصية دوّارة.', en: 'Medium radii, magnetic buttons that follow the pointer, rotating circular text.' },
      imagery: { ar: 'صور كبيرة بحركة عمق (parallax) وتكبير بطيء، أو أشكال متدرجة متحولة.', en: 'Large photos with parallax depth and slow zoom, or morphing gradient blobs.' },
      motion: { ar: 'غني ومدروس: تتابع 60–90ms بين العناصر، منحنى ease-out قوي، وكل شيء يتوقف مع prefers-reduced-motion.', en: 'Rich but deliberate: 60–90ms staggers, strong ease-out curves, and everything stops under prefers-reduced-motion.' },
      details: { ar: 'عدّادات أرقام، شريط تقدم التمرير، مؤشر مخصص، نص يتلوّن عند المرور.', en: 'Counters, a scroll progress bar, a custom cursor, text that fills with colour on hover.' },
      avoid: { ar: 'الحركة بلا هدف، التحريك المستمر الذي يشتت القراءة، تجاهل تفضيل تقليل الحركة.', en: 'Motion without purpose, constant movement that hurts reading, ignoring reduced-motion preferences.' },
    },
    defaults: layout({ hero: 'type', about: 'overlap', quotes: 'marquee', contact: 'center', cta: 'big', footer: 'big', stats: 'big', gallery: 'strip' }),
    motion: 'rich', radius: 16,
    tile: { bg: '#0B0B0F', ink: '#F5F5F0', accent: '#FF5B2E', font: 'unbounded', fontAr: 'lalezar' },
  },
  {
    id: 'heritage',
    name: { ar: 'تراثي', en: 'Heritage' },
    tagline: { ar: 'زخارف عربية وأقواس وتطريز', en: 'Arabesque, arches and embroidery' },
    description: {
      ar: 'من عمارتنا وفنوننا: نجوم هندسية، أقواس ومشربيات، تطريز فلاحي، وخطوط عربية أصيلة كالكوفي والرقعة والنسخ، بألوان الأرض والفخار والنيلة.',
      en: 'From Arab architecture and crafts: geometric stars, arches and mashrabiya, Palestinian cross-stitch, and true Arabic scripts (Kufi, Ruqaa, Naskh) in earth, clay and indigo tones.',
    },
    dna: {
      type: { ar: 'خط عربي أصيل للعناوين (رقعة أو كوفي أو ثلث مبسط)، ونسخ واضح للنص، ومقابل لاتيني كلاسيكي بأحرف كبيرة.', en: 'An authentic Arabic display script (Ruqaa, Kufi or a simplified Thuluth), clear Naskh for text, and a classical Latin capital face to pair.' },
      color: { ar: 'ألوان الأرض: رملي وطيني وزيتي، مع أحمر التطريز أو أزرق النيلة أو تركواز الزليج، ولمسات نحاسية.', en: 'Earth tones (sand, clay, olive) with embroidery red, indigo or zellige turquoise, and touches of brass.' },
      layout: { ar: 'تكوينات متماثلة، صور داخل أقواس، أشرطة زخرفية تفصل الأقسام، عناوين في الوسط.', en: 'Symmetrical compositions, photos inside arches, ornamental bands between sections, centred headings.' },
      shape: { ar: 'أقواس مدببة أو نصف دائرية للصور، نجوم ثمانية، حدود بنقش التطريز، زوايا مزخرفة.', en: 'Pointed or round arches for images, eight-point stars, cross-stitch borders, ornamented corners.' },
      imagery: { ar: 'عمارة قديمة، أبواب وأزقة، حرف يدوية، أطعمة تقليدية بإضاءة دافئة.', en: 'Old architecture, doors and alleys, handicrafts, traditional food in warm light.' },
      motion: { ar: 'هادئ: ظهور ناعم ودوران بطيء جدًا للنجوم الزخرفية.', en: 'Calm: soft reveals and a very slow rotation of ornamental stars.' },
      details: { ar: 'نقش هندسي خفيف كخلفية، شرائط تطريز، أرقام عربية-هندية في التفاصيل إن ناسبت.', en: 'A faint geometric pattern as a background, embroidery ribbons, Arabic-Indic numerals in details where they fit.' },
      avoid: { ar: 'استخدام الزخرفة بكثافة تخنق المحتوى، الخطوط العربية المشوهة أو المقطعة، تباعد الحروف العربية.', en: 'Ornament so dense it smothers content, broken or disconnected Arabic lettering, letter-spacing Arabic.' },
    },
    defaults: layout({ nav: 'center', hero: 'arch', quotes: 'single' }),
    motion: 'subtle', radius: 0,
    tile: { bg: '#F3E9D8', ink: '#3A1F14', accent: '#B23A2E', font: 'marcellus', fontAr: 'aref-ruqaa' },
  },
  {
    id: 'digital',
    name: { ar: 'رقمي', en: 'Digital' },
    tagline: { ar: 'شاشات وأكواد وتوهج نيون', en: 'Screens, code and neon glow' },
    description: {
      ar: 'جماليات الشاشة والتقنية: خلفيات داكنة، خطوط برمجية أحادية العرض، شبكات وخطوط قياس، نوافذ طرفية، وتوهج نيون. للتقنية والبرمجيات والفعاليات التقنية.',
      en: 'The aesthetics of screens and technology: dark backgrounds, monospaced type, grids and measurement lines, terminal windows and neon glow. For tech, software and tech events.',
    },
    dna: {
      type: { ar: 'خط أحادي العرض للعناوين والتسميات، وخط بلا تذييل تقني للنص، وأحرف لاتينية كبيرة صغيرة الحجم للتسميات.', en: 'A monospaced face for headings and labels, a technical sans for text, small uppercase labels.' },
      color: { ar: 'خلفية شبه سوداء أو كحلية عميقة، نص فاتح، ولون نيون واحد أو اثنان (أخضر، سماوي، أرجواني) مع توهج.', en: 'Near-black or deep navy background, light text, one or two neon accents (green, cyan, magenta) with glow.' },
      layout: { ar: 'شبكة مرئية بخطوط رفيعة، أقسام كلوحات تحكم، جداول ومواصفات، أرقام وإحداثيات في الزوايا.', en: 'A visible hairline grid, sections like dashboards, tables and specs, numbers and coordinates in corners.' },
      shape: { ar: 'زوايا صغيرة (4–6px)، حدود رفيعة متوهجة، زوايا تحديد على شكل [ ]، نوافذ طرفية بثلاث نقاط.', en: 'Small radii (4–6px), thin glowing borders, bracket corners [ ], terminal windows with three dots.' },
      imagery: { ar: 'لقطات شاشة، رسوم بيانية، صور ليلية للمدن والأضواء، أو بدون صور مع رسومات شبكية.', en: 'Screenshots, charts, night city and light photos, or no photos with wireframe graphics.' },
      motion: { ar: 'كتابة نص حرفًا حرفًا، مؤشر يومض، خطوط مسح، ظهور بخطوات.', en: 'Text typed letter by letter, a blinking caret, scanlines, stepped reveals.' },
      details: { ar: 'أسطر أوامر ($ أو >)، أرقام إصدارات، حالة "متصل" بنقطة خضراء، تلميحات لوحة مفاتيح.', en: 'Command prompts ($ or >), version numbers, an "online" status dot, keyboard hints.' },
      avoid: { ar: 'الخطوط المذيّلة الكلاسيكية، الألوان الترابية، الصور الدافئة الناعمة.', en: 'Classical serifs, earth tones, soft warm photography.' },
    },
    defaults: layout({ about: 'columns', contact: 'form', stats: 'big', schedule: 'table', extra: 'table' }),
    motion: 'lively', radius: 6,
    tile: { bg: '#05070B', ink: '#C8FFD4', accent: '#22F59A', font: 'jetbrains-mono', fontAr: 'changa' },
  },
  {
    id: 'minimal',
    name: { ar: 'بسيط', en: 'Minimal' },
    tagline: { ar: 'أقل عناصر، أكثر هدوء', en: 'Fewer things, more calm' },
    description: {
      ar: 'الفراغ هو العنصر الأهم: لونان أو ثلاثة، خط واحد بأوزان خفيفة، شبكة دقيقة، ولا شيء زائد. يناسب من يريد أن يتكلم عمله وحده.',
      en: 'Empty space is the main element: two or three colours, one typeface in light weights, a precise grid and nothing extra. For work that should speak for itself.',
    },
    dna: {
      type: { ar: 'خط واحد بلا تذييل أو خط مذيّل رفيع، بأوزان خفيفة إلى متوسطة، أحجام صغيرة للنص، تباين بالحجم لا بالوزن.', en: 'One sans or a light serif in light to medium weights, small text sizes, contrast through size rather than weight.' },
      color: { ar: 'أبيض دافئ أو رمادي حجري، حبر أسود، ولون مميز واحد خافت أو بدون لون مميز.', en: 'Warm white or stone grey, black ink, one muted accent or none.' },
      layout: { ar: 'هوامش واسعة جدًا، محاذاة صارمة إلى بداية السطر، قوائم بدل البطاقات، أقسام قليلة.', en: 'Very wide margins, strict alignment to the start edge, lists instead of cards, few sections.' },
      shape: { ar: 'بلا زوايا دائرية وبلا ظلال، خطوط شعرية فاصلة، أزرار نصية بخط تحتها.', en: 'No radii, no shadows, hairline dividers, text buttons with an underline.' },
      imagery: { ar: 'صور قليلة كبيرة بإضاءة طبيعية، كثير منها بالأبيض والأسود أو بألوان باهتة.', en: 'Few, large photos in natural light, often black-and-white or muted.' },
      motion: { ar: 'شبه معدوم: تلاشٍ خفيف وانتقال لون عند المرور.', en: 'Almost none: light fades and colour transitions on hover.' },
      details: { ar: 'أرقام أقسام صغيرة (01، 02)، تسميات صغيرة بلون رمادي، سطر واحد للتواصل.', en: 'Small section numbers (01, 02), small grey labels, a one-line contact.' },
      avoid: { ar: 'الأيقونات الكثيرة، الألوان المشبعة، الزخارف، الأزرار الضخمة.', en: 'Lots of icons, saturated colour, ornament, oversized buttons.' },
    },
    defaults: layout({ nav: 'minimal', hero: 'centered', about: 'columns', quotes: 'single', contact: 'center', cta: 'big', footer: 'simple', offer: 'list', gallery: 'masonry', pricing: 'table', process: 'list', schedule: 'list', extra: 'list' }),
    motion: 'calm', radius: 0,
    tile: { bg: '#FAFAF8', ink: '#141414', accent: '#9A9A94', font: 'inter', fontAr: 'alexandria' },
  },
  {
    id: 'luxury',
    name: { ar: 'فاخر', en: 'Luxury' },
    tagline: { ar: 'أسود وذهبي وصور كبيرة', en: 'Black, gold and big imagery' },
    description: {
      ar: 'فخامة هادئة: ألوان داكنة عميقة مع ذهبي أو شمبانيا، خطوط مذيّلة رفيعة عالية التباين، صور بعرض الشاشة، وحركة بطيئة واثقة.',
      en: 'Quiet opulence: deep dark colours with gold or champagne, thin high-contrast serifs, full-screen photography and slow, assured motion.',
    },
    dna: {
      type: { ar: 'خط مذيّل رفيع عالي التباين (ديدون) للعناوين، وأحرف لاتينية كبيرة متباعدة جدًا للتسميات، وخط عربي أنيق كالرقعة أو المسيري.', en: 'A thin high-contrast Didone serif for headings, widely spaced capitals for labels, and an elegant Arabic face such as Ruqaa or El Messiri.' },
      color: { ar: 'أسود دافئ أو أخضر زمردي أو عنابي داكن، مع ذهبي أو شمبانيا، ونص كريمي فاتح.', en: 'Warm black, emerald or deep burgundy, with gold or champagne and light cream text.' },
      layout: { ar: 'صور بعرض الشاشة، نص متمركز قصير، أقسام متناوبة صورة/نص، فراغات كبيرة.', en: 'Full-bleed images, short centred text, alternating image/text sections, large pauses.' },
      shape: { ar: 'زوايا حادة، خطوط ذهبية شعرية، إطارات رفيعة متداخلة، شعار حرفي (مونوغرام).', en: 'Square corners, hairline gold rules, thin overlapping frames, a monogram logo.' },
      imagery: { ar: 'صور داكنة عالية التباين بإضاءة جانبية، تفاصيل مقربة للمواد والأقمشة.', en: 'Dark, high-contrast photos with side light, close-ups of materials and textures.' },
      motion: { ar: 'بطيء: تلاشٍ 900ms، تكبير بطيء للصور، بلا قفزات.', en: 'Slow: 900ms fades, slow image zooms, no bounces.' },
      details: { ar: 'خط فاصل ذهبي قصير تحت العناوين، أرقام رومانية، توقيع بخط يدوي.', en: 'A short gold rule under headings, Roman numerals, a handwritten signature.' },
      avoid: { ar: 'الألوان الزاهية، الأيقونات الكرتونية، الزوايا الدائرية، ازدحام النص.', en: 'Bright colours, cartoon icons, rounded corners, crowded text.' },
    },
    defaults: layout({ nav: 'split', hero: 'fullbleed', about: 'overlap', quotes: 'single', contact: 'card', cta: 'image', footer: 'big', offer: 'zigzag', gallery: 'masonry', extra: 'zigzag' }),
    motion: 'calm', radius: 0,
    tile: { bg: '#0D0C0A', ink: '#EADBC0', accent: '#C9A45C', font: 'bodoni-moda', fontAr: 'aref-ruqaa' },
  },
  {
    id: 'playful',
    name: { ar: 'مرح', en: 'Playful' },
    tagline: { ar: 'ألوان زاهية وأشكال مستديرة', en: 'Bright colours and round shapes' },
    description: {
      ar: 'بهجة واضحة: ألوان مشبعة، أشكال مستديرة وفقاعات، ملصقات مائلة، حدود سميكة وظلال صلبة، وحركات نطّاطة. للأطفال والحلويات والتطبيقات الودودة.',
      en: 'Unmistakable joy: saturated colours, round shapes and blobs, tilted stickers, thick outlines with solid shadows and bouncy motion. For kids, sweets and friendly apps.',
    },
    dna: {
      type: { ar: 'خط مستدير عريض للعناوين، وخط ودود سهل القراءة للنص، وكلمات مميزة داخل فقاعات ملونة.', en: 'A rounded, chunky display face, a friendly readable text face, key words inside coloured blobs.' },
      color: { ar: 'ثلاثة إلى أربعة ألوان مشبعة متجاورة (وردي، أصفر، نعناعي، بنفسجي) على خلفية كريمية.', en: 'Three or four saturated colours side by side (pink, yellow, mint, purple) on a cream background.' },
      layout: { ar: 'بطاقات بألوان مختلفة، فواصل متموجة بين الأقسام، عناصر مائلة قليلًا، أشكال طافية في الخلفية.', en: 'Cards in different colours, wavy dividers between sections, slightly rotated elements, floating shapes in the background.' },
      shape: { ar: 'زوايا دائرية كبيرة جدًا، حدود سوداء سميكة (2–3px) وظل صلب مزاح، أقنعة صور على شكل فقاعة.', en: 'Very large radii, thick black outlines (2–3px) with an offset solid shadow, blob-shaped image masks.' },
      imagery: { ar: 'صور ساطعة داخل أشكال عضوية، ملصقات ونجوم، رسومات بسيطة.', en: 'Bright photos inside organic shapes, stickers and stars, simple drawings.' },
      motion: { ar: 'نطّاطة: تكبير مع ارتداد عند المرور، اهتزاز خفيف للملصقات، طفو بطيء للأشكال.', en: 'Bouncy: scale with overshoot on hover, a light wobble for stickers, slow floating shapes.' },
      details: { ar: 'ملصقات "جديد!" مائلة، رموز تعبيرية مرسومة، خطوط تحت الكلمات متموجة.', en: 'Tilted "New!" stickers, drawn emoji-like marks, wavy underlines.' },
      avoid: { ar: 'الرمادي الباهت، الخطوط الرفيعة الجادة، الزوايا الحادة، الصرامة.', en: 'Dull grey, thin serious type, sharp corners, rigidity.' },
    },
    defaults: layout({ nav: 'pill', quotes: 'wall', contact: 'card', footer: 'big' }),
    motion: 'lively', radius: 28,
    tile: { bg: '#FFE45E', ink: '#2B2118', accent: '#FF5C8A', font: 'fredoka', fontAr: 'lemonada' },
  },
  {
    id: 'editorial',
    name: { ar: 'مجلة', en: 'Editorial' },
    tagline: { ar: 'أعمدة صحفية وعناوين ضخمة', en: 'Newspaper columns and huge headlines' },
    description: {
      ar: 'صفحة مجلة أو جريدة: عناوين ضخمة بخط مذيّل، أعمدة نص، خطوط فاصلة، أرقام أعداد، اقتباسات بارزة، وصور بالأبيض والأسود.',
      en: 'A magazine or newspaper page: huge serif headlines, text columns, column rules, issue numbers, pull quotes and black-and-white photographs.',
    },
    dna: {
      type: { ar: 'خط مذيّل عرض ضخم للعناوين بتباعد أسطر ضيق، خط مذيّل للنص بأعمدة، وحرف أول كبير (drop cap) في الفقرة الأولى.', en: 'A huge display serif with tight leading for headlines, a text serif set in columns, and a drop cap on the first paragraph.' },
      color: { ar: 'ورق أبيض مائل للصفرة، حبر أسود، ولون واحد للتمييز (أحمر صحفي غالبًا).', en: 'Off-white newsprint, black ink and one spot colour (usually newspaper red).' },
      layout: { ar: 'ترويسة كالجريدة، أعمدة متعددة بفواصل رفيعة، شبكة صارمة، عناوين تمتد عبر الأعمدة.', en: 'A masthead, multiple columns with hairline rules, a strict grid, headlines spanning columns.' },
      shape: { ar: 'بلا زوايا دائرية، خطوط أفقية سميكة ورفيعة متتالية، مربعات معلومات بحدود.', en: 'No radii, thick-and-thin rule pairs, boxed information panels.' },
      imagery: { ar: 'صور بالأبيض والأسود أو بألوان باهتة، مع تعليقات صغيرة تحتها.', en: 'Black-and-white or muted photographs with small captions beneath.' },
      motion: { ar: 'هادئ جدًا: تلاشٍ بسيط فقط.', en: 'Very calm: simple fades only.' },
      details: { ar: 'تاريخ ورقم عدد في الترويسة، بيانات الكاتب، أرقام صفحات، شريط أخبار.', en: 'Date and issue number in the masthead, bylines, page numbers, a news ticker.' },
      avoid: { ar: 'الأزرار الملونة الكبيرة، الزوايا الدائرية، التدرجات، الأيقونات الملونة.', en: 'Big colourful buttons, rounded corners, gradients, colourful icons.' },
    },
    defaults: layout({ nav: 'center', hero: 'editorial', about: 'columns', quotes: 'single', cta: 'big', offer: 'list', gallery: 'masonry', pricing: 'table', process: 'list', schedule: 'table', extra: 'list' }),
    motion: 'calm', radius: 0,
    tile: { bg: '#F5F2EA', ink: '#111111', accent: '#D7261E', font: 'playfair-display', fontAr: 'markazi-text' },
  },
  {
    id: 'brutalist',
    name: { ar: 'خام', en: 'Brutalist' },
    tagline: { ar: 'حدود سميكة وألوان صادمة بلا تجميل', en: 'Thick borders, loud colour, no polish' },
    description: {
      ar: 'تصميم خام متعمد: حدود سوداء سميكة، ظلال صلبة مزاحة، ألوان صادمة، خطوط ثقيلة ضخمة، وشبكات مكشوفة. جريء ولا يُنسى.',
      en: 'Deliberately raw: thick black borders, hard offset shadows, loud colours, massive heavy type and exposed grids. Bold and memorable.',
    },
    dna: {
      type: { ar: 'خط ثقيل جدًا ومضغوط للعناوين بأحجام هائلة، وخط أحادي العرض أو خط بلا تذييل عادي للنص.', en: 'Very heavy condensed display type at enormous sizes, and a monospace or plain sans for text.' },
      color: { ar: 'أبيض أو رمادي فاتح مع أسود، ولون صادم واحد أو اثنان (أصفر، أحمر، أزرق كهربائي).', en: 'White or light grey with black, and one or two loud colours (yellow, red, electric blue).' },
      layout: { ar: 'شبكة مكشوفة بخطوط سوداء، كتل متراصة، عناصر متداخلة، جداول بدل البطاقات.', en: 'An exposed grid with black lines, stacked blocks, overlapping elements, tables instead of cards.' },
      shape: { ar: 'زوايا حادة دائمًا، حدود 3px سوداء، ظل صلب 6–8px مزاح بلا ضبابية.', en: 'Always square corners, 3px black borders, a 6–8px offset solid shadow with no blur.' },
      imagery: { ar: 'صور عالية التباين بالأبيض والأسود أو بلون واحد، مقصوصة بقسوة.', en: 'High-contrast black-and-white or single-colour photos, cropped hard.' },
      motion: { ar: 'مباشر: حركة الظل عند الضغط، شريط نصي يجري، بلا انتقالات ناعمة.', en: 'Direct: shadows that shift on press, a running text band, no soft easing.' },
      details: { ar: 'أرقام ضخمة، نص مقلوب أو عمودي، ملصقات تحذير، روابط بخط تحتها.', en: 'Huge numbers, rotated or vertical text, warning labels, underlined links.' },
      avoid: { ar: 'الظلال الناعمة، التدرجات، الزوايا الدائرية، الألوان الباستيل.', en: 'Soft shadows, gradients, rounded corners, pastel colours.' },
    },
    defaults: layout({ hero: 'poster', about: 'columns', quotes: 'wall', contact: 'form', cta: 'big', footer: 'big', stats: 'big', offer: 'table', schedule: 'table', extra: 'table' }),
    motion: 'subtle', radius: 0,
    tile: { bg: '#F2F2F2', ink: '#000000', accent: '#FFE600', font: 'archivo-black', fontAr: 'lalezar' },
  },
  {
    id: 'glass',
    name: { ar: 'زجاجي', en: 'Glass' },
    tagline: { ar: 'زجاج ضبابي فوق شفق ملوّن', en: 'Frosted glass over colourful light' },
    description: {
      ar: 'مستقبلي وناعم: بطاقات من زجاج ضبابي شفاف فوق خلفيات متدرجة كالشفق، حدود مضيئة رفيعة، وتوهجات لونية. للتطبيقات والتقنية والجمال.',
      en: 'Futuristic and soft: translucent frosted-glass cards over aurora-like gradients, thin luminous borders and colour glows. For apps, tech and beauty.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل هندسي نظيف بأوزان متوسطة، وأرقام كبيرة رفيعة.', en: 'A clean geometric sans in medium weights, with large light numerals.' },
      color: { ar: 'خلفية داكنة أو فاتحة عليها بقع لونية ضبابية كبيرة (بنفسجي، سماوي، وردي)، وبطاقات بيضاء شفافة 8–14%.', en: 'Dark or light background with large blurred colour blobs (violet, cyan, pink) and white cards at 8–14% opacity.' },
      layout: { ar: 'بطاقات طافية فوق الخلفية، شبكات بينتو، عناصر متداخلة بعمق.', en: 'Cards floating above the background, bento grids, layered depth.' },
      shape: { ar: 'زوايا 20–28px، backdrop-filter: blur(18px)، حد داخلي 1px أبيض شفاف، ظلال ملونة ناعمة.', en: '20–28px radii, backdrop-filter: blur(18px), a 1px translucent white inner border, soft coloured shadows.' },
      imagery: { ar: 'صور منتجات أو أجهزة على خلفيات متدرجة، أو صور بلمعة ضوئية.', en: 'Product or device shots on gradients, or photos with light flares.' },
      motion: { ar: 'بقع لونية تتحرك ببطء، ميلان خفيف للبطاقات مع المؤشر، ظهور بالتكبير.', en: 'Slowly drifting colour blobs, a light tilt of cards with the pointer, scale-in reveals.' },
      details: { ar: 'شارات زجاجية صغيرة، خطوط متوهجة، أيقونات بتدرج لوني.', en: 'Small glass pills, glowing lines, gradient icons.' },
      avoid: { ar: 'الشفافية التي تضعف قراءة النص، الحدود السوداء السميكة، الخطوط المذيّلة القديمة.', en: 'Transparency that hurts legibility, thick black borders, old-style serifs.' },
    },
    defaults: layout({ nav: 'pill', hero: 'centered', about: 'overlap', contact: 'card', offer: 'bento' }),
    motion: 'lively', radius: 24,
    tile: { bg: '#0E0B2B', ink: '#F1EEFF', accent: '#8B5CF6', font: 'sora', fontAr: 'readex-pro' },
  },
  {
    id: 'retro',
    name: { ar: 'ريترو', en: 'Retro' },
    tagline: { ar: 'السبعينات والثمانينات والتسعينات', en: 'The seventies, eighties and nineties' },
    description: {
      ar: 'حنين لعقود مضت: خطوط السبعينات المنتفخة وأشرطتها الملونة، شمس الثمانينات وشبكات النيون، نوافذ الحواسيب القديمة، ونقوش ممفيس.',
      en: 'Nostalgia for past decades: puffy seventies type and rainbow stripes, eighties sunsets and neon grids, old computer windows and Memphis patterns.',
    },
    dna: {
      type: { ar: 'خط عرض بروح العقد المختار (منتفخ، نيون، بكسل)، مع خط بسيط واضح للنص.', en: 'A display face true to the chosen decade (puffy, neon, pixel), with a plain readable text face.' },
      color: { ar: 'لوحة العقد: برتقالي وبني وخردلي للسبعينات، وردي وبنفسجي وسماوي للثمانينات، رمادي وأزرق ويندوز للتسعينات.', en: 'The decade\'s palette: orange, brown and mustard for the 70s; pink, purple and cyan for the 80s; Windows grey and blue for the 90s.' },
      layout: { ar: 'أشرطة ملونة متوازية، شمس نصف دائرية، نوافذ بأشرطة عنوان، ملصقات وأيقونات قديمة.', en: 'Parallel colour stripes, a half-sun, windows with title bars, period stickers and icons.' },
      shape: { ar: 'زوايا دائرية متوسطة أو بكسلية، حدود مزدوجة، ظلال صلبة ملونة.', en: 'Medium or pixel corners, double outlines, solid coloured shadows.' },
      imagery: { ar: 'صور بألوان مشبعة دافئة أو بتأثير لونين (duotone)، سيارات وأجهزة قديمة.', en: 'Warm saturated or duotone photos, old cars and gadgets.' },
      motion: { ar: 'حيوي: أشرطة تجري، توهج نيون يومض، مؤشر بكسل.', en: 'Lively: running stripes, flickering neon, a pixel cursor.' },
      details: { ar: 'نجوم وبريق، شبكة منظور، أزرار ثلاثية الأبعاد قديمة، شرائط كاسيت.', en: 'Stars and sparkles, a perspective grid, old 3D buttons, cassette tapes.' },
      avoid: { ar: 'خلط عدة عقود في تصميم واحد، الخطوط العصرية المحايدة، البهتان.', en: 'Mixing several decades in one design, neutral modern type, dullness.' },
    },
    defaults: layout({ hero: 'poster', contact: 'card', footer: 'big', stats: 'big' }),
    motion: 'lively', radius: 12,
    tile: { bg: '#FFF1D6', ink: '#3A1C0B', accent: '#F0592A', font: 'shrikhand', fontAr: 'lalezar' },
  },
  {
    id: 'organic',
    name: { ar: 'طبيعي', en: 'Organic' },
    tagline: { ar: 'ألوان الأرض وأشكال ناعمة', en: 'Earth tones and soft shapes' },
    description: {
      ar: 'قريب من الطبيعة: أخضر زيتوني وطيني ورملي، أشكال عضوية ناعمة، أوراق ونباتات، ملمس ورقي، وخطوط مذيّلة دافئة. للمنتجات الطبيعية والعافية والطعام.',
      en: 'Close to nature: olive, clay and sand, soft organic shapes, leaves and plants, paper texture and warm serifs. For natural products, wellness and food.',
    },
    dna: {
      type: { ar: 'خط مذيّل دافئ ناعم للعناوين، وخط إنساني مريح للنص، مع لمسة مائلة.', en: 'A soft warm serif for headings, a comfortable humanist face for text, a touch of italic.' },
      color: { ar: 'أخضر زيتوني، طيني، رملي، كريمي، مع لون ثمرة واحد (برتقالي أو مشمشي).', en: 'Olive green, clay, sand and cream with one fruit colour (orange or apricot).' },
      layout: { ar: 'أشكال عضوية خلف الصور، فواصل متموجة، صور بأقواس أو بيضاوية، تكوينات مريحة غير متصلبة.', en: 'Organic shapes behind photos, wavy dividers, arched or oval photos, relaxed compositions.' },
      shape: { ar: 'زوايا دائرية كبيرة وغير منتظمة، حدود ناعمة، بلا خطوط حادة.', en: 'Large, irregular radii, soft edges, no sharp lines.' },
      imagery: { ar: 'نباتات، أيدٍ، مكونات طبيعية، ضوء الشمس الدافئ.', en: 'Plants, hands, natural ingredients, warm sunlight.' },
      motion: { ar: 'هادئ: ظهور بطيء وتمايل خفيف للأوراق الزخرفية.', en: 'Gentle: slow reveals and a light sway of ornamental leaves.' },
      details: { ar: 'رسومات أوراق خطية، ملمس ورق خفيف، شارات "طبيعي ١٠٠٪".', en: 'Line-drawn leaves, a light paper texture, "100% natural" badges.' },
      avoid: { ar: 'الألوان النيونية، الزوايا الحادة، الأسود الحاد الكثير، الأشكال الهندسية الصارمة.', en: 'Neon colours, sharp corners, lots of hard black, rigid geometry.' },
    },
    defaults: layout({ hero: 'arch', cta: 'image', gallery: 'masonry' }),
    motion: 'subtle', radius: 32,
    tile: { bg: '#EEF0E5', ink: '#26301F', accent: '#7A8F3B', font: 'fraunces', fontAr: 'el-messiri' },
  },
  {
    id: 'artdeco',
    name: { ar: 'آرت ديكو', en: 'Art Deco' },
    tagline: { ar: 'خطوط ذهبية هندسية من العشرينات', en: 'Geometric gold lines from the 1920s' },
    description: {
      ar: 'بريق العشرينات: خطوط ذهبية هندسية، أشعة شمس ومراوح، درجات متصاعدة، تماثل صارم، وخطوط رفيعة طويلة. للحفلات والفنادق والعطور.',
      en: 'The glamour of the twenties: geometric gold lines, sunbursts and fans, stepped forms, strict symmetry and tall thin letters. For parties, hotels and perfume.',
    },
    dna: {
      type: { ar: 'خط عرض رفيع طويل بطابع العشرينات للعناوين، بأحرف لاتينية كبيرة متباعدة، وخط كوفي هندسي للعربية.', en: 'A tall thin twenties display face in widely spaced capitals, and a geometric Kufi for Arabic.' },
      color: { ar: 'أسود أو أخضر زمردي أو كحلي، مع ذهبي ونحاسي، وكريمي للنص.', en: 'Black, emerald or navy, with gold and brass, and cream for text.' },
      layout: { ar: 'تماثل كامل، أشكال مركزية، إطارات بزوايا متدرجة، أقسام مفصولة بخطوط ذهبية بنقاط ماسية.', en: 'Full symmetry, central motifs, frames with stepped corners, sections divided by gold lines with diamond ends.' },
      shape: { ar: 'زوايا مشطوفة أو متدرجة، أقواس، معينات، أشعة شمس.', en: 'Chamfered or stepped corners, arches, diamonds, sunbursts.' },
      imagery: { ar: 'عمارة الآرت ديكو، داخليات فاخرة، كؤوس وأضواء.', en: 'Art Deco architecture, rich interiors, glasses and lights.' },
      motion: { ar: 'هادئ وراقٍ: أشعة تتسع، خطوط ذهبية تُرسم.', en: 'Composed: sunbursts that open, gold lines that draw in.' },
      details: { ar: 'زخرفة مروحة فوق العناوين، أرقام داخل معينات، خطوط متوازية ثلاثية.', en: 'A fan motif above headings, numbers in diamonds, triple parallel lines.' },
      avoid: { ar: 'الأشكال العضوية، الخطوط الثقيلة المستديرة، الألوان الباستيل الطفولية.', en: 'Organic shapes, chunky rounded type, childish pastels.' },
    },
    defaults: layout({ nav: 'center', hero: 'framed', about: 'quote', quotes: 'single', contact: 'card', footer: 'big' }),
    motion: 'subtle', radius: 0,
    tile: { bg: '#0E1A17', ink: '#E9DCC0', accent: '#C8A24E', font: 'poiret-one', fontAr: 'reem-kufi' },
  },
  {
    id: 'handdrawn',
    name: { ar: 'مرسوم باليد', en: 'Hand-drawn' },
    tagline: { ar: 'خربشات وخط يد وورق دفاتر', en: 'Doodles, handwriting and notebook paper' },
    description: {
      ar: 'دافئ وإنساني: خطوط يد، حدود مرسومة غير منتظمة، خربشات وأسهم، ورق دفتر مسطّر، أوراق لاصقة وشريط لاصق. للتعليم والحرف والمقاهي الصغيرة.',
      en: 'Warm and human: handwriting, wobbly drawn borders, doodles and arrows, ruled notebook paper, sticky notes and tape. For learning, crafts and small cafes.',
    },
    dna: {
      type: { ar: 'خط يد واضح للعناوين، وخط بسيط مريح للنص، وكلمات مميزة بخط تحتها مرسوم.', en: 'A clear handwriting face for headings, a simple comfortable text face, key words with a drawn underline.' },
      color: { ar: 'ورق أبيض مائل للصفرة، حبر أزرق داكن أو رصاصي، ولونان مثل ألوان الأقلام (برتقالي، أخضر).', en: 'Off-white paper, dark blue or pencil-grey ink, and two marker colours (orange, green).' },
      layout: { ar: 'عناصر مائلة قليلًا، أوراق لاصقة، أسهم مرسومة تربط العناصر، خلفية دفتر مسطّر أو مربعات.', en: 'Slightly rotated elements, sticky notes, drawn arrows linking things, a ruled or grid notebook background.' },
      shape: { ar: 'حدود غير منتظمة (border-radius غير متساوٍ)، شريط لاصق على زوايا الصور، دوائر مرسومة حول الكلمات.', en: 'Wobbly borders (uneven border-radius), tape on photo corners, circles drawn around words.' },
      imagery: { ar: 'صور كأنها مثبتة بشريط لاصق، رسومات خطية بسيطة.', en: 'Photos that look taped on, simple line drawings.' },
      motion: { ar: 'حيوي خفيف: رسم الخطوط تحت الكلمات، اهتزاز بسيط عند المرور.', en: 'Lightly lively: underlines that draw in, a small wiggle on hover.' },
      details: { ar: 'أسهم ونجوم مرسومة، علامات ✓، تعليقات جانبية بخط اليد.', en: 'Drawn arrows and stars, ✓ marks, handwritten side notes.' },
      avoid: { ar: 'الحواف الحادة المثالية، الظلال الرقمية الناعمة، الصرامة المؤسسية.', en: 'Perfect sharp edges, soft digital shadows, corporate stiffness.' },
    },
    defaults: layout({ quotes: 'wall', contact: 'card', footer: 'simple' }),
    motion: 'lively', radius: 0,
    tile: { bg: '#FBF7EE', ink: '#22313F', accent: '#E4572E', font: 'caveat', fontAr: 'playpen-sans-arabic' },
  },
  {
    id: 'geometric',
    name: { ar: 'هندسي', en: 'Geometric' },
    tagline: { ar: 'باوهاوس وشبكة سويسرية', en: 'Bauhaus and the Swiss grid' },
    description: {
      ar: 'نظام صارم وجميل: شبكة سويسرية، دوائر ومربعات ومثلثات، ألوان أساسية (أحمر، أصفر، أزرق، أسود)، وخطوط بلا تذييل قوية بمحاذاة واحدة.',
      en: 'A strict, beautiful system: the Swiss grid, circles, squares and triangles, primary colours (red, yellow, blue, black) and strong sans type on one alignment.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل جروتسك قوي بأوزان ثقيلة، محاذاة إلى بداية السطر دائمًا، أرقام ضخمة.', en: 'A strong grotesque in heavy weights, always aligned to the start edge, huge numerals.' },
      color: { ar: 'خلفية بيضاء أو ورقية، أسود، وألوان أساسية صافية بمساحات كبيرة.', en: 'White or paper background, black, and pure primaries in large areas.' },
      layout: { ar: 'شبكة صارمة ظاهرة، كتل ألوان مستطيلة، تكوينات غير متماثلة متوازنة، أشكال هندسية كعناصر رئيسية.', en: 'A strict visible grid, rectangular colour blocks, balanced asymmetry, geometric shapes as main elements.' },
      shape: { ar: 'دوائر كاملة، مربعات، أنصاف دوائر، مثلثات؛ بلا زوايا دائرية للبطاقات.', en: 'Full circles, squares, half-circles and triangles; no rounded card corners.' },
      imagery: { ar: 'صور مقصوصة داخل دوائر ومربعات، أو بتأثير لونين مع الألوان الأساسية.', en: 'Photos cropped into circles and squares, or duotoned with the primaries.' },
      motion: { ar: 'أشكال تنزلق وتدور إلى أماكنها، بلا ارتداد.', en: 'Shapes slide and rotate into place, without bounce.' },
      details: { ar: 'أرقام أقسام ضخمة، خطوط سميكة قصيرة، نص عمودي جانبي.', en: 'Huge section numbers, short thick bars, vertical side text.' },
      avoid: { ar: 'الزخارف، التدرجات، الظلال، الخطوط المذيّلة الزخرفية.', en: 'Ornament, gradients, shadows, decorative serifs.' },
    },
    defaults: layout({ hero: 'type', about: 'columns', stats: 'big', schedule: 'table' }),
    motion: 'subtle', radius: 0,
    tile: { bg: '#F5F1E8', ink: '#111111', accent: '#E63B2E', font: 'inter-tight', fontAr: 'noto-kufi-arabic' },
  },
  {
    id: 'conventional',
    name: { ar: 'تقليدي', en: 'Conventional' },
    tagline: { ar: 'موقع الشركات المألوف الواضح', en: 'The familiar, clear business site' },
    description: {
      ar: 'الشكل المألوف الذي يفهمه كل زائر فورًا: شريط معلومات علوي، قائمة واضحة، صورة رئيسية مع زر، خدمات بأيقونات، أرقام، آراء العملاء، نموذج تواصل، وتذييل بعدة أعمدة.',
      en: 'The familiar layout every visitor understands at once: a top info bar, a clear menu, a hero photo with a button, services with icons, numbers, reviews, a contact form and a multi-column footer.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل واضح وشائع بأوزان متوسطة وثقيلة، أحجام معتدلة، وضوح قبل كل شيء.', en: 'A clear, familiar sans in medium and bold weights at moderate sizes; clarity above all.' },
      color: { ar: 'كحلي أو أزرق مؤسسي مع لون ثانوي دافئ للأزرار (برتقالي أو أخضر)، وخلفيات بيضاء ورمادية فاتحة متناوبة.', en: 'Navy or corporate blue with a warm secondary for buttons (orange or green), alternating white and light grey sections.' },
      layout: { ar: 'شريط علوي بالهاتف والبريد، صورة رئيسية بعرض كامل مع طبقة داكنة، شبكة خدمات 3 أعمدة، قسم "لماذا نحن"، نموذج تواصل.', en: 'A top bar with phone and email, a full-width hero photo with a dark overlay, a three-column services grid, a "why us" section, a contact form.' },
      shape: { ar: 'زوايا 6–8px، ظلال خفيفة للبطاقات، أزرار ممتلئة واضحة.', en: '6–8px radii, light card shadows, clear filled buttons.' },
      imagery: { ar: 'صور حقيقية لفريق العمل والمشاريع والمكان.', en: 'Real photos of the team, projects and premises.' },
      motion: { ar: 'خفيف: ظهور عند التمرير وعدّاد للأرقام.', en: 'Light: reveals on scroll and counting numbers.' },
      details: { ar: 'أيقونات داخل دوائر ملونة، أرقام إنجازات، زر واتساب عائم.', en: 'Icons in coloured circles, achievement numbers, a floating WhatsApp button.' },
      avoid: { ar: 'التجريب الذي يربك الزائر، الخطوط الغريبة، إخفاء معلومات التواصل.', en: 'Experiments that confuse visitors, odd fonts, hiding contact details.' },
    },
    defaults: layout({ hero: 'fullbleed', contact: 'form' }),
    motion: 'subtle', radius: 8,
    tile: { bg: '#FFFFFF', ink: '#13294B', accent: '#F28C28', font: 'figtree', fontAr: 'cairo' },
  },
  {
    id: 'interactive',
    name: { ar: 'تفاعلي', en: 'Interactive' },
    tagline: { ar: 'واجهات تتحرك مع الفأرة ومع التمرير', en: 'Heroes that answer the mouse and the scroll' },
    description: {
      ar: 'مواقع تتحرك مع زائرها: صورة تكبر حتى تملأ الشاشة مع التمرير، طبقات تتبع الفأرة، ضوء يكشف ما تحته، ستارة تنفتح، وأقسام تُقرأ كلمة بعد كلمة. لكل تفاعل بديل ثابت يظهر فيه المحتوى كاملًا لمن يفضّل تقليل الحركة.',
      en: 'Sites that move with their visitor: a photo that grows to fill the screen as you scroll, layers that follow the mouse, a light that reveals what lies underneath, a curtain that opens, sections read word by word. Every interaction has a still version that shows all the content to people who prefer less motion.',
    },
    dna: {
      type: { ar: 'عناوين ضخمة بخط عرض قوي (أحجام حتى 7rem) وسطور قصيرة، ونص بخط واضح بلا تذييل؛ الكلمة الكبيرة جزء من التفاعل.', en: 'Huge headlines in a strong display face (up to 7rem) on short lines, body text in a clear sans; the big words are part of the interaction.' },
      color: { ar: 'خلفية واحدة قوية (داكنة جدًا أو فاتحة جدًا) ولون رئيسي حيّ واحد، والصور تحمل بقية الألوان.', en: 'One strong background (very dark or very light) and a single vivid accent; the photos carry the rest of the colour.' },
      layout: { ar: 'واجهة بملء الشاشة تثبت في مكانها (sticky) بينما يقودها التمرير، ثم أقسام عادية تتخللها لحظات مثبتة أخرى (عبارة تُضاء أو شريط بطاقات أفقي).', en: 'A full-screen hero that holds in place (sticky) while the scroll drives it, then regular sections broken by other pinned moments (a statement that lights up, a sideways rail of cards).' },
      shape: { ar: 'أزرار كبسولية، صور كبيرة بزوايا مستديرة تصبح بعرض الشاشة، وبطاقات عائمة بظلال ناعمة.', en: 'Pill buttons, large rounded photos that become full-bleed, floating cards with soft shadows.' },
      imagery: { ar: 'صور كبيرة عالية الجودة تصلح لملء الشاشة، وصور صغيرة متعددة للطبقات والأثر.', en: 'Big, high-quality photos that work full screen, plus several smaller ones for layers and trails.' },
      motion: { ar: 'مرتبطة بالتمرير وبالمؤشر لا بالوقت: متغير تقدم من 0 إلى 1 يحرّك التحويلات، وحركة المؤشر مخففة بالتدرج، وأزرار مغناطيسية؛ وكل ذلك يتوقف مع prefers-reduced-motion.', en: 'Linked to the scroll and the pointer, not to time: a progress value from 0 to 1 drives the transforms, pointer movement is eased, buttons are magnetic; all of it stops with prefers-reduced-motion.' },
      details: { ar: 'شريط تقدم أعلى الصفحة، تلميح «مرّر للأسفل» يختفي عند البدء، مؤشر دائري يكبر فوق الروابط، وعدّادات للأرقام.', en: 'A progress bar along the top, a "scroll down" hint that fades once you start, a ring cursor that grows over links, counting numbers.' },
      avoid: { ar: 'خطف التمرير (لا تغيّر سرعة العجلة ولا تمنعها)، محتوى يبقى مخفيًا دون JavaScript، تأثيرات تعيق القراءة، ومكتبات ثقيلة لما تكفيه متغيرات CSS وrequestAnimationFrame.', en: 'Scroll-jacking (never change or block the wheel), content that stays hidden without JavaScript, effects that get in the way of reading, heavy libraries for what CSS variables and requestAnimationFrame can do.' },
    },
    defaults: layout({ nav: 'pill', hero: 'zoom', about: 'scrub', quotes: 'marquee', gallery: 'masonry', contact: 'card', cta: 'big', footer: 'big', stats: 'big' }),
    motion: 'rich', radius: 22,
    tile: { bg: '#FFD84D', ink: '#141414', accent: '#FF5A36', font: 'unbounded', fontAr: 'lalezar' },
  },
  {
    id: 'bento',
    name: { ar: 'بِنتو', en: 'Bento' },
    tagline: { ar: 'شبكة بطاقات بأحجام مختلفة', en: 'A grid of cards in different sizes' },
    description: {
      ar: 'الصفحة صندوق بِنتو: بطاقات مستديرة بأحجام مختلفة تتجاور في شبكة واحدة، كل بطاقة تحمل فكرة واحدة (رقم، صورة، ميزة، عنوان). هادئ ومرتب على طريقة صفحات آبل، ومناسب للتطبيقات والمنتجات والمقاهي الحديثة.',
      en: 'The page is a bento box: rounded cards of different sizes sitting side by side in one grid, each holding a single idea (a number, a photo, a feature, an address). Calm and orderly in the manner of Apple\'s pages, and a good fit for apps, products and modern cafés.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل نظيف بأوزان ثقيلة للعناوين وأرقام كبيرة جدًا داخل البطاقات، ونص صغير هادئ بلون رمادي.', en: 'A clean sans in heavy weights for headings and very large numbers inside the cards, with small quiet grey text.' },
      color: { ar: 'خلفية رمادية فاتحة جدًا (#F5F5F7 أو قريب منها) أو داكنة جدًا، بطاقات بيضاء أو أغمق قليلًا، ولون رئيسي واحد يملأ بطاقة أو اثنتين فقط.', en: 'A very light grey page (#F5F5F7 or close) or a very dark one, white or slightly darker cards, and one brand colour that fills only one or two cards.' },
      layout: { ar: 'شبكة من أربعة أعمدة تمتد فيها البطاقات على عمودين أو صفين، بطاقة كبيرة بمساحة ٢×٢ تفتتح كل شبكة، وفجوات ثابتة بين ١٢ و١٦ بكسل؛ حتى الأرقام والتواصل تصير بطاقات.', en: 'A four-column CSS grid with varied spans (grid-column/grid-row: span), a large 2×2 card opening each grid, and fixed gaps of 12–16px; even the figures and the contact details become cards.' },
      shape: { ar: 'زوايا مستديرة كبيرة (٢٤ بكسل)، ظل خفيف جدًا، بلا حدود سميكة، وأزرار كبسولية.', en: 'Large rounded corners (24px), a very soft shadow, no heavy borders, pill buttons.' },
      imagery: { ar: 'صور منتج أو مكان تملأ البطاقة كاملة (object-fit: cover)، وأيقونات خطية بسيطة.', en: 'Product or place photos that fill their card completely (object-fit: cover), and simple line icons.' },
      motion: { ar: 'هادئة: البطاقة تكبر قليلًا عند المرور (scale 1.02) وتظهر البطاقات بالتتابع عند التمرير.', en: 'Quiet: a card grows slightly on hover (scale 1.02) and the cards appear one after another on scroll.' },
      details: { ar: 'تسميات صغيرة أعلى كل بطاقة، أرقام ضخمة، شارة كبسولية للحالة، وسهم صغير في زاوية البطاقة القابلة للنقر.', en: 'Small labels at the top of each card, huge numbers, a pill badge for status, a small arrow in the corner of clickable cards.' },
      avoid: { ar: 'بطاقات متساوية الحجم كلها، ظلال ثقيلة، ألوان كثيرة، ونصوص طويلة داخل البطاقات.', en: 'Cards all the same size, heavy shadows, many colours, long text inside cards.' },
    },
    defaults: layout({ nav: 'pill', hero: 'split', about: 'split', quotes: 'cards', contact: 'card', cta: 'band', footer: 'columns', stats: 'row', offer: 'bento', gallery: 'bento', extra: 'bento' }),
    motion: 'subtle', radius: 24,
    tile: { bg: '#F5F5F7', ink: '#1D1D1F', accent: '#0071E3', font: 'inter-tight', fontAr: 'ibm-plex-sans-arabic' },
  },
  {
    id: 'clay',
    name: { ar: 'طيني', en: 'Clay' },
    tagline: { ar: 'أشكال منتفخة كالمعجون', en: 'Puffy shapes like modelling clay' },
    description: {
      ar: 'كل شيء يبدو مصنوعًا من الصلصال: بطاقات وأزرار منتفخة بألوان الباستيل، ظل داخلي فاتح وآخر داكن مع ظل خارجي ناعم، وزوايا مستديرة جدًا وحركة نطّاطة. للأطفال والتعليم والتطبيقات الودودة والحلويات.',
      en: 'Everything looks made of modelling clay: puffy pastel cards and buttons, a light and a dark inner shadow with a soft outer one, very round corners and bouncy motion. For children, learning, friendly apps and sweets.',
    },
    dna: {
      type: { ar: 'خط مستدير ممتلئ للعناوين (مثل Baloo أو Fredoka، وللعربية Baloo Bhaijaan أو Lemonada) ونص مستدير واضح.', en: 'A full, rounded face for headings (such as Baloo or Fredoka; Baloo Bhaijaan or Lemonada for Arabic) and a clear rounded text face.' },
      color: { ar: 'خلفية باستيل بتدرج خفيف، وبطاقات بألوان باستيل متعددة (خوخي، سماوي، نعناعي، ليلكي)، ولون رئيسي أعمق للأزرار.', en: 'A pastel background with a faint gradient, cards in several pastels (peach, sky, mint, lilac), and a deeper main colour for buttons.' },
      layout: { ar: 'تخطيط بسيط ومتمركز بعناصر كبيرة متباعدة، بطاقات تطفو فوق الخلفية، وصور داخل أشكال مستديرة.', en: 'A simple, centred layout with large, well-spaced elements, cards floating over the background, and photos inside rounded shapes.' },
      shape: { ar: 'زوايا بين ٢٤ و٣٢ بكسل، حد أبيض بسماكة ٣ بكسل، وثلاثة ظلال: ظل داخلي داكن شفاف في الزاوية السفلية، وظل داخلي أبيض في الزاوية العلوية، وظل خارجي ناعم بنفسجي شفاف.', en: '24–32px corners, a 3px white border, shadows: inset -4px -4px 10px translucent dark + inset 4px 4px 10px white + an outer 8px 12px 24px in translucent violet.' },
      imagery: { ar: 'صور مشرقة داخل إطارات منتفخة، وأيقونات داخل دوائر صلصالية ملونة.', en: 'Bright photos inside puffy frames, and icons inside coloured clay circles.' },
      motion: { ar: 'نطّاطة بمنحنى يتجاوز هدفه قليلًا ثم يعود، الزر ينضغط عند النقر ويرتد، والبطاقات ترتفع قليلًا عند المرور.', en: 'Bouncy: cubic-bezier(.34,1.56,.64,1), buttons squash when pressed and spring back, cards lift a little on hover.' },
      details: { ar: 'فقاعات صلصال ملونة في الخلفية، أرقام داخل دوائر، وشارات منتفخة.', en: 'Coloured clay bubbles in the background, numbers inside circles, puffy badges.' },
      avoid: { ar: 'الحدود السوداء الحادة، الزوايا القائمة، الألوان المشبعة جدًا، والظلال الصلبة.', en: 'Hard black outlines, square corners, very saturated colours, solid shadows.' },
    },
    defaults: layout({ nav: 'pill', hero: 'arch', about: 'split', quotes: 'cards', contact: 'center', cta: 'band', footer: 'simple', stats: 'row', process: 'steps' }),
    motion: 'lively', radius: 30,
    tile: { bg: '#EFE6FF', ink: '#3B2A55', accent: '#7C5CE0', font: 'fredoka', fontAr: 'baloo-bhaijaan-2' },
  },
  {
    id: 'soft',
    name: { ar: 'ناعم', en: 'Soft UI' },
    tagline: { ar: 'عناصر بارزة ومحفورة من لون الخلفية', en: 'Raised and pressed shapes in the background colour' },
    description: {
      ar: 'نيومورفيزم: الصفحة سطح واحد بلون واحد، والعناصر تبرز منه أو تنحفر فيه بظلين متعاكسين (فاتح من أعلى اليسار وداكن من أسفل اليمين). هادئ وناعم، للعافية والتأمل والعيادات والتطبيقات البسيطة.',
      en: 'Neumorphism: the page is one surface in one colour, and elements rise out of it or sink into it with two opposite shadows (light from the top left, dark from the bottom right). Quiet and soft, for wellness, meditation, clinics and simple apps.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل ناعم بأوزان متوسطة وثقيلة، وحجم نص مريح؛ النص داكن بما يكفي للتباين لأن السطح فاتح وباهت.', en: 'A soft sans in medium and heavy weights at a comfortable size; text dark enough for contrast, since the surface is pale and muted.' },
      color: { ar: 'لون سطح واحد فاتح مائل للرمادي (مثل #E4E9EF) للخلفية والبطاقات معًا، ولون رئيسي واحد هادئ (أزرق أو أخضر أو وردي باهت) للأزرار والأيقونات.', en: 'One pale greyish surface colour (such as #E4E9EF) for both page and cards, and a single calm accent (a muted blue, green or pink) for buttons and icons.' },
      layout: { ar: 'مساحات واسعة وعناصر قليلة، بطاقات بنفس لون الخلفية لا يميزها إلا الظل، ودوائر ومقابض كأزرار جهاز.', en: 'Generous space and few elements, cards in the background colour told apart only by their shadow, dials and knobs like a device\'s controls.' },
      shape: { ar: 'زوايا بين ١٤ و٢٠ بكسل. البارز له ظلان: أبيض من أعلى اليسار، ورمادي مزرق شفاف من أسفل اليمين؛ والمحفور له الظلان نفساهما من الداخل. بلا حدود.', en: '14–20px corners. Raised: box-shadow: -8px -8px 18px white, 8px 8px 18px translucent blue-grey; pressed: the same two shadows inset. No borders.' },
      imagery: { ar: 'صور هادئة داخل إطارات محفورة، وأيقونات داخل دوائر محفورة.', en: 'Calm photos inside pressed frames, and icons inside pressed circles.' },
      motion: { ar: 'بطيئة وناعمة: الزر ينتقل من بارز إلى محفور عند الضغط (150ms)، والعناصر تظهر بتلاشٍ خفيف.', en: 'Slow and soft: a button goes from raised to pressed when clicked (150ms), elements fade in gently.' },
      details: { ar: 'مقبض دائري كبير يحمل رقمًا، حقول إدخال محفورة، ومفاتيح تبديل.', en: 'A large round dial holding a number, pressed input fields, toggle switches.' },
      avoid: { ar: 'نص رمادي فاتح ضعيف التباين، ألوان كثيرة، حدود، وظلال على كل شيء حتى يضيع الترتيب.', en: 'Pale low-contrast grey text, many colours, borders, and shadows on everything until the hierarchy is lost.' },
    },
    defaults: layout({ nav: 'pill', hero: 'split', about: 'split', quotes: 'cards', contact: 'form', cta: 'band', footer: 'simple', stats: 'row', process: 'steps' }),
    motion: 'subtle', radius: 20,
    tile: { bg: '#E4E9EF', ink: '#3E4A5A', accent: '#3D6BA8', font: 'nunito', fontAr: 'almarai' },
  },
  {
    id: 'aurora',
    name: { ar: 'شفق', en: 'Aurora' },
    tagline: { ar: 'تدرجات لونية تتحرك كالشفق', en: 'Colour that drifts like the northern lights' },
    description: {
      ar: 'ألوان واسعة تنساب وتتمازج ببطء خلف الصفحة كالشفق القطبي: أزرق كهربائي ووردي وبنفسجي وفيروزي، فوق خلفية عميقة. العناوين والأرقام تأخذ التدرج نفسه، والبطاقات بحواف ملونة رفيعة. للمهرجانات والموسيقى والتقنية والعلامات الحديثة.',
      en: 'Wide fields of colour that flow and blend slowly behind the page like the northern lights: electric blue, pink, violet and teal over a deep ground. Headings and numbers take the same gradient, and cards get thin coloured edges. For festivals, music, tech and modern brands.',
    },
    dna: {
      type: { ar: 'خط بلا تذييل حديث بأوزان رفيعة وثقيلة معًا، وعناوين كبيرة يملؤها تدرج لوني.', en: 'A modern sans used in both light and heavy weights, with large headings filled with a gradient (background-clip: text).' },
      color: { ar: 'خلفية عميقة (كحلي أو بنفسجي داكن جدًا) وأربعة ألوان شفق متكاملة (#00E0FF، #FF2E9A، #7B3CFF، #00FF9C أو ما يقاربها)، تشبع مرتفع قليلًا.', en: 'A deep ground (navy or very dark violet) and four complementary aurora colours (#00E0FF, #FF2E9A, #7B3CFF, #00FF9C or close), slightly raised saturation.' },
      layout: { ar: 'واجهة كبيرة مفتوحة يملؤها الشفق، أقسام متباعدة بمساحات واسعة، وبطاقات قليلة شبه شفافة.', en: 'A big open hero filled by the aurora, widely spaced sections, and a few semi-transparent cards.' },
      shape: { ar: 'زوايا ١٨–٢٤ بكسل، حواف ملونة رفيعة بتدرج (border بقناع أو خلفية مزدوجة)، وأزرار كبسولية بتدرج.', en: '18–24px corners, thin gradient edges (a masked border or a double background), and gradient pill buttons.' },
      imagery: { ar: 'صور بإضاءة ليلية أو ملونة، تمتزج مع الخلفية بطبقة لونية خفيفة (mix-blend-mode).', en: 'Night-lit or colourful photos, blended into the page with a light colour layer (mix-blend-mode).' },
      motion: { ar: 'تدرجات شعاعية ضبابية جدًا تتحرك وتدور ببطء في حلقة ٨–١٢ ثانية، وتغيّر hue-rotate خفيف؛ تتوقف مع تقليل الحركة.', en: 'Blurred radial gradients (blur 40–60px) that drift and turn slowly on an 8–12s loop, with a light hue-rotate; they stop with reduced motion.' },
      details: { ar: 'أرقام بتدرج لوني، خط فاصل متوهج، ونقطة متوهجة قبل التسميات.', en: 'Gradient numbers, a glowing divider line, a glowing dot before labels.' },
      avoid: { ar: 'تدرج بنفسجي-أزرق عادي على خلفية بيضاء، نص فوق أجزاء فاتحة من التدرج بلا تباين، وحركة سريعة.', en: 'A plain purple-to-blue gradient on white, text over light parts of the gradient without contrast, fast motion.' },
    },
    defaults: layout({ nav: 'pill', hero: 'centered', about: 'overlap', quotes: 'wall', contact: 'card', cta: 'big', footer: 'big', stats: 'big' }),
    motion: 'lively', radius: 22,
    tile: { bg: '#0B0B1E', ink: '#FFFFFF', accent: '#FF2E9A', font: 'sora', fontAr: 'readex-pro' },
  },
  {
    id: 'y2k',
    name: { ar: 'ألفيني', en: 'Y2K' },
    tagline: { ar: 'كروم ولمعان وفقاعات من سنة ٢٠٠٠', en: 'Chrome, gloss and bubbles from the year 2000' },
    description: {
      ar: 'جمالية مطلع الألفية: عناوين كرومية فضية، أزرار لامعة كالحلوى، وردي ساخن وسماوي وبنفسجي، فقاعات ونجوم تلمع، وتدرجات قزحية. للأزياء والموسيقى والعلامات الشبابية.',
      en: 'The look of the turn of the millennium: silver chrome headings, glossy candy buttons, hot pink, cyan and purple, bubbles and twinkling stars, iridescent gradients. For fashion, music and youth brands.',
    },
    dna: {
      type: { ar: 'خط عرض ممتلئ أو مستدير للعناوين بملء كرومي (تدرج فضي من أعلى لأسفل مع حد ملون رفيع وتوهج)، ونص بخط بلا تذييل بسيط.', en: 'A full or rounded display face for headings with a chrome fill (a vertical silver gradient with a thin coloured stroke and a glow), body in a simple sans.' },
      color: { ar: 'وردي ساخن #FF69B4، سماوي #00FFFF، فضي #C0C0C0، بنفسجي #9400D3، فوق خلفية قزحية فاتحة (وردي-سماوي-ليلكي) أو سوداء.', en: 'Hot pink #FF69B4, cyan #00FFFF, silver #C0C0C0, purple #9400D3, over a light iridescent ground (pink, cyan, lilac) or black.' },
      layout: { ar: 'تركيب مرح متمركز، عناصر مائلة قليلًا، بطاقات كفقاعات، وشريط متحرك.', en: 'A playful centred composition, slightly tilted elements, bubble-like cards, a moving ticker.' },
      shape: { ar: 'كبسولات وفقاعات مستديرة تمامًا، لمعة بيضاء على النصف العلوي لكل زر، وحدود قزحية.', en: 'Pills and bubbles (border-radius 999px), a white shine on the top half of every button (linear-gradient(180deg, #fffc 0, transparent 50%)), iridescent borders.' },
      imagery: { ar: 'صور ملونة بإطارات لامعة، نجوم بأربعة رؤوس، وفقاعات شفافة.', en: 'Colourful photos in glossy frames, four-pointed stars, transparent bubbles.' },
      motion: { ar: 'نجوم تومض، فقاعات تطفو، توهج ينبض على الأزرار، وتدرج قزحي ينساب.', en: 'Twinkling stars, floating bubbles, a pulsing glow on buttons, an iridescent gradient that drifts.' },
      details: { ar: 'نجوم لامعة حول العناوين، شارات كبسولية بلمعة، ومؤشر على شكل نجمة.', en: 'Sparkles around headings, glossy pill badges, a star-shaped cursor.' },
      avoid: { ar: 'الألوان الباهتة، الزوايا القائمة، الخطوط الكلاسيكية المذيلة، والبساطة الشديدة.', en: 'Muted colours, square corners, classic serif faces, strict minimalism.' },
    },
    defaults: layout({ nav: 'pill', hero: 'centered', about: 'split', quotes: 'marquee', contact: 'card', cta: 'big', footer: 'big', stats: 'big', gallery: 'masonry' }),
    motion: 'lively', radius: 28,
    tile: { bg: '#FFD6F0', ink: '#3A0D57', accent: '#FF69B4', font: 'righteous', fontAr: 'lemonada' },
  },
  {
    id: 'pixel',
    name: { ar: 'بكسل', en: 'Pixel' },
    tagline: { ar: 'مربعات حادة كألعاب الثمانينات', en: 'Hard square pixels like 1980s games' },
    description: {
      ar: 'الصفحة لعبة فيديو قديمة: حدود وظلال بكسلية متدرجة، خطوط بكسل، ألوان محدودة كلوحة NES، أشرطة طاقة وقلوب وصناديق حوار. لمقاهي الألعاب والفعاليات والتطبيقات المرحة.',
      en: 'The page is an old video game: stepped pixel borders and shadows, pixel type, a limited NES-like palette, health bars, hearts and dialogue boxes. For game cafés, events and playful apps.',
    },
    dna: {
      type: { ar: 'خط بكسل للعناوين والتسميات (Press Start 2P أو Silkscreen، وللعربية Handjet)، ونص بخط واضح عادي حتى يبقى مقروءًا.', en: 'A pixel face for headings and labels (Press Start 2P or Silkscreen; Handjet for Arabic), and a plain clear face for text so it stays readable.' },
      color: { ar: 'لوحة محدودة من ٤–٦ ألوان مشبعة (كحلي داكن، أصفر، أحمر، أخضر) بلا تدرجات، وأسود للحدود.', en: 'A limited palette of 4–6 saturated colours (dark navy, yellow, red, green) with no gradients, and black for outlines.' },
      layout: { ar: 'شبكة صارمة على وحدة ٤ أو ٨ بكسل، أقسام كمراحل لعبة (LEVEL 01، 02…)، بطاقات كصناديق حوار.', en: 'A strict grid on a 4 or 8px unit, sections as game levels (LEVEL 01, 02…), cards as dialogue boxes.' },
      shape: { ar: 'زوايا قائمة تمامًا، حدود بكسل مصنوعة من أربعة ظلال صلبة بعرض ٤ بكسل في الجهات الأربع، وظل صلب مزاح ٨ بكسل.', en: 'Perfectly square corners, pixel borders from stacked shadows (box-shadow: 4px 0 0 #000, -4px 0 0 #000, 0 4px 0 #000, 0 -4px 0 #000), and a solid 8px offset shadow.' },
      imagery: { ar: 'صور بإطار بكسلي، أيقونات بكسل (قلوب، نجوم، عملات)، وشبكة مربعات في الخلفية.', en: 'Photos in pixel frames, pixel icons (hearts, stars, coins), a faint square grid in the background.' },
      motion: { ar: 'حركة على خطوات متقطعة بلا انسياب: مؤشر يومض، نص يُكتب حرفًا حرفًا، والزر ينزل ٤ بكسل عند الضغط.', en: 'Stepped motion (steps()) with no easing: a blinking cursor, text typed letter by letter, a button that drops 4px when pressed.' },
      details: { ar: 'شريط طاقة، قلوب الحياة، عدّاد نقاط، وكلمة START ▶ على الزر.', en: 'A health bar, life hearts, a score counter, START ▶ on the button.' },
      avoid: { ar: 'الزوايا المستديرة، الظلال الضبابية، التدرجات، وخط البكسل للفقرات الطويلة.', en: 'Rounded corners, blurred shadows, gradients, pixel type for long paragraphs.' },
    },
    defaults: layout({ nav: 'bar', hero: 'split', about: 'split', quotes: 'cards', contact: 'split', cta: 'band', footer: 'columns', stats: 'row', process: 'steps' }),
    motion: 'lively', radius: 0,
    tile: { bg: '#2B2D5C', ink: '#F8F4E3', accent: '#FFD23F', font: 'press-start-2p', fontAr: 'handjet' },
  },
  {
    id: 'skeuo',
    name: { ar: 'واقعي', en: 'Skeuo' },
    tagline: { ar: 'خشب ونحاس وجلد وورق', en: 'Wood, brass, leather and paper' },
    description: {
      ar: 'سكيومورفيزم: الواجهة تقلّد الخامات الحقيقية، خشب بعروقه وجلد مخيط وورق ونحاس لامع، بظلال عميقة وأزرار تبدو قابلة للضغط فعلًا. للحِرف والساعات والمكتبات والمنتجات الفاخرة.',
      en: 'Skeuomorphism: the interface copies real materials, grained wood, stitched leather, paper and polished brass, with deep shadows and buttons that look truly pressable. For crafts, watchmakers, bookshops and premium products.',
    },
    dna: {
      type: { ar: 'خط مذيل كلاسيكي بأوزان ثقيلة، بنقش بارز (ظل فاتح من أعلى وداكن من أسفل)، ونص مذيل مريح للقراءة.', en: 'A classic serif in heavy weights, embossed (a light text-shadow above and a dark one below), with a comfortable serif for text.' },
      color: { ar: 'ألوان الخامات: بني الخشب والجلد، كريمي الورق، نحاسي ذهبي للأزرار، وأخضر أو عنابي داكن كلون ثانٍ.', en: 'Material colours: wood and leather browns, paper cream, golden brass for buttons, and a dark green or oxblood as a second colour.' },
      layout: { ar: 'أقسام كأسطح مختلفة: لوح خشبي، ورقة مثبتة، لوحة جلدية بخياطة؛ بطاقات كبطاقات ورقية أو أدراج.', en: 'Sections as different surfaces: a wooden board, a pinned sheet of paper, a stitched leather panel; cards as paper cards or drawers.' },
      shape: { ar: 'زوايا صغيرة بين ٦ و١٠ بكسل، خياطة متقطعة داخل الحواف، ظلال متعددة الطبقات، وأزرار نحاسية بتدرج من ٤ نقاط.', en: 'Small corners (6–10px), dashed stitching inside the edges (a dashed outline with a negative outline-offset), multi-layer shadows, and brass buttons with a four-stop gradient.' },
      imagery: { ar: 'صور دافئة بإطار ورقي أبيض وظل، كصور مطبوعة على طاولة.', en: 'Warm photos in a white paper frame with a shadow, like prints laid on a table.' },
      motion: { ar: 'واقعية ومتأنية (300–500ms): الزر ينضغط للداخل، والبطاقة ترتفع عن السطح عند المرور.', en: 'Realistic and unhurried (300–500ms): buttons press in, cards lift off the surface on hover.' },
      details: { ar: 'عروق خشب من تدرجات متكررة، نسيج ورق، مسامير نحاسية في الزوايا، وأشرطة لاصقة.', en: 'Wood grain from repeating gradients, paper texture, brass rivets in the corners, strips of tape.' },
      avoid: { ar: 'الألوان المسطحة الزاهية، الخطوط الهندسية الحديثة، وصور خامات حقيقية ثقيلة الحجم (ابنِ الخامات بـ CSS).', en: 'Flat bright colours, modern geometric sans faces, heavy real texture photos (build the materials in CSS).' },
    },
    defaults: layout({ nav: 'center', hero: 'framed', about: 'split', quotes: 'cards', contact: 'card', cta: 'band', footer: 'columns', stats: 'row' }),
    motion: 'subtle', radius: 8,
    tile: { bg: '#5A3920', ink: '#F3E3C3', accent: '#D4A94E', font: 'playfair-display', fontAr: 'amiri' },
  },
];

export const categoryIds = CATEGORIES.map(c => c.id);

export function category(id: CategoryId): Category {
  const found = CATEGORIES.find(c => c.id === id);
  if (!found) throw new Error(`Unknown category "${id}"`);
  return found;
}
