import type { Profile } from '../types';
import { item, same, t } from './helpers';

export const construction: Profile = {
  id: 'construction',
  label: t('شركة مقاولات', 'Construction company'),
  brand: t('أساس للمقاولات', 'Asas Contracting'),
  mark: t('أ', 'A'),
  tagline: t('نبني ما يبقى', 'We build what lasts'),
  navCta: t('اطلب عرض سعر', 'Get a quote'),
  socials: ['linkedin', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('هندسة وبناء منذ ٢٠٠٤', 'Engineering & building since 2004'),
      title: t('نبني على أساس متين', 'Built on solid ground'),
      lead: t('تصميم وتنفيذ مبانٍ سكنية وتجارية وبنى تحتية، بفريق من ١٢٠ مهندسًا وفنيًا، وبالتزام كامل بالموعد والميزانية.', 'Design and construction of residential, commercial and infrastructure projects by a team of 120 engineers and technicians, on time and on budget.'),
      cta: t('اطلب عرض سعر', 'Get a quote'),
      cta2: t('مشاريعنا', 'Our projects'),
      img: 1076, imgs: [500, 331, 444],
      badge: t('ISO 9001', 'ISO 9001'),
    },
    {
      kind: 'about', id: 'company', nav: t('الشركة', 'Company'),
      eyebrow: t('من نحن', 'Who we are'),
      title: t('عشرون عامًا من المشاريع المسلَّمة', 'Twenty years of delivered projects'),
      text: [
        t('بدأت أساس كمكتب هندسي صغير في رام الله، وأصبحت اليوم من أكبر شركات المقاولات المصنفة درجة أولى في فلسطين.', 'Asas began as a small engineering office in Ramallah and is now one of Palestine\'s largest first-class contractors.'),
        t('ندير المشروع من الدراسة الأولى حتى تسليم المفتاح، مع تقارير أسبوعية ومهندس مقيم في كل موقع.', 'We run projects from the first study to handover, with weekly reports and a resident engineer on every site.'),
      ],
      img: 491, img2: 331,
      quote: t('السلامة أولًا، والجودة دائمًا.', 'Safety first, quality always.'),
      sign: t('م. خالد منصور، المدير العام', 'Eng. Khaled Mansour, CEO'),
    },
    {
      kind: 'items', id: 'services', nav: t('الخدمات', 'Services'), role: 'offer',
      eyebrow: t('الخدمات', 'Services'),
      title: t('كل مراحل البناء تحت سقف واحد', 'Every stage of building under one roof'),
      items: [
        item(t('التصميم الهندسي', 'Engineering design'), { text: t('معماري وإنشائي وكهروميكانيك', 'Architectural, structural and MEP'), icon: 'pencil-ruler' }),
        item(t('المباني السكنية', 'Residential buildings'), { text: t('عمارات وفلل ومجمعات', 'Apartments, villas and compounds'), icon: 'house' }),
        item(t('المشاريع التجارية', 'Commercial projects'), { text: t('مكاتب ومراكز تسوق ومستودعات', 'Offices, malls and warehouses'), icon: 'building-2' }),
        item(t('البنية التحتية', 'Infrastructure'), { text: t('طرق وجسور وشبكات مياه', 'Roads, bridges and water networks'), icon: 'construction' }),
        item(t('الترميم', 'Restoration'), { text: t('ترميم المباني التراثية', 'Restoring heritage buildings'), icon: 'hammer' }),
        item(t('إدارة المشاريع', 'Project management'), { text: t('إشراف وجدولة وضبط تكاليف', 'Supervision, scheduling and cost control'), icon: 'hard-hat' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '20', label: t('عامًا من الخبرة', 'years of experience') },
      { value: '340', label: t('مشروعًا مسلَّمًا', 'projects delivered') },
      { value: '120', label: t('مهندسًا وفنيًا', 'engineers and technicians') },
      { value: '0', label: t('حوادث في ٢٠٢٥', 'accidents in 2025') },
    ] },
    {
      kind: 'items', id: 'projects', nav: t('المشاريع', 'Projects'), role: 'gallery',
      eyebrow: t('المشاريع', 'Projects'),
      title: t('أعمال نفخر بها', 'Work we are proud of'),
      items: [
        item(t('برج الماصيون', 'Masyoun Tower'), { meta: t('تجاري · ٢٢ طابقًا', 'Commercial · 22 floors'), img: 500 }),
        item(t('مجمع الريحان', 'Rihan Compound'), { meta: t('سكني · ١٨٠ شقة', 'Residential · 180 units'), img: 1031 }),
        item(t('مركز المؤتمرات', 'Convention Centre'), { meta: t('عام · ١٢ ألف م²', 'Public · 12,000 m²'), img: 444 }),
        item(t('محطة الحافلات', 'Bus Terminal'), { meta: t('بنية تحتية', 'Infrastructure'), img: 616 }),
        item(t('جسر الوادي', 'Wadi Bridge'), { meta: t('طرق وجسور', 'Roads & bridges'), img: 134 }),
        item(t('مكاتب الإرسال', 'Irsal Offices'), { meta: t('تجاري · ٩ طوابق', 'Commercial · 9 floors'), img: 887 }),
      ],
    },
    {
      kind: 'items', id: 'process', role: 'process',
      eyebrow: t('طريقة العمل', 'How we work'),
      title: t('أربع مراحل واضحة', 'Four clear stages'),
      items: [
        item(t('الدراسة', 'Study'), { text: t('زيارة الموقع ودراسة الجدوى والتربة', 'Site visit, feasibility and soil study'), icon: 'search' }),
        item(t('التصميم', 'Design'), { text: t('مخططات كاملة ونموذج ثلاثي الأبعاد', 'Full drawings and a 3D model'), icon: 'pencil-ruler' }),
        item(t('التنفيذ', 'Build'), { text: t('جدول زمني وتقارير أسبوعية', 'A schedule and weekly reports'), icon: 'hard-hat' }),
        item(t('التسليم', 'Handover'), { text: t('فحص نهائي وضمان عشر سنوات', 'Final inspection and a ten-year warranty'), icon: 'key' }),
      ],
    },
    {
      kind: 'testimonials', id: 'clients',
      eyebrow: t('عملاؤنا', 'Clients'),
      title: t('ثقة نبنيها مشروعًا بعد مشروع', 'Trust built project by project'),
      items: [
        { quote: t('سلّموا المجمع قبل الموعد بثلاثة أسابيع، والتقارير الأسبوعية جعلتنا نعرف كل شيء أولًا بأول.', 'They handed over the compound three weeks early, and the weekly reports kept us informed at every step.'), name: t('م. سهام الأحمد', 'Eng. Siham Al-Ahmad'), role: t('مجموعة الريحان العقارية', 'Rihan Real Estate Group') },
        { quote: t('أصعب ما في الترميم هو احترام الحجر القديم، وفريق أساس فعل ذلك بإتقان.', 'The hardest part of restoration is respecting old stone, and the Asas team did it with real skill.'), name: t('د. يوسف عابد', 'Dr. Yousef Abed'), role: t('بلدية بيت لحم', 'Bethlehem Municipality') },
        { quote: t('شفافية في التكاليف من أول يوم، دون مفاجآت في النهاية.', 'Transparent costs from day one, with no surprises at the end.'), name: t('رامي جبر', 'Rami Jaber'), role: t('شركة جبر للتجارة', 'Jaber Trading') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل معنا', 'Contact us'),
      title: t('لنبدأ مشروعك', 'Let\'s start your project'),
      text: t('أرسل لنا تفاصيل مشروعك ونعود إليك بزيارة ودراسة أولية مجانية خلال ثلاثة أيام عمل.', 'Send us your project details and we\'ll come back with a free visit and initial study within three working days.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'projects@asas.example',
      address: t('عمارة أساس، الماصيون، رام الله', 'Asas Building, Al-Masyoun, Ramallah'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('08:00 – 16:00') },
      ],
      cta: t('اطلب عرض سعر', 'Request a quote'),
    },
  ],
};

export const agency: Profile = {
  id: 'agency',
  label: t('وكالة إبداعية', 'Creative agency'),
  brand: t('مِداد', 'Midad'),
  mark: t('م', 'M'),
  tagline: t('هويات ومواقع لعلامات تعرف ماذا تريد', 'Identities and websites for brands that know what they want'),
  navCta: t('ابدأ مشروعًا', 'Start a project'),
  socials: ['instagram', 'behance', 'linkedin'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('استوديو تصميم · رام الله', 'Design studio · Ramallah'),
      title: t('نصمّم علامات يتذكّرها الناس', 'We design brands people remember'),
      lead: t('هويات بصرية، مواقع، وحملات للشركات العربية التي تريد أن تبدو بحجم طموحها. صغار بما يكفي لنهتم بكل تفصيلة.', 'Visual identities, websites and campaigns for Arab companies that want to look as big as their ambition. Small enough to care about every detail.'),
      cta: t('ابدأ مشروعًا', 'Start a project'),
      cta2: t('شاهد أعمالنا', 'See our work'),
      img: 526, imgs: [252, 534, 464],
      badge: t('منذ ٢٠١٦', 'Since 2016'),
    },
    { kind: 'marquee', items: [t('هويات بصرية', 'Brand identity'), t('مواقع', 'Websites'), t('تغليف', 'Packaging'), t('حملات', 'Campaigns'), t('خطوط عربية', 'Arabic type'), t('موشن', 'Motion')] },
    {
      kind: 'about', id: 'studio', nav: t('الاستوديو', 'Studio'),
      eyebrow: t('الاستوديو', 'The studio'),
      title: t('تسعة أشخاص، وطاولة واحدة طويلة', 'Nine people and one long table'),
      text: [
        t('نعمل مع عدد قليل من العملاء في الوقت نفسه، لأن الأفكار الجيدة تحتاج انتباهًا كاملًا.', 'We work with a few clients at a time, because good ideas need full attention.'),
        t('نؤمن أن الحرف العربي يستحق أن يكون في قلب الهوية لا ترجمة لها، فنرسم الشعارات العربية واللاتينية معًا.', 'We believe Arabic letters deserve to be at the heart of an identity, not a translation of it, so we draw Arabic and Latin logos together.'),
      ],
      img: 534, img2: 20,
      quote: t('التصميم الجيد يحل مشكلة قبل أن يزيّن صفحة.', 'Good design solves a problem before it decorates a page.'),
      sign: t('ريم عوّاد، المديرة الإبداعية', 'Reem Awwad, creative director'),
    },
    {
      kind: 'items', id: 'services', nav: t('الخدمات', 'Services'), role: 'offer',
      eyebrow: t('ماذا نفعل', 'What we do'),
      title: t('من الفكرة إلى الإطلاق', 'From idea to launch'),
      items: [
        item(t('الهوية البصرية', 'Brand identity'), { text: t('شعار ثنائي اللغة، ألوان، خطوط ودليل استخدام', 'Bilingual logo, colours, type and guidelines'), icon: 'pen-tool', img: 252 }),
        item(t('المواقع الإلكترونية', 'Websites'), { text: t('تصميم وتطوير مواقع سريعة بالعربية والإنجليزية', 'Fast Arabic and English websites, designed and built'), icon: 'monitor', img: 370 }),
        item(t('التغليف', 'Packaging'), { text: t('علب وملصقات تبيع من الرف', 'Boxes and labels that sell from the shelf'), icon: 'package', img: 526 }),
        item(t('الحملات', 'Campaigns'), { text: t('أفكار ومحتوى للسوشال ميديا والشارع', 'Ideas and content for social media and the street'), icon: 'megaphone', img: 855 }),
      ],
    },
    {
      kind: 'items', id: 'work', nav: t('الأعمال', 'Work'), role: 'gallery',
      eyebrow: t('أعمال مختارة', 'Selected work'),
      title: t('مشاريع حديثة', 'Recent projects'),
      items: [
        item(t('دار نشر الفجر', 'Al-Fajr Publishing'), { meta: t('هوية · كتب', 'Identity · Books'), img: 464 }),
        item(t('قهوة حبّة', 'Habba Coffee'), { meta: t('تغليف', 'Packaging'), img: 526 }),
        item(t('مهرجان الخط', 'Calligraphy Festival'), { meta: t('حملة', 'Campaign'), img: 252 }),
        item(t('مكتب أسس', 'Osos Office'), { meta: t('موقع', 'Website'), img: 528 }),
        item(t('معرض اللون', 'Colour Show'), { meta: t('معرض', 'Exhibition'), img: 1068 }),
        item(t('ستوديو صدى', 'Sada Studio'), { meta: t('هوية صوتية', 'Sound identity'), img: 529 }),
      ],
    },
    { kind: 'logos', title: t('عملنا مع', 'We\'ve worked with'), items: ['AL-FAJR', 'HABBA', 'SADA', 'OSOS', 'NOOR BANK', 'MADAR'] },
    {
      kind: 'items', id: 'process', role: 'process',
      eyebrow: t('طريقتنا', 'Our process'),
      title: t('أربعة أسابيع إلى هوية كاملة', 'Four weeks to a full identity'),
      items: [
        item(t('نستمع', 'Listen'), { text: t('ورشة يوم كامل مع فريقك', 'A full-day workshop with your team'), icon: 'messages-square' }),
        item(t('نستكشف', 'Explore'), { text: t('ثلاثة اتجاهات مختلفة', 'Three distinct directions'), icon: 'compass' }),
        item(t('نصقل', 'Refine'), { text: t('اتجاه واحد حتى أدق تفصيلة', 'One direction, down to the last detail'), icon: 'sparkles' }),
        item(t('نسلّم', 'Deliver'), { text: t('ملفات ودليل وتدريب لفريقك', 'Files, guidelines and training for your team'), icon: 'package-check' }),
      ],
    },
    {
      kind: 'testimonials', id: 'clients',
      eyebrow: t('آراء العملاء', 'Clients say'),
      title: t('شركاء لا مورّدون', 'Partners, not suppliers'),
      items: [
        { quote: t('فهموا ما نريد قبل أن نعرف كيف نقوله. الهوية الجديدة رفعت مبيعاتنا ٣٠٪ في ستة أشهر.', 'They understood what we wanted before we knew how to say it. The new identity lifted our sales by 30% in six months.'), name: t('علا مصطفى', 'Ola Mustafa'), role: t('مؤسسة قهوة حبّة', 'Founder, Habba Coffee') },
        { quote: t('أول وكالة ترسم شعارًا عربيًا يقف بجانب اللاتيني بندّية.', 'The first agency to draw an Arabic logo that stands as an equal next to the Latin one.'), name: t('زياد قطّان', 'Ziad Qattan'), role: t('دار الفجر للنشر', 'Al-Fajr Publishing') },
        { quote: t('دقيقون في المواعيد بشكل نادر.', 'Rarely have I seen a studio this punctual.'), name: t('لمى ياسين', 'Lama Yassin'), role: t('بنك النور', 'Noor Bank') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('لنتحدث', 'Let\'s talk'),
      title: t('عندك مشروع؟', 'Have a project?'),
      text: t('أخبرنا عن فكرتك وميزانيتك التقريبية، ونرد خلال يومين.', 'Tell us about your idea and rough budget, and we\'ll reply within two days.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'hello@midad.example',
      address: t('الطابق الثالث، شارع ركب، رام الله', '3rd floor, Rukab Street, Ramallah'),
      hours: [
        { d: t('الأحد – الخميس', 'Sun – Thu'), t: same('09:00 – 17:00') },
      ],
      cta: t('احجز مكالمة', 'Book a call'),
    },
  ],
};

export const software: Profile = {
  id: 'software',
  label: t('شركة برمجيات', 'Software company'),
  brand: t('نواة', 'Nawa'),
  mark: t('ن', 'N'),
  tagline: t('برمجيات وسحابة للشركات النامية', 'Software and cloud for growing companies'),
  navCta: t('احجز عرضًا', 'Book a demo'),
  socials: ['linkedin', 'x'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('برمجيات حسب الطلب', 'Custom software'),
      title: t('برمجيات تعمل كما تعمل شركتك', 'Software that works the way you do'),
      lead: t('نبني أنظمة إدارة وتطبيقات وواجهات برمجية آمنة وقابلة للتوسع، ونستضيفها ونراقبها على مدار الساعة.', 'We build secure, scalable management systems, apps and APIs, then host and monitor them around the clock.'),
      cta: t('احجز عرضًا', 'Book a demo'),
      cta2: t('دراسات حالة', 'Case studies'),
      img: 60, imgs: [668, 352, 1078],
      badge: t('٩٩٫٩٨٪ وقت تشغيل', '99.98% uptime'),
    },
    { kind: 'logos', title: t('تثق بنا', 'Trusted by'), items: ['PALPAY', 'MADAR', 'JAWWAL CLOUD', 'NOOR BANK', 'ASAS', 'SANAD'] },
    {
      kind: 'about', id: 'about', nav: t('عن نواة', 'About'),
      eyebrow: t('عن نواة', 'About Nawa'),
      title: t('فريق هندسي صغير بخبرة كبيرة', 'A small engineering team with big experience'),
      text: [
        t('أربعون مهندسًا في رام الله ونابلس وغزة، عملوا سابقًا في شركات عالمية واختاروا البناء من هنا.', 'Forty engineers in Ramallah, Nablus and Gaza who worked for global companies and chose to build from here.'),
        t('نكتب كودًا مختبرًا وموثقًا، ونسلّمك ملكيته الكاملة. لا عقود احتكار ولا صناديق سوداء.', 'We write tested, documented code and hand you full ownership. No lock-in contracts, no black boxes.'),
      ],
      img: 0, img2: 366,
      quote: t('أفضل نظام هو الذي لا تشعر بوجوده.', 'The best system is the one you never notice.'),
      sign: t('سامي النتشة، المدير التقني', 'Sami Natsheh, CTO'),
    },
    {
      kind: 'items', id: 'services', nav: t('الحلول', 'Solutions'), role: 'offer',
      eyebrow: t('الحلول', 'Solutions'),
      title: t('ما نبنيه لعملائنا', 'What we build'),
      items: [
        item(t('أنظمة ERP', 'ERP systems'), { text: t('محاسبة ومخزون وموارد بشرية في نظام واحد', 'Accounting, inventory and HR in one system'), icon: 'layers' }),
        item(t('تطبيقات الجوال', 'Mobile apps'), { text: t('iOS وأندرويد بكود واحد', 'iOS and Android from one codebase'), icon: 'smartphone' }),
        item(t('واجهات برمجية', 'APIs & integrations'), { text: t('ربط البنوك وبوابات الدفع والأنظمة الحكومية', 'Banks, payment gateways and government systems'), icon: 'code' }),
        item(t('الاستضافة السحابية', 'Cloud hosting'), { text: t('خوادم مُدارة ونسخ احتياطي يومي', 'Managed servers and daily backups'), icon: 'cloud' }),
        item(t('الأمن السيبراني', 'Cybersecurity'), { text: t('اختبار اختراق ومراقبة مستمرة', 'Penetration testing and continuous monitoring'), icon: 'shield-check' }),
        item(t('الذكاء الاصطناعي', 'AI features'), { text: t('بحث ذكي وتلخيص ومساعدين بالعربية', 'Smart search, summaries and Arabic assistants'), icon: 'cpu' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '99.98%', label: t('وقت التشغيل', 'uptime') },
      { value: '140+', label: t('نظامًا في الإنتاج', 'systems in production') },
      { value: '40', label: t('مهندسًا', 'engineers') },
      { value: '15m', label: t('زمن الاستجابة للأعطال', 'incident response') },
    ] },
    {
      kind: 'items', id: 'plans', nav: t('الباقات', 'Plans'), role: 'pricing',
      eyebrow: t('الدعم والاستضافة', 'Support & hosting'),
      title: t('باقات شهرية واضحة', 'Clear monthly plans'),
      items: [
        item(t('أساسي', 'Starter'), { price: '$290', meta: t('شهريًا', 'per month'), list: [t('خادم مُدار واحد', 'One managed server'), t('نسخ احتياطي يومي', 'Daily backups'), t('دعم بالبريد', 'Email support')] }),
        item(t('نمو', 'Growth'), { price: '$790', meta: t('شهريًا', 'per month'), featured: true, tag: t('الأكثر اختيارًا', 'Most chosen'), list: [t('ثلاثة خوادم', 'Three servers'), t('مراقبة ٢٤/٧', '24/7 monitoring'), t('دعم خلال ساعة', 'One-hour support'), t('١٠ ساعات تطوير', '10 development hours')] }),
        item(t('مؤسسات', 'Enterprise'), { price: t('حسب الطلب', 'Custom'), meta: t('سنويًا', 'per year'), list: [t('بنية مخصصة', 'Custom infrastructure'), t('اتفاقية مستوى خدمة', 'Service-level agreement'), t('فريق مخصص', 'Dedicated team')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'cases',
      eyebrow: t('دراسات حالة', 'Case studies'),
      title: t('نتائج يمكن قياسها', 'Results you can measure'),
      items: [
        { quote: t('نظام المخزون الجديد خفّض أخطاء الطلبات ٨٠٪، والفريق تعلّمه في يومين.', 'The new inventory system cut order errors by 80%, and the team learned it in two days.'), name: t('هاني الشريف', 'Hani Al-Sharif'), role: t('مدير العمليات، سند', 'COO, Sanad') },
        { quote: t('منذ انتقلنا إلى استضافتهم لم نتعرض لانقطاع واحد في موسم الذروة.', 'Since moving to their hosting we haven\'t had a single outage in peak season.'), name: t('ديما عاروري', 'Dima Arouri'), role: t('بال باي', 'PalPay') },
        { quote: t('يشرحون التقنية بلغة يفهمها مجلس الإدارة.', 'They explain technology in language the board understands.'), name: t('نبيل صبّاغ', 'Nabil Sabbagh'), role: t('بنك النور', 'Noor Bank') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة شائعة', 'FAQ'),
      title: t('قبل أن تسأل', 'Before you ask'),
      items: [
        { q: t('من يملك الكود؟', 'Who owns the code?'), a: t('أنت. نسلّم المستودع كاملًا مع التوثيق في نهاية كل مرحلة.', 'You do. We hand over the full repository with documentation at the end of every phase.') },
        { q: t('كم يستغرق بناء نظام؟', 'How long does a system take?'), a: t('أول نسخة قابلة للاستخدام خلال ٦–١٠ أسابيع عادة.', 'A first usable version usually takes 6–10 weeks.') },
        { q: t('هل تعملون مع شركات خارج فلسطين؟', 'Do you work with companies abroad?'), a: t('نعم، ثلث عملائنا في الخليج وأوروبا.', 'Yes, a third of our clients are in the Gulf and Europe.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('لنتحدث عن نظامك', 'Let\'s talk about your system'),
      text: t('احجز عرضًا مدته ثلاثون دقيقة مع أحد مهندسينا.', 'Book a 30-minute demo with one of our engineers.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'sales@nawa.example',
      address: t('مجمع التكنولوجيا، البيرة', 'Tech Park, Al-Bireh'),
      hours: [
        { d: t('الدعم', 'Support'), t: same('24/7') },
        { d: t('المبيعات', 'Sales'), t: t('الأحد – الخميس، ٩–٥', 'Sun – Thu, 9–5') },
      ],
      cta: t('احجز عرضًا', 'Book a demo'),
    },
  ],
};

export const clinic: Profile = {
  id: 'clinic',
  label: t('عيادة', 'Clinic'),
  brand: t('عيادة بسمة', 'Basma Clinic'),
  mark: t('ب', 'B'),
  tagline: t('طب أسنان هادئ للعائلة كلها', 'Calm dentistry for the whole family'),
  navCta: t('احجز موعدًا', 'Book a visit'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('طب الأسنان · الخليل', 'Dental care · Hebron'),
      title: t('ابتسامة بلا خوف', 'A smile without fear'),
      lead: t('عيادة أسنان حديثة بأجهزة رقمية وتخدير بلا ألم، وفريق يشرح لك كل خطوة قبل أن يبدأ. للأطفال والكبار.', 'A modern dental clinic with digital equipment, painless anaesthesia and a team that explains every step before starting. For children and adults.'),
      cta: t('احجز موعدًا', 'Book a visit'),
      cta2: t('خدماتنا', 'Our services'),
      img: 1068, imgs: [954, 798, 830],
      badge: t('أول استشارة مجانًا', 'First consultation free'),
    },
    {
      kind: 'about', id: 'about', nav: t('العيادة', 'Clinic'),
      eyebrow: t('العيادة', 'The clinic'),
      title: t('صُمّمت لتهدئ أعصابك', 'Designed to calm your nerves'),
      text: [
        t('ضوء طبيعي، موسيقى هادئة، ولا روائح عيادات. نحجز لكل مريض وقتًا كافيًا فلا يطول انتظارك.', 'Natural light, quiet music and none of the usual clinic smells. Every patient gets enough time, so you never wait long.'),
        t('د. بسمة الجعبري وفريقها من أربعة أطباء متخصصين في التقويم وزراعة الأسنان وطب أسنان الأطفال.', 'Dr. Basma Al-Jaabari and her four specialists in orthodontics, implants and paediatric dentistry.'),
      ],
      img: 954, img2: 798,
      quote: t('المريض المطمئن نصف العلاج.', 'A reassured patient is half the treatment.'),
      sign: t('د. بسمة الجعبري', 'Dr. Basma Al-Jaabari'),
    },
    {
      kind: 'items', id: 'services', nav: t('الخدمات', 'Services'), role: 'offer',
      eyebrow: t('الخدمات', 'Services'),
      title: t('كل ما تحتاجه أسنانك', 'Everything your teeth need'),
      items: [
        item(t('فحص وتنظيف', 'Check-up & cleaning'), { text: t('كل ستة أشهر، مع صور رقمية', 'Every six months, with digital X-rays'), icon: 'smile' }),
        item(t('تقويم شفاف', 'Clear aligners'), { text: t('تقويم غير مرئي بخطة رقمية', 'Invisible aligners with a digital plan'), icon: 'sparkles' }),
        item(t('زراعة الأسنان', 'Implants'), { text: t('زرعات أوروبية بضمان مدى الحياة', 'European implants with a lifetime warranty'), icon: 'shield-check' }),
        item(t('تبييض', 'Whitening'), { text: t('جلسة واحدة في العيادة', 'One session in the clinic'), icon: 'sun' }),
        item(t('أسنان الأطفال', 'Children\'s dentistry'), { text: t('غرفة ألعاب وأطباء صبورون', 'A play room and patient doctors'), icon: 'baby' }),
        item(t('طوارئ', 'Emergencies'), { text: t('موعد في اليوم نفسه', 'Same-day appointments'), icon: 'heart-pulse' }),
      ],
    },
    {
      kind: 'items', id: 'visit', role: 'process',
      eyebrow: t('زيارتك الأولى', 'Your first visit'),
      title: t('ثلاث خطوات بسيطة', 'Three simple steps'),
      items: [
        item(t('احجز', 'Book'), { text: t('عبر واتساب أو الهاتف', 'On WhatsApp or by phone'), icon: 'calendar' }),
        item(t('افحص', 'Check'), { text: t('فحص وصور رقمية في ٢٠ دقيقة', 'Exam and digital X-rays in 20 minutes'), icon: 'stethoscope' }),
        item(t('خطة واضحة', 'A clear plan'), { text: t('خطة علاج مكتوبة بالسعر قبل أي إجراء', 'A written, priced plan before anything happens'), icon: 'file-text' }),
      ],
    },
    {
      kind: 'items', id: 'prices', nav: t('الأسعار', 'Prices'), role: 'pricing',
      eyebrow: t('الأسعار', 'Prices'),
      title: t('أسعار معلنة بلا مفاجآت', 'Published prices, no surprises'),
      items: [
        item(t('فحص وتنظيف', 'Check-up & cleaning'), { price: '150 ₪', meta: t('للجلسة', 'per visit'), list: [t('صور رقمية', 'Digital X-rays'), t('تلميع', 'Polishing'), t('خطة وقائية', 'Prevention plan')] }),
        item(t('تقويم شفاف', 'Clear aligners'), { price: '6,500 ₪', meta: t('للخطة كاملة', 'full plan'), featured: true, tag: t('تقسيط ١٢ شهرًا', '12-month instalments'), list: [t('مسح ثلاثي الأبعاد', '3D scan'), t('كل القوالب', 'All aligners'), t('زيارات المتابعة', 'Follow-up visits')] }),
        item(t('زرعة سن', 'Single implant'), { price: '2,800 ₪', meta: t('للسن', 'per tooth'), list: [t('زرعة وتاج', 'Implant and crown'), t('ضمان مدى الحياة', 'Lifetime warranty')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('مرضانا', 'Our patients'),
      title: t('من كان يخاف، صار يأتي مبتسمًا', 'Those who were afraid now come smiling'),
      items: [
        { quote: t('كنت أؤجل علاجي سنوات من الخوف. هنا شرحوا كل شيء ولم أشعر بأي ألم.', 'I put off treatment for years out of fear. Here they explained everything and I felt no pain at all.'), name: t('إيمان التميمي', 'Iman Tamimi'), role: t('مريضة تقويم', 'Aligner patient') },
        { quote: t('ابني يسأل متى موعد الطبيبة القادم. هذا وحده يكفي.', 'My son asks when his next visit is. That says it all.'), name: t('حسام قفيشة', 'Hussam Qafisheh'), role: t('أب', 'Father') },
        { quote: t('السعر المكتوب في الخطة كان السعر النهائي فعلًا.', 'The price in the written plan really was the final price.'), name: t('أمل الشويكي', 'Amal Shweiki'), role: t('مريضة زراعة', 'Implant patient') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة شائعة', 'FAQ'),
      title: t('أسئلة يسألها الجميع', 'Questions everyone asks'),
      items: [
        { q: t('هل العلاج مؤلم؟', 'Does treatment hurt?'), a: t('نستخدم تخديرًا موضعيًا بجهاز رقمي بلا إبرة مؤلمة.', 'We use local anaesthesia delivered by a digital device, without a painful needle.') },
        { q: t('هل تقبلون التأمين؟', 'Do you accept insurance?'), a: t('نعم، نتعامل مع أغلب شركات التأمين المحلية.', 'Yes, we work with most local insurers.') },
        { q: t('من أي عمر تستقبلون الأطفال؟', 'From what age do you see children?'), a: t('من سن الثالثة، ونوصي بالزيارة الأولى قبلها.', 'From age three; we recommend a first visit even earlier.') },
      ],
    },
    {
      kind: 'contact', id: 'book', nav: t('احجز', 'Book'),
      eyebrow: t('احجز', 'Book'),
      title: t('موعدك خلال يومين', 'An appointment within two days'),
      text: t('أرسل اسمك ووقتك المفضل عبر واتساب، ونؤكد الموعد خلال ساعة.', 'Send your name and preferred time on WhatsApp and we\'ll confirm within the hour.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'care@basma.example',
      address: t('عين سارة، بناية الأمل، الخليل', 'Al-Amal Building, Ein Sara, Hebron'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('09:00 – 19:00') },
        { d: t('الجمعة', 'Friday'), t: t('طوارئ فقط', 'Emergencies only') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const law: Profile = {
  id: 'law',
  label: t('مكتب محاماة', 'Law firm'),
  brand: t('العدل وشركاه', 'Al-Adl & Partners'),
  mark: t('ع', 'A'),
  tagline: t('محاماة واستشارات قانونية منذ ١٩٩١', 'Advocates and legal counsel since 1991'),
  navCta: t('احجز استشارة', 'Book a consultation'),
  socials: ['linkedin'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('محاماة واستشارات قانونية', 'Advocates & legal counsel'),
      title: t('حقك في أيدٍ أمينة', 'Your rights, in safe hands'),
      lead: t('نمثّل الشركات والأفراد أمام المحاكم الفلسطينية، ونصيغ العقود ونحمي الاستثمارات، بخبرة ثلاثين عامًا وسرية تامة.', 'We represent companies and individuals before Palestinian courts, draft contracts and protect investments, with thirty years of experience and complete confidentiality.'),
      cta: t('احجز استشارة', 'Book a consultation'),
      cta2: t('مجالات الممارسة', 'Practice areas'),
      img: 856, imgs: [24, 378, 998],
      badge: t('منذ ١٩٩١', 'Since 1991'),
    },
    {
      kind: 'about', id: 'firm', nav: t('المكتب', 'The firm'),
      eyebrow: t('المكتب', 'The firm'),
      title: t('ثلاثة عقود من الدفاع عن الحق', 'Three decades of standing for what\'s right'),
      text: [
        t('أسس المكتب المحامي عادل الحسيني عام ١٩٩١، ويضم اليوم أحد عشر محاميًا ومستشارًا في القدس ورام الله.', 'Founded by advocate Adel Al-Husseini in 1991, the firm now has eleven lawyers and counsel in Jerusalem and Ramallah.'),
        t('نقدّم رأيًا قانونيًا صريحًا ومكتوبًا، ونخبرك بفرصك الحقيقية قبل أن تبدأ أي قضية.', 'We give frank, written legal opinions and tell you your real chances before any case begins.'),
      ],
      img: 24, img2: 998,
      quote: t('العدل لا يتجزأ.', 'Justice is indivisible.'),
      sign: t('المحامي عادل الحسيني، الشريك المؤسس', 'Adel Al-Husseini, founding partner'),
    },
    {
      kind: 'items', id: 'practice', nav: t('الممارسة', 'Practice'), role: 'offer',
      eyebrow: t('مجالات الممارسة', 'Practice areas'),
      title: t('خبرة في القضايا التي تهمك', 'Expertise where it matters to you'),
      items: [
        item(t('قانون الشركات', 'Corporate law'), { text: t('تأسيس، اندماج، حوكمة', 'Formation, mergers and governance'), icon: 'briefcase' }),
        item(t('العقود التجارية', 'Commercial contracts'), { text: t('صياغة ومراجعة وتفاوض', 'Drafting, review and negotiation'), icon: 'file-text' }),
        item(t('التقاضي', 'Litigation'), { text: t('أمام المحاكم بدرجاتها', 'Before courts at every level'), icon: 'gavel' }),
        item(t('العقارات والأراضي', 'Real estate & land'), { text: t('تسجيل، إفراز، نزاعات ملكية', 'Registration, subdivision and title disputes'), icon: 'landmark' }),
        item(t('قانون العمل', 'Employment law'), { text: t('عقود ولوائح ونزاعات عمالية', 'Contracts, policies and labour disputes'), icon: 'users' }),
        item(t('الأحوال الشخصية', 'Family law'), { text: t('ميراث ووصايا وحضانة', 'Inheritance, wills and custody'), icon: 'scale' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '33', label: t('عامًا من الممارسة', 'years of practice') },
      { value: '2,400+', label: t('قضية', 'cases') },
      { value: '11', label: t('محاميًا ومستشارًا', 'lawyers and counsel') },
      { value: '2', label: t('مكتبان', 'offices') },
    ] },
    {
      kind: 'items', id: 'approach', role: 'process',
      eyebrow: t('منهجنا', 'Our approach'),
      title: t('كيف نعمل على قضيتك', 'How we handle your matter'),
      items: [
        item(t('استشارة أولى', 'First consultation'), { text: t('نستمع ونطلب المستندات', 'We listen and request documents'), icon: 'messages-square' }),
        item(t('رأي مكتوب', 'Written opinion'), { text: t('تقييم صريح للفرص والتكاليف', 'A frank assessment of chances and costs'), icon: 'file-text' }),
        item(t('خطة وتمثيل', 'Plan & representation'), { text: t('نتابع كل جلسة ونطلعك أولًا بأول', 'We attend every hearing and keep you informed'), icon: 'gavel' }),
      ],
    },
    {
      kind: 'testimonials', id: 'clients',
      eyebrow: t('عملاؤنا', 'Clients'),
      title: t('ثقة تُكتسب بالنتائج', 'Trust earned through results'),
      items: [
        { quote: t('أنهوا نزاع الأرض الذي استمر عشر سنوات بتسوية عادلة خلال ثمانية أشهر.', 'They settled a ten-year land dispute fairly within eight months.'), name: t('عائلة الخطيب', 'The Al-Khatib family'), role: t('قضية عقارية', 'Real estate case') },
        { quote: t('مستشارنا القانوني منذ تأسيس الشركة. دقة ووضوح وسرعة في الرد.', 'Our legal counsel since the company was founded. Precise, clear and quick to respond.'), name: t('م. طارق العلمي', 'Eng. Tareq Al-Alami'), role: t('شركة العلمي للصناعات', 'Alami Industries') },
        { quote: t('أخبروني بصراحة أن قضيتي ضعيفة ووفّروا عليّ وقتًا ومالًا.', 'They told me honestly my case was weak and saved me time and money.'), name: t('سليم دجاني', 'Salim Dajani'), role: t('عميل', 'Client') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة شائعة', 'FAQ'),
      title: t('ما تحتاج معرفته', 'What you need to know'),
      items: [
        { q: t('كم تكلّف الاستشارة الأولى؟', 'How much is the first consultation?'), a: t('٣٠٠ شيكل لساعة كاملة، تُخصم من الأتعاب إن توكّلنا القضية.', '300 shekels for a full hour, deducted from fees if we take the case.') },
        { q: t('هل معلوماتي سرية؟', 'Is my information confidential?'), a: t('بالكامل، بحكم القانون وأخلاقيات المهنة.', 'Completely, by law and professional ethics.') },
        { q: t('هل تعملون عن بُعد؟', 'Do you work remotely?'), a: t('نعم، للاستشارات ومراجعة العقود.', 'Yes, for consultations and contract review.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('احجز استشارتك', 'Book your consultation'),
      text: t('اتصل بنا أو أرسل رسالة، وسيعود إليك أحد الشركاء خلال يوم عمل.', 'Call or send a message and a partner will get back to you within one working day.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'office@aladl.example',
      address: t('شارع صلاح الدين ٤٥، القدس', '45 Salah Al-Din Street, Jerusalem'),
      hours: [
        { d: t('الاثنين – الجمعة', 'Mon – Fri'), t: same('08:30 – 16:30') },
        { d: t('السبت', 'Saturday'), t: t('بموعد مسبق', 'By appointment') },
      ],
      cta: t('احجز استشارة', 'Book a consultation'),
    },
  ],
};

export const realestate: Profile = {
  id: 'realestate',
  label: t('عقارات', 'Real estate'),
  brand: t('سكن', 'Sakan'),
  mark: t('س', 'S'),
  tagline: t('بيوت تختارك بقدر ما تختارها', 'Homes that choose you as much as you choose them'),
  navCta: t('ابحث عن بيت', 'Find a home'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('بيع وإيجار عقارات', 'Homes for sale & rent'),
      title: t('بيتك القادم أقرب مما تظن', 'Your next home is closer than you think'),
      lead: t('شقق وفلل وأراضٍ موثّقة في رام الله ونابلس وبيت لحم، بزيارات مرافَقة ومساعدة في التمويل والأوراق.', 'Verified apartments, villas and land in Ramallah, Nablus and Bethlehem, with accompanied viewings and help with financing and paperwork.'),
      cta: t('ابحث عن بيت', 'Find a home'),
      cta2: t('اعرض عقارك', 'List your property'),
      img: 625, imgs: [514, 1008, 764],
      badge: t('٣٢٠ عقارًا متاحًا', '320 listings'),
    },
    {
      kind: 'items', id: 'listings', nav: t('العقارات', 'Listings'), role: 'offer',
      eyebrow: t('عقارات مختارة', 'Featured listings'),
      title: t('أحدث ما وصلنا', 'Just listed'),
      items: [
        item(t('شقة في الطيرة', 'Apartment in Al-Tireh'), { text: t('٣ غرف · ١٦٥ م² · إطلالة', '3 bed · 165 m² · view'), price: '$185,000', meta: t('رام الله', 'Ramallah'), img: 1008, tag: t('جديد', 'New') }),
        item(t('فيلا مع حديقة', 'Villa with garden'), { text: t('٥ غرف · ٤٢٠ م² · مسبح', '5 bed · 420 m² · pool'), price: '$640,000', meta: t('بيت جالا', 'Beit Jala'), img: 116 }),
        item(t('بيت حجري قديم', 'Old stone house'), { text: t('مرمّم · ٢٢٠ م² · ساحة', 'Restored · 220 m² · courtyard'), price: '$310,000', meta: t('نابلس', 'Nablus'), img: 946 }),
        item(t('شقة للإيجار', 'Apartment for rent'), { text: t('غرفتان · مفروشة', '2 bed · furnished'), price: '$650', meta: t('شهريًا، البيرة', 'per month, Al-Bireh'), img: 625 }),
        item(t('مكاتب تجارية', 'Office floor'), { text: t('٣٠٠ م² · موقف سيارات', '300 m² · parking'), price: '$420,000', meta: t('الماصيون', 'Al-Masyoun'), img: 764 }),
        item(t('بيت عائلي', 'Family house'), { text: t('٤ غرف · ٢٦٠ م²', '4 bed · 260 m²'), price: '$355,000', meta: t('بيرزيت', 'Birzeit'), img: 514 }),
      ],
    },
    { kind: 'stats', items: [
      { value: '320', label: t('عقارًا متاحًا', 'listings available') },
      { value: '1,100+', label: t('عائلة وجدت بيتها', 'families housed') },
      { value: '14', label: t('عامًا في السوق', 'years in the market') },
      { value: '48h', label: t('لترتيب زيارة', 'to arrange a viewing') },
    ] },
    {
      kind: 'about', id: 'about', nav: t('عنّا', 'About'),
      eyebrow: t('لماذا سكن', 'Why Sakan'),
      title: t('كل عقار نعرضه زرناه بأنفسنا', 'We\'ve visited every home we list'),
      text: [
        t('نتحقق من الأوراق والملكية ونصوّر العقار كما هو، دون فلاتر تخدعك.', 'We check the papers and ownership and photograph each property as it is, with no filters to fool you.'),
        t('مستشارونا يرافقونك من أول زيارة حتى توقيع العقد وتسجيله.', 'Our advisers stay with you from the first viewing to signing and registration.'),
      ],
      img: 1081, img2: 954,
      quote: t('البيت قرار عمر، لا صفقة.', 'A home is a life decision, not a deal.'),
      sign: t('ياسمين حمدان، المديرة', 'Yasmin Hamdan, director'),
    },
    {
      kind: 'items', id: 'services', role: 'extra',
      eyebrow: t('خدماتنا', 'Services'),
      title: t('أكثر من مجرد وسيط', 'More than a broker'),
      items: [
        item(t('تقييم العقار', 'Property valuation'), { text: t('تقييم مجاني بسعر السوق', 'A free market valuation'), icon: 'chart-line' }),
        item(t('التمويل', 'Financing'), { text: t('مقارنة عروض البنوك', 'Compare bank offers'), icon: 'wallet' }),
        item(t('الأوراق القانونية', 'Paperwork'), { text: t('تسجيل ونقل ملكية', 'Registration and transfer'), icon: 'file-text' }),
        item(t('إدارة الإيجار', 'Rental management'), { text: t('تحصيل وصيانة ومتابعة', 'Collection, upkeep and follow-up'), icon: 'key' }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('آراء', 'Reviews'),
      title: t('بيوت سعيدة', 'Happy homes'),
      items: [
        { quote: t('وجدوا لنا شقة بإطلالة على البحر في أسبوعين، وساعدونا في قرض البنك.', 'They found us a flat with a sea view in two weeks and helped with the bank loan.'), name: t('مالك وسناء', 'Malek & Sanaa'), role: t('مشترون جدد', 'First-time buyers') },
        { quote: t('بعت بيت أهلي بسعر عادل ودون أي تعقيد.', 'I sold my parents\' house at a fair price without any hassle.'), name: t('جورج قسيس', 'George Qassis'), role: t('بائع', 'Seller') },
        { quote: t('الصور كانت مطابقة تمامًا للواقع. نادرًا ما يحدث هذا.', 'The photos matched reality exactly. That rarely happens.'), name: t('ريما برغوثي', 'Rima Barghouti'), role: t('مستأجرة', 'Tenant') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('أخبرنا عن البيت الذي تحلم به', 'Tell us about the home you dream of'),
      text: t('المنطقة، الميزانية، عدد الغرف. نرسل لك الخيارات المناسبة خلال يوم.', 'Area, budget, number of rooms. We\'ll send matching options within a day.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'homes@sakan.example',
      address: t('شارع المعارف، رام الله', 'Al-Ma\'aref Street, Ramallah'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('09:00 – 18:00') },
      ],
      cta: t('تواصل عبر واتساب', 'Message on WhatsApp'),
    },
  ],
};

export const signage: Profile = {
  id: 'signage',
  label: t('دعاية وإعلان', 'Signage & print'),
  brand: t('لافتة', 'Lafta'),
  mark: t('ل', 'L'),
  tagline: t('يافطات ونيون وطباعة تلفت النظر', 'Signs, neon and print that turn heads'),
  navCta: t('اطلب تسعيرة', 'Get a price'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('ورشة دعاية وإعلان', 'Signage & print workshop'),
      title: t('اسمك يُرى من آخر الشارع', 'Your name, seen from the end of the street'),
      lead: t('يافطات محلات، حروف بارزة، نيون، ستيكرات، طباعة بأحجام كبيرة وحفر ليزر. من التصميم إلى التركيب، في ورشتنا.', 'Shop signs, 3D letters, neon, stickers, large-format print and laser engraving. From design to installation, all in our own workshop.'),
      cta: t('اطلب تسعيرة', 'Get a price'),
      cta2: t('أعمالنا', 'Our work'),
      img: 451, imgs: [274, 252, 946],
      badge: t('تركيب خلال ٧ أيام', 'Installed in 7 days'),
    },
    { kind: 'marquee', items: [t('يافطات', 'Shop signs'), t('نيون', 'Neon'), t('ستيكرات', 'Stickers'), t('فليكس', 'Flex banners'), t('ليزر', 'Laser'), t('CNC', 'CNC'), t('تغليف سيارات', 'Vehicle wraps')] },
    {
      kind: 'about', id: 'workshop', nav: t('الورشة', 'Workshop'),
      eyebrow: t('الورشة', 'The workshop'),
      title: t('كل الآلات تحت سقف واحد', 'Every machine under one roof'),
      text: [
        t('ليزر CO2 وفايبر، راوتر CNC، بلوتر قص، طابعات حتى عرض خمسة أمتار، وطابعة سبلميشن ومكبس حراري. لا نرسل شغلك لأحد.', 'CO2 and fibre lasers, a CNC router, a vinyl cutter, printers up to five metres wide, a sublimation printer and heat press. Your job never leaves our hands.'),
        t('لهذا نلتزم بالمواعيد، ونصلح أي خطأ في اليوم نفسه.', 'That\'s why we keep our deadlines and fix any mistake the same day.'),
      ],
      img: 491, img2: 527,
      quote: t('اليافطة الجيدة تبيع وأنت نائم.', 'A good sign sells while you sleep.'),
      sign: t('عمر، صاحب الورشة', 'Omar, owner'),
    },
    {
      kind: 'items', id: 'services', nav: t('الخدمات', 'Services'), role: 'offer',
      eyebrow: t('الخدمات', 'Services'),
      title: t('ماذا نصنع', 'What we make'),
      items: [
        item(t('يافطات المحلات', 'Shop signs'), { text: t('كلادينج وحروف بارزة مضيئة', 'Cladding and illuminated 3D letters'), icon: 'store', img: 946 }),
        item(t('نيون LED', 'LED neon'), { text: t('شعارات وعبارات للمحلات والمناسبات', 'Logos and phrases for shops and events'), icon: 'lightbulb', img: 274 }),
        item(t('ستيكرات', 'Stickers'), { text: t('قص وطباعة بأي شكل وحجم', 'Printed and cut to any shape and size'), icon: 'scissors', img: 855 }),
        item(t('طباعة كبيرة', 'Large-format print'), { text: t('فليكس وفينيل حتى ٥ أمتار', 'Flex and vinyl up to 5 m'), icon: 'printer', img: 951 }),
        item(t('حفر ليزر', 'Laser engraving'), { text: t('خشب، أكريليك، معدن وهدايا', 'Wood, acrylic, metal and gifts'), icon: 'zap', img: 252 }),
        item(t('تغليف السيارات', 'Vehicle wraps'), { text: t('أساطيل الشركات والسيارات الخاصة', 'Company fleets and private cars'), icon: 'car', img: 859 }),
      ],
    },
    {
      kind: 'items', id: 'work', nav: t('الأعمال', 'Work'), role: 'gallery',
      eyebrow: t('أعمالنا', 'Our work'),
      title: t('من الورشة إلى الشارع', 'From the workshop to the street'),
      items: [
        item(t('يافطة موتيل', 'Motel sign'), { meta: t('نيون', 'Neon'), img: 451 }),
        item(t('واجهة مقهى', 'Cafe front'), { meta: t('حروف بارزة', '3D letters'), img: 946 }),
        item(t('شارع تجاري', 'High street'), { meta: t('إضاءة', 'Lighting'), img: 274 }),
        item(t('هوية مطبعة', 'Print shop identity'), { meta: t('طباعة', 'Print'), img: 526 }),
        item(t('جدار إعلاني', 'Ad wall'), { meta: t('فليكس', 'Flex'), img: 951 }),
        item(t('باب محل', 'Shop door'), { meta: t('ستيكر', 'Sticker'), img: 859 }),
      ],
    },
    {
      kind: 'items', id: 'process', role: 'process',
      eyebrow: t('كيف نعمل', 'How it works'),
      title: t('من الفكرة إلى التركيب', 'From idea to installation'),
      items: [
        item(t('أرسل الفكرة', 'Send your idea'), { text: t('صورة الواجهة والمقاسات', 'A photo of the front and its size'), icon: 'camera' }),
        item(t('تصميم ومعاينة', 'Design & preview'), { text: t('نرسل لك التصميم على صورة محلك', 'We show the design on a photo of your shop'), icon: 'pen-tool' }),
        item(t('تصنيع', 'Production'), { text: t('في ورشتنا خلال ٣–٥ أيام', 'In our workshop within 3–5 days'), icon: 'hammer' }),
        item(t('تركيب', 'Installation'), { text: t('فريقنا يركّب ويضمن', 'Our team installs and guarantees it'), icon: 'wrench' }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('عملاؤنا', 'Clients'),
      title: t('محلات صارت معروفة', 'Shops that became landmarks'),
      items: [
        { quote: t('اليافطة الجديدة ضاعفت الزبائن الذين يدخلون من الشارع. الناس صاروا يصورونها.', 'The new sign doubled the people walking in from the street. People take photos of it now.'), name: t('مجدي عوض', 'Majdi Awad'), role: t('مطعم الفانوس', 'Al-Fanous restaurant') },
        { quote: t('طلبت ٥٠٠ ستيكر للمنتجات مساءً واستلمتها في اليوم التالي.', 'I ordered 500 product stickers in the evening and had them the next day.'), name: t('رولا سمارة', 'Rula Samara'), role: t('متجر صابون طبيعي', 'Natural soap shop') },
        { quote: t('نيون الاسم في عرسنا كان أجمل تفصيلة، وما زال معلقًا في البيت.', 'The neon of our names was the nicest touch at our wedding, and it still hangs at home.'), name: t('أحمد ودينا', 'Ahmad & Dina'), role: t('عروسان', 'Newlyweds') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('أسئلة متكررة', 'Common questions'),
      items: [
        { q: t('كم تكلّف يافطة محل؟', 'How much does a shop sign cost?'), a: t('حسب المقاس والمواد والإضاءة. أرسل صورة الواجهة ونرسل التسعيرة في اليوم نفسه.', 'It depends on size, materials and lighting. Send a photo of the front and we\'ll price it the same day.') },
        { q: t('هل تصممون أم أحضر التصميم؟', 'Do you design, or do I bring the design?'), a: t('الاثنان. التصميم مجاني مع التنفيذ.', 'Either. Design is free when we make it.') },
        { q: t('هل تركّبون خارج المدينة؟', 'Do you install outside the city?'), a: t('نعم، في كل محافظات الشمال والوسط.', 'Yes, across the northern and central governorates.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('أرسل صورة واجهتك', 'Send a photo of your shop front'),
      text: t('ونرسل لك تصميمًا مبدئيًا وتسعيرة خلال ٢٤ ساعة.', 'We\'ll send a first design and a price within 24 hours.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'work@lafta.example',
      address: t('المنطقة الصناعية، نابلس', 'Industrial Zone, Nablus'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('08:00 – 18:00') },
      ],
      cta: t('أرسل عبر واتساب', 'Send on WhatsApp'),
    },
  ],
};
