import type { Profile } from '../types';
import { item, same, t } from './helpers';

export const restaurant: Profile = {
  id: 'restaurant',
  label: t('مطعم', 'Restaurant'),
  brand: t('بيت الزعتر', 'Bayt Al Zaatar'),
  mark: t('ز', 'Z'),
  tagline: t('مطبخ شامي من البيت، منذ ١٩٩٨', 'Levantine home cooking since 1998'),
  navCta: t('احجز طاولة', 'Book a table'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مطبخ شامي · رام الله', 'Levantine kitchen · Ramallah'),
      title: t('طعم البيت، على طاولة أكبر', 'Home cooking, on a bigger table'),
      lead: t('خبز طابون من الفرن، مقبلات تُحضَّر كل صباح، ومشاوٍ على الفحم. وصفات جدّاتنا كما هي، بخضار من حقول قريبة.', 'Taboon bread from the oven, mezze made every morning and charcoal grills. Our grandmothers\' recipes as they were, with produce from nearby fields.'),
      cta: t('احجز طاولة', 'Book a table'),
      cta2: t('تصفّح القائمة', 'See the menu'),
      img: 490, imgs: [999, 488, 292],
      badge: t('منذ ١٩٩٨', 'Since 1998'),
    },
    { kind: 'marquee', items: [t('مسخّن', 'Musakhan'), t('منسف', 'Mansaf'), t('مقلوبة', 'Maqluba'), t('فتّة', 'Fatteh'), t('كبّة', 'Kibbeh'), t('حمّص بلحمة', 'Hummus with lamb')] },
    {
      kind: 'about', id: 'story', nav: t('حكايتنا', 'Our story'),
      eyebrow: t('حكايتنا', 'Our story'),
      title: t('مطبخ صغير صار بيتًا للجميع', 'A small kitchen that became everyone\'s home'),
      text: [
        t('بدأنا عام ١٩٩٨ بست طاولات وفرن طابون واحد. اليوم نخبز أكثر من ثلاثمئة رغيف يوميًا، وما زالت أمي تتذوق كل طبخة قبل أن تخرج من المطبخ.', 'We started in 1998 with six tables and one taboon oven. Today we bake over three hundred loaves a day, and my mother still tastes every dish before it leaves the kitchen.'),
        t('نشتري الخضار من مزارعي مرج ابن عامر، والزيت من معاصر قرى رام الله، ونطحن الزعتر بأيدينا.', 'Our vegetables come from farmers in Marj Ibn Amer, our oil from village presses around Ramallah, and we grind the za\'atar by hand.'),
      ],
      img: 437, img2: 195,
      quote: t('الأكل الطيب يحتاج وقتًا، ونحن لا نستعجل.', 'Good food takes time, and we are never in a hurry.'),
      sign: t('أم خليل، المؤسِّسة', 'Um Khalil, founder'),
    },
    {
      kind: 'items', id: 'menu', nav: t('القائمة', 'Menu'), role: 'offer',
      eyebrow: t('القائمة', 'The menu'),
      title: t('من الفرن والمقلى والفحم', 'From the oven, the pan and the coals'),
      lead: t('الأسعار بالشيكل وتشمل الخبز الساخن.', 'Prices in shekels, warm bread included.'),
      items: [
        item(t('مسخّن', 'Musakhan'), { text: t('دجاج بلدي، بصل بالسماق، خبز طابون', 'Free-range chicken, sumac onions, taboon bread'), price: '55 ₪', img: 999 }),
        item(t('مقلوبة', 'Maqluba'), { text: t('أرز وباذنجان ودجاج، تُقلب على الطاولة', 'Rice, aubergine and chicken, flipped at your table'), price: '52 ₪', img: 490 }),
        item(t('فتّوش', 'Fattoush'), { text: t('خضار بلدية، سماق وخبز محمّص', 'Garden vegetables, sumac and toasted bread'), price: '22 ₪', img: 488 }),
        item(t('حمّص بيروتي', 'Beiruti hummus'), { text: t('حمّص ناعم، طحينة، ليمون وثوم', 'Silky chickpeas, tahini, lemon and garlic'), price: '18 ₪', img: 326 }),
        item(t('مشاوي مشكّلة', 'Mixed grill'), { text: t('كباب وشيش طاووق وريش على الفحم', 'Kebab, shish taouk and lamb chops over charcoal'), price: '68 ₪', img: 23 }),
        item(t('سلطة الموسم', 'Season\'s salad'), { text: t('ما يأتي به المزارعون هذا الأسبوع', 'Whatever the farmers bring this week'), price: '24 ₪', img: 292 }),
      ],
      groups: [
        { name: t('مقبلات', 'Mezze'), items: [
          item(t('حمّص بيروتي', 'Beiruti hummus'), { text: t('حمّص ناعم، طحينة، ليمون وثوم', 'Silky chickpeas, tahini, lemon and garlic'), price: '18 ₪' }),
          item(t('متبّل', 'Moutabal'), { text: t('باذنجان مشوي على الفحم مع دبس الرمان', 'Charcoal aubergine with pomegranate molasses'), price: '18 ₪' }),
          item(t('فتّوش', 'Fattoush'), { text: t('خضار بلدية، سماق وخبز محمّص', 'Garden vegetables, sumac and toasted bread'), price: '22 ₪' }),
          item(t('كبّة مقلية', 'Fried kibbeh'), { text: t('أربع قطع محشوة بالصنوبر', 'Four pieces filled with pine nuts'), price: '26 ₪' }),
        ] },
        { name: t('أطباق رئيسية', 'Mains'), items: [
          item(t('مسخّن', 'Musakhan'), { text: t('دجاج بلدي، بصل بالسماق، خبز طابون', 'Free-range chicken, sumac onions, taboon bread'), price: '55 ₪' }),
          item(t('مقلوبة', 'Maqluba'), { text: t('أرز وباذنجان وزهرة ودجاج', 'Rice, aubergine, cauliflower and chicken'), price: '52 ₪' }),
          item(t('منسف', 'Mansaf'), { text: t('لحم بلدي، جميد كركي، أرز ولوز', 'Local lamb, Karak jameed, rice and almonds'), price: '75 ₪' }),
          item(t('مشاوي مشكّلة', 'Mixed grill'), { text: t('كباب وشيش طاووق وريش', 'Kebab, shish taouk and chops'), price: '68 ₪' }),
        ] },
        { name: t('حلويات ومشروبات', 'Sweets & drinks'), items: [
          item(t('كنافة نابلسية', 'Nablusi knafeh'), { text: t('جبنة نابلسية وقطر بماء الورد', 'Nablus cheese and rose-water syrup'), price: '20 ₪' }),
          item(t('شاي بالميرمية', 'Sage tea'), { text: t('إبريق لشخصين', 'A pot for two'), price: '8 ₪' }),
          item(t('ليمون بالنعناع', 'Lemon & mint'), { text: t('مثلّج ومحلّى بالعسل', 'Iced, sweetened with honey'), price: '12 ₪' }),
        ] },
      ],
      cta: t('القائمة كاملة', 'Full menu'),
    },
    { kind: 'stats', items: [
      { value: '25', label: t('سنة في المطبخ', 'years in the kitchen') },
      { value: '300+', label: t('رغيف طابون يوميًا', 'taboon loaves a day') },
      { value: '40', label: t('طبقًا في القائمة', 'dishes on the menu') },
      { value: '4.9', label: t('تقييم الزوار', 'guest rating') },
    ] },
    {
      kind: 'items', id: 'place', nav: t('المكان', 'The place'), role: 'gallery',
      eyebrow: t('المكان', 'The place'),
      title: t('سهرات على الشرفة', 'Evenings on the terrace'),
      items: [
        item(t('الشرفة', 'The terrace'), { img: 163 }),
        item(t('الصالة', 'The dining room'), { img: 395 }),
        item(t('ليالي الصيف', 'Summer nights'), { img: 351 }),
        item(t('الحارة', 'The street'), { img: 195 }),
        item(t('موسم ورق العنب', 'Vine-leaf season'), { img: 75 }),
        item(t('من الحقل', 'From the field'), { img: 674 }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('قالوا عنا', 'Kind words'),
      title: t('يعودون مع العائلة', 'They come back with family'),
      items: [
        { quote: t('أطيب مسخّن أكلته خارج بيت جدتي. الخبز يخرج ساخنًا والزيت من قرية قريبة، وهذا واضح من أول لقمة.', 'The best musakhan I\'ve had outside my grandmother\'s house. The bread comes out hot and the oil is from a nearby village; you taste it in the first bite.'), name: t('رنا عودة', 'Rana Odeh'), role: t('زبونة منذ ٢٠١٢', 'Guest since 2012') },
        { quote: t('حجزنا لعيد ميلاد أبي، ثلاثين شخصًا، وكان كل شيء جاهزًا قبل وصولنا. الخدمة دافئة كأنك في بيت أهلك.', 'We booked my father\'s birthday for thirty people and everything was ready before we arrived. The service is as warm as your parents\' home.'), name: t('سامر حدّاد', 'Samer Haddad'), role: t('مناسبة عائلية', 'Family celebration') },
        { quote: t('المقلوبة تُقلب أمامك على الطاولة، والكنافة تستحق الطريق من نابلس.', 'The maqluba is flipped at your table, and the knafeh is worth the drive from Nablus.'), name: t('ليلى ناصر', 'Layla Nasser'), role: t('كاتبة طعام', 'Food writer') },
      ],
    },
    {
      kind: 'cta',
      title: t('عندك مناسبة؟', 'Planning a gathering?'),
      text: t('نجهّز ولائم للعائلات والشركات حتى ٨٠ شخصًا، في المطعم أو عندكم.', 'We cater family and company feasts for up to 80 people, here or at your place.'),
      cta: t('اطلب عرض سعر', 'Ask for a quote'),
      img: 351,
    },
    {
      kind: 'contact', id: 'visit', nav: t('زورونا', 'Visit'),
      eyebrow: t('زورونا', 'Visit us'),
      title: t('طاولتك جاهزة', 'Your table is ready'),
      text: t('احجز عبر واتساب أو اتصل بنا. نفتح كل يوم ما عدا الاثنين.', 'Book on WhatsApp or give us a call. Open every day except Monday.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'table@baytalzaatar.example',
      address: t('شارع الإرسال ١٢، رام الله', '12 Al-Irsal Street, Ramallah'),
      hours: [
        { d: t('الثلاثاء – الخميس', 'Tue – Thu'), t: same('12:00 – 23:00') },
        { d: t('الجمعة – الأحد', 'Fri – Sun'), t: same('12:00 – 00:00') },
        { d: t('الاثنين', 'Monday'), t: t('مغلق', 'Closed') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const cafe: Profile = {
  id: 'cafe',
  label: t('مقهى', 'Cafe'),
  brand: t('حبّة', 'Habba'),
  mark: t('ح', 'H'),
  tagline: t('محمصة ومقهى مختص', 'Specialty roastery and cafe'),
  navCta: t('اطلب الآن', 'Order now'),
  socials: ['instagram', 'x'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('محمصة ومقهى · بيت لحم', 'Roastery & cafe · Bethlehem'),
      title: t('قهوة تُحمَّص هنا، كل صباح', 'Coffee roasted here, every morning'),
      lead: t('نختار حبوبنا من مزارع صغيرة في إثيوبيا وكولومبيا واليمن، ونحمّصها على دفعات صغيرة، ونقدّمها كما يجب: بلا عجلة.', 'We buy from small farms in Ethiopia, Colombia and Yemen, roast in small batches and serve it the way it deserves: without hurry.'),
      cta: t('اطلب للاستلام', 'Order for pickup'),
      cta2: t('القائمة', 'Menu'),
      img: 431, imgs: [1060, 425, 635],
      badge: t('تحميص طازج', 'Fresh roast'),
    },
    { kind: 'marquee', items: [t('إسبريسو', 'Espresso'), t('V60', 'V60'), t('قهوة عربية بالهيل', 'Arabic coffee with cardamom'), t('كورتادو', 'Cortado'), t('كولد برو', 'Cold brew'), t('شاي بالنعناع', 'Mint tea')] },
    {
      kind: 'about', id: 'roastery', nav: t('المحمصة', 'Roastery'),
      eyebrow: t('المحمصة', 'The roastery'),
      title: t('من الحبّة إلى الفنجان في أربعة أيام', 'From bean to cup in four days'),
      text: [
        t('نحمّص يومي الأحد والأربعاء فقط، ولا نبيع حبوبًا مضى على تحميصها أكثر من ثلاثة أسابيع.', 'We roast on Sundays and Wednesdays only, and never sell beans more than three weeks past roasting.'),
        t('كل كيس يحمل اسم المزرعة وتاريخ التحميص وملاحظات التذوق، لتعرف ماذا تشرب.', 'Every bag carries the farm\'s name, the roast date and tasting notes, so you know what you\'re drinking.'),
      ],
      img: 513, img2: 1060,
      quote: t('القهوة الجيدة لا تحتاج سكرًا، تحتاج صبرًا.', 'Good coffee doesn\'t need sugar; it needs patience.'),
      sign: t('ميرا، المحمّصة', 'Mira, head roaster'),
    },
    {
      kind: 'items', id: 'menu', nav: t('القائمة', 'Menu'), role: 'offer',
      eyebrow: t('القائمة', 'The menu'),
      title: t('ماذا نصبّ اليوم', 'What we\'re pouring today'),
      items: [
        item(t('إسبريسو', 'Espresso'), { text: t('خلطة البيت: شوكولاتة وكراميل', 'House blend: chocolate and caramel'), price: '9 ₪', img: 1060 }),
        item(t('V60 إثيوبي', 'Ethiopian V60'), { text: t('ياسمين، ليمون، شاي أسود', 'Jasmine, lemon, black tea'), price: '16 ₪', img: 635 }),
        item(t('قهوة عربية', 'Arabic coffee'), { text: t('بالهيل، تُقدّم في دلّة', 'With cardamom, served in a dallah'), price: '12 ₪', img: 882 }),
        item(t('لاتيه', 'Latte'), { text: t('حليب بلدي مخفوق برفق', 'Gently steamed local milk'), price: '14 ₪', img: 431 }),
        item(t('كولد برو', 'Cold brew'), { text: t('منقوع ١٨ ساعة', 'Steeped for 18 hours'), price: '15 ₪', img: 63 }),
        item(t('شاي بالنعناع', 'Mint tea'), { text: t('نعناع من الحديقة', 'Mint from the garden'), price: '8 ₪', img: 225 }),
      ],
      groups: [
        { name: t('إسبريسو', 'Espresso bar'), items: [
          item(t('إسبريسو', 'Espresso'), { text: t('خلطة البيت', 'House blend'), price: '9 ₪' }),
          item(t('كورتادو', 'Cortado'), { text: t('إسبريسو وقليل من الحليب', 'Espresso with a little milk'), price: '12 ₪' }),
          item(t('لاتيه', 'Latte'), { text: t('حليب بلدي مخفوق برفق', 'Gently steamed local milk'), price: '14 ₪' }),
          item(t('فلات وايت', 'Flat white'), { text: t('جرعتان وحليب ناعم', 'Double shot, silky milk'), price: '14 ₪' }),
        ] },
        { name: t('تقطير وتقليدي', 'Brew & tradition'), items: [
          item(t('V60 إثيوبي', 'Ethiopian V60'), { text: t('ياسمين، ليمون، شاي أسود', 'Jasmine, lemon, black tea'), price: '16 ₪' }),
          item(t('قهوة عربية', 'Arabic coffee'), { text: t('بالهيل، في دلّة', 'With cardamom, in a dallah'), price: '12 ₪' }),
          item(t('كولد برو', 'Cold brew'), { text: t('منقوع ١٨ ساعة', 'Steeped for 18 hours'), price: '15 ₪' }),
        ] },
        { name: t('مع القهوة', 'On the side'), items: [
          item(t('كعك بالسمسم', 'Sesame ka\'ak'), { text: t('من فرن الحارة', 'From the neighbourhood oven'), price: '6 ₪' }),
          item(t('معمول بالتمر', 'Date ma\'amoul'), { text: t('ثلاث قطع', 'Three pieces'), price: '10 ₪' }),
          item(t('كيكة الهيل', 'Cardamom cake'), { text: t('شريحة دافئة', 'A warm slice'), price: '14 ₪' }),
        ] },
      ],
    },
    {
      kind: 'items', id: 'beans', nav: t('الحبوب', 'Beans'), role: 'extra',
      eyebrow: t('للبيت', 'For home'),
      title: t('حبوب هذا الشهر', 'This month\'s beans'),
      lead: t('أكياس ٢٥٠ غرامًا، نطحنها لك حسب أداتك.', '250 g bags, ground for your brewer.'),
      items: [
        item(t('غوجي، إثيوبيا', 'Guji, Ethiopia'), { text: t('خوخ، ياسمين، عسل', 'Peach, jasmine, honey'), price: '58 ₪', img: 425, tag: t('فاتح', 'Light') }),
        item(t('هويلا، كولومبيا', 'Huila, Colombia'), { text: t('كرز، شوكولاتة حليب', 'Cherry, milk chocolate'), price: '52 ₪', img: 766, tag: t('متوسط', 'Medium') }),
        item(t('حراز، اليمن', 'Haraz, Yemen'), { text: t('زبيب، توابل، كاكاو', 'Raisin, spice, cocoa'), price: '74 ₪', img: 882, tag: t('نادر', 'Rare') }),
      ],
    },
    {
      kind: 'items', id: 'corner', role: 'gallery',
      eyebrow: t('الزاوية', 'The corner'),
      title: t('مكان للقراءة والعمل واللقاء', 'A place to read, work and meet'),
      items: [
        item(t('الطاولة الطويلة', 'The long table'), { img: 42 }),
        item(t('ركن العمل', 'The work corner'), { img: 48 }),
        item(t('الشبّاك', 'By the window'), { img: 192 }),
        item(t('الصباح', 'Mornings'), { img: 113 }),
        item(t('الشتاء', 'Winter'), { img: 755 }),
        item(t('بعد الظهر', 'Afternoons'), { img: 365 }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('من روّادنا', 'From our regulars'),
      title: t('فنجان واحد يكفي لتعود', 'One cup and you\'ll be back'),
      items: [
        { quote: t('أول مرة أفهم لماذا يتكلم الناس عن "ملاحظات" القهوة. الـV60 الإثيوبي هنا طعمه فعلًا مثل الياسمين.', 'The first time I understood why people talk about coffee "notes". The Ethiopian V60 here really does taste like jasmine.'), name: t('جاد سعيد', 'Jad Saeed'), role: t('مصمم', 'Designer') },
        { quote: t('أعمل من هنا كل ثلاثاء. الإنترنت سريع والضجيج قليل، والقهوة العربية بالهيل تذكّرني ببيت جدي.', 'I work from here every Tuesday. Fast internet, little noise, and the cardamom coffee reminds me of my grandfather\'s house.'), name: t('هبة خوري', 'Hiba Khoury'), role: t('مترجمة', 'Translator') },
        { quote: t('اشتريت كيس حراز اليمني هدية لأبي، واتصل بي في اليوم التالي يسأل من أين.', 'I bought the Yemeni Haraz as a gift for my father, and he called the next day asking where it was from.'), name: t('كريم عيسى', 'Karim Issa'), role: t('زبون', 'Regular') },
      ],
    },
    {
      kind: 'contact', id: 'visit', nav: t('زورونا', 'Visit'),
      eyebrow: t('زورونا', 'Visit us'),
      title: t('الفنجان التالي علينا؟', 'Next cup on us?'),
      text: t('اطلب مسبقًا عبر واتساب واستلم طلبك دون انتظار.', 'Order ahead on WhatsApp and skip the queue.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'hello@habba.example',
      address: t('شارع النجمة ٤، بيت لحم', '4 Star Street, Bethlehem'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('07:00 – 21:00') },
        { d: t('الجمعة', 'Friday'), t: same('09:00 – 22:00') },
      ],
      cta: t('اطلب عبر واتساب', 'Order on WhatsApp'),
    },
  ],
};

export const sweets: Profile = {
  id: 'sweets',
  label: t('حلويات', 'Sweets & bakery'),
  brand: t('سُكّر', 'Sukkar'),
  mark: t('س', 'S'),
  tagline: t('حلويات وكعك يُخبز كل يوم', 'Cakes and sweets baked daily'),
  navCta: t('اطلب كعكتك', 'Order a cake'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مخبز حلويات · نابلس', 'Patisserie · Nablus'),
      title: t('كل يوم عيد صغير', 'A small celebration, every day'),
      lead: t('كعك بالفواكه الطازجة، بسكويت بالزبدة، ومعمول العيد طوال السنة. نخبز كل صباح ونبيع حتى ينفد.', 'Fresh fruit cakes, butter cookies and Eid ma\'amoul all year round. We bake every morning and sell until it\'s gone.'),
      cta: t('اطلب كعكتك', 'Order a cake'),
      cta2: t('شاهد الحلويات', 'See the sweets'),
      img: 835, imgs: [1080, 429, 312],
      badge: t('طازج اليوم', 'Fresh today'),
    },
    {
      kind: 'about', id: 'story', nav: t('عنّا', 'About'),
      eyebrow: t('عنّا', 'About us'),
      title: t('زبدة حقيقية وسكر أقل', 'Real butter, less sugar'),
      text: [
        t('أختان وفرن واحد في البلدة القديمة. نستعمل زبدة بلدية وعسلًا من مناحل الجبل، ونخفف السكر لأن الفاكهة حلوة بما يكفي.', 'Two sisters and one oven in the old city. We use local butter and mountain honey, and we go easy on sugar because the fruit is sweet enough.'),
        t('نخبز كعكات المناسبات حسب الطلب، ونكتب عليها ما تريد بخط اليد.', 'We bake celebration cakes to order and write whatever you like on them by hand.'),
      ],
      img: 312, img2: 835,
      quote: t('الكعكة الجميلة تُرى، والطيبة تُتذكّر.', 'A beautiful cake is seen; a good one is remembered.'),
      sign: t('دانة وسلمى', 'Dana & Salma'),
    },
    {
      kind: 'items', id: 'sweets', nav: t('الحلويات', 'Sweets'), role: 'offer',
      eyebrow: t('الحلويات', 'The sweets'),
      title: t('من فرننا اليوم', 'From our oven today'),
      items: [
        item(t('تارت الفراولة', 'Strawberry tart'), { text: t('كريمة الفانيلا وفراولة الموسم', 'Vanilla cream and seasonal strawberries'), price: '18 ₪', img: 1080, tag: t('الأكثر طلبًا', 'Bestseller') }),
        item(t('كعكة التوت', 'Berry cake'), { text: t('إسفنج خفيف وتوت أحمر', 'Light sponge and red berries'), price: '140 ₪', img: 889 }),
        item(t('كوب التوت', 'Raspberry cup'), { text: t('توت العليق وكريمة اللبنة', 'Raspberries and labneh cream'), price: '16 ₪', img: 429 }),
        item(t('بسكويت الليمون', 'Lemon cookies'), { text: t('علبة من ١٢ قطعة', 'A box of 12'), price: '35 ₪', img: 835 }),
        item(t('كيكة العسل', 'Honey cake'), { text: t('عسل الجبل والقرفة', 'Mountain honey and cinnamon'), price: '120 ₪', img: 312 }),
        item(t('فطور الفاكهة', 'Fruit breakfast bowl'), { text: t('شوفان، لبن وفاكهة', 'Oats, yoghurt and fruit'), price: '22 ₪', img: 493 }),
      ],
      groups: [
        { name: t('قطع فردية', 'Single pieces'), items: [
          item(t('تارت الفراولة', 'Strawberry tart'), { price: '18 ₪' }),
          item(t('كوب التوت', 'Raspberry cup'), { price: '16 ₪' }),
          item(t('كنافة بالقشطة', 'Knafeh with cream'), { price: '15 ₪' }),
          item(t('معمول بالفستق', 'Pistachio ma\'amoul'), { price: '6 ₪' }),
        ] },
        { name: t('كعكات كاملة', 'Whole cakes'), items: [
          item(t('كعكة التوت', 'Berry cake'), { text: t('لـ ١٠ أشخاص', 'Serves 10'), price: '140 ₪' }),
          item(t('كيكة العسل', 'Honey cake'), { text: t('لـ ٨ أشخاص', 'Serves 8'), price: '120 ₪' }),
          item(t('كعكة الشوكولاتة', 'Chocolate cake'), { text: t('لـ ١٢ شخصًا', 'Serves 12'), price: '160 ₪' }),
        ] },
      ],
    },
    {
      kind: 'items', id: 'steps', role: 'process',
      eyebrow: t('كعكة المناسبة', 'Celebration cakes'),
      title: t('اطلب كعكتك في ثلاث خطوات', 'Order your cake in three steps'),
      items: [
        item(t('اختر النكهة والحجم', 'Pick a flavour and size'), { text: t('من القائمة أو اقترح علينا', 'From the menu, or suggest your own'), icon: 'cake' }),
        item(t('أرسل الكتابة والتاريخ', 'Send the message and date'), { text: t('قبل يومين على الأقل', 'At least two days ahead'), icon: 'pen' }),
        item(t('استلم أو نوصلها', 'Collect or we deliver'), { text: t('توصيل داخل نابلس', 'Delivery within Nablus'), icon: 'truck' }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('قالوا', 'They said'),
      title: t('الحلو يكمّل الفرحة', 'Sweetness completes the joy'),
      items: [
        { quote: t('طلبت كعكة لعيد ميلاد ابنتي فكانت أجمل من الصورة، والأهم أنها خلصت قبل أن نصورها.', 'I ordered my daughter\'s birthday cake and it was prettier than the picture; more importantly, it was gone before we could photograph it.'), name: t('نور شاهين', 'Nour Shaheen'), role: t('أم سعيدة', 'Happy mother') },
        { quote: t('بسكويت الليمون هو هديتي لكل زيارة. خفيف وغير محلّى زيادة.', 'The lemon cookies are my gift for every visit. Light and never too sweet.'), name: t('عمر بدران', 'Omar Badran'), role: t('زبون دائم', 'Regular') },
        { quote: t('معمول العيد هنا مثل معمول ستّي بالضبط.', 'The Eid ma\'amoul here is exactly like my grandmother\'s.'), name: t('سهى قاسم', 'Suha Qasem'), role: t('زبونة', 'Customer') },
      ],
    },
    {
      kind: 'contact', id: 'order', nav: t('اطلب', 'Order'),
      eyebrow: t('اطلب', 'Order'),
      title: t('ماذا نخبز لك؟', 'What shall we bake for you?'),
      text: t('اطلب عبر واتساب قبل يومين للكعكات، وفي اليوم نفسه للقطع الفردية.', 'Order on WhatsApp two days ahead for cakes, same day for single pieces.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'orders@sukkar.example',
      address: t('البلدة القديمة، قرب الساحة، نابلس', 'Old City, by the square, Nablus'),
      hours: [
        { d: t('كل يوم', 'Every day'), t: same('08:00 – 20:00') },
      ],
      cta: t('اطلب عبر واتساب', 'Order on WhatsApp'),
    },
  ],
};

export const farm: Profile = {
  id: 'farm',
  label: t('منتجات بلدية', 'Farm shop'),
  brand: t('بيادر', 'Bayader'),
  mark: t('ب', 'B'),
  tagline: t('زيت وزعتر وعسل من الأرض مباشرة', 'Oil, za\'atar and honey straight from the land'),
  navCta: t('اطلب سلّتك', 'Order a basket'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('منتجات بلدية · جنين', 'Farm produce · Jenin'),
      title: t('من بيادرنا إلى مطبخك', 'From our fields to your kitchen'),
      lead: t('زيت زيتون بكر عصرة أولى، زعتر بري مجفف في الظل، عسل سدر وقمح فريكة. نزرع ونقطف ونعبّئ بأيدينا.', 'First cold-press olive oil, wild za\'atar dried in the shade, sidr honey and freekeh. We grow, pick and pack it ourselves.'),
      cta: t('اطلب سلّتك', 'Order a basket'),
      cta2: t('المنتجات', 'Products'),
      img: 206, imgs: [674, 312, 785],
      badge: t('موسم ٢٠٢٦', '2026 harvest'),
    },
    {
      kind: 'about', id: 'land', nav: t('الأرض', 'The land'),
      eyebrow: t('الأرض', 'The land'),
      title: t('ثلاثة أجيال على التلة نفسها', 'Three generations on the same hill'),
      text: [
        t('زرع جدي أول زيتونة هنا عام ١٩٥٢. اليوم نعتني بأربعمئة شجرة وكروم عنب وخلايا نحل، بلا مبيدات.', 'My grandfather planted the first olive tree here in 1952. Today we look after four hundred trees, vines and beehives, without pesticides.'),
        t('نبيع مباشرة للعائلات، فيصلك الزيت بسعر عادل ويصلنا ثمن تعبنا كاملًا.', 'We sell directly to families, so you get a fair price and we get the full value of our work.'),
      ],
      img: 116, img2: 785,
      quote: t('الأرض تعطي من يعطيها.', 'The land gives back to those who give to it.'),
      sign: t('أبو سليم', 'Abu Salim'),
    },
    {
      kind: 'items', id: 'products', nav: t('المنتجات', 'Products'), role: 'offer',
      eyebrow: t('المنتجات', 'Products'),
      title: t('من الموسم الجديد', 'From the new season'),
      items: [
        item(t('زيت زيتون بكر', 'Extra virgin olive oil'), { text: t('تنكة ١٦ لترًا أو قنينة لتر', '16 L tin or 1 L bottle'), price: '650 ₪', meta: t('١٦ لترًا', '16 L'), img: 116, tag: t('عصرة أولى', 'First press') }),
        item(t('زعتر بلدي', 'Wild za\'atar'), { text: t('مع السمسم والسماق', 'With sesame and sumac'), price: '30 ₪', meta: t('٥٠٠ غرام', '500 g'), img: 785 }),
        item(t('عسل سدر', 'Sidr honey'), { text: t('من خلايانا في الجبل', 'From our mountain hives'), price: '120 ₪', meta: t('كيلوغرام', '1 kg'), img: 312 }),
        item(t('دبس العنب', 'Grape molasses'), { text: t('من كروم الخليل', 'From Hebron vines'), price: '35 ₪', meta: t('لتر', '1 L'), img: 75 }),
        item(t('فريكة', 'Freekeh'), { text: t('قمح أخضر محمّص على الحطب', 'Green wheat roasted over wood'), price: '28 ₪', meta: t('كيلوغرام', '1 kg'), img: 112 }),
        item(t('سلة الموسم', 'Season basket'), { text: t('خضار وفاكهة هذا الأسبوع', 'This week\'s vegetables and fruit'), price: '90 ₪', meta: t('أسبوعيًا', 'Weekly'), img: 292 }),
      ],
    },
    { kind: 'stats', items: [
      { value: '400', label: t('شجرة زيتون', 'olive trees') },
      { value: '1952', label: t('سنة أول غرسة', 'first planting') },
      { value: '0', label: t('مبيدات', 'pesticides') },
      { value: '1200+', label: t('عائلة تشتري منّا', 'families buy from us') },
    ] },
    {
      kind: 'items', id: 'how', role: 'process',
      eyebrow: t('كيف نعمل', 'How it works'),
      title: t('من الشجرة إلى بابك', 'From the tree to your door'),
      items: [
        item(t('نقطف في وقته', 'We pick on time'), { text: t('الزيتون في تشرين، والزعتر في الربيع', 'Olives in October, za\'atar in spring'), icon: 'sprout' }),
        item(t('نعصر خلال ٢٤ ساعة', 'Pressed within 24 hours'), { text: t('في معصرة القرية على البارد', 'Cold-pressed at the village mill'), icon: 'droplet' }),
        item(t('نوصل إلى بيتك', 'Delivered to your home'), { text: t('في كل مدن الضفة', 'Across all West Bank cities'), icon: 'truck' }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('من زبائننا', 'From our customers'),
      title: t('طعم الزيت يحكي', 'The oil speaks for itself'),
      items: [
        { quote: t('نأخذ تنكة الزيت من بيادر منذ خمس سنوات. لونه أخضر وطعمه يلسع الحلق كما يجب.', 'We\'ve bought our oil from Bayader for five years. It\'s green and catches the throat the way it should.'), name: t('منى سليمان', 'Mona Suleiman'), role: t('رام الله', 'Ramallah') },
        { quote: t('سلة الموسم الأسبوعية غيّرت مطبخنا. خضار حقيقية بطعم أيام زمان.', 'The weekly season basket changed our kitchen. Real vegetables that taste like the old days.'), name: t('باسل عمرو', 'Basel Amro'), role: t('الخليل', 'Hebron') },
        { quote: t('أرسلت العسل والزعتر لأختي في عمّان، وقالت إنه أطيب ما ذاقت.', 'I sent the honey and za\'atar to my sister in Amman, and she said it was the best she\'d tasted.'), name: t('رهام دويكات', 'Reham Dweikat'), role: t('نابلس', 'Nablus') },
      ],
    },
    {
      kind: 'cta',
      title: t('احجز تنكة الموسم', 'Reserve this season\'s tin'),
      text: t('الكمية محدودة. احجز الآن وادفع عند الاستلام.', 'Quantities are limited. Reserve now, pay on delivery.'),
      cta: t('احجز الآن', 'Reserve now'),
      img: 955,
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('اطلب سلّتك', 'Order your basket'),
      text: t('نوصل كل خميس. أرسل طلبك عبر واتساب قبل الثلاثاء.', 'We deliver every Thursday. Send your order on WhatsApp by Tuesday.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'orders@bayader.example',
      address: t('قرية برقين، جنين', 'Burqin village, Jenin'),
      hours: [
        { d: t('الطلبات', 'Orders'), t: t('كل يوم', 'Every day') },
        { d: t('التوصيل', 'Delivery'), t: t('الخميس', 'Thursday') },
      ],
      cta: t('اطلب عبر واتساب', 'Order on WhatsApp'),
    },
  ],
};
