import type { L, Profile } from '../types';
import { item, same, t } from './helpers';

/** A price in Jordanian dinars, written the way each language reads it. */
const jd = (n: string): L => t(`${n} د.أ`, `JD ${n}`);

export const dive: Profile = {
  id: 'dive',
  label: t('مركز غوص', 'Dive centre'),
  brand: t('مرجان', 'Marjan'),
  mark: t('م', 'M'),
  tagline: t('غوص وسنوركل في خليج العقبة', 'Diving and snorkelling in the Gulf of Aqaba'),
  navCta: t('احجز غطستك', 'Book a dive'),
  socials: ['instagram', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مركز غوص · العقبة', 'Dive centre · Aqaba'),
      title: t('البحر الأحمر أقرب مما تظن', 'The Red Sea is closer than you think'),
      lead: t('من أول غطسة تجريبية إلى شهادة الغوص المتقدم: مدرّبون معتمدون، ومعدات جديدة، وشعاب مرجانية على بعد عشر دقائق من الشاطئ.', 'From your first try dive to an advanced licence: certified instructors, new equipment, and coral reefs ten minutes from the shore.'),
      cta: t('احجز غطستك', 'Book a dive'),
      cta2: t('الدورات', 'Courses'),
      img: 446, imgs: [541, 1069, 124],
      badge: t('الماء ٢٤° طوال العام', 'Water at 24° all year'),
    },
    { kind: 'stats', items: [
      { value: '22', label: t('موقع غوص', 'dive sites') },
      { value: '9,000+', label: t('غطسة آمنة', 'safe dives') },
      { value: '12', label: t('مدرّبًا معتمدًا', 'certified instructors') },
      { value: '30 m', label: t('مدى الرؤية تحت الماء', 'visibility under water') },
    ] },
    {
      kind: 'items', id: 'courses', nav: t('الدورات', 'Courses'), role: 'offer',
      eyebrow: t('الدورات', 'Courses'),
      title: t('من السطح إلى الأعماق', 'From the surface to the deep'),
      items: [
        item(t('غطسة تجريبية', 'Try dive'), { text: t('بلا خبرة، ومدرّب بجانبك طوال الوقت', 'No experience, an instructor beside you all the way'), meta: t('نصف يوم', 'Half a day'), price: jd('45'), img: 446, tag: t('للمبتدئين', 'Beginners') }),
        item(t('سنوركل الشعاب', 'Reef snorkelling'), { text: t('قارب وغداء ومعدات', 'Boat, lunch and gear'), meta: t('٤ ساعات', '4 hours'), price: jd('25'), img: 124 }),
        item(t('الغواص المفتوح', 'Open water diver'), { text: t('شهادة دولية حتى عمق ١٨ مترًا', 'An international licence to 18 metres'), meta: t('٤ أيام', '4 days'), price: jd('320'), img: 541 }),
        item(t('الغوص المتقدم', 'Advanced diver'), { text: t('غوص ليلي وحطام سفن وملاحة تحت الماء', 'Night, wreck and navigation dives'), meta: t('٣ أيام', '3 days'), price: jd('280'), img: 874 }),
        item(t('غطسة الحطام', 'Wreck dive'), { text: t('سفينة غارقة على عمق ٢٥ مترًا', 'A sunken ship at 25 metres'), meta: t('غطستان', 'Two dives'), price: jd('60'), img: 848 }),
        item(t('تصوير تحت الماء', 'Underwater photography'), { text: t('كاميرا وإضاءة ودرس خاص', 'Camera, lights and a private lesson'), meta: t('يومان', '2 days'), price: jd('150'), img: 1069 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن مرجان', 'About'),
      eyebrow: t('عن مرجان', 'About Marjan'),
      title: t('غوّاصون قبل أن نكون مدرّبين', 'Divers before we were instructors'),
      text: [
        t('بدأ المركز عام ٢٠٠٦ بقارب صيد قديم وثلاثة أصدقاء يعرفون كل صخرة في الخليج. ما زلنا نغوص كل صباح قبل أن نعلّم.', 'The centre began in 2006 with an old fishing boat and three friends who knew every rock in the gulf. We still dive every morning before we teach.'),
        t('نحمي الشعاب التي نعيش منها: لا نلمس المرجان، ونجمع البلاستيك من القاع مرة في الشهر مع غواصينا.', 'We protect the reef we live from: we never touch the coral, and once a month we clear plastic from the seabed with our divers.'),
      ],
      img: 871, img2: 642,
      quote: t('البحر لا يُخيف من يعرفه.', 'The sea holds no fear for those who know it.'),
      sign: t('كابتن وائل الرواشدة، مؤسس المركز', 'Captain Wael Al-Rawashdeh, founder'),
    },
    {
      kind: 'items', id: 'first', role: 'process',
      eyebrow: t('أول غطسة', 'Your first dive'),
      title: t('أربع خطوات وتكون تحت الماء', 'Four steps and you\'re under water'),
      items: [
        item(t('استمارة صحية', 'Health form'), { text: t('دقيقتان من هاتفك', 'Two minutes on your phone'), icon: 'clipboard-check' }),
        item(t('درس في المسبح', 'Pool lesson'), { text: t('التنفس ومعادلة الضغط والإشارات', 'Breathing, equalising and hand signals'), icon: 'waves' }),
        item(t('القارب إلى الشعاب', 'Boat to the reef'), { text: t('عشر دقائق من المرسى', 'Ten minutes from the jetty'), icon: 'ship' }),
        item(t('الغطسة', 'The dive'), { text: t('أربعون دقيقة بين المرجان', 'Forty minutes among the coral'), icon: 'fish' }),
      ],
    },
    {
      kind: 'items', id: 'reef', nav: t('الشعاب', 'The reef'), role: 'gallery',
      eyebrow: t('تحت الماء', 'Under water'),
      title: t('ما ستراه هناك', 'What you\'ll see down there'),
      items: [
        item(t('الحديقة اليابانية', 'The Japanese Garden'), { img: 871 }),
        item(t('قناديل البحر', 'Jellyfish'), { img: 581 }),
        item(t('الخليج الهادئ', 'The calm bay'), { img: 218 }),
        item(t('في الأعماق', 'In the deep'), { img: 881 }),
        item(t('قارب المركز', 'Our boat'), { img: 875 }),
        item(t('موجة الصباح', 'Morning swell'), { img: 846 }),
      ],
    },
    {
      kind: 'items', id: 'packages', nav: t('الباقات', 'Packages'), role: 'pricing',
      eyebrow: t('الباقات', 'Packages'),
      title: t('للغواصين المعتمدين', 'For certified divers'),
      items: [
        item(t('يوم واحد', 'One day'), { price: jd('55'), meta: t('غطستان', 'two dives'), list: [t('القارب والمعدات', 'Boat and gear'), t('دليل غوص', 'A dive guide')] }),
        item(t('عطلة نهاية الأسبوع', 'Weekend'), { price: jd('150'), meta: t('ست غطسات', 'six dives'), featured: true, tag: t('الأكثر حجزًا', 'Most booked'), list: [t('غطسة ليلية', 'A night dive'), t('غداء على القارب', 'Lunch on the boat'), t('صور غطساتك', 'Photos of your dives')] }),
        item(t('عشر غطسات', 'Ten dives'), { price: jd('230'), meta: t('صالحة لسنة', 'valid for a year'), list: [t('أي موقع تختاره', 'Any site you like'), t('تأمين الغوص', 'Dive insurance')] }),
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل أن تنزل', 'Before you go down'),
      items: [
        { q: t('هل يجب أن أكون سبّاحًا ماهرًا؟', 'Do I need to be a strong swimmer?'), a: t('يكفي أن تسبح مئتي متر بأي طريقة وأن تطفو عشر دقائق.', 'You only need to swim 200 metres any way you like and float for ten minutes.') },
        { q: t('من أي عمر؟', 'From what age?'), a: t('السنوركل من ست سنوات، والغوص من عشر.', 'Snorkelling from six, diving from ten.') },
        { q: t('ماذا أحضر معي؟', 'What should I bring?'), a: t('ملابس السباحة ومنشفة وواقي شمس آمن على المرجان. الباقي علينا.', 'Swimwear, a towel and reef-safe sunscreen. We bring the rest.') },
      ],
    },
    {
      kind: 'testimonials', id: 'divers',
      eyebrow: t('قالوا عنا', 'Divers say'),
      title: t('من أول غطسة إلى الشهادة', 'From the first dive to the licence'),
      items: [
        { quote: t('كنت أخاف الماء العميق، فأمسكت المدرّبة يدي حتى نسيت خوفي عند أول سمكة ملوّنة.', 'I was afraid of deep water; my instructor held my hand until I forgot my fear at the first bright fish.'), name: t('رنا خليل', 'Rana Khalil'), role: t('غطسة تجريبية', 'Try dive') },
        { quote: t('أخذت شهادتي في أربعة أيام، والمعدات كانت جديدة ونظيفة كل صباح.', 'I got my licence in four days, and the gear was new and clean every morning.'), name: t('فادي العمري', 'Fadi Al-Omari'), role: t('غواص مفتوح', 'Open water diver') },
        { quote: t('غطسة الحطام كانت أجمل ساعة في رحلتنا كلها إلى الأردن.', 'The wreck dive was the best hour of our whole trip to Jordan.'), name: t('سارة وتوماس', 'Sara and Thomas'), role: t('زوار من ألمانيا', 'Visitors from Germany') },
      ],
    },
    {
      kind: 'contact', id: 'book', nav: t('احجز', 'Book'),
      eyebrow: t('احجز', 'Book'),
      title: t('البحر ينتظرك صباح الغد', 'The sea is waiting for you tomorrow'),
      text: t('أرسل التاريخ وعددكم، ونرد عليك بالموعد والسعر خلال ساعة.', 'Send the date and how many of you, and we\'ll reply with a time and a price within the hour.'),
      phone: '+962 3 200 0000', whatsapp: '+962 79 000 0000', email: 'dive@marjan.example',
      address: t('الشاطئ الجنوبي، العقبة', 'South Beach, Aqaba'),
      hours: [
        { d: t('كل يوم', 'Every day'), t: same('07:00 – 18:00') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const trails: Profile = {
  id: 'trails',
  label: t('نادي مشي', 'Hiking club'),
  brand: t('درب', 'Darb'),
  mark: t('د', 'D'),
  tagline: t('مسارات مشي في جبال فلسطين ووديانها', 'Walking trails through the hills and valleys of Palestine'),
  navCta: t('انضم إلى المشية', 'Join a walk'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('نادي مشي · كل جمعة', 'Hiking club · every Friday'),
      title: t('اعرف البلاد بقدميك', 'Know the land on foot'),
      lead: t('مشيات أسبوعية في الوديان والجبال والقرى، بدليل يعرف كل شجرة زيتون وكل نبع. لكل الأعمار، ولكل لياقة مسار يناسبها.', 'Weekly walks through valleys, hills and villages, with a guide who knows every olive tree and every spring. All ages, and a trail for every level of fitness.'),
      cta: t('انضم إلى المشية', 'Join a walk'),
      cta2: t('المسارات القادمة', 'Upcoming walks'),
      img: 1006, imgs: [455, 1036, 665],
      date: '2026-11-06T06:30:00',
      place: t('نقطة اللقاء: عين القلط، أريحا', 'Meeting point: Ein Qelt, Jericho'),
    },
    {
      kind: 'items', id: 'walks', nav: t('المشيات', 'Walks'), role: 'schedule',
      eyebrow: t('المشيات القادمة', 'Upcoming walks'),
      title: t('هذا الشهر على الدرب', 'On the trail this month'),
      items: [
        item(t('وادي القلط', 'Wadi Qelt'), { meta: t('الجمعة ٦ نوفمبر', 'Fri 6 November'), text: t('١٢ كم · متوسط · من النبع إلى الدير', '12 km · moderate · from the spring to the monastery'), icon: 'mountain' }),
        item(t('مدرجات بتير', 'Battir terraces'), { meta: t('الجمعة ١٣ نوفمبر', 'Fri 13 November'), text: t('٨ كم · سهل · بين البساتين القديمة', '8 km · easy · through the old orchards'), icon: 'trees' }),
        item(t('جبال سلفيت', 'The Salfit hills'), { meta: t('الجمعة ٢٠ نوفمبر', 'Fri 20 November'), text: t('١٥ كم · صعب · مع قطاف الزيتون', '15 km · hard · with the olive harvest'), icon: 'footprints' }),
        item(t('ليلة في البرية', 'A night in the wild'), { meta: t('٢٧ – ٢٨ نوفمبر', '27 – 28 November'), text: t('مشي ومخيم وعشاء على النار', 'Walking, a camp and dinner by the fire'), icon: 'tent' }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن درب', 'About'),
      eyebrow: t('عن درب', 'About Darb'),
      title: t('نمشي لنعرف، لا لنصل', 'We walk to know, not to arrive'),
      text: [
        t('بدأنا عام ٢٠١٥ بعشرة أصدقاء يمشون كل جمعة. اليوم يمشي معنا أكثر من أربعة آلاف شخص، وما زلنا نتوقف عند كل نبع.', 'We started in 2015 as ten friends walking every Friday. Today more than four thousand people walk with us, and we still stop at every spring.'),
        t('نأكل الغداء في بيوت القرى التي نمرّ بها، فيبقى ثمن المشية في البلد.', 'We eat lunch in the homes of the villages we pass, so the price of the walk stays in the land.'),
      ],
      img: 1044, img2: 1001,
      quote: t('الطريق يحكي لمن يمشيه.', 'The road talks to those who walk it.'),
      sign: t('سامر جرادات، دليل المشي', 'Samer Jaradat, trail guide'),
    },
    {
      kind: 'items', id: 'trails', nav: t('المسارات', 'Trails'), role: 'offer',
      eyebrow: t('المسارات', 'Trails'),
      title: t('اختر مشيتك', 'Choose your walk'),
      items: [
        item(t('مشية العائلة', 'Family walk'), { text: t('مسار قصير مع الأطفال ونقاط للراحة', 'A short trail with children and plenty of stops'), meta: t('٣ ساعات', '3 hours'), price: '40 ₪', img: 1001 }),
        item(t('مشية السهول', 'Plains walk'), { text: t('طرق ريفية مفتوحة على المدى', 'Country lanes open to the horizon'), meta: t('٥ ساعات', '5 hours'), price: '60 ₪', img: 1018 }),
        item(t('يوم في الوادي', 'A day in the valley'), { text: t('من الفجر إلى العصر، والغداء من القرية', 'From dawn to afternoon, lunch from the village'), meta: t('يوم كامل', 'Full day'), price: '95 ₪', img: 1043, tag: t('الأكثر طلبًا', 'Most popular') }),
        item(t('مسار الشلالات', 'Waterfall trail'), { text: t('في الشتاء حين تمتلئ الينابيع', 'In winter, when the springs are full'), meta: t('٦ ساعات', '6 hours'), price: '80 ₪', img: 573 }),
        item(t('مخيم الليلة', 'Overnight camp'), { text: t('خيام ومعدات وعشاء وفطور', 'Tents, gear, dinner and breakfast'), meta: t('ليلة واحدة', 'One night'), price: '220 ₪', img: 1036 }),
        item(t('مشية التصوير', 'Photography walk'), { text: t('مع مصوّر يعلّمك ضوء الصباح', 'With a photographer who teaches you morning light'), meta: t('٤ ساعات', '4 hours'), price: '120 ₪', img: 980 }),
      ],
    },
    {
      kind: 'items', id: 'join', role: 'process',
      eyebrow: t('كيف تنضم', 'How to join'),
      title: t('من التسجيل إلى أول خطوة', 'From signing up to the first step'),
      items: [
        item(t('سجّل اسمك', 'Sign up'), { text: t('قبل المشية بيومين على الأقل', 'At least two days before the walk'), icon: 'clipboard-list' }),
        item(t('جهّز حقيبتك', 'Pack your bag'), { text: t('نرسل لك قائمة بما تحتاجه', 'We send you a list of what to bring'), icon: 'backpack' }),
        item(t('نقطة اللقاء', 'Meeting point'), { text: t('الحافلة تنطلق من رام الله وبيت لحم', 'The bus leaves from Ramallah and Bethlehem'), icon: 'map-pin' }),
        item(t('امشِ معنا', 'Walk with us'), { text: t('دليل في المقدمة وآخر في الخلف', 'A guide at the front and another at the back'), icon: 'footprints' }),
      ],
    },
    {
      kind: 'items', id: 'photos', nav: t('من الدرب', 'From the trail'), role: 'gallery',
      eyebrow: t('من الدرب', 'From the trail'),
      title: t('صور المشّائين', 'Photos by our walkers'),
      items: [
        item(t('النهر في الربيع', 'The river in spring'), { img: 1044 }),
        item(t('بحيرة الصباح', 'Morning lake'), { img: 980 }),
        item(t('الشلال', 'The waterfall'), { img: 509 }),
        item(t('استراحة على السور', 'A rest on the wall'), { img: 665 }),
        item(t('على القمة', 'On the summit'), { img: 455 }),
        item(t('فوق الغيم', 'Above the clouds'), { img: 1006 }),
      ],
    },
    {
      kind: 'testimonials', id: 'walkers',
      eyebrow: t('المشّاؤون', 'Walkers'),
      title: t('جاؤوا مرة وبقوا', 'They came once and stayed'),
      items: [
        { quote: t('عشت ثلاثين سنة في رام الله ولم أعرف أن على بعد ساعة منها وديانًا بهذا الجمال.', 'I lived in Ramallah for thirty years and never knew valleys this beautiful were an hour away.'), name: t('نادين قسيس', 'Nadine Kassis'), role: t('مشّاءة منذ ٢٠٢٣', 'Walking since 2023') },
        { quote: t('أخذت أولادي إلى مشية العائلة، والآن هم من يوقظونني صباح الجمعة.', 'I took my children on the family walk; now they are the ones who wake me on Friday mornings.'), name: t('باسل عودة', 'Basel Odeh'), role: t('أب لثلاثة', 'Father of three') },
        { quote: t('الدليل يحكي قصة كل قرية نمرّ بها. تعلّمت تاريخ البلاد وأنا أمشي.', 'The guide tells the story of every village we pass. I learned the country\'s history on foot.'), name: t('ريم طه', 'Reem Taha'), role: t('طالبة جامعية', 'University student') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل المشية', 'Before the walk'),
      items: [
        { q: t('هل أحتاج لياقة عالية؟', 'Do I need to be very fit?'), a: t('لا، كل مسار مكتوب عليه مستواه، والمسارات السهلة تناسب الجميع.', 'No, every trail shows its level, and the easy ones suit everyone.') },
        { q: t('ماذا لو أمطرت؟', 'What if it rains?'), a: t('نؤجل المشية ونعيد لك المبلغ أو ننقله إلى موعد آخر.', 'We postpone the walk and refund you or move you to another date.') },
        { q: t('هل يمكن أن نحجز لمجموعة؟', 'Can we book for a group?'), a: t('نعم، للمدارس والشركات والعائلات، بمسار ودليل خاصين.', 'Yes, for schools, companies and families, with your own trail and guide.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('سجّل', 'Sign up'),
      eyebrow: t('سجّل', 'Sign up'),
      title: t('الجمعة القادمة على الدرب', 'Next Friday, on the trail'),
      text: t('أرسل اسمك والمشية التي تريدها، ونرسل لك التفاصيل وقائمة الحقيبة.', 'Send your name and the walk you want, and we\'ll send the details and a packing list.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'walk@darb.example',
      address: t('شارع الإرسال، رام الله', 'Al-Irsal Street, Ramallah'),
      hours: [
        { d: t('الأحد – الخميس', 'Sun – Thu'), t: same('10:00 – 18:00') },
        { d: t('الجمعة', 'Friday'), t: t('على الدرب', 'On the trail') },
      ],
      cta: t('سجّل عبر واتساب', 'Sign up on WhatsApp'),
    },
  ],
};

export const stars: Profile = {
  id: 'stars',
  label: t('نادي فلك', 'Astronomy club'),
  brand: t('سُها', 'Suha'),
  mark: t('س', 'S'),
  tagline: t('ليالٍ تحت السماء الصافية في وادي رم', 'Nights under clear skies in Wadi Rum'),
  navCta: t('احجز ليلتك', 'Book a night'),
  socials: ['instagram', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('نادي فلك · وادي رم', 'Astronomy club · Wadi Rum'),
      title: t('السماء التي نسيتها المدينة', 'The sky the city forgot'),
      lead: t('بعيدًا عن أضواء المدن ترى درب التبانة بعينك. نأخذك إلى الصحراء بمناظير كبيرة وفلكيين يحكون لك أسماء النجوم كما سمّاها العرب.', 'Far from the city lights you see the Milky Way with your own eyes. We take you to the desert with large telescopes and astronomers who tell you the stars\' names as the Arabs named them.'),
      cta: t('احجز ليلتك', 'Book a night'),
      cta2: t('الليالي القادمة', 'Upcoming nights'),
      img: 974, imgs: [903, 683, 1042],
      date: '2026-12-13T21:00:00',
      place: t('ذروة شهب التوأميات · وادي رم', 'Peak of the Geminids · Wadi Rum'),
    },
    {
      kind: 'items', id: 'nights', nav: t('الليالي', 'Nights'), role: 'schedule',
      eyebrow: t('الليالي القادمة', 'Upcoming nights'),
      title: t('على جدول السماء', 'On the sky\'s timetable'),
      items: [
        item(t('ليلة بلا قمر', 'A moonless night'), { meta: t('١٤ نوفمبر', '14 November'), text: t('أفضل ليلة لرؤية درب التبانة', 'The best night to see the Milky Way'), icon: 'moon' }),
        item(t('زحل وحلقاته', 'Saturn and its rings'), { meta: t('٢٨ نوفمبر', '28 November'), text: t('من خلال منظار بقطر ٣٠ سم', 'Through a 30 cm telescope'), icon: 'telescope' }),
        item(t('شهب التوأميات', 'The Geminids'), { meta: t('١٣ ديسمبر', '13 December'), text: t('حتى مئة شهاب في الساعة', 'Up to a hundred meteors an hour'), icon: 'sparkles' }),
        item(t('السماء الشتوية', 'The winter sky'), { meta: t('٩ يناير', '9 January'), text: t('الجبار والثريا وسهيل', 'Orion, the Pleiades and Canopus'), icon: 'star' }),
      ],
    },
    {
      kind: 'items', id: 'experiences', nav: t('التجارب', 'Experiences'), role: 'offer',
      eyebrow: t('التجارب', 'Experiences'),
      title: t('ليلة تناسبك', 'A night that suits you'),
      items: [
        item(t('ليلة في الصحراء', 'A night in the desert'), { text: t('رصد وعشاء بدوي ومبيت في المخيم', 'Stargazing, a Bedouin dinner and a night in camp'), meta: t('ليلة واحدة', 'One night'), price: jd('65'), img: 981, tag: t('الأكثر حجزًا', 'Most booked') }),
        item(t('مطاردة الشهب', 'Meteor watch'), { text: t('أكياس نوم وشاي ساخن حتى الفجر', 'Sleeping bags and hot tea until dawn'), meta: t('حتى الفجر', 'Until dawn'), price: jd('40'), img: 537 }),
        item(t('دورة المنظار', 'Telescope course'), { text: t('كيف تختار منظارك وتوجّهه بنفسك', 'How to choose a telescope and aim it yourself'), meta: t('٣ أمسيات', '3 evenings'), price: jd('90'), img: 825 }),
        item(t('تصوير السماء', 'Astrophotography'), { text: t('تصوير درب التبانة بكاميرتك', 'Photograph the Milky Way with your own camera'), meta: t('ليلتان', '2 nights'), price: jd('140'), img: 1042 }),
        item(t('الفضاء للأطفال', 'Space for children'), { text: t('قبة فلكية متنقلة تزور المدارس', 'A mobile planetarium that visits schools'), meta: t('ساعتان', '2 hours'), price: jd('8'), img: 967 }),
        item(t('رحلة الشفق', 'Aurora trip'), { text: t('أسبوع في شمال النرويج مع فلكيّنا', 'A week in northern Norway with our astronomer'), meta: t('٧ أيام', '7 days'), price: jd('1,450'), img: 1022 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن سُها', 'About'),
      eyebrow: t('لماذا سُها؟', 'Why Suha?'),
      title: t('اسم نجم كان العرب يختبرون به البصر', 'A star the Arabs used to test their eyesight'),
      text: [
        t('سُها نجم خافت بجانب بنات نعش، من رآه فبصره حاد. اخترنا اسمه لأن السماء الصافية صارت نادرة كهذا النجم.', 'Suha is a faint star beside the Plough; whoever could see it had sharp eyes. We chose its name because a clear sky has become as rare as the star itself.'),
        t('بدأنا عام ٢٠١٩ بمنظار واحد وعشرة أصدقاء. اليوم نأخذ أكثر من ثلاثة آلاف زائر كل سنة إلى الصحراء.', 'We started in 2019 with one telescope and ten friends. Today we take more than three thousand visitors a year into the desert.'),
      ],
      img: 884, img2: 967,
      quote: t('حين تنطفئ الأضواء، تبدأ السماء بالكلام.', 'When the lights go out, the sky begins to speak.'),
      sign: t('د. عمّار الحسيني، فلكي النادي', 'Dr. Ammar Al-Husseini, club astronomer'),
    },
    {
      kind: 'items', id: 'sky', nav: t('السماء', 'The sky'), role: 'gallery',
      eyebrow: t('من كاميرات الأعضاء', 'From members\' cameras'),
      title: t('ما رأيناه هذا العام', 'What we saw this year'),
      items: [
        item(t('شفق النرويج', 'Northern lights'), { img: 1022 }),
        item(t('درب التبانة', 'The Milky Way'), { img: 903 }),
        item(t('دوران النجوم', 'Star trails'), { img: 683 }),
        item(t('صخور رم ليلًا', 'Rum rocks at night'), { img: 981 }),
        item(t('غابة تحت الشفق', 'Forest under the aurora'), { img: 724 }),
        item(t('شهاب منتصف الليل', 'A midnight meteor'), { img: 537 }),
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل الليلة', 'Before the night'),
      items: [
        { q: t('ماذا لو كانت السماء غائمة؟', 'What if it\'s cloudy?'), a: t('نراقب الطقس قبل يومين، ونؤجل الليلة مجانًا إن توقعنا الغيم.', 'We watch the forecast two days ahead and move your night for free if clouds are expected.') },
        { q: t('هل الصحراء باردة ليلًا؟', 'Is the desert cold at night?'), a: t('نعم، حتى في الصيف. أحضر سترة دافئة، والبطانيات علينا.', 'Yes, even in summer. Bring a warm jacket; the blankets are on us.') },
        { q: t('هل يناسب الأطفال؟', 'Is it suitable for children?'), a: t('من سن السابعة، ولدينا أمسيات مبكرة للعائلات.', 'From seven, and we hold early evenings for families.') },
      ],
    },
    {
      kind: 'testimonials', id: 'guests',
      eyebrow: t('ضيوفنا', 'Our guests'),
      title: t('ليلة لا تُنسى', 'A night you don\'t forget'),
      items: [
        { quote: t('رأيت حلقات زحل بعيني لأول مرة، وصرخت كطفل أمام الجميع.', 'I saw Saturn\'s rings with my own eyes for the first time and shouted like a child in front of everyone.'), name: t('خالد المصري', 'Khaled Al-Masri'), role: t('مهندس', 'Engineer') },
        { quote: t('عدّ أولادي أكثر من خمسين شهابًا، ثم ناموا تحت السماء.', 'My children counted over fifty meteors, then fell asleep under the sky.'), name: t('دانة سعيد', 'Dana Saeed'), role: t('أم', 'Mother') },
        { quote: t('الصور التي التقطتها في دورة التصوير صارت على جدار بيتي.', 'The photos I took on the astrophotography course now hang on my wall.'), name: t('يزن حداد', 'Yazan Haddad'), role: t('مصوّر هاوٍ', 'Amateur photographer') },
      ],
    },
    {
      kind: 'contact', id: 'book', nav: t('احجز', 'Book'),
      eyebrow: t('احجز', 'Book'),
      title: t('الأماكن بعدد المناظير', 'As many places as telescopes'),
      text: t('اختر الليلة وأرسل عدد الأشخاص؛ النقل من عمّان والعقبة متاح.', 'Pick a night and tell us how many of you; transport from Amman and Aqaba is available.'),
      phone: '+962 6 500 0000', whatsapp: '+962 79 000 0000', email: 'sky@suha.example',
      address: t('مخيم سُها، وادي رم', 'Suha Camp, Wadi Rum'),
      hours: [
        { d: t('الحجز', 'Bookings'), t: same('10:00 – 22:00') },
        { d: t('الرصد', 'Stargazing'), t: t('من الغروب حتى الفجر', 'Sunset to dawn') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const travel: Profile = {
  id: 'travel',
  label: t('مكتب سفر', 'Travel agency'),
  brand: t('رحّال', 'Rahhal'),
  mark: t('ر', 'R'),
  tagline: t('رحلات جماعية صغيرة إلى مدن تستحق المشي', 'Small group trips to cities worth walking'),
  navCta: t('اختر رحلتك', 'Pick a trip'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مكتب سفر · عمّان', 'Travel agency · Amman'),
      title: t('سافر خفيفًا، وعُد بحكايات', 'Travel light, come back with stories'),
      lead: t('مجموعات لا تزيد عن ستة عشر مسافرًا، فنادق في قلب المدينة، ومرشد عربي يعرف المطاعم التي يأكل فيها أهل البلد. التأشيرة والطيران والتأمين علينا.', 'Groups of no more than sixteen, hotels in the heart of the city, and an Arabic-speaking guide who knows where the locals eat. Visas, flights and insurance are on us.'),
      cta: t('اختر رحلتك', 'Pick a trip'),
      cta2: t('كيف نعمل', 'How it works'),
      img: 397, imgs: [670, 401, 419],
      badge: t('دفعة أولى ٢٠٪ فقط', 'Only 20% to book'),
    },
    {
      kind: 'items', id: 'trips', nav: t('الرحلات', 'Trips'), role: 'offer',
      eyebrow: t('الرحلات', 'Trips'),
      title: t('مواسم هذا العام', 'This year\'s seasons'),
      lead: t('الأسعار للشخص في غرفة مزدوجة، شاملة الطيران من عمّان.', 'Prices per person sharing a double room, flights from Amman included.'),
      items: [
        item(t('إسطنبول', 'Istanbul'), { text: t('الأسواق والبوسفور وترام الاستقلال', 'The bazaars, the Bosphorus and the Istiklal tram'), meta: t('٥ أيام', '5 days'), price: jd('690'), img: 670, tag: t('الأكثر حجزًا', 'Most booked') }),
        item(t('كابادوكيا', 'Cappadocia'), { text: t('منطاد عند الفجر وفنادق في الكهوف', 'A balloon at dawn and hotels in the caves'), meta: t('٤ أيام', '4 days'), price: jd('640'), img: 401 }),
        item(t('لشبونة', 'Lisbon'), { text: t('الترام الأصفر وأحياء الصيادين', 'Yellow trams and fishermen\'s quarters'), meta: t('٦ أيام', '6 days'), price: jd('1,150'), img: 419 }),
        item(t('باريس', 'Paris'), { text: t('المتاحف مشيًا، والمقاهي القديمة', 'Museums on foot, and the old cafes'), meta: t('٦ أيام', '6 days'), price: jd('1,290'), img: 234 }),
        item(t('ساحل إيطاليا', 'The Italian coast'), { text: t('قرى ملونة على الصخر وقطار بين البحر والجبل', 'Bright villages on the rock and a train between sea and mountain'), meta: t('٧ أيام', '7 days'), price: jd('1,380'), img: 397 }),
        item(t('وادي رم', 'Wadi Rum'), { text: t('عطلة نهاية أسبوع في الكثبان الحمراء', 'A weekend among the red dunes'), meta: t('يومان', '2 days'), price: jd('120'), img: 525 }),
      ],
      cta: t('كل الرحلات', 'All trips'),
    },
    {
      kind: 'items', id: 'how', nav: t('كيف نعمل', 'How it works'), role: 'process',
      eyebrow: t('كيف نعمل', 'How it works'),
      title: t('أنت تختار، ونحن نرتّب الباقي', 'You choose; we arrange the rest'),
      items: [
        item(t('اختر الرحلة', 'Choose a trip'), { text: t('واحجز مقعدك بدفعة أولى', 'And hold your seat with a deposit'), icon: 'map' }),
        item(t('الأوراق علينا', 'We do the papers'), { text: t('التأشيرة والتأمين وتذاكر الطيران', 'Visa, insurance and flights'), icon: 'file-text' }),
        item(t('سافر مع المجموعة', 'Travel with the group'), { text: t('مرشد عربي من المطار إلى المطار', 'An Arabic-speaking guide from airport to airport'), icon: 'plane' }),
        item(t('نحن على الهاتف', 'We\'re on the phone'), { text: t('رقم طوارئ يرد ليلًا ونهارًا', 'An emergency line that answers day and night'), icon: 'phone' }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن رحّال', 'About'),
      eyebrow: t('عن رحّال', 'About Rahhal'),
      title: t('نسافر كما نحب أن نسافر', 'We travel the way we like to travel'),
      text: [
        t('بدأنا رحّال لأننا تعبنا من الرحلات التي تقضي نصفها في الحافلة. رحلاتنا تمشي المدينة، وتجلس في مقاهيها، وتعرف ناسها.', 'We started Rahhal because we were tired of trips spent half on a coach. Ours walk the city, sit in its cafes and meet its people.'),
        t('كل رحلة جرّبناها بأنفسنا قبل أن نبيعها، وكل فندق نمنا فيه.', 'We took every trip ourselves before selling it, and slept in every hotel.'),
      ],
      img: 442, img2: 364,
      quote: t('المدينة لا تُرى من نافذة الحافلة.', 'You don\'t see a city through a coach window.'),
      sign: t('ليلى الخطيب، مؤسِّسة رحّال', 'Layla Al-Khatib, founder of Rahhal'),
    },
    {
      kind: 'items', id: 'moments', nav: t('من رحلاتنا', 'From our trips'), role: 'gallery',
      eyebrow: t('من رحلاتنا', 'From our trips'),
      title: t('صور المسافرين', 'Our travellers\' photos'),
      items: [
        item(t('منظار على البحر', 'A sea viewer'), { img: 687 }),
        item(t('برج بيزا', 'The tower of Pisa'), { img: 629 }),
        item(t('ينابيع آيسلندا', 'Iceland\'s hot springs'), { img: 512 }),
        item(t('وادٍ من حجر', 'A canyon of stone'), { img: 564 }),
        item(t('منطاد فوق النخيل', 'A balloon over the palms'), { img: 174 }),
        item(t('تلفريك الجبل', 'The mountain cable car'), { img: 328 }),
      ],
    },
    {
      kind: 'testimonials', id: 'travellers',
      eyebrow: t('المسافرون', 'Travellers'),
      title: t('عادوا ليحجزوا الرحلة التالية', 'They came back to book the next one'),
      items: [
        { quote: t('سافرت وحدي لأول مرة، وعدت بخمسة عشر صديقًا من المجموعة.', 'I travelled alone for the first time and came back with fifteen friends from the group.'), name: t('مي العبادي', 'May Al-Abbadi'), role: t('إسطنبول', 'Istanbul') },
        { quote: t('المرشد أخذنا إلى مطعم صغير في لشبونة لا يعرفه أي دليل سياحي، وما زلنا نتحدث عنه.', 'Our guide took us to a tiny restaurant in Lisbon that no guidebook knows, and we still talk about it.'), name: t('أحمد ونور', 'Ahmad and Noor'), role: t('لشبونة', 'Lisbon') },
        { quote: t('تأشيرة شنغن جاهزة خلال أسبوعين دون أن أقف في أي طابور.', 'A Schengen visa ready in two weeks without standing in a single queue.'), name: t('سمير حدّاد', 'Samir Haddad'), role: t('باريس', 'Paris') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل أن تحجز', 'Before you book'),
      items: [
        { q: t('ماذا لو رُفضت التأشيرة؟', 'What if my visa is refused?'), a: t('نعيد لك المبلغ كاملًا ما عدا رسوم السفارة.', 'We refund everything except the embassy fee.') },
        { q: t('هل يمكن السفر وحدي؟', 'Can I travel on my own?'), a: t('نعم، ونجد لك شريك غرفة من المجموعة إن أردت.', 'Yes, and we find you a roommate from the group if you like.') },
        { q: t('هل الرحلات مناسبة للعائلات؟', 'Are the trips good for families?'), a: t('لدينا رحلات عائلية في الصيف بمرشد وبرنامج للأطفال.', 'We run family trips in summer with a guide and a programme for children.') },
      ],
    },
    {
      kind: 'cta',
      title: t('رحلة الربيع تمتلئ أولًا', 'The spring trip fills up first'),
      text: t('احجز مقعدك الآن بعشرين بالمئة، وادفع الباقي قبل السفر بشهر.', 'Hold your seat now with twenty per cent and pay the rest a month before you fly.'),
      cta: t('احجز مقعدك', 'Hold your seat'),
      img: 401,
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('خطّط معنا رحلتك', 'Plan your trip with us'),
      text: t('اتصل بنا أو زر المكتب، ونساعدك في اختيار الرحلة والموعد المناسبين.', 'Call us or drop by the office, and we\'ll help you choose the right trip and date.'),
      phone: '+962 6 400 0000', whatsapp: '+962 79 000 0000', email: 'go@rahhal.example',
      address: t('شارع الرينبو ١٨، جبل عمّان', '18 Rainbow Street, Jabal Amman'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('09:30 – 19:00') },
      ],
      cta: t('راسلنا عبر واتساب', 'Message us on WhatsApp'),
    },
  ],
};

export const bikes: Profile = {
  id: 'bikes',
  label: t('محل دراجات', 'Bike shop'),
  brand: t('عجلة', 'Ajala'),
  mark: t('ع', 'A'),
  tagline: t('دراجات وصيانة ورحلات جماعية في أريحا', 'Bikes, repairs and group rides in Jericho'),
  navCta: t('جرّب دراجة', 'Try a bike'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('محل دراجات · أريحا', 'Bike shop · Jericho'),
      title: t('المدينة أجمل على عجلتين', 'The city is better on two wheels'),
      lead: t('دراجات للمدينة والجبل والأطفال، ودراجات كهربائية تصعد أي طريق. نصلحها في يومها، ونأخذك كل سبت في جولة مع شروق الشمس.', 'Bikes for the city, the hills and the children, and e-bikes that climb any road. We fix yours the same day and take you on a sunrise ride every Saturday.'),
      cta: t('جرّب دراجة', 'Try a bike'),
      cta2: t('الدراجات', 'The bikes'),
      img: 839, imgs: [1023, 212, 428],
      badge: t('تجربة مجانية ليوم كامل', 'A free full-day test ride'),
    },
    { kind: 'marquee', items: [t('دراجات المدينة', 'City bikes'), t('دراجات الجبل', 'Mountain bikes'), t('كهربائية', 'E-bikes'), t('للأطفال', 'Kids\' bikes'), t('قطع غيار', 'Spare parts'), t('صيانة في يومها', 'Same-day repairs')] },
    {
      kind: 'items', id: 'bikes', nav: t('الدراجات', 'Bikes'), role: 'offer',
      eyebrow: t('الدراجات', 'The bikes'),
      title: t('دراجة لكل طريق', 'A bike for every road'),
      items: [
        item(t('دراجة المدينة', 'City bike'), { text: t('سلة وأضواء وقفل، جاهزة للعمل', 'A basket, lights and a lock, ready for the commute'), price: '1,200 ₪', img: 212 }),
        item(t('دراجة الجبل', 'Mountain bike'), { text: t('تعليق كامل وإطارات للحصى', 'Full suspension and tyres for gravel'), price: '2,900 ₪', img: 1023 }),
        item(t('دراجة كهربائية', 'E-bike'), { text: t('٨٠ كم بشحنة واحدة', '80 km on one charge'), price: '4,800 ₪', img: 839, tag: t('جديد', 'New') }),
        item(t('دراجة الأطفال', 'Kids\' bike'), { text: t('من ثلاث سنوات، بعجلات تدريب', 'From age three, with training wheels'), price: '450 ₪', img: 146 }),
        item(t('دراجة كلاسيكية', 'Classic bike'), { text: t('إطار فولاذي وسرج جلد', 'A steel frame and a leather saddle'), price: '1,650 ₪', img: 76 }),
        item(t('دراجة الطريق', 'Road bike'), { text: t('خفيفة وسريعة للمسافات الطويلة', 'Light and fast for long distances'), price: '3,400 ₪', img: 519 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن عجلة', 'About'),
      eyebrow: t('عن عجلة', 'About Ajala'),
      title: t('محل صغير في أدفأ مدينة', 'A small shop in the warmest town'),
      text: [
        t('أريحا مسطّحة ودافئة طوال الشتاء، فهي مدينة الدراجات بلا منازع. فتحنا المحل عام ٢٠١٧ لنصلح دراجات الجيران، فصار ملتقى للدرّاجين.', 'Jericho is flat and warm all winter, the natural town for bikes. We opened in 2017 to fix our neighbours\' bikes, and the shop became a meeting place for riders.'),
        t('نبيع دراجات جديدة ومستعملة نصلحها بأنفسنا، ونعلّم الأطفال القيادة الآمنة مجانًا كل سبت.', 'We sell new bikes and used ones we rebuild ourselves, and teach children safe riding for free every Saturday.'),
      ],
      img: 76, img2: 146,
      quote: t('الدراجة أبسط آلة تجعلك حرًا.', 'A bike is the simplest machine that sets you free.'),
      sign: t('رامي عريقات، صاحب المحل', 'Rami Erekat, owner'),
    },
    {
      kind: 'items', id: 'workshop', nav: t('الورشة', 'Workshop'), role: 'extra',
      eyebrow: t('الورشة', 'The workshop'),
      title: t('نعتني بدراجتك', 'We look after your bike'),
      items: [
        item(t('صيانة في يومها', 'Same-day service'), { text: t('فرامل وجنازير وغيارات من ٤٠ ₪', 'Brakes, chains and gears from 40 ₪'), icon: 'wrench' }),
        item(t('تأجير بالساعة', 'Hourly rental'), { text: t('من ١٥ ₪ للساعة مع خوذة', 'From 15 ₪ an hour, helmet included'), icon: 'key' }),
        item(t('ضبط المقاس', 'Bike fitting'), { text: t('نضبط السرج والمقود على جسمك', 'Saddle and bars set to your body'), icon: 'ruler' }),
        item(t('توصيل وإرجاع', 'Pick-up and return'), { text: t('نأخذ دراجتك من بيتك ونعيدها', 'We collect your bike from home and bring it back'), icon: 'truck' }),
      ],
    },
    {
      kind: 'items', id: 'rides', nav: t('الجولات', 'Rides'), role: 'schedule',
      eyebrow: t('الجولات الجماعية', 'Group rides'),
      title: t('اركب معنا', 'Ride with us'),
      items: [
        item(t('جولة الشروق', 'Sunrise ride'), { meta: t('السبت ٥:٣٠ ص', 'Sat 5:30 am'), text: t('٢٥ كم إلى البحر الميت', '25 km to the Dead Sea'), icon: 'sunrise' }),
        item(t('جولة العائلة', 'Family ride'), { meta: t('الجمعة ٤:٠٠ م', 'Fri 4:00 pm'), text: t('بين بساتين النخيل، بطيئة وآمنة', 'Through the palm groves, slow and safe'), icon: 'trees' }),
        item(t('صعود الجبل', 'Hill climb'), { meta: t('الثلاثاء ٦:٠٠ ص', 'Tue 6:00 am'), text: t('لمن يحب التحدي', 'For those who like a challenge'), icon: 'mountain' }),
        item(t('ليلة الأضواء', 'Night lights ride'), { meta: t('الخميس ٨:٠٠ م', 'Thu 8:00 pm'), text: t('جولة في المدينة بأضواء ملونة', 'A city ride with coloured lights'), icon: 'lightbulb' }),
      ],
    },
    {
      kind: 'items', id: 'roads', nav: t('الطرق', 'Roads'), role: 'gallery',
      eyebrow: t('طرقنا', 'Our roads'),
      title: t('حيث نركب', 'Where we ride'),
      items: [
        item(t('الطريق إلى الجبل', 'The road to the hills'), { img: 563 }),
        item(t('نفق الأشجار', 'The tree tunnel'), { img: 1063 }),
        item(t('درب الحديقة', 'The park path'), { img: 339 }),
        item(t('استراحة على الشاطئ', 'A rest by the shore'), { img: 203 }),
        item(t('طريق الوادي', 'The valley road'), { img: 191 }),
        item(t('أمام المحل', 'Outside the shop'), { img: 428 }),
      ],
    },
    {
      kind: 'testimonials', id: 'riders',
      eyebrow: t('الراكبون', 'Riders'),
      title: t('تركوا السيارة في البيت', 'They left the car at home'),
      items: [
        { quote: t('أذهب إلى عملي بالدراجة الكهربائية منذ سنة، ووفّرت ثمنها من البنزين.', 'I\'ve ridden my e-bike to work for a year and saved its price in fuel.'), name: t('هيثم جابر', 'Haitham Jaber'), role: t('موظف بنك', 'Bank clerk') },
        { quote: t('أصلحوا دراجة ابني في نصف ساعة وعلّموه كيف ينفخ الإطار بنفسه.', 'They fixed my son\'s bike in half an hour and taught him to pump the tyre himself.'), name: t('سوزان عيسى', 'Suzan Issa'), role: t('أم', 'Mother') },
        { quote: t('جولة الشروق إلى البحر الميت أجمل بداية لأي أسبوع.', 'The sunrise ride to the Dead Sea is the best start to any week.'), name: t('مازن الشريف', 'Mazen Al-Sharif'), role: t('راكب منذ ٢٠٢٢', 'Riding since 2022') },
      ],
    },
    {
      kind: 'contact', id: 'visit', nav: t('زورونا', 'Visit'),
      eyebrow: t('زورونا', 'Visit us'),
      title: t('جرّب قبل أن تشتري', 'Try before you buy'),
      text: t('تعال واختر دراجة وجرّبها يومًا كاملًا مجانًا، أو أحضر دراجتك للصيانة.', 'Come and pick a bike to ride free for a whole day, or bring yours in for a service.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'ride@ajala.example',
      address: t('شارع عمّان ٧، أريحا', '7 Amman Street, Jericho'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('07:00 – 19:00') },
        { d: t('الجمعة', 'Friday'), t: same('14:00 – 19:00') },
      ],
      cta: t('احجز تجربة', 'Book a test ride'),
    },
  ],
};
