import type { Profile } from '../types';
import { item, same, t } from './helpers';

export const photographer: Profile = {
  id: 'photographer',
  label: t('مصوّرة', 'Photographer'),
  brand: t('لينا حدّاد', 'Lina Haddad'),
  mark: t('ل', 'L'),
  tagline: t('بورتريه وأعراس وسفر', 'Portrait, wedding and travel photography'),
  navCta: t('احجز جلسة', 'Book a session'),
  socials: ['instagram', 'behance'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مصوّرة مستقلة', 'Independent photographer'),
      title: t('أصوّر الضوء قبل أن يختفي', 'I photograph light before it\'s gone'),
      lead: t('بورتريه، أعراس، ورحلات. عشر سنوات أبحث عن اللحظة الصادقة بين الوضعيات المصطنعة.', 'Portraits, weddings and journeys. Ten years of looking for the honest moment between the posed ones.'),
      cta: t('احجز جلسة', 'Book a session'),
      cta2: t('المعرض', 'Portfolio'),
      img: 1027, imgs: [1015, 829, 979],
      badge: t('الحجز لموسم ٢٠٢٧', 'Booking 2027'),
    },
    {
      kind: 'items', id: 'work', nav: t('الأعمال', 'Work'), role: 'gallery',
      eyebrow: t('مختارات', 'Selected'),
      title: t('أعمال مختارة', 'Selected work'),
      items: [
        item(t('فيورد', 'Fjord'), { meta: t('سفر', 'Travel'), img: 1015 }),
        item(t('نور', 'Nour'), { meta: t('بورتريه', 'Portrait'), img: 996 }),
        item(t('الوادي الأحمر', 'Red canyon'), { meta: t('سفر', 'Travel'), img: 1016 }),
        item(t('ليلة العرس', 'Wedding night'), { meta: t('أعراس', 'Weddings'), img: 1004 }),
        item(t('شفق', 'Aurora'), { meta: t('طبيعة', 'Nature'), img: 901 }),
        item(t('المظلة الحمراء', 'Red umbrella'), { meta: t('شارع', 'Street'), img: 797 }),
        item(t('كابادوكيا', 'Cappadocia'), { meta: t('سفر', 'Travel'), img: 791 }),
        item(t('قِباب', 'Domes'), { meta: t('عمارة', 'Architecture'), img: 979 }),
        item(t('القمة', 'The peak'), { meta: t('طبيعة', 'Nature'), img: 906 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عنّي', 'About'),
      eyebrow: t('عنّي', 'About me'),
      title: t('مرحبًا، أنا لينا', 'Hi, I\'m Lina'),
      text: [
        t('بدأت بكاميرا أبي القديمة في الرابعة عشرة. درست التصوير في عمّان وعملت مع صحف ومجلات قبل أن أتفرغ للبورتريه والأعراس.', 'I started with my father\'s old camera at fourteen. I studied photography in Amman and worked for newspapers and magazines before focusing on portraits and weddings.'),
        t('أحب الضوء الطبيعي والناس على حقيقتهم. لا أطلب منك أن تبتسم، أنتظر حتى تبتسم.', 'I love natural light and people as they are. I don\'t ask you to smile; I wait until you do.'),
      ],
      img: 823, img2: 435,
      quote: t('الصورة الجيدة لا تُلتقط، تُنتظر.', 'A good photograph isn\'t taken; it\'s waited for.'),
      sign: t('لينا', 'Lina'),
    },
    {
      kind: 'items', id: 'packages', nav: t('الباقات', 'Packages'), role: 'pricing',
      eyebrow: t('الباقات', 'Packages'),
      title: t('اختر جلستك', 'Choose your session'),
      items: [
        item(t('بورتريه', 'Portrait'), { price: '$180', meta: t('ساعة', '1 hour'), list: [t('٢٥ صورة معدّلة', '25 edited photos'), t('موقع واحد', 'One location'), t('معرض أونلاين', 'Online gallery')] }),
        item(t('عرس', 'Wedding'), { price: '$1,400', meta: t('يوم كامل', 'full day'), featured: true, tag: t('الأكثر حجزًا', 'Most booked'), list: [t('٤٠٠ صورة', '400 photos'), t('مصوّرة مساعدة', 'Second shooter'), t('ألبوم مطبوع', 'Printed album')] }),
        item(t('علامات تجارية', 'Brands'), { price: '$650', meta: t('نصف يوم', 'half day'), list: [t('٦٠ صورة منتجات', '60 product photos'), t('حقوق استخدام تجاري', 'Commercial rights')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'kind-words',
      eyebrow: t('كلمات لطيفة', 'Kind words'),
      title: t('صور نعود إليها', 'Photos we keep coming back to'),
      items: [
        { quote: t('لم نشعر بوجود كاميرا طوال العرس، ثم رأينا الصور وبكينا.', 'We never felt there was a camera all day, then we saw the photos and cried.'), name: t('هالة وسامي', 'Hala & Sami'), role: t('عرس', 'Wedding') },
        { quote: t('أخيرًا صورة بورتريه أحبها. لينا تعرف كيف تجعلك مرتاحًا.', 'Finally a portrait I love. Lina knows how to put you at ease.'), name: t('ميس عبده', 'Mais Abdo'), role: t('بورتريه', 'Portrait') },
        { quote: t('صور منتجاتنا صارت أجمل من المنتجات نفسها، تقريبًا.', 'Our product photos are now prettier than the products themselves, almost.'), name: t('غُرزة', 'Ghurza'), role: t('علامة تجارية', 'Brand') },
      ],
    },
    {
      kind: 'cta',
      title: t('لنصنع شيئًا جميلًا', 'Let\'s make something beautiful'),
      text: t('المواعيد محدودة كل شهر.', 'Dates are limited each month.'),
      cta: t('احجز الآن', 'Book now'),
      img: 1015,
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('أخبرني عن قصتك', 'Tell me your story'),
      text: t('اكتب لي التاريخ والمكان ونوع الجلسة.', 'Send me the date, the place and the kind of session.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'hello@linahaddad.example',
      address: t('حيفا، وأي مكان آخر', 'Haifa, and anywhere else'),
      hours: [
        { d: t('الرد على الرسائل', 'Replies'), t: t('خلال ٢٤ ساعة', 'Within 24 hours') },
      ],
      cta: t('راسلني', 'Message me'),
    },
  ],
};

export const app: Profile = {
  id: 'app',
  label: t('تطبيق', 'App'),
  brand: t('مشوار', 'Mishwar'),
  mark: t('م', 'M'),
  tagline: t('كل مشاويرك من تطبيق واحد', 'All your errands in one app'),
  navCta: t('حمّل التطبيق', 'Get the app'),
  socials: ['instagram', 'x', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('تطبيق توصيل محلي', 'Local delivery app'),
      title: t('مشوارك علينا', 'We\'ll run the errand'),
      lead: t('اطلب من محلات حارتك: البقالة، الصيدلية، المخبز والمطاعم. توصيل خلال ٣٠ دقيقة، تتبّع مباشر للسائق، والدفع نقدًا أو بالبطاقة.', 'Order from the shops in your neighbourhood: grocer, pharmacy, bakery and restaurants. Delivery in 30 minutes, live driver tracking, pay cash or by card.'),
      cta: t('حمّل التطبيق', 'Get the app'),
      cta2: t('كيف يعمل', 'How it works'),
      img: 504, imgs: [341, 160, 816],
      badge: t('٤٫٨ على المتاجر', '4.8 on the stores'),
    },
    { kind: 'logos', title: t('كتبوا عنا', 'As featured in'), items: ['SAWT NEWS', 'TECH ARABI', 'RAYA FM', 'WASL MAG', 'BAYAN'] },
    {
      kind: 'items', id: 'features', nav: t('المزايا', 'Features'), role: 'offer',
      eyebrow: t('المزايا', 'Features'),
      title: t('كل ما تحتاجه، من محلات تعرفها', 'Everything you need, from shops you know'),
      items: [
        item(t('محلات الحارة', 'Neighbourhood shops'), { text: t('أكثر من ٩٠٠ محل في ست مدن', 'Over 900 shops in six cities'), icon: 'store' }),
        item(t('تتبّع مباشر', 'Live tracking'), { text: t('تعرف أين طلبك كل لحظة', 'See where your order is at every moment'), icon: 'map-pin' }),
        item(t('دفع مرن', 'Flexible payment'), { text: t('نقدًا أو بالبطاقة أو بالمحفظة', 'Cash, card or wallet'), icon: 'wallet' }),
        item(t('جدولة الطلب', 'Scheduled orders'), { text: t('خبز الصباح يصل قبل أن تستيقظ', 'Morning bread arrives before you wake'), icon: 'calendar-days' }),
        item(t('طلب جماعي', 'Group orders'), { text: t('قسّم الفاتورة مع أصدقائك', 'Split the bill with friends'), icon: 'users' }),
        item(t('دعم بالعربية', 'Arabic support'), { text: t('فريق حقيقي على مدار الساعة', 'Real people around the clock'), icon: 'message-circle' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '900+', label: t('محل', 'shops') },
      { value: '30', label: t('دقيقة متوسط التوصيل', 'minutes average delivery') },
      { value: '120', label: t('ألف مستخدم', 'thousand users') },
      { value: '4.8', label: t('تقييم المتاجر', 'store rating') },
    ] },
    {
      kind: 'items', id: 'how', nav: t('كيف يعمل', 'How it works'), role: 'process',
      eyebrow: t('كيف يعمل', 'How it works'),
      title: t('ثلاث نقرات وتنتهي', 'Three taps and you\'re done'),
      items: [
        item(t('اختر المحل', 'Pick a shop'), { text: t('من محلات حارتك', 'From your neighbourhood'), icon: 'store' }),
        item(t('أضف طلبك', 'Add your order'), { text: t('أو صوّر قائمة المشتريات', 'Or snap your shopping list'), icon: 'shopping-bag' }),
        item(t('استلم عند بابك', 'Get it at your door'), { text: t('خلال ٣٠ دقيقة', 'Within 30 minutes'), icon: 'bike' }),
      ],
    },
    {
      kind: 'items', id: 'plans', nav: t('الأسعار', 'Pricing'), role: 'pricing',
      eyebrow: t('الأسعار', 'Pricing'),
      title: t('ابدأ مجانًا', 'Start for free'),
      items: [
        item(t('مجاني', 'Free'), { price: '0 ₪', meta: t('دائمًا', 'forever'), list: [t('كل المحلات', 'Every shop'), t('تتبّع مباشر', 'Live tracking'), t('توصيل بسعر عادي', 'Standard delivery fee')] }),
        item(t('مشوار بلس', 'Mishwar Plus'), { price: '19 ₪', meta: t('شهريًا', 'per month'), featured: true, tag: t('وفّر أكثر', 'Save more'), list: [t('توصيل مجاني فوق ٥٠ ₪', 'Free delivery over 50 ₪'), t('عروض حصرية', 'Exclusive offers'), t('أولوية في الذروة', 'Priority at peak times')] }),
        item(t('للمحلات', 'For shops'), { price: '99 ₪', meta: t('شهريًا', 'per month'), list: [t('لوحة تحكم', 'Dashboard'), t('تقارير المبيعات', 'Sales reports'), t('دعم مخصص', 'Dedicated support')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('المستخدمون', 'Users'),
      title: t('مشاوير أقل، وقت أكثر', 'Fewer errands, more time'),
      items: [
        { quote: t('دواء ابني وصل خلال عشرين دقيقة في منتصف الليل. صار التطبيق الأول على شاشتي.', 'My son\'s medicine arrived in twenty minutes at midnight. It\'s now the first app on my screen.'), name: t('علا حمّاد', 'Ola Hammad'), role: t('أم لطفلين', 'Mother of two') },
        { quote: t('محلي الصغير صار يبيع ضعف ما كان يبيعه، دون أن أوظّف سائقًا.', 'My small shop now sells twice as much, without hiring a driver.'), name: t('أبو رامي', 'Abu Rami'), role: t('بقالة الحارة', 'Corner grocer') },
        { quote: t('الطلب الجماعي حلّ مشكلة "مين بيدفع" في المكتب للأبد.', 'Group orders solved the office "who\'s paying" problem for good.'), name: t('تامر سلامة', 'Tamer Salameh'), role: t('مهندس', 'Engineer') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('أسئلة شائعة', 'Frequently asked'),
      items: [
        { q: t('في أي مدن يعمل مشوار؟', 'Which cities does Mishwar cover?'), a: t('رام الله والبيرة ونابلس وبيت لحم والخليل وجنين، وقريبًا المزيد.', 'Ramallah, Al-Bireh, Nablus, Bethlehem, Hebron and Jenin, with more coming soon.') },
        { q: t('كم رسوم التوصيل؟', 'How much is delivery?'), a: t('من ٥ إلى ١٠ شواكل حسب المسافة، ومجانًا لمشتركي بلس فوق ٥٠ شيكل.', 'From 5 to 10 shekels depending on distance, free over 50 ₪ for Plus members.') },
        { q: t('كيف أضيف محلي؟', 'How do I add my shop?'), a: t('سجّل من صفحة المحلات وسيتواصل معك فريقنا خلال يوم.', 'Sign up on the shops page and our team will call you within a day.') },
      ],
    },
    {
      kind: 'cta',
      title: t('حمّل مشوار الآن', 'Get Mishwar now'),
      text: t('متوفر على iPhone وأندرويد. أول توصيل مجاني.', 'On iPhone and Android. Your first delivery is free.'),
      cta: t('حمّل التطبيق', 'Download'),
      img: 816,
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('نحن هنا دائمًا', 'We\'re always here'),
      text: t('للدعم، الشراكات، أو انضمام محلك.', 'For support, partnerships, or adding your shop.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'support@mishwar.example',
      address: t('رام الله، فلسطين', 'Ramallah, Palestine'),
      hours: [
        { d: t('الدعم', 'Support'), t: same('24/7') },
      ],
      cta: t('راسل الدعم', 'Message support'),
    },
  ],
};

export const wedding: Profile = {
  id: 'wedding',
  label: t('دعوة عرس', 'Wedding invitation'),
  brand: t('سارة ويوسف', 'Sara & Yousef'),
  mark: t('س ي', 'S&Y'),
  tagline: t('٢٠ تشرين الثاني ٢٠٢٦', '20 November 2026'),
  navCta: t('أكّد حضورك', 'RSVP'),
  socials: ['instagram'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('ندعوكم لمشاركتنا فرحتنا', 'Together with our families'),
      title: t('سارة ويوسف', 'Sara & Yousef'),
      lead: t('بكل الحب ندعوكم لحضور حفل زفافنا يوم الجمعة ٢٠ تشرين الثاني ٢٠٢٦ في قاعة الأقواس، بيت لحم.', 'With all our love, we invite you to our wedding on Friday 20 November 2026 at the Arches Hall, Bethlehem.'),
      cta: t('أكّد حضورك', 'RSVP'),
      cta2: t('البرنامج', 'Programme'),
      img: 129, imgs: [815, 508, 696],
      badge: same('20.11.2026'),
      date: '2026-11-20T18:00:00',
      place: t('قاعة الأقواس، بيت لحم', 'The Arches Hall, Bethlehem'),
    },
    {
      kind: 'about', id: 'story', nav: t('حكايتنا', 'Our story'),
      eyebrow: t('حكايتنا', 'Our story'),
      title: t('التقينا صدفة، وبقينا عمدًا', 'We met by chance and stayed by choice'),
      text: [
        t('تعارفنا في مكتبة الجامعة عام ٢٠١٩، حين أخذ يوسف آخر نسخة من الكتاب الذي كانت سارة تبحث عنه. أعاده بعد أسبوع، ومعه فنجان قهوة.', 'We met in the university library in 2019, when Yousef took the last copy of the book Sara was looking for. He returned it a week later, with a cup of coffee.'),
        t('سبع سنوات من الرحلات والضحك والقهوة، والآن نبدأ الفصل الأجمل.', 'Seven years of trips, laughter and coffee, and now the best chapter begins.'),
      ],
      img: 815, img2: 1004,
      quote: t('وجعل بينكم مودّة ورحمة', 'And He placed between you affection and mercy'),
      sign: t('سارة ويوسف', 'Sara & Yousef'),
    },
    {
      kind: 'items', id: 'programme', nav: t('البرنامج', 'Programme'), role: 'schedule',
      eyebrow: t('البرنامج', 'Programme'),
      title: t('يوم الفرح', 'The day'),
      items: [
        item(t('استقبال الضيوف', 'Guests arrive'), { meta: same('18:00'), text: t('مشروبات ترحيبية في الحديقة', 'Welcome drinks in the garden'), icon: 'glass-water' }),
        item(t('الزفّة', 'The zaffeh'), { meta: same('19:00'), text: t('دخول العروسين مع الفرقة', 'The couple\'s entrance with the band'), icon: 'music' }),
        item(t('العشاء', 'Dinner'), { meta: same('20:30'), text: t('عشاء شامي على الطاولات', 'A Levantine dinner at the tables'), icon: 'utensils' }),
        item(t('الدبكة', 'Dabke'), { meta: same('22:00'), text: t('حتى آخر الليل', 'Until late'), icon: 'party-popper' }),
      ],
    },
    {
      kind: 'items', id: 'moments', nav: t('لحظات', 'Moments'), role: 'gallery',
      eyebrow: t('لحظات', 'Moments'),
      title: t('سبع سنوات في صور', 'Seven years in pictures'),
      items: [
        item(t('أول رحلة', 'First trip'), { img: 82 }),
        item(t('الخريف', 'Autumn'), { img: 553 }),
        item(t('شرارة', 'Sparkle'), { img: 660 }),
        item(t('ليلة الخطوبة', 'Engagement night'), { img: 828 }),
        item(t('قفل الحب', 'Love lock'), { img: 336 }),
        item(t('الزهور', 'Flowers'), { img: 696 }),
      ],
    },
    {
      kind: 'cta',
      title: t('كيف تصلون', 'Getting there'),
      text: t('قاعة الأقواس، طريق الخليل، بيت لحم. يتوفر موقف سيارات، وحافلة من رام الله الساعة ١٧:٠٠.', 'The Arches Hall, Hebron Road, Bethlehem. Parking available, with a shuttle from Ramallah at 17:00.'),
      cta: t('افتح الخريطة', 'Open the map'),
      img: 508,
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل الحفل', 'Before the day'),
      items: [
        { q: t('هل يمكن إحضار الأطفال؟', 'Can we bring children?'), a: t('نحب أطفالكم، لكن الحفل للكبار فقط هذه المرة.', 'We love your children, but this celebration is adults only.') },
        { q: t('ما اللباس المطلوب؟', 'What should we wear?'), a: t('رسمي، ونرحّب بالأثواب المطرزة.', 'Formal, and embroidered thobes are very welcome.') },
        { q: t('هل هناك قائمة هدايا؟', 'Is there a gift list?'), a: t('حضوركم هو الهدية.', 'Your presence is the gift.') },
      ],
    },
    {
      kind: 'contact', id: 'rsvp', nav: t('أكّد حضورك', 'RSVP'),
      eyebrow: t('تأكيد الحضور', 'RSVP'),
      title: t('هل ستكون معنا؟', 'Will you be with us?'),
      text: t('نرجو تأكيد الحضور قبل ١ تشرين الثاني عبر واتساب أو الاتصال بأهل العروسين.', 'Please let us know by 1 November on WhatsApp or by calling either family.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'rsvp@sarayousef.example',
      address: t('قاعة الأقواس، بيت لحم', 'The Arches Hall, Bethlehem'),
      hours: [
        { d: t('الجمعة ٢٠ تشرين الثاني', 'Friday 20 November'), t: same('18:00') },
      ],
      cta: t('أكّد عبر واتساب', 'RSVP on WhatsApp'),
    },
  ],
};

export const conference: Profile = {
  id: 'conference',
  label: t('مؤتمر', 'Conference'),
  brand: t('قمّة ٢٠٢٦', 'Qimma 2026'),
  mark: t('ق', 'Q'),
  tagline: t('المؤتمر السنوي للتقنية وريادة الأعمال', 'The annual tech and startup conference'),
  navCta: t('احجز تذكرتك', 'Get tickets'),
  socials: ['x', 'linkedin', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('١٢–١٣ كانون الأول ٢٠٢٦ · رام الله', '12–13 December 2026 · Ramallah'),
      title: t('المستقبل يُبنى هنا', 'The future is built here'),
      lead: t('يومان من المحاضرات وورش العمل واللقاءات مع ٤٠ متحدثًا و١٥٠٠ مشارك من رواد التقنية في فلسطين والمنطقة.', 'Two days of talks, workshops and meetings with 40 speakers and 1,500 founders, engineers and investors from Palestine and the region.'),
      cta: t('احجز تذكرتك', 'Get your ticket'),
      cta2: t('البرنامج', 'Agenda'),
      img: 158, imgs: [117, 1079, 452],
      badge: t('التذاكر المبكرة متاحة', 'Early-bird open'),
      date: '2026-12-12T09:00:00',
      place: t('قصر رام الله الثقافي', 'Ramallah Cultural Palace'),
    },
    { kind: 'marquee', items: [t('ذكاء اصطناعي', 'AI'), t('ريادة أعمال', 'Startups'), t('تمويل', 'Funding'), t('تصميم', 'Design'), t('أمن سيبراني', 'Security'), t('عمل عن بعد', 'Remote work')] },
    {
      kind: 'about', id: 'about', nav: t('عن القمة', 'About'),
      eyebrow: t('عن القمة', 'About'),
      title: t('أكبر لقاء تقني في فلسطين', 'Palestine\'s biggest tech gathering'),
      text: [
        t('منذ ٢٠١٨ تجمع القمة المبرمجين والمصممين والمستثمرين ليتعلموا من بعضهم ويبنوا شراكات حقيقية.', 'Since 2018, Qimma has brought engineers, designers and investors together to learn from one another and build real partnerships.'),
        t('هذا العام: مسار كامل للذكاء الاصطناعي بالعربية، ومسابقة للشركات الناشئة بجوائز ١٠٠ ألف دولار.', 'This year: a full track on Arabic AI and a startup competition with $100,000 in prizes.'),
      ],
      img: 1079, img2: 452,
      quote: t('الموهبة موجودة، ونحن نصنع لها المنصة.', 'The talent is here; we build the stage.'),
      sign: t('فريق القمة', 'The Qimma team'),
    },
    { kind: 'stats', items: [
      { value: '40', label: t('متحدثًا', 'speakers') },
      { value: '1,500', label: t('مشارك', 'attendees') },
      { value: '24', label: t('ورشة عمل', 'workshops') },
      { value: '100', label: t('ألف دولار جوائز', 'thousand dollars in prizes') },
    ] },
    {
      kind: 'items', id: 'speakers', nav: t('المتحدثون', 'Speakers'), role: 'extra',
      eyebrow: t('المتحدثون', 'Speakers'),
      title: t('أصوات تستحق الاستماع', 'Voices worth hearing'),
      items: [
        item(t('د. رنا قاسم', 'Dr. Rana Qasem'), { meta: t('باحثة ذكاء اصطناعي', 'AI researcher'), img: 1027 }),
        item(t('طارق حنّا', 'Tareq Hanna'), { meta: t('مؤسس شركة ناشئة', 'Startup founder'), img: 856 }),
        item(t('مايا خليل', 'Maya Khalil'), { meta: t('مصممة منتجات', 'Product designer'), img: 64 }),
        item(t('يزن عيسى', 'Yazan Issa'), { meta: t('مستثمر', 'Investor'), img: 1005 }),
        item(t('نور الهدى', 'Nour Al-Huda'), { meta: t('مهندسة أمن', 'Security engineer'), img: 996 }),
        item(t('كريم سابا', 'Karim Saba'), { meta: t('مطوّر', 'Developer'), img: 669 }),
      ],
    },
    {
      kind: 'items', id: 'agenda', nav: t('البرنامج', 'Agenda'), role: 'schedule',
      eyebrow: t('البرنامج', 'Agenda'),
      title: t('اليوم الأول', 'Day one'),
      items: [
        item(t('التسجيل والقهوة', 'Registration & coffee'), { meta: same('09:00'), icon: 'coffee' }),
        item(t('الكلمة الافتتاحية: الذكاء الاصطناعي بالعربية', 'Keynote: AI in Arabic'), { meta: same('10:00'), text: t('د. رنا قاسم', 'Dr. Rana Qasem'), icon: 'mic' }),
        item(t('حلقة نقاش: التمويل في ٢٠٢٧', 'Panel: funding in 2027'), { meta: same('11:30'), text: t('يزن عيسى وضيوف', 'Yazan Issa and guests'), icon: 'users' }),
        item(t('غداء وتعارف', 'Lunch & networking'), { meta: same('13:00'), icon: 'utensils' }),
        item(t('ورش عمل متوازية', 'Parallel workshops'), { meta: same('14:30'), text: t('ست ورش في ثلاث قاعات', 'Six workshops in three rooms'), icon: 'laptop' }),
        item(t('نهائي مسابقة الشركات الناشئة', 'Startup competition final'), { meta: same('17:00'), icon: 'trophy' }),
      ],
    },
    {
      kind: 'items', id: 'tickets', nav: t('التذاكر', 'Tickets'), role: 'pricing',
      eyebrow: t('التذاكر', 'Tickets'),
      title: t('احجز مكانك', 'Save your seat'),
      items: [
        item(t('طالب', 'Student'), { price: '$15', meta: t('يومان', 'two days'), list: [t('كل المحاضرات', 'All talks'), t('غداء', 'Lunch'), t('شهادة حضور', 'Attendance certificate')] }),
        item(t('عادي', 'Standard'), { price: '$45', meta: t('يومان', 'two days'), featured: true, tag: t('سعر مبكر', 'Early bird'), list: [t('كل المحاضرات', 'All talks'), t('ورشتا عمل', 'Two workshops'), t('غداء وقهوة', 'Lunch & coffee')] }),
        item(t('VIP', 'VIP'), { price: '$120', meta: t('يومان', 'two days'), list: [t('مقاعد أمامية', 'Front seats'), t('عشاء المتحدثين', 'Speakers\' dinner'), t('كل الورش', 'All workshops')] }),
      ],
    },
    { kind: 'logos', title: t('برعاية', 'Sponsored by'), items: ['NAWA', 'PALPAY', 'NOOR BANK', 'MADAR', 'JAWWAL CLOUD', 'SANAD'] },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('معلومات عملية', 'Practical info'),
      items: [
        { q: t('هل تُبث المحاضرات؟', 'Are talks streamed?'), a: t('الكلمات الرئيسية فقط، وتُنشر كل المحاضرات بعد أسبوع.', 'Keynotes only; every talk is published a week later.') },
        { q: t('هل يمكن استرداد التذكرة؟', 'Can I get a refund?'), a: t('حتى أسبوعين قبل المؤتمر.', 'Up to two weeks before the event.') },
        { q: t('كيف أشارك في المسابقة؟', 'How do I enter the competition?'), a: t('قدّم شركتك قبل ١٥ تشرين الثاني.', 'Submit your startup before 15 November.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('نراك في رام الله', 'See you in Ramallah'),
      text: t('للرعاية والإعلام والمتطوعين.', 'For sponsorship, press and volunteers.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'hello@qimma.example',
      address: t('قصر رام الله الثقافي', 'Ramallah Cultural Palace'),
      hours: [
        { d: t('١٢ كانون الأول', '12 December'), t: same('09:00 – 18:00') },
        { d: t('١٣ كانون الأول', '13 December'), t: same('09:00 – 17:00') },
      ],
      cta: t('احجز تذكرتك', 'Get your ticket'),
    },
  ],
};
