import type { Profile } from '../types';
import { item, same, t } from './helpers';

export const hotel: Profile = {
  id: 'hotel',
  label: t('فندق', 'Hotel'),
  brand: t('بيت البحر', 'Bayt Al Bahr'),
  mark: t('ب', 'B'),
  tagline: t('فندق بوتيك على شاطئ المتوسط', 'A boutique hotel on the Mediterranean'),
  navCta: t('احجز إقامتك', 'Book your stay'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('فندق بوتيك · على البحر', 'Boutique hotel · by the sea'),
      title: t('استيقظ على صوت الموج', 'Wake up to the sound of the waves'),
      lead: t('اثنتا عشرة غرفة في بيت حجري قديم فوق البحر، فطور على السطح، وأزقّة تقودك إلى الميناء.', 'Twelve rooms in an old stone house above the sea, breakfast on the roof, and alleys that lead down to the harbour.'),
      cta: t('احجز إقامتك', 'Book your stay'),
      cta2: t('الغرف', 'Rooms'),
      img: 947, imgs: [49, 691, 536],
      badge: t('١٢ غرفة فقط', 'Only 12 rooms'),
    },
    {
      kind: 'about', id: 'house', nav: t('البيت', 'The house'),
      eyebrow: t('البيت', 'The house'),
      title: t('بيت عمره مئتا عام', 'A house two hundred years old'),
      text: [
        t('رممنا البيت حجرًا حجرًا، وأبقينا الأقواس والبلاط الأصلي، وأضفنا كل ما تحتاجه من راحة.', 'We restored the house stone by stone, kept the arches and original tiles, and added every comfort you need.'),
        t('كل غرفة مختلفة، وكلها تطل على البحر أو على الحديقة الداخلية.', 'Every room is different, and all look out over the sea or the inner garden.'),
      ],
      img: 1065, img2: 305,
      quote: t('الضيف يأتي غريبًا ويغادر صديقًا.', 'Guests arrive as strangers and leave as friends.'),
      sign: t('عائلة الخوري', 'The Khoury family'),
    },
    {
      kind: 'items', id: 'rooms', nav: t('الغرف', 'Rooms'), role: 'offer',
      eyebrow: t('الغرف والأجنحة', 'Rooms & suites'),
      title: t('اختر نافذتك', 'Choose your window'),
      items: [
        item(t('غرفة الحديقة', 'Garden room'), { text: t('سرير مزدوج، إطلالة على الحديقة', 'Double bed, garden view'), price: '$140', meta: t('لليلة', 'per night'), img: 691 }),
        item(t('غرفة البحر', 'Sea room'), { text: t('شرفة فوق البحر', 'A balcony over the sea'), price: '$190', meta: t('لليلة', 'per night'), img: 947, tag: t('الأكثر حجزًا', 'Most booked') }),
        item(t('جناح السطح', 'Roof suite'), { text: t('صالة وتراس خاص', 'Lounge and private terrace'), price: '$290', meta: t('لليلة', 'per night'), img: 1008 }),
        item(t('غرفة البرج', 'Tower room'), { text: t('إطلالة من كل الجهات', 'Views on every side'), price: '$240', meta: t('لليلة', 'per night'), img: 49 }),
      ],
    },
    {
      kind: 'items', id: 'amenities', role: 'extra',
      eyebrow: t('الخدمات', 'Amenities'),
      title: t('كل ما تحتاجه، ولا شيء زائد', 'Everything you need, nothing you don\'t'),
      items: [
        item(t('فطور على السطح', 'Rooftop breakfast'), { text: t('من مخابز الحي', 'From neighbourhood bakeries'), icon: 'coffee' }),
        item(t('مسبح', 'Pool'), { text: t('مياه مالحة، مفتوح حتى منتصف الليل', 'Salt water, open until midnight'), icon: 'waves-ladder' }),
        item(t('سبا', 'Spa'), { text: t('حمّام تقليدي ومساج', 'Traditional hammam and massage'), icon: 'flower-2' }),
        item(t('واي فاي', 'Wi-Fi'), { text: t('سريع في كل الغرف', 'Fast in every room'), icon: 'wifi' }),
        item(t('نقل من المطار', 'Airport transfer'), { text: t('عند الطلب', 'On request'), icon: 'car' }),
        item(t('جولات', 'Tours'), { text: t('في البلدة القديمة', 'Of the old town'), icon: 'map' }),
      ],
    },
    {
      kind: 'items', id: 'gallery', nav: t('صور', 'Gallery'), role: 'gallery',
      eyebrow: t('صور', 'Gallery'),
      title: t('أيام بطيئة', 'Slow days'),
      items: [
        item(t('الرصيف', 'The pier'), { img: 77 }),
        item(t('المسبح ليلًا', 'The pool at night'), { img: 536 }),
        item(t('النخيل', 'The palms'), { img: 108 }),
        item(t('الممشى', 'The boardwalk'), { img: 521 }),
        item(t('الشاطئ', 'The beach'), { img: 645 }),
        item(t('الميناء', 'The harbour'), { img: 164 }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('ضيوفنا', 'Our guests'),
      title: t('يعودون كل صيف', 'They come back every summer'),
      items: [
        { quote: t('فتحنا الشبّاك فكان البحر أمامنا مباشرة. الفطور على السطح وحده يستحق الرحلة.', 'We opened the window and the sea was right there. Breakfast on the roof alone is worth the trip.'), name: t('ريم وأحمد', 'Reem & Ahmad'), role: t('شهر العسل', 'Honeymoon') },
        { quote: t('عائلة الخوري تعاملك كأنك قريبهم. نصحونا بأماكن لم نكن لنجدها وحدنا.', 'The Khoury family treat you like a relative. They pointed us to places we\'d never have found alone.'), name: t('كلارا مولر', 'Clara Müller'), role: t('برلين', 'Berlin') },
        { quote: t('هدوء تام، وكل تفصيلة في الغرفة مدروسة.', 'Total calm, and every detail in the room is considered.'), name: t('ماهر الدجاني', 'Maher Dajani'), role: t('رحلة عمل', 'Business trip') },
      ],
    },
    {
      kind: 'cta',
      title: t('عروض الشتاء', 'Winter offers'),
      text: t('الليلة الثالثة مجانًا من تشرين الثاني حتى آذار.', 'Your third night free from November to March.'),
      cta: t('احجز العرض', 'Book the offer'),
      img: 521,
    },
    {
      kind: 'contact', id: 'book', nav: t('احجز', 'Book'),
      eyebrow: t('الحجز', 'Booking'),
      title: t('غرفتك تنتظرك', 'Your room is waiting'),
      text: t('احجز مباشرة معنا للحصول على أفضل سعر وفطور مجاني.', 'Book directly with us for the best price and free breakfast.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'stay@baytalbahr.example',
      address: t('الحي القديم، على البحر', 'The old quarter, by the sea'),
      hours: [
        { d: t('تسجيل الدخول', 'Check-in'), t: same('15:00') },
        { d: t('تسجيل الخروج', 'Check-out'), t: same('12:00') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const academy: Profile = {
  id: 'academy',
  label: t('أكاديمية', 'Academy'),
  brand: t('أكاديمية مدار', 'Madar Academy'),
  mark: t('م', 'M'),
  tagline: t('دورات عملية في البرمجة والتصميم واللغات', 'Hands-on courses in coding, design and languages'),
  navCta: t('سجّل الآن', 'Enrol now'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('تعليم عملي · رام الله وأونلاين', 'Hands-on learning · Ramallah & online'),
      title: t('تعلّم مهارة تغيّر مسارك', 'Learn a skill that changes your path'),
      lead: t('دورات قصيرة يقدّمها خبراء يعملون في المجال، بمشاريع حقيقية ومجموعات صغيرة، وشهادة معتمدة في النهاية.', 'Short courses taught by working professionals, with real projects, small groups and an accredited certificate at the end.'),
      cta: t('سجّل الآن', 'Enrol now'),
      cta2: t('الدورات', 'Courses'),
      img: 832, imgs: [180, 24, 1010],
      badge: t('خصم ٢٠٪ للطلاب', '20% off for students'),
    },
    {
      kind: 'items', id: 'courses', nav: t('الدورات', 'Courses'), role: 'offer',
      eyebrow: t('الدورات', 'Courses'),
      title: t('ابدأ هذا الشهر', 'Starting this month'),
      items: [
        item(t('تطوير الويب', 'Web development'), { text: t('HTML وCSS وJavaScript وReact', 'HTML, CSS, JavaScript and React'), meta: t('١٢ أسبوعًا', '12 weeks'), price: '1,200 ₪', img: 180, tag: t('يبدأ قريبًا', 'Starting soon'), icon: 'code' }),
        item(t('التصميم الجرافيكي', 'Graphic design'), { text: t('Illustrator وPhotoshop والهويات', 'Illustrator, Photoshop and identities'), meta: t('٨ أسابيع', '8 weeks'), price: '900 ₪', img: 534, icon: 'pen-tool' }),
        item(t('اللغة الإنجليزية', 'English'), { text: t('محادثة وكتابة للعمل', 'Speaking and writing for work'), meta: t('١٠ أسابيع', '10 weeks'), price: '650 ₪', img: 24, icon: 'languages' }),
        item(t('الخط العربي', 'Arabic calligraphy'), { text: t('النسخ والرقعة والديواني', 'Naskh, Ruqaa and Diwani'), meta: t('٦ أسابيع', '6 weeks'), price: '500 ₪', img: 533, icon: 'feather' }),
        item(t('برمجة للأطفال', 'Coding for kids'), { text: t('Scratch وروبوتات', 'Scratch and robots'), meta: t('٨ أسابيع', '8 weeks'), price: '450 ₪', img: 1010, icon: 'blocks' }),
        item(t('تحليل البيانات', 'Data analysis'), { text: t('Excel وPython وPower BI', 'Excel, Python and Power BI'), meta: t('١٠ أسابيع', '10 weeks'), price: '1,100 ₪', img: 0, icon: 'chart-column' }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن مدار', 'About'),
      eyebrow: t('عن مدار', 'About Madar'),
      title: t('نتعلّم بالعمل لا بالحفظ', 'We learn by doing, not memorising'),
      text: [
        t('كل دورة تنتهي بمشروع حقيقي تضيفه إلى ملف أعمالك، ويقيّمه أصحاب عمل من السوق.', 'Every course ends with a real project for your portfolio, reviewed by employers from the market.'),
        t('مجموعات لا تزيد عن اثني عشر طالبًا، ومدرّبون يعملون يوميًا فيما يعلّمونه.', 'Groups of no more than twelve, and trainers who do what they teach every day.'),
      ],
      img: 193, img2: 1012,
      quote: t('المهارة تُكتسب باليد، لا بالأذن.', 'A skill is learned with the hands, not the ears.'),
      sign: t('د. منى عبد الهادي، المديرة', 'Dr. Mona Abdel Hadi, director'),
    },
    { kind: 'stats', items: [
      { value: '3,800', label: t('خرّيج', 'graduates') },
      { value: '24', label: t('دورة', 'courses') },
      { value: '86%', label: t('وجدوا عملًا خلال ٦ أشهر', 'found work within 6 months') },
      { value: '12', label: t('طالبًا كحد أقصى للمجموعة', 'students per group, max') },
    ] },
    {
      kind: 'items', id: 'path', role: 'process',
      eyebrow: t('رحلتك', 'Your path'),
      title: t('من أول يوم إلى أول وظيفة', 'From day one to your first job'),
      items: [
        item(t('اختر دورتك', 'Choose a course'), { text: t('مع جلسة إرشاد مجانية', 'With a free guidance session'), icon: 'compass' }),
        item(t('تعلّم بمشروع', 'Learn through a project'), { text: t('من الأسبوع الأول', 'From the first week'), icon: 'hammer' }),
        item(t('احصل على شهادتك', 'Get certified'), { text: t('معتمدة من وزارة العمل', 'Accredited by the Ministry of Labour'), icon: 'award' }),
        item(t('انضم إلى الخريجين', 'Join the alumni'), { text: t('فرص عمل وتدريب', 'Jobs and internships'), icon: 'users' }),
      ],
    },
    {
      kind: 'items', id: 'plans', nav: t('الرسوم', 'Fees'), role: 'pricing',
      eyebrow: t('طرق التعلّم', 'Ways to learn'),
      title: t('اختر ما يناسبك', 'Pick what suits you'),
      items: [
        item(t('أونلاين', 'Online'), { price: '-30%', meta: t('من سعر الدورة', 'off the course price'), list: [t('بث مباشر وتسجيلات', 'Live sessions and recordings'), t('مرشد شخصي', 'Personal mentor')] }),
        item(t('حضوري', 'In person'), { price: t('سعر الدورة', 'Course price'), meta: t('رام الله', 'Ramallah'), featured: true, tag: t('الأكثر تأثيرًا', 'Most effective'), list: [t('مختبرات مجهزة', 'Equipped labs'), t('مجموعات صغيرة', 'Small groups'), t('مشروع مع شركة', 'A project with a company')] }),
        item(t('اشتراك سنوي', 'Annual pass'), { price: '3,900 ₪', meta: t('سنويًا', 'per year'), list: [t('أي ثلاث دورات', 'Any three courses'), t('ورش شهرية', 'Monthly workshops')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'alumni',
      eyebrow: t('خرّيجونا', 'Alumni'),
      title: t('بدأوا هنا', 'They started here'),
      items: [
        { quote: t('دخلت دورة الويب بلا أي خلفية برمجية، وبعد أربعة أشهر بدأت عملي الأول في شركة برمجيات.', 'I joined the web course with no coding background; four months later I started my first job at a software company.'), name: t('محمد زيد', 'Mohammad Zaid'), role: t('مطوّر واجهات', 'Front-end developer') },
        { quote: t('المشروع النهائي في التصميم صار أول عمل لعميل حقيقي.', 'My final design project became my first real client job.'), name: t('جنى مصلح', 'Jana Musleh'), role: t('مصممة', 'Designer') },
        { quote: t('ابني ينتظر يوم البرمجة أكثر من العطلة.', 'My son looks forward to coding day more than the holidays.'), name: t('سوسن داود', 'Sawsan Daoud'), role: t('أم طالب', 'Parent') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل أن تسجّل', 'Before you enrol'),
      items: [
        { q: t('هل أحتاج خبرة سابقة؟', 'Do I need experience?'), a: t('لا، أغلب الدورات تبدأ من الصفر.', 'No, most courses start from zero.') },
        { q: t('هل يمكن التقسيط؟', 'Can I pay in instalments?'), a: t('نعم، على ثلاث دفعات بلا فوائد.', 'Yes, in three interest-free payments.') },
        { q: t('ماذا لو فاتتني محاضرة؟', 'What if I miss a class?'), a: t('كل المحاضرات مسجّلة ومتاحة لك.', 'Every class is recorded and available to you.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('سجّل', 'Enrol'),
      eyebrow: t('التسجيل', 'Enrolment'),
      title: t('المقاعد محدودة', 'Seats are limited'),
      text: t('سجّل اسمك والدورة التي تهمك، ونتصل بك لترتيب جلسة تعارف.', 'Leave your name and the course you\'re interested in, and we\'ll call to arrange an intro session.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'learn@madar.example',
      address: t('شارع الإذاعة، رام الله', 'Al-Itha\'a Street, Ramallah'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('09:00 – 20:00') },
      ],
      cta: t('سجّل عبر واتساب', 'Enrol on WhatsApp'),
    },
  ],
};

export const gym: Profile = {
  id: 'gym',
  label: t('نادٍ رياضي', 'Fitness club'),
  brand: t('نبض', 'Nabd'),
  mark: t('ن', 'N'),
  tagline: t('نادٍ رياضي ومسبح ودروس جماعية', 'Gym, pool and group classes'),
  navCta: t('جرّب مجانًا', 'Try it free'),
  socials: ['instagram', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('نادي نبض · نابلس', 'Nabd Club · Nablus'),
      title: t('أقوى من الأمس', 'Stronger than yesterday'),
      lead: t('أجهزة حديثة، مسبح نصف أولمبي، ودرس جماعي كل ساعة، ومدرّبون يتابعون تقدّمك أسبوعًا بأسبوع.', 'Modern equipment, a half-Olympic pool, a group class every hour and coaches who track your progress week by week.'),
      cta: t('جرّب أسبوعًا مجانًا', 'Try a week free'),
      cta2: t('الاشتراكات', 'Memberships'),
      img: 1077, imgs: [841, 390, 177],
      badge: t('مفتوح ٦ص – ١١م', 'Open 6am – 11pm'),
    },
    { kind: 'marquee', items: [t('كروس فت', 'CrossFit'), t('سباحة', 'Swimming'), t('يوغا', 'Yoga'), t('ملاكمة', 'Boxing'), t('دراجات', 'Spinning'), t('تمارين قوة', 'Strength')] },
    {
      kind: 'about', id: 'club', nav: t('النادي', 'The club'),
      eyebrow: t('النادي', 'The club'),
      title: t('مكان يدفعك للاستمرار', 'A place that keeps you going'),
      text: [
        t('ألفان وخمسمئة متر مربع من الأجهزة والقاعات والمسبح، وزوايا هادئة للتمدد والتعافي.', 'Two and a half thousand square metres of equipment, studios and pool, with quiet corners for stretching and recovery.'),
        t('يبدأ كل مشترك بتقييم جسدي وخطة مكتوبة، ونعيد القياس كل شهر.', 'Every member starts with a body assessment and a written plan, and we re-measure every month.'),
      ],
      img: 637, img2: 103,
      quote: t('لا أحد يندم على تمرين.', 'Nobody regrets a workout.'),
      sign: t('رامي، المدرّب الرئيسي', 'Rami, head coach'),
    },
    {
      kind: 'items', id: 'programs', nav: t('البرامج', 'Programs'), role: 'offer',
      eyebrow: t('البرامج', 'Programs'),
      title: t('اختر طريقتك في الحركة', 'Choose how you move'),
      items: [
        item(t('دراجات داخلية', 'Indoor cycling'), { text: t('إيقاع وموسيقى وعرق', 'Rhythm, music and sweat'), meta: t('٤٥ دقيقة', '45 min'), img: 1077, icon: 'bike' }),
        item(t('سباحة', 'Swimming'), { text: t('دروس لكل الأعمار', 'Lessons for every age'), meta: t('٢٥ م', '25 m pool'), img: 841, icon: 'waves' }),
        item(t('تدريب عالي الشدة', 'HIIT'), { text: t('حرق أكبر في وقت أقل', 'Burn more in less time'), meta: t('٣٠ دقيقة', '30 min'), img: 390, icon: 'flame' }),
        item(t('تمارين خارجية', 'Outdoor training'), { text: t('مسارات الجبل كل جمعة', 'Mountain trails every Friday'), meta: t('أسبوعيًا', 'weekly'), img: 177, icon: 'mountain' }),
        item(t('تنس', 'Tennis'), { text: t('ملعبان ومدرّب', 'Two courts and a coach'), meta: t('بالحجز', 'by booking'), img: 840, icon: 'trophy' }),
        item(t('نادي الجري', 'Running club'), { text: t('٥ و١٠ كيلومترات', '5 and 10 km'), meta: t('السبت', 'Saturdays'), img: 103, icon: 'timer' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '2,500', label: t('متر مربع', 'square metres') },
      { value: '60', label: t('درسًا أسبوعيًا', 'classes a week') },
      { value: '18', label: t('مدرّبًا', 'coaches') },
      { value: '25m', label: t('مسبح', 'pool') },
    ] },
    {
      kind: 'items', id: 'schedule', nav: t('الجدول', 'Schedule'), role: 'schedule',
      eyebrow: t('جدول اليوم', 'Today\'s classes'),
      title: t('درس كل ساعة', 'A class every hour'),
      items: [
        item(t('كروس فت', 'CrossFit'), { meta: same('06:30'), text: t('مع رامي', 'with Rami'), icon: 'dumbbell' }),
        item(t('يوغا', 'Yoga'), { meta: same('09:00'), text: t('مع لانا', 'with Lana'), icon: 'flower-2' }),
        item(t('سباحة حرّة', 'Open swim'), { meta: same('12:00'), text: t('المسبح كله لك', 'The whole pool is yours'), icon: 'waves' }),
        item(t('ملاكمة', 'Boxing'), { meta: same('17:30'), text: t('مع زيد', 'with Zaid'), icon: 'swords' }),
        item(t('دراجات', 'Spinning'), { meta: same('19:00'), text: t('مع هبة', 'with Hiba'), icon: 'bike' }),
        item(t('تمارين قوة', 'Strength'), { meta: same('20:30'), text: t('مع سامي', 'with Sami'), icon: 'dumbbell' }),
      ],
    },
    {
      kind: 'items', id: 'plans', nav: t('الاشتراكات', 'Memberships'), role: 'pricing',
      eyebrow: t('الاشتراكات', 'Memberships'),
      title: t('بلا رسوم تسجيل', 'No joining fee'),
      items: [
        item(t('شهري', 'Monthly'), { price: '220 ₪', meta: t('شهريًا', 'per month'), list: [t('كل الأجهزة', 'All equipment'), t('المسبح', 'Pool'), t('درسان أسبوعيًا', 'Two classes a week')] }),
        item(t('ربع سنوي', 'Quarterly'), { price: '590 ₪', meta: t('لثلاثة أشهر', 'for three months'), featured: true, tag: t('الأكثر توفيرًا', 'Best value'), list: [t('كل الدروس', 'All classes'), t('تقييم شهري', 'Monthly assessment'), t('جلسة مع مدرّب', 'One coaching session')] }),
        item(t('سنوي', 'Annual'), { price: '1,990 ₪', meta: t('سنويًا', 'per year'), list: [t('كل شيء', 'Everything'), t('خطة غذائية', 'Nutrition plan'), t('دعوتان للأصدقاء شهريًا', 'Two guest passes a month')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'members',
      eyebrow: t('أعضاؤنا', 'Members'),
      title: t('نتائج حقيقية', 'Real results'),
      items: [
        { quote: t('خسرت ١٤ كيلوغرامًا في ستة أشهر، والأهم أنني صرت أحب المجيء.', 'I lost 14 kilos in six months, and more importantly I now love coming.'), name: t('أحمد شلبي', 'Ahmad Shalabi'), role: t('عضو منذ سنة', 'Member for a year') },
        { quote: t('دروس اليوغا مع لانا أفضل ساعة في أسبوعي.', 'Yoga with Lana is the best hour of my week.'), name: t('رغد مرعي', 'Raghad Mar\'i'), role: t('عضوة', 'Member') },
        { quote: t('أولادي تعلّموا السباحة هنا خلال الصيف.', 'My kids learned to swim here over the summer.'), name: t('وائل حجّة', 'Wael Hijjeh'), role: t('أب', 'Father') },
      ],
    },
    {
      kind: 'contact', id: 'join', nav: t('انضم', 'Join'),
      eyebrow: t('انضم', 'Join'),
      title: t('أسبوعك الأول علينا', 'Your first week is on us'),
      text: t('تعال في أي وقت مع هويتك، أو احجز جولة مع مدرّب.', 'Drop in any time with your ID, or book a tour with a coach.'),
      phone: '+970 9 000 0000', whatsapp: '+970 59 000 0000', email: 'join@nabd.example',
      address: t('شارع رفيديا، نابلس', 'Rafidia Street, Nablus'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('06:00 – 23:00') },
        { d: t('الجمعة', 'Friday'), t: same('08:00 – 20:00') },
      ],
      cta: t('احجز تجربة', 'Book a trial'),
    },
  ],
};
