import type { Profile } from '../types';
import { item, same, t } from './helpers';

export const perfume: Profile = {
  id: 'perfume',
  label: t('عطور', 'Perfumery'),
  brand: t('دار العود', 'Dar Al Oud'),
  mark: t('ع', 'O'),
  tagline: t('عطور شرقية تُركّب يدويًا منذ ١٩٥٦', 'Oriental perfumes blended by hand since 1956'),
  navCta: t('تسوّق', 'Shop'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('عطور شرقية · القدس', 'Oriental perfumery · Jerusalem'),
      title: t('عطر يشبهك', 'A scent that is yours'),
      lead: t('عود كمبودي، ورد طائفي، عنبر ومسك أبيض. نركّب عطورنا يدويًا بتركيز عالٍ يدوم من الصباح حتى المساء.', 'Cambodian oud, Taif rose, amber and white musk. We blend by hand at high concentrations that last from morning to night.'),
      cta: t('تسوّق العطور', 'Shop perfumes'),
      cta2: t('اصنع عطرك', 'Make your own'),
      img: 738, imgs: [953, 696, 891],
      badge: t('تركيب يدوي', 'Hand blended'),
    },
    {
      kind: 'about', id: 'house', nav: t('الدار', 'The house'),
      eyebrow: t('الدار', 'The house'),
      title: t('ثلاثة أجيال من العطّارين', 'Three generations of perfumers'),
      text: [
        t('في سوق العطّارين بالقدس القديمة بدأ جدي يقطّر ماء الورد عام ١٩٥٦. ما زلنا نعمل بالطريقة نفسها، بزيوت نختارها من مصادرها.', 'My grandfather began distilling rose water in Jerusalem\'s old perfumers\' market in 1956. We still work the same way, with oils chosen at the source.'),
        t('يمكنك أن تجلس معنا وتركّب عطرك الخاص، ونحفظ وصفته باسمك.', 'You can sit with us and blend your own scent; we keep the formula under your name.'),
      ],
      img: 953, img2: 852,
      quote: t('العطر ذاكرة لا تُرى.', 'Perfume is an invisible memory.'),
      sign: t('حسن العطّار', 'Hasan Al-Attar'),
    },
    {
      kind: 'items', id: 'collection', nav: t('المجموعة', 'Collection'), role: 'offer',
      eyebrow: t('المجموعة', 'The collection'),
      title: t('عطور الدار', 'House perfumes'),
      items: [
        item(t('عود ملكي', 'Royal Oud'), { text: t('عود كمبودي، زعفران، جلد', 'Cambodian oud, saffron, leather'), price: '420 ₪', meta: t('٥٠ مل', '50 ml'), img: 953, tag: t('توقيع الدار', 'Signature') }),
        item(t('ورد طائفي', 'Taif Rose'), { text: t('ورد، فلفل وردي، مسك', 'Rose, pink pepper, musk'), price: '320 ₪', meta: t('٥٠ مل', '50 ml'), img: 696 }),
        item(t('عنبر', 'Amber'), { text: t('عنبر، فانيلا، صندل', 'Amber, vanilla, sandalwood'), price: '290 ₪', meta: t('٥٠ مل', '50 ml'), img: 112 }),
        item(t('مسك أبيض', 'White Musk'), { text: t('مسك، قطن، زهر البرتقال', 'Musk, cotton, orange blossom'), price: '240 ₪', meta: t('٥٠ مل', '50 ml'), img: 798 }),
        item(t('ليل', 'Layl'), { text: t('بخور، باتشولي، توت أسود', 'Incense, patchouli, blackcurrant'), price: '360 ₪', meta: t('٥٠ مل', '50 ml'), img: 891 }),
        item(t('زعفران', 'Saffron'), { text: t('زعفران، هيل، عسل', 'Saffron, cardamom, honey'), price: '340 ₪', meta: t('٥٠ مل', '50 ml'), img: 360 }),
      ],
    },
    { kind: 'stats', items: [
      { value: '1956', label: t('سنة التأسيس', 'founded') },
      { value: '40+', label: t('زيتًا عطريًا', 'perfume oils') },
      { value: '12h', label: t('ثبات العطر', 'lasting power') },
      { value: '3', label: t('أجيال', 'generations') },
    ] },
    {
      kind: 'items', id: 'bespoke', nav: t('عطرك الخاص', 'Bespoke'), role: 'process',
      eyebrow: t('عطرك الخاص', 'Bespoke'),
      title: t('اصنع عطرك في جلسة واحدة', 'Make your own scent in one sitting'),
      items: [
        item(t('اختر القلب', 'Choose the heart'), { text: t('من أربعين زيتًا', 'From forty oils'), icon: 'flask-conical' }),
        item(t('وازن النسب', 'Balance the notes'), { text: t('مع عطّارنا', 'With our perfumer'), icon: 'scale' }),
        item(t('خذ زجاجتك', 'Take your bottle'), { text: t('نحفظ الوصفة باسمك', 'We keep the formula under your name'), icon: 'gift' }),
      ],
    },
    {
      kind: 'items', id: 'atelier', role: 'gallery',
      eyebrow: t('المشغل', 'The atelier'),
      title: t('حيث تولد العطور', 'Where perfumes are born'),
      items: [
        item(t('المشغل', 'The atelier'), { img: 983 }),
        item(t('الزجاجات', 'Bottles'), { img: 36 }),
        item(t('المواد', 'Materials'), { img: 26 }),
        item(t('الليل', 'Night'), { img: 852 }),
        item(t('الزهور', 'Flowers'), { img: 152 }),
        item(t('الزنبق', 'Lily'), { img: 738 }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('قالوا', 'They said'),
      title: t('عطور تُسأل عنها', 'Scents people ask about'),
      items: [
        { quote: t('كل من يقترب مني يسأل عن العطر. العود الملكي يبقى حتى اليوم التالي.', 'Everyone who comes close asks what I\'m wearing. The Royal Oud lasts until the next day.'), name: t('فادي نصّار', 'Fadi Nassar'), role: t('زبون منذ ٢٠١٥', 'Customer since 2015') },
        { quote: t('ركّبت عطري الخاص في ساعة، وصار توقيعي. أعود كل سنة لأجدده.', 'I blended my own scent in an hour and it became my signature. I come back every year to refill it.'), name: t('لانا الشيخ', 'Lana Al-Sheikh'), role: t('عطر خاص', 'Bespoke client') },
        { quote: t('أجمل هدية قدمتها لأمي. التغليف وحده تحفة.', 'The most beautiful gift I\'ve given my mother. The wrapping alone is a work of art.'), name: t('رامي عطاالله', 'Rami Atallah'), role: t('هدية', 'Gift') },
      ],
    },
    {
      kind: 'cta',
      title: t('هدية لا تُنسى', 'A gift they won\'t forget'),
      text: t('علب هدايا مع بطاقة بخط اليد وتغليف مجاني.', 'Gift boxes with a handwritten card and free wrapping.'),
      cta: t('اختر هدية', 'Choose a gift'),
      img: 738,
    },
    {
      kind: 'contact', id: 'visit', nav: t('زورونا', 'Visit'),
      eyebrow: t('زورونا', 'Visit us'),
      title: t('تعال وشمّ بنفسك', 'Come and smell for yourself'),
      text: t('نرسل العينات والطلبات إلى كل المدن، أو زرنا في السوق القديم.', 'We send samples and orders to every city, or visit us in the old market.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'scent@daraloud.example',
      address: t('سوق العطّارين، البلدة القديمة، القدس', 'Perfumers\' Market, Old City, Jerusalem'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('10:00 – 20:00') },
      ],
      cta: t('اطلب عبر واتساب', 'Order on WhatsApp'),
    },
  ],
};

export const boutique: Profile = {
  id: 'boutique',
  label: t('متجر أزياء', 'Fashion boutique'),
  brand: t('غُرزة', 'Ghurza'),
  mark: t('غ', 'G'),
  tagline: t('تطريز فلسطيني يُلبس كل يوم', 'Palestinian embroidery for every day'),
  navCta: t('تسوّقي', 'Shop'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('تطريز فلسطيني معاصر', 'Contemporary Palestinian embroidery'),
      title: t('كل غرزة حكاية', 'Every stitch tells a story'),
      lead: t('أثواب وجاكيتات وحقائب مطرزة يدويًا على أيدي ستين امرأة في قرى الخليل وبيت لحم وغزة، بتصاميم تُلبس كل يوم.', 'Dresses, jackets and bags hand-embroidered by sixty women in villages around Hebron, Bethlehem and Gaza, designed to be worn every day.'),
      cta: t('تسوّقي المجموعة', 'Shop the collection'),
      cta2: t('حكايتنا', 'Our story'),
      img: 758, imgs: [535, 1059, 26],
      badge: t('مجموعة الخريف', 'Autumn collection'),
    },
    {
      kind: 'about', id: 'story', nav: t('حكايتنا', 'Our story'),
      eyebrow: t('حكايتنا', 'Our story'),
      title: t('من صندوق جدتي إلى خزانتك', 'From my grandmother\'s chest to your wardrobe'),
      text: [
        t('وجدنا في صندوق جدتي ثوبًا عمره سبعون عامًا، فقررنا أن نحمل غرزاته إلى ملابس اليوم.', 'In my grandmother\'s chest we found a seventy-year-old thobe and decided to carry its stitches into today\'s clothes.'),
        t('كل قطعة تحمل اسم المطرزة التي صنعتها، وتحصل على أجر عادل يصلها كاملًا.', 'Every piece carries the name of the woman who embroidered it, and she receives a fair wage in full.'),
      ],
      img: 1059, img2: 758,
      quote: t('التطريز لغة، ونحن نحفظها حيّة.', 'Embroidery is a language, and we keep it alive.'),
      sign: t('سلمى، المؤسِّسة', 'Salma, founder'),
    },
    {
      kind: 'items', id: 'collection', nav: t('المجموعة', 'Collection'), role: 'offer',
      eyebrow: t('المجموعة', 'The collection'),
      title: t('قطع الموسم', 'This season\'s pieces'),
      items: [
        item(t('ثوب الخليل', 'Hebron dress'), { text: t('قطن، تطريز أحمر عنابي', 'Cotton, deep red cross-stitch'), price: '780 ₪', img: 535, tag: t('مطرز يدويًا', 'Hand embroidered') }),
        item(t('شال القرى', 'Village scarf'), { text: t('صوف ناعم بنقشة السرو', 'Soft wool with the cypress motif'), price: '240 ₪', img: 758 }),
        item(t('حقيبة اليوم', 'Day bag'), { text: t('جلد طبيعي ولوحة مطرزة', 'Leather with an embroidered panel'), price: '420 ₪', img: 26 }),
        item(t('جاكيت الجينز', 'Denim jacket'), { text: t('ظهر مطرز بنجمة بيت لحم', 'Back embroidered with the Bethlehem star'), price: '560 ₪', img: 604 }),
        item(t('حذاء الفرح', 'Celebration shoes'), { text: t('حواف مطرزة يدويًا', 'Hand-embroidered trim'), price: '390 ₪', img: 21 }),
        item(t('طقم الإكسسوار', 'Accessory set'), { text: t('أساور وقلادة بالخرز', 'Beaded bracelets and necklace'), price: '180 ₪', img: 1059 }),
      ],
    },
    {
      kind: 'items', id: 'motifs', role: 'extra',
      eyebrow: t('النقوش', 'The motifs'),
      title: t('ماذا تقول الغرز', 'What the stitches say'),
      items: [
        item(t('السرو', 'Cypress'), { text: t('رمز الصمود والبقاء', 'A sign of steadfastness'), icon: 'trees' }),
        item(t('نجمة بيت لحم', 'Bethlehem star'), { text: t('ثماني رؤوس من المهد', 'Eight points from the Nativity'), icon: 'star' }),
        item(t('عرق الورد', 'Rose branch'), { text: t('زينة أثواب الأعراس', 'The wedding thobe\'s ornament'), icon: 'flower-2' }),
        item(t('ريش الطاووس', 'Peacock feathers'), { text: t('من نقوش غزة القديمة', 'From old Gaza patterns'), icon: 'feather' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '60', label: t('مطرزة', 'embroiderers') },
      { value: '14', label: t('قرية', 'villages') },
      { value: '100%', label: t('عمل يدوي', 'handmade') },
      { value: '40h', label: t('لتطريز ثوب واحد', 'to embroider one dress') },
    ] },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('من زبوناتنا', 'From our customers'),
      title: t('تراث يُلبس بفخر', 'Heritage worn with pride'),
      items: [
        { quote: t('لبست ثوب الخليل في تخرجي في لندن، وسألني الجميع عنه. شعرت أنني أحمل بلدي معي.', 'I wore the Hebron dress to my graduation in London and everyone asked about it. I felt I was carrying home with me.'), name: t('دانة صالح', 'Dana Saleh'), role: t('لندن', 'London') },
        { quote: t('الجاكيت مطرز بإتقان مدهش، ومع البطاقة اسم السيدة التي طرّزته. لمسة لا تُنسى.', 'The jacket is embroidered with amazing precision, and the card names the woman who made it. An unforgettable touch.'), name: t('رهف خليل', 'Rahaf Khalil'), role: t('عمّان', 'Amman') },
        { quote: t('أجمل هدية لخالتي في عيدها.', 'The most beautiful gift for my aunt\'s birthday.'), name: t('ياسر بنّا', 'Yaser Banna'), role: t('رام الله', 'Ramallah') },
      ],
    },
    {
      kind: 'cta',
      title: t('ثوب على مقاسك', 'A dress made to measure'),
      text: t('نطرز ثوب العرس أو الخطبة حسب مقاسك والألوان التي تختارينها.', 'We embroider wedding and engagement dresses to your measurements and colours.'),
      cta: t('احجزي موعدًا', 'Book a fitting'),
      img: 758,
    },
    {
      kind: 'contact', id: 'visit', nav: t('زورينا', 'Visit'),
      eyebrow: t('المتجر', 'The shop'),
      title: t('زورينا أو اطلبي أونلاين', 'Visit us or order online'),
      text: t('نشحن إلى كل العالم خلال أسبوع.', 'We ship worldwide within a week.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'hello@ghurza.example',
      address: t('البلدة القديمة، الخليل', 'Old City, Hebron'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('10:00 – 19:00') },
      ],
      cta: t('اطلبي عبر واتساب', 'Order on WhatsApp'),
    },
  ],
};
