import type { L, Profile } from '../types';
import { item, same, t } from './helpers';

/** A price in Jordanian dinars, written the way each language reads it. */
const jd = (n: string): L => t(`${n} د.أ`, `JD ${n}`);

export const bookshop: Profile = {
  id: 'bookshop',
  label: t('مكتبة', 'Bookshop'),
  brand: t('دار الورّاق', 'Dar Al-Warraq'),
  mark: t('و', 'W'),
  tagline: t('كتب جديدة ومستعملة في البلدة القديمة، منذ ١٩٧٤', 'New and second-hand books in the old city, since 1974'),
  navCta: t('اطلب كتابًا', 'Order a book'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مكتبة مستقلة · نابلس', 'Independent bookshop · Nablus'),
      title: t('كتاب واحد قد يغيّر صيفك', 'One book can change your summer'),
      lead: t('رفوف من الأرض إلى السقف: روايات عربية ومترجمة، وكتب أطفال، وطبعات قديمة نادرة. وإن لم نجد كتابك طلبناه لك خلال أسبوع.', 'Shelves from floor to ceiling: Arabic and translated novels, children\'s books and rare old editions. If we don\'t have your book, we\'ll order it within a week.'),
      cta: t('اطلب كتابًا', 'Order a book'),
      cta2: t('وصل حديثًا', 'New arrivals'),
      img: 1073, imgs: [885, 367, 403],
      badge: t('توصيل مجاني فوق ١٠٠ ₪', 'Free delivery over 100 ₪'),
    },
    { kind: 'marquee', items: [t('روايات', 'Novels'), t('شعر', 'Poetry'), t('تاريخ فلسطين', 'Palestinian history'), t('كتب أطفال', 'Children\'s books'), t('فلسفة', 'Philosophy'), t('طبعات نادرة', 'Rare editions')] },
    {
      kind: 'about', id: 'story', nav: t('حكايتنا', 'Our story'),
      eyebrow: t('حكايتنا', 'Our story'),
      title: t('ثلاثة أجيال بين الرفوف', 'Three generations among the shelves'),
      text: [
        t('فتح جدّي المكتبة عام ١٩٧٤ في دكان صغير قرب خان التجار، يبيع الكتب ويعيرها لمن لا يقدر على شرائها. وما زلنا نعير.', 'My grandfather opened the shop in 1974 in a small room near Khan al-Tujjar, selling books and lending them to anyone who couldn\'t buy. We still lend.'),
        t('نحمل اليوم أكثر من عشرين ألف عنوان، ونشتري المكتبات المنزلية القديمة لنعيد كتبها إلى قرّاء جدد.', 'Today we carry over twenty thousand titles, and we buy old home libraries to pass their books on to new readers.'),
      ],
      img: 119, img2: 486,
      quote: t('البيت بلا كتب غرفة بلا نافذة.', 'A house without books is a room without a window.'),
      sign: t('سامي الورّاق، صاحب المكتبة', 'Sami Al-Warraq, owner'),
    },
    {
      kind: 'items', id: 'new', nav: t('وصل حديثًا', 'New in'), role: 'offer',
      eyebrow: t('وصل حديثًا', 'Just in'),
      title: t('على طاولة هذا الأسبوع', 'On this week\'s table'),
      lead: t('اختيارات فريق المكتبة، ولكل كتاب بطاقة كتبها من قرأه.', 'Picked by the shop team, each with a card written by whoever read it.'),
      items: [
        item(t('رواية الشهر', 'Novel of the month'), { text: t('رواية عربية جديدة عن مدينة على البحر', 'A new Arabic novel about a city by the sea'), price: '55 ₪', img: 1073, tag: t('الأكثر طلبًا', 'Most wanted') }),
        item(t('ديوان مختار', 'A chosen collection'), { text: t('قصائد الحب والمنفى في طبعة أنيقة', 'Poems of love and exile in a fine edition'), price: '40 ₪', img: 486 }),
        item(t('تاريخ المدن', 'History of the cities'), { text: t('نابلس ويافا والقدس في الصور القديمة', 'Nablus, Jaffa and Jerusalem in old photographs'), price: '120 ₪', img: 885 }),
        item(t('صندوق الأطفال', 'The children\'s box'), { text: t('خمس قصص مصوّرة لسن ٤ – ٨', 'Five picture books for ages 4 – 8'), price: '95 ₪', img: 403 }),
        item(t('كتب إلكترونية', 'E-books'), { text: t('أكثر من ٣٠٠ عنوان عربي بصيغة رقمية', 'Over 300 Arabic titles in digital form'), price: '25 ₪', img: 367 }),
        item(t('طبعة نادرة', 'Rare edition'), { text: t('طبعة بيروت الأولى، ١٩٦٢، بحالة ممتازة', 'First Beirut printing, 1962, in fine condition'), price: '480 ₪', img: 119 }),
      ],
      cta: t('كل العناوين', 'All titles'),
    },
    {
      kind: 'items', id: 'evenings', nav: t('الأمسيات', 'Evenings'), role: 'schedule',
      eyebrow: t('في المكتبة', 'At the shop'),
      title: t('أمسيات هذا الشهر', 'Evenings this month'),
      items: [
        item(t('نادي القراءة', 'Book club'), { meta: t('الثلاثاء ٧:٠٠ م', 'Tue 7:00 pm'), text: t('نناقش رواية الشهر مع الشاي', 'We discuss the novel of the month over tea'), icon: 'book-open' }),
        item(t('ساعة الحكاية', 'Story hour'), { meta: t('السبت ١١:٠٠ ص', 'Sat 11:00 am'), text: t('للأطفال من ٤ إلى ٨ سنوات', 'For children aged 4 to 8'), icon: 'smile' }),
        item(t('توقيع كتاب', 'Book signing'), { meta: t('الخميس ٦:٣٠ م', 'Thu 6:30 pm'), text: t('مع كاتبة الرواية الفائزة بجائزة هذا العام', 'With the author of this year\'s prize-winning novel'), icon: 'pen' }),
        item(t('سوق المستعمل', 'Second-hand market'), { meta: t('آخر جمعة في الشهر', 'Last Friday of the month'), text: t('بادل كتابك القديم بكتاب جديد', 'Swap your old book for a new one'), icon: 'repeat' }),
      ],
    },
    {
      kind: 'testimonials', id: 'readers',
      eyebrow: t('قرّاؤنا', 'Our readers'),
      title: t('يعودون كل خميس', 'They come back every Thursday'),
      items: [
        { quote: t('طلبت كتابًا نفدت طبعته منذ عشرين سنة، فوجدوه لي خلال عشرة أيام.', 'I asked for a book out of print for twenty years, and they found it for me in ten days.'), name: t('هالة النابلسي', 'Hala Nabulsi'), role: t('معلّمة تاريخ', 'History teacher') },
        { quote: t('لا تخرج ابنتي من ساعة الحكاية إلا وفي يدها كتاب جديد.', 'My daughter never leaves story hour without a new book in her hands.'), name: t('عمر شاهين', 'Omar Shaheen'), role: t('أب', 'Parent') },
        { quote: t('أجمل ما فيها البطاقات المكتوبة باليد على كل كتاب. تشعر أن أحدًا اختاره لك.', 'The best part is the handwritten card on every book. It feels like someone chose it for you.'), name: t('لينا حمدان', 'Lina Hamdan'), role: t('طالبة أدب', 'Literature student') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل أن تطلب', 'Before you order'),
      items: [
        { q: t('هل توصلون خارج نابلس؟', 'Do you deliver outside Nablus?'), a: t('نعم، إلى كل مدن الضفة خلال يومين، وإلى الأردن بالبريد.', 'Yes, to every West Bank city within two days, and to Jordan by post.') },
        { q: t('هل تشترون الكتب المستعملة؟', 'Do you buy used books?'), a: t('نشتري المكتبات كاملة أو الكتب المفردة بحالة جيدة، ونزورك لتقييمها.', 'We buy whole libraries or single books in good condition, and visit you to value them.') },
        { q: t('هل يمكن حجز كتاب؟', 'Can I reserve a book?'), a: t('نحجزه لك أسبوعًا كاملًا برسالة واتساب واحدة.', 'We hold it for a full week with one WhatsApp message.') },
      ],
    },
    {
      kind: 'contact', id: 'visit', nav: t('زورونا', 'Visit'),
      eyebrow: t('زورونا', 'Visit us'),
      title: t('بين الرفوف متّسع لك', 'There is room for you among the shelves'),
      text: t('اسأل عن أي كتاب برسالة، أو تعال وتصفّح على راحتك؛ القهوة على حسابنا.', 'Ask about any book by message, or come and browse at your own pace; the coffee is on us.'),
      phone: '+970 9 000 0000', whatsapp: '+970 59 000 0000', email: 'books@warraq.example',
      address: t('شارع النصر ٤، البلدة القديمة، نابلس', '4 An-Nasr Street, Old City, Nablus'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('09:00 – 20:00') },
        { d: t('الجمعة', 'Friday'), t: same('16:00 – 21:00') },
      ],
      cta: t('اسأل عن كتاب', 'Ask about a book'),
    },
  ],
};

export const music: Profile = {
  id: 'music',
  label: t('مدرسة موسيقى', 'Music school'),
  brand: t('مقام', 'Maqam'),
  mark: t('م', 'M'),
  tagline: t('دروس موسيقى للأطفال والكبار في جبل اللويبدة', 'Music lessons for children and adults in Jabal Al-Weibdeh'),
  navCta: t('احجز درسًا تجريبيًا', 'Book a trial lesson'),
  socials: ['instagram', 'youtube', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مدرسة موسيقى · عمّان', 'Music school · Amman'),
      title: t('لم يفت الأوان لتعزف', 'It\'s never too late to play'),
      lead: t('بيانو وعود وجيتار وغناء، بدروس فردية ومجموعات صغيرة. معلّمون يعزفون على المسرح كل أسبوع، وحفلة في آخر كل فصل يصعد فيها كل طالب.', 'Piano, oud, guitar and voice, in private lessons and small groups. Teachers who play on stage every week, and an end-of-term concert where every student performs.'),
      cta: t('احجز درسًا تجريبيًا', 'Book a trial lesson'),
      cta2: t('الآلات', 'Instruments'),
      img: 1082, imgs: [145, 836, 39],
      badge: t('الدرس الأول مجاني', 'First lesson free'),
    },
    {
      kind: 'about', id: 'about', nav: t('عن مقام', 'About'),
      eyebrow: t('عن مقام', 'About Maqam'),
      title: t('نعلّم الأذن قبل الأصابع', 'We train the ear before the fingers'),
      text: [
        t('في مقام يتعلم الطالب أن يسمع قبل أن يعزف: المقامات العربية والسلم الغربي جنبًا إلى جنب، منذ الدرس الأول.', 'At Maqam students learn to listen before they play: Arabic maqamat and the Western scale side by side, from the very first lesson.'),
        t('بيت قديم من ثلاث طبقات، فيه سبع غرف عزف معزولة واستوديو تسجيل صغير وقاعة لخمسين مستمعًا.', 'An old three-storey house with seven soundproofed practice rooms, a small recording studio and a hall for fifty listeners.'),
      ],
      img: 453, img2: 304,
      quote: t('الموسيقى لغة، ومن يسمعها يتعلم الكلام بها.', 'Music is a language, and whoever listens learns to speak it.'),
      sign: t('أ. رامي سمارة، مدير المدرسة', 'Rami Samara, director'),
    },
    {
      kind: 'items', id: 'instruments', nav: t('الآلات', 'Instruments'), role: 'offer',
      eyebrow: t('الآلات', 'Instruments'),
      title: t('اختر صوتك', 'Choose your sound'),
      items: [
        item(t('البيانو', 'Piano'), { text: t('من القراءة الأولى إلى قطع الحفلات', 'From first reading to concert pieces'), meta: t('٤٥ دقيقة', '45 min'), price: jd('18'), img: 1082 }),
        item(t('الجيتار', 'Guitar'), { text: t('كلاسيكي وأكوستيك وإيقاعات عربية', 'Classical, acoustic and Arabic rhythms'), meta: t('٤٥ دقيقة', '45 min'), price: jd('16'), img: 145 }),
        item(t('الفرقة العربية', 'Arabic ensemble'), { text: t('عود وقانون وإيقاع يعزفون معًا', 'Oud, qanun and percussion playing together'), meta: t('ساعتان', '2 hours'), price: jd('12'), img: 453, tag: t('جماعي', 'Group') }),
        item(t('الجيتار الكهربائي', 'Electric guitar'), { text: t('روك وبلوز وارتجال', 'Rock, blues and improvisation'), meta: t('٤٥ دقيقة', '45 min'), price: jd('16'), img: 836 }),
        item(t('الإنتاج الموسيقي', 'Music production'), { text: t('تسجيل ومكساج في استوديو المدرسة', 'Recording and mixing in the school studio'), meta: t('٩٠ دقيقة', '90 min'), price: jd('25'), img: 304 }),
        item(t('الاستماع والنظريات', 'Listening and theory'), { text: t('كيف تُبنى الأغنية، من أم كلثوم إلى اليوم', 'How a song is built, from Umm Kulthum to today'), meta: t('ساعة', '1 hour'), price: jd('10'), img: 39 }),
      ],
    },
    {
      kind: 'items', id: 'week', nav: t('الأسبوع', 'The week'), role: 'schedule',
      eyebrow: t('هذا الأسبوع', 'This week'),
      title: t('في غرف العزف', 'In the practice rooms'),
      items: [
        item(t('عود للمبتدئين', 'Oud for beginners'), { meta: t('الأحد ٥:٠٠ م', 'Sun 5:00 pm'), text: t('مع الأستاذ نزار', 'with Nizar'), icon: 'music' }),
        item(t('كورال الأطفال', 'Children\'s choir'), { meta: t('الاثنين ٤:٠٠ م', 'Mon 4:00 pm'), text: t('من ٦ إلى ١٢ سنة', 'Ages 6 to 12'), icon: 'mic' }),
        item(t('ورشة الإيقاع', 'Rhythm workshop'), { meta: t('الأربعاء ٧:٠٠ م', 'Wed 7:00 pm'), text: t('دربكة ودف ورق', 'Darbuka, daf and riq'), icon: 'drum' }),
        item(t('جلسة ارتجال', 'Jam session'), { meta: t('الخميس ٨:٣٠ م', 'Thu 8:30 pm'), text: t('مفتوحة لكل الطلاب', 'Open to every student'), icon: 'guitar' }),
      ],
    },
    {
      kind: 'items', id: 'fees', nav: t('الرسوم', 'Fees'), role: 'pricing',
      eyebrow: t('الرسوم', 'Fees'),
      title: t('اشتراك شهري بلا عقود', 'A monthly plan, no contract'),
      items: [
        item(t('درس أسبوعي', 'Weekly lesson'), { price: jd('65'), meta: t('شهريًا', 'per month'), list: [t('أربعة دروس فردية', 'Four private lessons'), t('غرفة تدريب ساعة أسبوعيًا', 'A practice room one hour a week')] }),
        item(t('درسان أسبوعيًا', 'Two a week'), { price: jd('120'), meta: t('شهريًا', 'per month'), featured: true, tag: t('الأسرع تقدمًا', 'Fastest progress'), list: [t('ثمانية دروس فردية', 'Eight private lessons'), t('الفرقة أو الكورال', 'Ensemble or choir'), t('حفلة نهاية الفصل', 'The end-of-term concert')] }),
        item(t('العائلة', 'Family'), { price: jd('190'), meta: t('شهريًا لثلاثة', 'per month for three'), list: [t('ثلاثة طلاب من البيت نفسه', 'Three students from one home'), t('خصم على الآلات', 'Discount on instruments')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'students',
      eyebrow: t('طلابنا', 'Our students'),
      title: t('صعدوا المسرح', 'They took the stage'),
      items: [
        { quote: t('بدأت البيانو في الخمسين، وعزفت في حفلة الفصل أمام أحفادي.', 'I started piano at fifty and played the term concert in front of my grandchildren.'), name: t('سهام البطاينة', 'Siham Al-Bataineh'), role: t('طالبة بيانو', 'Piano student') },
        { quote: t('ابني كان يكره التدريب، والآن يسجّل أغانيه في الاستوديو.', 'My son used to hate practising; now he records his own songs in the studio.'), name: t('فراس قعوار', 'Firas Qawar'), role: t('أب', 'Parent') },
        { quote: t('الفرقة العربية علّمتني أن أسمع الآخرين وأنا أعزف.', 'The Arabic ensemble taught me to listen to the others while I play.'), name: t('جود الزعبي', 'Joud Al-Zoubi'), role: t('عازفة عود', 'Oud player') },
      ],
    },
    {
      kind: 'cta',
      title: t('حفلة الشتاء', 'The winter concert'),
      text: t('أربعون طالبًا على مسرح واحد، الخميس ١٨ ديسمبر. الدخول مجاني والمقاعد بالحجز.', 'Forty students on one stage, Thursday 18 December. Free entry; seats by reservation.'),
      cta: t('احجز مقعدك', 'Reserve a seat'),
      img: 836,
    },
    {
      kind: 'contact', id: 'contact', nav: t('سجّل', 'Enrol'),
      eyebrow: t('التسجيل', 'Enrolment'),
      title: t('الدرس الأول علينا', 'The first lesson is on us'),
      text: t('اختر الآلة والوقت المناسب، ونرتب لك درسًا تجريبيًا مع المعلّم.', 'Choose the instrument and a time that suits you, and we\'ll arrange a trial lesson with the teacher.'),
      phone: '+962 6 460 0000', whatsapp: '+962 79 000 0000', email: 'play@maqam.example',
      address: t('شارع باريس ٣، جبل اللويبدة، عمّان', '3 Paris Street, Jabal Al-Weibdeh, Amman'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('14:00 – 21:00') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const garage: Profile = {
  id: 'garage',
  label: t('ورشة سيارات', 'Car workshop'),
  brand: t('كراج عزّت', 'Izzat Garage'),
  mark: t('ع', 'I'),
  tagline: t('ترميم السيارات الكلاسيكية وصيانتها منذ ١٩٨٥', 'Restoring and servicing classic cars since 1985'),
  navCta: t('احجز فحصًا', 'Book an inspection'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('ورشة سيارات · الخليل', 'Car workshop · Hebron'),
      title: t('نعيد السيارة كما خرجت من المصنع', 'We bring a car back as it left the factory'),
      lead: t('ترميم كامل للسيارات الكلاسيكية: هيكل ومحرك وتنجيد ودهان، بقطع أصلية أو مصنوعة باليد. ونخدم سيارتك اليومية أيضًا، بفحص صادق وسعر مكتوب قبل أن نبدأ.', 'Full restoration of classic cars: body, engine, upholstery and paint, with original or hand-made parts. We service your everyday car too, with an honest check and a written price before we start.'),
      cta: t('احجز فحصًا', 'Book an inspection'),
      cta2: t('أعمالنا', 'Our work'),
      img: 133, imgs: [1071, 111, 892],
      badge: t('ضمان سنة على كل عمل', 'A year\'s warranty on every job'),
    },
    { kind: 'stats', items: [
      { value: '40', label: t('سنة في الورشة', 'years in the workshop') },
      { value: '160', label: t('سيارة كلاسيكية رُمّمت', 'classic cars restored') },
      { value: '9', label: t('فنيين', 'mechanics') },
      { value: '24 h', label: t('لتقرير الفحص', 'for an inspection report') },
    ] },
    {
      kind: 'items', id: 'services', nav: t('الخدمات', 'Services'), role: 'offer',
      eyebrow: t('الخدمات', 'Services'),
      title: t('من البرغي إلى الدهان', 'From the bolts to the paint'),
      items: [
        item(t('ترميم كامل', 'Full restoration'), { text: t('تفكيك السيارة قطعة قطعة وإعادة بنائها', 'The car taken apart piece by piece and rebuilt'), meta: t('٣ – ٨ أشهر', '3 – 8 months'), price: t('حسب الحالة', 'By quote'), img: 1072 }),
        item(t('إصلاح المحرك', 'Engine rebuild'), { text: t('محركات الكاربراتير والحقن القديمة', 'Old carburettor and injection engines'), meta: t('٢ – ٤ أسابيع', '2 – 4 weeks'), price: t('من ٤٬٥٠٠ ₪', 'From 4,500 ₪'), img: 892 }),
        item(t('التنجيد', 'Upholstery'), { text: t('جلد وقماش بالخياطة الأصلية', 'Leather and cloth in the original stitching'), meta: t('أسبوعان', '2 weeks'), price: t('من ٣٬٢٠٠ ₪', 'From 3,200 ₪'), img: 757 }),
        item(t('الدهان', 'Paint'), { text: t('ألوان المصنع الأصلية بالرقم', 'Original factory colours by code'), meta: t('٣ أسابيع', '3 weeks'), price: t('من ٦٬٠٠٠ ₪', 'From 6,000 ₪'), img: 263 }),
        item(t('الكهرباء والعدادات', 'Wiring and gauges'), { text: t('أسلاك جديدة بمخطط السيارة الأصلي', 'New wiring to the car\'s original diagram'), meta: t('أسبوع', '1 week'), price: t('من ١٬٨٠٠ ₪', 'From 1,800 ₪'), img: 605 }),
        item(t('الصيانة الدورية', 'Regular service'), { text: t('زيت وفلاتر وفرامل لأي سيارة', 'Oil, filters and brakes for any car'), meta: t('يوم واحد', 'Same day'), price: '350 ₪', img: 183 }),
      ],
    },
    {
      kind: 'items', id: 'process', role: 'process',
      eyebrow: t('كيف نعمل', 'How we work'),
      title: t('لا مفاجآت في الفاتورة', 'No surprises on the bill'),
      items: [
        item(t('الفحص', 'Inspection'), { text: t('تقرير مصوّر خلال ٢٤ ساعة', 'A photo report within 24 hours'), icon: 'search' }),
        item(t('السعر المكتوب', 'Written price'), { text: t('لا نبدأ قبل موافقتك', 'We don\'t start before you agree'), icon: 'file-text' }),
        item(t('العمل', 'The work'), { text: t('صور أسبوعية من الورشة', 'Weekly photos from the workshop'), icon: 'wrench' }),
        item(t('تجربة الطريق', 'Road test'), { text: t('نقودها معًا قبل التسليم', 'We drive it together before handover'), icon: 'car' }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('الورشة', 'The workshop'),
      eyebrow: t('الورشة', 'The workshop'),
      title: t('عدّة الأب في يد الابن', 'The father\'s tools in the son\'s hands'),
      text: [
        t('فتح عزّت الورشة عام ١٩٨٥ بمفتاحين ورافعة واحدة، وكان أول من رمّم سيارة مرسيدس قديمة في المدينة.', 'Izzat opened the workshop in 1985 with two spanners and one jack, and was the first in town to restore an old Mercedes.'),
        t('اليوم يديرها ابنه سمير مع تسعة فنيين، وما زالت عدّة أبيه معلقة على الجدار، وما زالوا يستعملونها.', 'Today his son Samir runs it with nine mechanics. His father\'s tools still hang on the wall, and they still use them.'),
      ],
      img: 284, img2: 605,
      quote: t('السيارة القديمة لا تموت، تنتظر من يفهمها.', 'An old car never dies; it waits for someone who understands it.'),
      sign: t('سمير عزّت، صاحب الورشة', 'Samir Izzat, owner'),
    },
    {
      kind: 'items', id: 'work', nav: t('أعمالنا', 'Our work'), role: 'gallery',
      eyebrow: t('أعمالنا', 'Our work'),
      title: t('قبل وبعد', 'Before and after'),
      items: [
        item(t('كونتيننتال ١٩٦٤', '1964 Continental'), { img: 1071 }),
        item(t('شيفروليه ١٩٣٨', '1938 Chevrolet'), { img: 111 }),
        item(t('فولكسفاغن الزرقاء', 'The blue Volkswagen'), { img: 655 }),
        item(t('جاغوار بلونين', 'Two Jaguars'), { img: 133 }),
        item(t('رحلة الصحراء', 'The desert run'), { img: 551 }),
        item(t('قبل الترميم', 'Before restoration'), { img: 1072 }),
      ],
    },
    {
      kind: 'testimonials', id: 'owners',
      eyebrow: t('أصحاب السيارات', 'Owners'),
      title: t('سلّمناهم مفاتيح ذكرياتهم', 'We handed them back their memories'),
      items: [
        { quote: t('سيارة أبي بقيت في المخزن ثلاثين سنة، والآن أقودها يوم الجمعة كما كان يقودها.', 'My father\'s car sat in a garage for thirty years; now I drive it on Fridays the way he did.'), name: t('نبيل الجعبري', 'Nabil Al-Jabari'), role: t('مرسيدس ١٩٧٢', '1972 Mercedes') },
        { quote: t('أرسلوا لي صور كل أسبوع، حتى صرت أعرف كل برغي في سيارتي.', 'They sent me photos every week, until I knew every bolt in my car.'), name: t('رهام التميمي', 'Reham Al-Tamimi'), role: t('فولكسفاغن ١٩٦٨', '1968 Volkswagen') },
        { quote: t('السعر المكتوب كان هو نفسه في الفاتورة، وهذا نادر.', 'The written price was the same on the bill, and that is rare.'), name: t('وليد أبو سنينة', 'Walid Abu Sneineh'), role: t('صيانة دورية', 'Regular service') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل أن تحضر سيارتك', 'Before you bring your car'),
      items: [
        { q: t('هل تجدون القطع الأصلية؟', 'Can you find original parts?'), a: t('نستورد من أوروبا وأمريكا، وما لا نجده نصنعه في الورشة.', 'We import from Europe and America, and what we can\'t find we make in the workshop.') },
        { q: t('هل يمكن الدفع على مراحل؟', 'Can I pay in stages?'), a: t('نعم، الترميم يُدفع على أربع مراحل مع تقدم العمل.', 'Yes, a restoration is paid in four stages as the work goes on.') },
        { q: t('هل تنقلون السيارة؟', 'Do you transport the car?'), a: t('نعم، بشاحنة مغلقة من أي مدينة.', 'Yes, on an enclosed truck from any city.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('احجز', 'Book'),
      eyebrow: t('احجز', 'Book'),
      title: t('أحضرها لنفحصها', 'Bring her in for a look'),
      text: t('الفحص الأول مجاني للسيارات الكلاسيكية. أرسل صورًا لسيارتك ونحدد معك موعدًا.', 'The first inspection is free for classic cars. Send us photos of your car and we\'ll set a time.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'garage@izzat.example',
      address: t('المنطقة الصناعية، الخليل', 'Industrial Zone, Hebron'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('07:30 – 17:00') },
        { d: t('الجمعة', 'Friday'), t: t('مغلق', 'Closed') },
      ],
      cta: t('أرسل الصور عبر واتساب', 'Send photos on WhatsApp'),
    },
  ],
};

export const florist: Profile = {
  id: 'florist',
  label: t('محل زهور', 'Florist'),
  brand: t('ياسمينة', 'Yasmina'),
  mark: t('ي', 'Y'),
  tagline: t('باقات من مزارع قريبة، تُلفّ في الصباح نفسه', 'Bouquets from nearby farms, wrapped the same morning'),
  navCta: t('اطلب باقة', 'Order a bouquet'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('محل زهور · بيت لحم', 'Florist · Bethlehem'),
      title: t('قل ما تريد بباقة', 'Say it with a bouquet'),
      lead: t('زهور موسمية من مزارع قريبة، ونباتات تعيش طويلًا في البيت والمكتب. نلفّها في الصباح ونوصلها في اليوم نفسه، مع بطاقة بخط اليد.', 'Seasonal flowers from nearby farms, and plants that live long at home and in the office. Wrapped in the morning and delivered the same day, with a handwritten card.'),
      cta: t('اطلب باقة', 'Order a bouquet'),
      cta2: t('الاشتراك الأسبوعي', 'Weekly flowers'),
      img: 976, imgs: [106, 25, 940],
      badge: t('توصيل في اليوم نفسه', 'Same-day delivery'),
    },
    {
      kind: 'items', id: 'bouquets', nav: t('الباقات', 'Bouquets'), role: 'offer',
      eyebrow: t('الباقات', 'Bouquets'),
      title: t('من حقل هذا الأسبوع', 'From this week\'s field'),
      items: [
        item(t('خزامى الربيع', 'Spring tulips'), { text: t('عشرون زهرة توليب برتقالية', 'Twenty orange tulips'), price: '120 ₪', img: 976, tag: t('موسمية', 'In season') }),
        item(t('الوردة الحمراء', 'Red blossom'), { text: t('باقة حمراء لمناسبة لا تُنسى', 'A red bouquet for a day to remember'), price: '150 ₪', img: 106 }),
        item(t('أغصان مزهرة', 'Blossom branches'), { text: t('أغصان طويلة لمزهرية كبيرة', 'Tall branches for a large vase'), price: '95 ₪', img: 25 }),
        item(t('صندوق الصبّار', 'Succulent box'), { text: t('ست نبتات لا تحتاج إلا القليل من الماء', 'Six plants that need hardly any water'), price: '110 ₪', img: 940 }),
        item(t('حديقة زجاجية', 'Glass garden'), { text: t('تيراريوم مغلق يعيش سنوات', 'A sealed terrarium that lives for years'), price: '180 ₪', img: 530 }),
        item(t('صبّارة المكتب', 'Desk cactus'), { text: t('هدية صغيرة لزميل جديد', 'A small gift for a new colleague'), price: '35 ₪', img: 248 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن ياسمينة', 'About'),
      eyebrow: t('عن ياسمينة', 'About Yasmina'),
      title: t('زهور لم تسافر بالطائرة', 'Flowers that never flew'),
      text: [
        t('نشتري من ثلاث مزارع في قرى بيت لحم وأريحا، فتصلك الزهرة بعد يوم واحد من قطفها لا بعد أسبوع.', 'We buy from three farms in the villages around Bethlehem and Jericho, so a flower reaches you a day after it was cut, not a week.'),
        t('نلفّ باقاتنا بورق مُعاد تدويره وخيط قطني، بلا بلاستيك وبلا إسفنج.', 'We wrap in recycled paper and cotton string, with no plastic and no foam.'),
      ],
      img: 400, img2: 530,
      quote: t('الزهرة الطازجة لا تحتاج إلى كثير من الزينة.', 'A fresh flower needs very little dressing up.'),
      sign: t('ياسمين قمصية، صاحبة المحل', 'Yasmin Qumsiyeh, owner'),
    },
    {
      kind: 'items', id: 'weekly', nav: t('الاشتراك', 'Subscription'), role: 'pricing',
      eyebrow: t('زهور كل أسبوع', 'Flowers every week'),
      title: t('بيت فيه زهور دائمًا', 'A home that always has flowers'),
      items: [
        item(t('صغيرة', 'Small'), { price: '60 ₪', meta: t('أسبوعيًا', 'per week'), list: [t('باقة لطاولة الطعام', 'A bouquet for the dining table'), t('توصيل مجاني', 'Free delivery')] }),
        item(t('البيت', 'Home'), { price: '95 ₪', meta: t('أسبوعيًا', 'per week'), featured: true, tag: t('الأكثر اختيارًا', 'Most chosen'), list: [t('باقتان كبيرتان', 'Two large bouquets'), t('مزهرية في الشهر الأول', 'A vase in the first month'), t('توصيل مجاني', 'Free delivery')] }),
        item(t('المكتب', 'Office'), { price: '240 ₪', meta: t('أسبوعيًا', 'per week'), list: [t('الاستقبال وغرف الاجتماعات', 'Reception and meeting rooms'), t('نباتات نعتني بها', 'Plants we look after')] }),
      ],
    },
    {
      kind: 'items', id: 'garden', nav: t('من المشتل', 'From the nursery'), role: 'gallery',
      eyebrow: t('من المشتل', 'From the nursery'),
      title: t('ما ينمو عندنا الآن', 'What\'s growing now'),
      items: [
        item(t('حقل الربيع', 'The spring field'), { img: 701 }),
        item(t('صبّار من فوق', 'Succulents from above'), { img: 958 }),
        item(t('زنبقة الماء', 'Water lily'), { img: 306 }),
        item(t('صبّارة صغيرة', 'A small cactus'), { img: 248 }),
        item(t('براعم جديدة', 'New buds'), { img: 400 }),
        item(t('أغصان اللوز', 'Almond branches'), { img: 25 }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('قالوا عنا', 'Kind words'),
      title: t('باقات وصلت في وقتها', 'Bouquets that arrived on time'),
      items: [
        { quote: t('طلبت الباقة من دبي لأمي في بيت لحم، ووصلت قبل الظهر مع بطاقة كتبوها كما أمليتها.', 'I ordered from Dubai for my mother in Bethlehem; it arrived before noon with the card written just as I dictated.'), name: t('جورج سلسع', 'George Salsaa'), role: t('ابن بعيد', 'A son far away') },
        { quote: t('الاشتراك الأسبوعي غيّر شكل مكتبنا، والموظفون صاروا ينتظرون يوم الزهور.', 'The weekly subscription changed our office; the team now looks forward to flower day.'), name: t('منى عوض', 'Mona Awad'), role: t('مديرة مكتب', 'Office manager') },
        { quote: t('التوليب عاش عندي أسبوعين كاملين، وهذا لم يحدث من قبل.', 'The tulips lasted two whole weeks, which has never happened before.'), name: t('ريما حزبون', 'Rima Hazboun'), role: t('مشتركة', 'Subscriber') },
      ],
    },
    {
      kind: 'contact', id: 'order', nav: t('اطلب', 'Order'),
      eyebrow: t('اطلب', 'Order'),
      title: t('أخبرنا لمن الباقة', 'Tell us who it\'s for'),
      text: t('أرسل المناسبة والعنوان والكلمات التي تريدها على البطاقة، ونرسل لك صورة الباقة قبل خروجها.', 'Send the occasion, the address and the words for the card, and we\'ll send a photo of the bouquet before it leaves.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'flowers@yasmina.example',
      address: t('شارع المهد ٢١، بيت لحم', '21 Manger Street, Bethlehem'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('08:00 – 20:00') },
        { d: t('الجمعة', 'Friday'), t: same('09:00 – 14:00') },
      ],
      cta: t('اطلب عبر واتساب', 'Order on WhatsApp'),
    },
  ],
};

export const vet: Profile = {
  id: 'vet',
  label: t('عيادة بيطرية', 'Vet clinic'),
  brand: t('رفيق', 'Rafiq'),
  mark: t('ر', 'R'),
  tagline: t('رعاية للحيوانات الأليفة وحيوانات المزرعة', 'Care for pets and farm animals'),
  navCta: t('احجز موعدًا', 'Book a visit'),
  socials: ['instagram', 'facebook'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('عيادة بيطرية · جنين', 'Vet clinic · Jenin'),
      title: t('يحبونك بلا كلام، فاعتنِ بهم', 'They love you without words; look after them'),
      lead: t('فحوصات وتطعيمات وجراحة للقطط والكلاب، وزيارات إلى المزارع للخيول والأغنام والأبقار. وخط طوارئ يرد في منتصف الليل.', 'Checkups, vaccines and surgery for cats and dogs, and farm visits for horses, sheep and cattle. And an emergency line that answers at midnight.'),
      cta: t('احجز موعدًا', 'Book a visit'),
      cta2: t('الخدمات', 'Services'),
      img: 237, imgs: [837, 1025, 659],
      badge: t('طوارئ ٢٤ ساعة', '24-hour emergencies'),
    },
    {
      kind: 'items', id: 'services', nav: t('الخدمات', 'Services'), role: 'offer',
      eyebrow: t('الخدمات', 'Services'),
      title: t('من أول تطعيم إلى آخر العمر', 'From the first jab to old age'),
      items: [
        item(t('الفحص الشامل', 'Full checkup'), { text: t('وزن وقلب وأسنان وجلد', 'Weight, heart, teeth and skin'), meta: t('٣٠ دقيقة', '30 min'), price: '80 ₪', img: 837 }),
        item(t('التطعيمات', 'Vaccines'), { text: t('جدول كامل للجراء والقطط الصغيرة', 'A full schedule for puppies and kittens'), meta: t('١٥ دقيقة', '15 min'), price: '60 ₪', img: 1062 }),
        item(t('الجراحة', 'Surgery'), { text: t('تعقيم وكسور وأورام، بتخدير آمن', 'Neutering, fractures and growths, under safe anaesthesia'), meta: t('بموعد', 'By appointment'), price: t('حسب الحالة', 'By quote'), img: 659 }),
        item(t('زيارة المزرعة', 'Farm visit'), { text: t('للأغنام والأبقار في مزرعتك', 'For sheep and cattle on your farm'), meta: t('حتى ٤٠ كم', 'Up to 40 km'), price: '150 ₪', img: 699, tag: t('نأتي إليك', 'We come to you') }),
        item(t('عيادة الخيول', 'Horse clinic'), { text: t('أسنان وحوافر ورعاية ما بعد السباق', 'Teeth, hooves and after-race care'), meta: t('بموعد', 'By appointment'), price: '200 ₪', img: 584 }),
        item(t('فندق الحيوانات', 'Pet boarding'), { text: t('رعاية يومية حين تسافر', 'Daily care while you travel'), meta: t('لليلة', 'Per night'), price: '45 ₪', img: 1025 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('العيادة', 'The clinic'),
      eyebrow: t('العيادة', 'The clinic'),
      title: t('طبيبان من القرية نفسها', 'Two vets from the same village'),
      text: [
        t('درسنا الطب البيطري معًا وعدنا إلى جنين، لأن المزارعين هنا كانوا يقطعون ساعة كاملة ليصلوا إلى أقرب طبيب.', 'We studied veterinary medicine together and came back to Jenin, because farmers here used to drive a full hour to reach the nearest vet.'),
        t('في العيادة غرفة عمليات وأشعة ومختبر، وفي السيارة كل ما نحتاجه لنعالج في الحقل.', 'The clinic has a theatre, an X-ray and a lab, and the van carries everything we need to treat in the field.'),
      ],
      img: 200, img2: 169,
      quote: t('كل حيوان يستحق طبيبًا يعرف اسمه.', 'Every animal deserves a vet who knows its name.'),
      sign: t('د. هبة جرار ود. أنس صبّاح', 'Dr. Hiba Jarrar and Dr. Anas Sabbah'),
    },
    { kind: 'stats', items: [
      { value: '6,500', label: t('حيوان عالجناه', 'animals treated') },
      { value: '320', label: t('مزرعة نزورها', 'farms we visit') },
      { value: '24/7', label: t('خط الطوارئ', 'emergency line') },
      { value: '2', label: t('طبيبان وأربعة ممرضين', 'vets and four nurses') },
    ] },
    {
      kind: 'items', id: 'visit', role: 'process',
      eyebrow: t('الزيارة الأولى', 'The first visit'),
      title: t('هادئة قدر الإمكان', 'As calm as we can make it'),
      items: [
        item(t('احجز', 'Book'), { text: t('برسالة أو اتصال', 'By message or a call'), icon: 'calendar-days' }),
        item(t('غرفة انتظار منفصلة', 'Separate waiting rooms'), { text: t('للقطط وحدها وللكلاب وحدها', 'One for cats, one for dogs'), icon: 'cat' }),
        item(t('الفحص', 'The checkup'), { text: t('نشرح لك كل ما نراه', 'We explain everything we see'), icon: 'stethoscope' }),
        item(t('المتابعة', 'Follow-up'), { text: t('نتصل بك بعد ثلاثة أيام', 'We call you three days later'), icon: 'phone' }),
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل الزيارة', 'Before your visit'),
      items: [
        { q: t('ماذا أفعل في الطوارئ ليلًا؟', 'What do I do in an emergency at night?'), a: t('اتصل بخط الطوارئ، ويرد أحد الطبيبين ويستقبلك في العيادة خلال نصف ساعة.', 'Call the emergency line; one of us will answer and meet you at the clinic within half an hour.') },
        { q: t('هل تعالجون الطيور؟', 'Do you treat birds?'), a: t('نعم، الدواجن وطيور الزينة.', 'Yes, poultry and pet birds.') },
        { q: t('هل يجب أن يكون الحيوان صائمًا قبل الجراحة؟', 'Should my pet fast before surgery?'), a: t('اثنتا عشرة ساعة بلا طعام، والماء مسموح.', 'Twelve hours without food; water is fine.') },
      ],
    },
    {
      kind: 'testimonials', id: 'owners',
      eyebrow: t('أصحابهم', 'Their owners'),
      title: t('عادوا إلى البيت بخير', 'They went home well'),
      items: [
        { quote: t('اتصلت في الثانية فجرًا وكلبي لا يتنفس جيدًا، فكانت الطبيبة في العيادة قبلي.', 'I called at 2 am when my dog couldn\'t breathe properly, and the vet was at the clinic before me.'), name: t('علاء زكارنة', 'Alaa Zakarneh'), role: t('صاحب ماكس', 'Max\'s owner') },
        { quote: t('يزورون مزرعتنا كل شهر، وصار القطيع أصحّ من أي وقت.', 'They visit our farm every month, and the flock has never been healthier.'), name: t('أبو محمود', 'Abu Mahmoud'), role: t('مربّي أغنام', 'Sheep farmer') },
        { quote: t('قطتي تكره الطبيب، لكنها لم تخف هنا. غرفة القطط فكرة رائعة.', 'My cat hates vets, but she wasn\'t scared here. The cats-only room is a brilliant idea.'), name: t('سلمى أبو الرب', 'Salma Abu Al-Rub'), role: t('صاحبة لولو', 'Lulu\'s owner') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('احجز', 'Book'),
      eyebrow: t('احجز', 'Book'),
      title: t('نراك أنت ورفيقك', 'See you and your friend'),
      text: t('احجز موعدًا عاديًا برسالة، وفي الطوارئ اتصل مباشرة في أي ساعة.', 'Book a regular visit by message, and in an emergency call us directly at any hour.'),
      phone: '+970 4 000 0000', whatsapp: '+970 59 000 0000', email: 'care@rafiq.example',
      address: t('شارع حيفا ٣٠، جنين', '30 Haifa Street, Jenin'),
      hours: [
        { d: t('السبت – الخميس', 'Sat – Thu'), t: same('09:00 – 19:00') },
        { d: t('الطوارئ', 'Emergencies'), t: same('24/7') },
      ],
      cta: t('احجز عبر واتساب', 'Book on WhatsApp'),
    },
  ],
};

export const cowork: Profile = {
  id: 'cowork',
  label: t('مساحة عمل مشتركة', 'Coworking space'),
  brand: t('مكتبنا', 'Maktabna'),
  mark: t('م', 'M'),
  tagline: t('مكتب بالساعة أو بالشهر، وإنترنت لا ينقطع', 'A desk by the hour or the month, and internet that never drops'),
  navCta: t('احجز يومًا مجانيًا', 'Book a free day'),
  socials: ['instagram', 'linkedin'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('مساحة عمل مشتركة · إربد', 'Coworking · Irbid'),
      title: t('اخرج من البيت، وابقَ قريبًا من عملك', 'Leave the house, stay close to your work'),
      lead: t('مكاتب مفتوحة ومغلقة وغرف اجتماعات، بإنترنت ألياف ومولّد كهرباء وقهوة لا تنفد. للمستقلين والشركات الصغيرة وطلاب الدراسات العليا.', 'Open desks, private offices and meeting rooms, with fibre internet, a backup generator and coffee that never runs out. For freelancers, small companies and graduate students.'),
      cta: t('احجز يومًا مجانيًا', 'Book a free day'),
      cta2: t('الأسعار', 'Pricing'),
      img: 1, imgs: [445, 532, 7],
      badge: t('مفتوح ٢٤ ساعة للأعضاء', 'Open 24 hours for members'),
    },
    {
      kind: 'items', id: 'spaces', nav: t('المساحات', 'Spaces'), role: 'offer',
      eyebrow: t('المساحات', 'Spaces'),
      title: t('مكان لكل نوع من العمل', 'A place for every kind of work'),
      items: [
        item(t('مكتب مفتوح', 'Hot desk'), { text: t('اجلس حيث تجد مكانًا', 'Sit wherever there\'s room'), meta: t('بالساعة أو اليوم', 'By the hour or day'), price: jd('3'), img: 1 }),
        item(t('مكتب ثابت', 'Fixed desk'), { text: t('مكتبك وخزانتك ولا أحد يجلس مكانك', 'Your own desk and locker'), meta: t('شهريًا', 'Monthly'), price: jd('70'), img: 8 }),
        item(t('مكتب مغلق', 'Private office'), { text: t('لفريق من ٢ إلى ٦ أشخاص', 'For a team of two to six'), meta: t('شهريًا', 'Monthly'), price: jd('260'), img: 445, tag: t('اثنان متاحان', 'Two available') }),
        item(t('غرفة اجتماعات', 'Meeting room'), { text: t('شاشة وسبورة لثمانية أشخاص', 'A screen and a whiteboard for eight'), meta: t('بالساعة', 'Hourly'), price: jd('8'), img: 7 }),
        item(t('غرفة المكالمات', 'Call booth'), { text: t('عازلة للصوت لاجتماعاتك عن بعد', 'Soundproofed for your video calls'), meta: t('مع العضوية', 'With membership'), price: t('مجانًا', 'Free'), img: 3 }),
        item(t('ركن التصميم', 'Design corner'), { text: t('شاشات كبيرة وطابعة ألوان', 'Large screens and a colour printer'), meta: t('باليوم', 'Daily'), price: jd('6'), img: 532 }),
      ],
    },
    {
      kind: 'items', id: 'plans', nav: t('الأسعار', 'Pricing'), role: 'pricing',
      eyebrow: t('العضوية', 'Membership'),
      title: t('ادفع لما تستعمله فقط', 'Pay only for what you use'),
      items: [
        item(t('يومي', 'Day pass'), { price: jd('5'), meta: t('لليوم', 'per day'), list: [t('مكتب مفتوح', 'A hot desk'), t('قهوة وشاي', 'Coffee and tea')] }),
        item(t('المستقل', 'Freelancer'), { price: jd('55'), meta: t('شهريًا', 'per month'), featured: true, tag: t('الأكثر اشتراكًا', 'Most popular'), list: [t('مكتب مفتوح كل يوم', 'A hot desk every day'), t('ساعتا اجتماع أسبوعيًا', 'Two meeting hours a week'), t('عنوان بريدي للعمل', 'A business address')] }),
        item(t('الفريق', 'Team'), { price: jd('260'), meta: t('شهريًا', 'per month'), list: [t('مكتب مغلق', 'A private office'), t('دخول ٢٤ ساعة', '24-hour access'), t('خزائن وطابعة', 'Lockers and printing')] }),
      ],
    },
    {
      kind: 'items', id: 'included', role: 'extra',
      eyebrow: t('مع كل عضوية', 'With every membership'),
      title: t('كل ما يحتاجه يوم عمل', 'Everything a working day needs'),
      items: [
        item(t('إنترنت ألياف', 'Fibre internet'), { text: t('٥٠٠ ميغابت مع خط احتياطي', '500 Mbps with a backup line'), icon: 'wifi' }),
        item(t('كهرباء لا تنقطع', 'No power cuts'), { text: t('مولّد وطاقة شمسية', 'A generator and solar panels'), icon: 'zap' }),
        item(t('قهوة مختصة', 'Specialty coffee'), { text: t('من محمصة في المدينة', 'From a roaster in town'), icon: 'coffee' }),
        item(t('طباعة ومسح', 'Printing and scanning'), { text: t('مئة صفحة شهريًا', 'A hundred pages a month'), icon: 'printer' }),
        item(t('مجتمع', 'Community'), { text: t('فطور شهري وورش للأعضاء', 'A monthly breakfast and member workshops'), icon: 'users' }),
        item(t('خزائن آمنة', 'Secure lockers'), { text: t('اترك حاسوبك وأغراضك بأمان', 'Leave your laptop and things safely'), icon: 'lock' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '120', label: t('عضوًا', 'members') },
      { value: '64', label: t('مكتبًا', 'desks') },
      { value: '500', label: t('ميغابت في الثانية', 'Mbps') },
      { value: '24/7', label: t('للأعضاء', 'for members') },
    ] },
    {
      kind: 'testimonials', id: 'members',
      eyebrow: t('الأعضاء', 'Members'),
      title: t('أنجزوا هنا', 'They got it done here'),
      items: [
        { quote: t('كتبت رسالة الماجستير كلها على المكتب نفسه قرب النافذة.', 'I wrote my whole master\'s thesis at the same desk by the window.'), name: t('رغد الشرع', 'Raghad Al-Sharaa'), role: t('طالبة دراسات عليا', 'Graduate student') },
        { quote: t('بدأنا شركتنا هنا بشخصين، والآن نحن ستة في مكتب مغلق.', 'We started our company here with two people; now we\'re six in a private office.'), name: t('مهند العزام', 'Mohannad Al-Azzam'), role: t('مؤسس شركة برمجيات', 'Software founder') },
        { quote: t('الكهرباء لم تنقطع مرة واحدة في اجتماع مع عميل. هذا وحده يستحق الاشتراك.', 'The power never once cut out during a client call. That alone is worth it.'), name: t('دعاء البشير', 'Duaa Al-Bashir'), role: t('مترجمة مستقلة', 'Freelance translator') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('قبل أن تأتي', 'Before you come'),
      items: [
        { q: t('هل اليوم الأول مجاني فعلًا؟', 'Is the first day really free?'), a: t('نعم، يوم كامل بلا التزام لتجرّب المكان.', 'Yes, a whole day with no commitment, to try the place.') },
        { q: t('هل يمكن استعمال العنوان للشركة؟', 'Can I register my company at your address?'), a: t('نعم، مع عضوية المستقل أو الفريق.', 'Yes, with the Freelancer or Team plan.') },
        { q: t('هل يوجد موقف سيارات؟', 'Is there parking?'), a: t('موقف مجاني للأعضاء أمام المبنى.', 'Free parking for members in front of the building.') },
      ],
    },
    {
      kind: 'contact', id: 'contact', nav: t('زورونا', 'Visit'),
      eyebrow: t('زورونا', 'Visit us'),
      title: t('مكتبك جاهز صباح الغد', 'Your desk is ready tomorrow morning'),
      text: t('احجز يومك المجاني أو جولة في المكان برسالة.', 'Book your free day or a tour of the space by message.'),
      phone: '+962 2 700 0000', whatsapp: '+962 79 000 0000', email: 'hello@maktabna.example',
      address: t('شارع الجامعة ١١٠، إربد', '110 University Street, Irbid'),
      hours: [
        { d: t('الاستقبال', 'Front desk'), t: same('08:00 – 20:00') },
        { d: t('الأعضاء', 'Members'), t: same('24/7') },
      ],
      cta: t('احجز يومك المجاني', 'Book your free day'),
    },
  ],
};

export const gallery: Profile = {
  id: 'gallery',
  label: t('صالة عرض', 'Art gallery'),
  brand: t('دار اللون', 'Dar Al-Loun'),
  mark: t('ل', 'L'),
  tagline: t('فن معاصر من فلسطين والمنطقة', 'Contemporary art from Palestine and the region'),
  navCta: t('خطّط لزيارتك', 'Plan your visit'),
  socials: ['instagram', 'facebook', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('صالة عرض · القدس', 'Art gallery · Jerusalem'),
      title: t('فن يُرى من قريب', 'Art you see up close'),
      lead: t('ثلاثة معارض في السنة لفنانين من فلسطين والمنطقة، وأمسيات حوار وورش للأطفال. الدخول مجاني، وكل عمل له حكاية يحكيها لك فريقنا.', 'Three exhibitions a year by artists from Palestine and the region, with talks and workshops for children. Entry is free, and our team will tell you the story behind every work.'),
      cta: t('خطّط لزيارتك', 'Plan your visit'),
      cta2: t('المعارض', 'Exhibitions'),
      img: 949, imgs: [834, 618, 546],
      badge: t('الدخول مجاني', 'Free entry'),
    },
    {
      kind: 'items', id: 'exhibitions', nav: t('المعارض', 'Exhibitions'), role: 'offer',
      eyebrow: t('المعارض', 'Exhibitions'),
      title: t('الآن وقريبًا', 'Now and next'),
      items: [
        item(t('بيوت من ورق', 'Houses of paper'), { text: t('رسومات لبيوت القرى المهجّرة', 'Drawings of the houses of emptied villages'), meta: t('حتى ٣٠ نوفمبر', 'Until 30 November'), img: 834, tag: t('الآن', 'Now on') }),
        item(t('جدران تتكلم', 'Walls that speak'), { text: t('صور الجداريات في مدن المنطقة', 'Photographs of murals across the region\'s cities'), meta: t('حتى ٣٠ نوفمبر', 'Until 30 November'), img: 619, tag: t('الآن', 'Now on') }),
        item(t('ضوء أبيض', 'White light'), { text: t('عمارة بالأبيض والأسود', 'Architecture in black and white'), meta: t('ديسمبر – فبراير', 'December – February'), img: 939 }),
        item(t('أقواس', 'Arches'), { text: t('من القناطر القديمة إلى الجسور الحديثة', 'From old vaults to modern bridges'), meta: t('ديسمبر – فبراير', 'December – February'), img: 952 }),
        item(t('عمودي', 'Vertical'), { text: t('المدن حين ننظر إلى الأعلى', 'Cities when we look up'), meta: t('مارس – مايو', 'March – May'), img: 948 }),
        item(t('صليب السماء', 'A cross of sky'), { text: t('تركيب ضوئي في الساحة', 'A light installation in the courtyard'), meta: t('مارس – مايو', 'March – May'), img: 677 }),
      ],
    },
    {
      kind: 'about', id: 'about', nav: t('عن الدار', 'About'),
      eyebrow: t('عن الدار', 'About the house'),
      title: t('بيت قديم بأبواب مفتوحة', 'An old house with open doors'),
      text: [
        t('رمّمنا بيتًا مقدسيًا من القرن التاسع عشر وحوّلنا غرفه إلى قاعات عرض، وساحته إلى مسرح صغير.', 'We restored a nineteenth-century Jerusalem house, turning its rooms into galleries and its courtyard into a small stage.'),
        t('نؤمن أن الفن ليس للنخبة: الدخول مجاني دائمًا، وكل معرض له جولة بالعربية للمدارس.', 'We believe art isn\'t for the few: entry is always free, and every exhibition has an Arabic tour for schools.'),
      ],
      img: 893, img2: 942,
      quote: t('اللوحة تكتمل حين يقف أمامها أحد.', 'A painting is finished when someone stands in front of it.'),
      sign: t('رنا نسيبة، مديرة الدار', 'Rana Nusseibeh, director'),
    },
    {
      kind: 'items', id: 'programme', nav: t('البرنامج', 'Programme'), role: 'schedule',
      eyebrow: t('البرنامج', 'Programme'),
      title: t('هذا الشهر في الدار', 'This month at the house'),
      items: [
        item(t('حوار مع الفنانة', 'Artist talk'), { meta: t('الخميس ٦:٣٠ م', 'Thu 6:30 pm'), text: t('عن رسم البيوت من الذاكرة', 'On drawing houses from memory'), icon: 'message-circle' }),
        item(t('ورشة الأطفال', 'Children\'s workshop'), { meta: t('السبت ١٠:٠٠ ص', 'Sat 10:00 am'), text: t('نرسم بيوتنا بالألوان المائية', 'Painting our homes in watercolour'), icon: 'palette' }),
        item(t('جولة المعرض', 'Gallery tour'), { meta: t('الجمعة ٤:٠٠ م', 'Fri 4:00 pm'), text: t('مع القيّمة على المعرض', 'With the exhibition\'s curator'), icon: 'footprints' }),
        item(t('ليلة أفلام', 'Film night'), { meta: t('الأربعاء ٧:٣٠ م', 'Wed 7:30 pm'), text: t('أفلام قصيرة عن المدينة في الساحة', 'Short films about the city in the courtyard'), icon: 'film' }),
      ],
    },
    {
      kind: 'items', id: 'house', nav: t('القاعات', 'The rooms'), role: 'gallery',
      eyebrow: t('القاعات', 'The rooms'),
      title: t('جولة في الدار', 'A walk through the house'),
      items: [
        item(t('الرواق', 'The arcade'), { img: 546 }),
        item(t('السقف الزجاجي', 'The glass roof'), { img: 618 }),
        item(t('القاعة البيضاء', 'The white room'), { img: 942 }),
        item(t('السلّم', 'The staircase'), { img: 893 }),
        item(t('القبة', 'The dome'), { img: 952 }),
        item(t('الساحة', 'The courtyard'), { img: 1048 }),
      ],
    },
    {
      kind: 'cta',
      title: t('كن صديقًا للدار', 'Become a friend of the house'),
      text: t('اشتراك سنوي يدعم المعارض المجانية، ويمنحك دعوة إلى كل افتتاح وخصمًا على الكتالوجات.', 'An annual membership that keeps the exhibitions free, with an invitation to every opening and a discount on catalogues.'),
      cta: t('انضم إلى الأصدقاء', 'Join the friends'),
      img: 949,
    },
    {
      kind: 'contact', id: 'visit', nav: t('زيارتك', 'Visit'),
      eyebrow: t('زيارتك', 'Your visit'),
      title: t('الأبواب مفتوحة', 'The doors are open'),
      text: t('للزيارات المدرسية والجولات الخاصة، احجز قبل أسبوع.', 'For school visits and private tours, book a week ahead.'),
      phone: '+970 2 000 0000', whatsapp: '+970 59 000 0000', email: 'visit@darelloun.example',
      address: t('شارع صلاح الدين ٤٢، القدس', '42 Salah Eddin Street, Jerusalem'),
      hours: [
        { d: t('الثلاثاء – الأحد', 'Tue – Sun'), t: same('10:00 – 19:00') },
        { d: t('الاثنين', 'Monday'), t: t('مغلق', 'Closed') },
      ],
      cta: t('احجز جولة', 'Book a tour'),
    },
  ],
};

export const wallet: Profile = {
  id: 'wallet',
  label: t('تطبيق ميزانية', 'Budget app'),
  brand: t('قرش', 'Qirsh'),
  mark: t('ق', 'Q'),
  tagline: t('ميزانية البيت في جيبك', 'Your household budget in your pocket'),
  navCta: t('حمّل قرش', 'Get Qirsh'),
  socials: ['instagram', 'x', 'youtube'],
  sections: [
    {
      kind: 'hero',
      eyebrow: t('تطبيق ميزانية للعائلة', 'A budget app for families'),
      title: t('اعرف أين يذهب راتبك', 'Know where your salary goes'),
      lead: t('سجّل مصروفك بصورة للفاتورة، وقسّم الراتب على البيت والمدارس والادخار، وشارك الميزانية مع العائلة. بالعربية، وبالشيكل والدينار والدولار.', 'Log spending with a photo of the receipt, split the salary between home, school and savings, and share the budget with your family. In Arabic, in shekels, dinars and dollars.'),
      cta: t('حمّل قرش', 'Get Qirsh'),
      cta2: t('كيف يعمل', 'How it works'),
      img: 373, imgs: [858, 838, 342],
      badge: t('مجاني لأول ثلاثة أشهر', 'Free for the first three months'),
    },
    { kind: 'logos', title: t('كتبوا عنا', 'As featured in'), items: ['MAL WA AAMAL', 'TECH ARABI', 'RAYA FM', 'IQTISAD', 'BAYAN'] },
    {
      kind: 'items', id: 'features', nav: t('المزايا', 'Features'), role: 'offer',
      eyebrow: t('المزايا', 'Features'),
      title: t('ميزانية لا تحتاج إلى محاسب', 'A budget that doesn\'t need an accountant'),
      items: [
        item(t('صوّر الفاتورة', 'Snap the receipt'), { text: t('يقرأ المبلغ والمحل والتاريخ', 'Reads the amount, the shop and the date'), icon: 'camera' }),
        item(t('ظروف الراتب', 'Salary envelopes'), { text: t('لكل بند ظرف يفرغ أمامك', 'An envelope for every item that empties before your eyes'), icon: 'wallet' }),
        item(t('ميزانية العائلة', 'Family budget'), { text: t('الزوج والزوجة والأبناء في حساب واحد', 'Partners and children in one account'), icon: 'users' }),
        item(t('هدف الادخار', 'Savings goal'), { text: t('للعرس أو السيارة أو الحج', 'For a wedding, a car or the Hajj'), icon: 'piggy-bank' }),
        item(t('تذكير الفواتير', 'Bill reminders'), { text: t('الكهرباء والماء والأقساط في وقتها', 'Power, water and instalments on time'), icon: 'bell' }),
        item(t('تقارير شهرية', 'Monthly reports'), { text: t('رسم واضح لكل شهر', 'A clear chart for every month'), icon: 'chart-pie' }),
      ],
    },
    { kind: 'stats', items: [
      { value: '85K', label: t('عائلة تستعمله', 'families use it') },
      { value: '18%', label: t('متوسط ما يوفّرونه شهريًا', 'saved a month on average') },
      { value: '3', label: t('عملات', 'currencies') },
      { value: '4.9', label: t('تقييم المتاجر', 'store rating') },
    ] },
    {
      kind: 'items', id: 'how', nav: t('كيف يعمل', 'How it works'), role: 'process',
      eyebrow: t('كيف يعمل', 'How it works'),
      title: t('ثلاث دقائق في الأسبوع', 'Three minutes a week'),
      items: [
        item(t('أدخل راتبك', 'Add your salary'), { text: t('ويقترح قرش تقسيمًا يناسب بيتك', 'And Qirsh suggests a split that suits your home'), icon: 'banknote' }),
        item(t('سجّل مصروفك', 'Log your spending'), { text: t('بصورة أو بكلمتين', 'With a photo or two words'), icon: 'receipt' }),
        item(t('راقب الظروف', 'Watch the envelopes'), { text: t('تنبيه قبل أن ينفد أي بند', 'An alert before any envelope runs out'), icon: 'bell' }),
      ],
    },
    {
      kind: 'items', id: 'plans', nav: t('الأسعار', 'Pricing'), role: 'pricing',
      eyebrow: t('الأسعار', 'Pricing'),
      title: t('ابدأ مجانًا', 'Start for free'),
      items: [
        item(t('مجاني', 'Free'), { price: '0 ₪', meta: t('دائمًا', 'forever'), list: [t('حساب واحد', 'One account'), t('خمسة ظروف', 'Five envelopes')] }),
        item(t('العائلة', 'Family'), { price: '12 ₪', meta: t('شهريًا', 'per month'), featured: true, tag: t('الأكثر اختيارًا', 'Most chosen'), list: [t('حتى ستة أفراد', 'Up to six people'), t('ظروف بلا حد', 'Unlimited envelopes'), t('قراءة الفواتير', 'Receipt scanning')] }),
        item(t('المشروع الصغير', 'Small business'), { price: '29 ₪', meta: t('شهريًا', 'per month'), list: [t('فصل مصروف البيت عن العمل', 'Home and business kept apart'), t('تصدير للمحاسب', 'Export for your accountant')] }),
      ],
    },
    {
      kind: 'testimonials', id: 'reviews',
      eyebrow: t('المستخدمون', 'Users'),
      title: t('آخر الشهر صار أهدأ', 'The end of the month got calmer'),
      items: [
        { quote: t('اكتشفنا أن نصف مصروف البيت يذهب على التوصيل، فوفّرنا في ثلاثة أشهر قسط المدرسة.', 'We found half our household spending went on delivery, and in three months we saved the school fees.'), name: t('إيمان ورامي', 'Iman and Rami'), role: t('زوجان', 'A couple') },
        { quote: t('ابني صار عنده ظرف مصروف خاص به، ويعرف كم بقي فيه قبل أن يطلب.', 'My son has his own pocket-money envelope now and checks it before he asks.'), name: t('نسرين حمّاد', 'Nisreen Hammad'), role: t('أم لثلاثة', 'Mother of three') },
        { quote: t('أخيرًا تطبيق يفهم الشيكل والدينار في الحساب نفسه.', 'Finally an app that understands shekels and dinars in the same account.'), name: t('طارق الأحمد', 'Tareq Al-Ahmad'), role: t('صاحب بقالة', 'Grocer') },
      ],
    },
    {
      kind: 'faq', id: 'faq',
      eyebrow: t('أسئلة', 'Questions'),
      title: t('أسئلة شائعة', 'Frequently asked'),
      items: [
        { q: t('هل يرتبط بحسابي في البنك؟', 'Does it connect to my bank?'), a: t('لا، قرش لا يطلب بيانات البنك أبدًا. أنت من يسجّل.', 'No, Qirsh never asks for bank details. You log it yourself.') },
        { q: t('أين تُحفظ بياناتي؟', 'Where is my data kept?'), a: t('مشفّرة على هاتفك، ونسخة احتياطية تختار أنت تفعيلها.', 'Encrypted on your phone, with a backup you choose to turn on.') },
        { q: t('هل يعمل دون إنترنت؟', 'Does it work offline?'), a: t('نعم، ويزامن حين يعود الاتصال.', 'Yes, and it syncs when you\'re back online.') },
      ],
    },
    {
      kind: 'cta',
      title: t('ابدأ ميزانية الشهر القادم', 'Start next month\'s budget'),
      text: t('متوفر على iPhone وأندرويد. ثلاثة أشهر مجانًا لخطة العائلة.', 'On iPhone and Android. Three months of the Family plan free.'),
      cta: t('حمّل التطبيق', 'Download'),
      img: 822,
    },
    {
      kind: 'contact', id: 'contact', nav: t('تواصل', 'Contact'),
      eyebrow: t('تواصل', 'Contact'),
      title: t('نرد بالعربية', 'We answer in Arabic'),
      text: t('للدعم والاقتراحات والشراكات مع البنوك والجمعيات.', 'For support, suggestions and partnerships with banks and charities.'),
      phone: '+970 59 000 0000', whatsapp: '+970 59 000 0000', email: 'help@qirsh.example',
      address: t('نابلس، فلسطين', 'Nablus, Palestine'),
      hours: [
        { d: t('الدعم', 'Support'), t: same('09:00 – 23:00') },
      ],
      cta: t('راسل الدعم', 'Message support'),
    },
  ],
};
