import type { DesignInput } from './input';

export const animated: DesignInput[] = [
  {
    slug: 'kinetic', profile: 'agency',
    name: { ar: 'حركة', en: 'Kinetic' },
    blurb: { ar: 'أسود وبرتقالي ناري، عنوان يصعد كلمة كلمة، شريط نصي مائل ومؤشر يتبعك.', en: 'Black and fiery orange, a headline that rises word by word, a tilted text band and a cursor that follows you.' },
    scheme: 'dark',
    palette: { bg: '#0B0B0F', surface: '#15151B', ink: '#F5F5F0', muted: '#9D9DA6', accent: '#FF5B2E', accent2: '#7C5CFF', line: '#26262E', onAccent: '#0B0B0F' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'lalezar', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'minimal' },
    decor: ['progress', 'cursor', 'parallax', 'stamp'],
  },
  {
    slug: 'aurora', profile: 'wallet',
    name: { ar: 'شفق', en: 'Aurora' },
    blurb: { ar: 'كحلي عميق تتحرك فوقه أضواء بنفسجية وسماوية، تطبيق ميزانية بهاتفين يطفوان ومزايا في شبكة بينتو.', en: 'Deep navy under drifting violet and cyan light, a budget app with two floating phones and its features in a bento grid.' },
    scheme: 'dark',
    palette: { bg: '#070B1A', surface: '#0F1530', ink: '#EEF1FF', muted: '#9AA3C7', accent: '#7C5CFF', accent2: '#22D3EE', line: '#1E2850', onAccent: '#FFFFFF' },
    fonts: { display: 'syne', body: 'dm-sans', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { nav: 'pill', hero: 'device', offer: 'bento' },
    decor: ['blobs', 'progress', 'icons'],
  },
  {
    slug: 'skyline', profile: 'travel',
    name: { ar: 'أفق', en: 'Skyline' },
    blurb: { ar: 'خط طويل مضغوط وصور بعمق متحرك، مكتب سفر تمر مدنه أفقيًا كشريط.', en: 'Tall condensed type and layered parallax photos, a travel agency whose cities scroll sideways like a reel.' },
    scheme: 'light',
    palette: { bg: '#F4F1EC', surface: '#FFFFFF', ink: '#171512', muted: '#6B655C', accent: '#E0592A', accent2: '#1E3A34', line: '#E2DCD2', onAccent: '#FFFFFF' },
    fonts: { display: 'big-shoulders-display', body: 'work-sans', displayAr: 'changa', bodyAr: 'tajawal' },
    layout: { nav: 'bar', hero: 'fullbleed', offer: 'strip', contact: 'split' },
    decor: ['parallax', 'progress'],
  },
  {
    slug: 'countdown', profile: 'conference',
    name: { ar: 'العدّ التنازلي', en: 'Countdown' },
    blurb: { ar: 'أصفر نيون على الأسود وعدّاد حيّ للأيام، كشاشة انتظار قبل الإطلاق.', en: 'Neon yellow on black with a live day counter, like a screen before launch.' },
    scheme: 'dark',
    palette: { bg: '#0A0A0A', surface: '#141414', ink: '#FAFAFA', muted: '#A1A1A1', accent: '#E8FF59', accent2: '#FF4FD8', line: '#262626', onAccent: '#0A0A0A' },
    fonts: { display: 'archivo', body: 'inter', displayAr: 'kufam', bodyAr: 'readex-pro' },
    layout: { nav: 'bar', extra: 'strip', schedule: 'timeline' },
    decor: ['progress', 'cursor', 'grid'],
  },
  {
    slug: 'mist', profile: 'perfume',
    name: { ar: 'رذاذ', en: 'Mist' },
    blurb: { ar: 'وردي ضبابي وأشكال لونية تتحوّل ببطء، والعطور تنساب أفقيًا.', en: 'Misty pink and slowly morphing colour, with perfumes that glide sideways.' },
    scheme: 'light',
    palette: { bg: '#F7F1F4', surface: '#FFFFFF', ink: '#2B1B2E', muted: '#7A6680', accent: '#B04A7A', accent2: '#E6B9A6', line: '#EADCE4', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'outfit', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { nav: 'pill', hero: 'centered', offer: 'strip', gallery: 'masonry', quotes: 'single', contact: 'card' },
    decor: ['blobs', 'parallax'],
  },
  {
    slug: 'saffron', profile: 'restaurant',
    name: { ar: 'زعفران', en: 'Saffron' },
    blurb: { ar: 'ليل دافئ ولون الزعفران، أطباق تنزلق متناوبة وصور تتحرك مع التمرير.', en: 'A warm night and saffron yellow, dishes sliding in turn and photos moving as you scroll.' },
    scheme: 'dark',
    palette: { bg: '#120D0A', surface: '#1C1511', ink: '#F6EBDD', muted: '#B6A390', accent: '#F2A23A', accent2: '#C2412D', line: '#33271F', onAccent: '#120D0A' },
    fonts: { display: 'dm-serif-display', body: 'dm-sans', displayAr: 'reem-kufi', bodyAr: 'tajawal' },
    layout: { nav: 'minimal', offer: 'zigzag' },
    decor: ['parallax', 'progress', 'cursor'],
  },
  {
    slug: 'sprint', profile: 'bikes',
    name: { ar: 'انطلاقة', en: 'Sprint' },
    blurb: { ar: 'أسود ومرجاني حار وسماوي، عنوان ضخم يصعد كلمة كلمة، دراجات تمر في شريط جانبي، ومواعيد الجولات في جدول.', en: 'Black, hot coral and cyan, a huge headline rising word by word, bikes passing on a sideways strip and ride times in a table.' },
    scheme: 'dark',
    palette: { bg: '#0A0A0A', surface: '#151515', ink: '#F7F7F2', muted: '#A0A09A', accent: '#FF3E5F', accent2: '#00D1FF', line: '#262626', onAccent: '#0A0A0A' },
    fonts: { display: 'bebas-neue', body: 'inter', displayAr: 'beiruti', bodyAr: 'cairo' },
    layout: { nav: 'bar', offer: 'strip', schedule: 'table' },
    decor: ['progress', 'cursor', 'parallax'],
  },
  {
    slug: 'drip', profile: 'cafe',
    name: { ar: 'تقطير', en: 'Drip' },
    blurb: { ar: 'أبيض دافئ وبرتقالي محروق وأخضر بترولي، صورة كاملة تتحرك ببطء، أصناف تنزلق متناوبة، وآراء تمر كشريط.', en: 'Warm white, burnt orange and petrol green, a full-screen photo drifting slowly, items sliding in turn and reviews running like a ticker.' },
    scheme: 'light',
    palette: { bg: '#FFF8F0', surface: '#FFFFFF', ink: '#2B1A12', muted: '#6F5A4E', accent: '#C2410C', accent2: '#0F766E', line: '#F0E2D3', onAccent: '#FFFFFF' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { nav: 'pill', hero: 'fullbleed', offer: 'zigzag', gallery: 'strip', quotes: 'marquee' },
    decor: ['parallax', 'progress', 'blobs'],
  },
  {
    slug: 'glare', profile: 'signage',
    name: { ar: 'وهج', en: 'Glare' },
    blurb: { ar: 'ليل أزرق ووردي نيون وفيروزي، كواجهة محل لافتات مضاءة: خط ضخم، أعمال في جدار، وخطوات تظهر بالتتابع.', en: 'Blue night, neon pink and turquoise, like a lit sign shop at night: huge type, work on a wall and steps that appear one after another.' },
    scheme: 'dark',
    palette: { bg: '#0B0F14', surface: '#131A22', ink: '#F2F5F8', muted: '#9AA6B2', accent: '#FF2E63', accent2: '#08D9D6', line: '#1F2833', onAccent: '#FFFFFF' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'reem-kufi', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'strip', gallery: 'masonry', process: 'steps', contact: 'center' },
    decor: ['cursor', 'progress', 'grid'],
  },
  {
    slug: 'reel', profile: 'photographer',
    name: { ar: 'بكرة', en: 'Reel' },
    blurb: { ar: 'أسود السينما وذهبي ووردي، صور متراكبة تتحرك بعمق، الأعمال تمر كشريط فيلم، وشهادة واحدة تتبدّل.', en: 'Cinema black, gold and rose, stacked photos moving in depth, the work rolling by like film and one testimonial changing at a time.' },
    scheme: 'dark',
    palette: { bg: '#0E0E10', surface: '#18181B', ink: '#FAFAFA', muted: '#A1A1AA', accent: '#F5C518', accent2: '#E11D48', line: '#27272A', onAccent: '#0E0E10' },
    fonts: { display: 'unbounded', body: 'manrope', displayAr: 'zain', bodyAr: 'readex-pro' },
    layout: { nav: 'minimal', hero: 'collage', gallery: 'strip', quotes: 'single' },
    decor: ['parallax', 'cursor'],
  },
  {
    slug: 'swirl', profile: 'florist',
    name: { ar: 'دوّامة', en: 'Swirl' },
    blurb: { ar: 'ليلكي وبنفسجي وكهرماني، بقع لونية تدور خلف العنوان كالبتلات، الباقات في شريط منزلق، وآراء الزبائن تمر ببطء.', en: 'Lilac, violet and amber, colour blobs turning behind the headline like petals, the bouquets on a sliding strip and reviews drifting by.' },
    scheme: 'light',
    palette: { bg: '#F5F0FF', surface: '#FFFFFF', ink: '#241B35', muted: '#6B5E80', accent: '#7C3AED', accent2: '#F59E0B', line: '#E7DEF7', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'outfit', displayAr: 'marhey', bodyAr: 'mada' },
    layout: { nav: 'pill', hero: 'centered', offer: 'strip', extra: 'cards', quotes: 'marquee' },
    decor: ['blobs', 'parallax'],
  },
  {
    slug: 'flux', profile: 'software',
    name: { ar: 'تدفّق', en: 'Flux' },
    blurb: { ar: 'أخضر ليلي ونعناعي وأزرق، شبكة خافتة وعنوان بعرض الصفحة، خدمات في شبكة بينتو، وباقات تبرز فيها المميزة.', en: 'Night green, mint and blue, a faint grid and a full-width headline, services in a bento grid and plans with the featured one standing out.' },
    scheme: 'dark',
    palette: { bg: '#06120F', surface: '#0D1F1A', ink: '#E8F5F0', muted: '#8FB3A6', accent: '#2EE6A6', accent2: '#7AA2FF', line: '#173029', onAccent: '#06120F' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'bento', contact: 'form' },
    decor: ['grid', 'progress', 'cursor', 'icons'],
  },
];
