import type { DesignInput } from './input';

export const animated: DesignInput[] = [
  {
    slug: 'kinetic', profile: 'agency',
    name: { ar: 'حركة', en: 'Kinetic' },
    blurb: { ar: 'أسود وبرتقالي ناري، عنوان يصعد كلمة كلمة، شريط نصي مائل ومؤشر يتبعك.', en: 'Black and fiery orange, a headline that rises word by word, a tilted text band and a cursor that follows you.' },
    scheme: 'dark',
    palette: { bg: '#0B0B0F', surface: '#15151B', ink: '#F5F5F0', muted: '#9D9DA6', accent: '#FF5B2E', accent2: '#7C5CFF', line: '#26262E', onAccent: '#0B0B0F' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'lalezar', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'minimal' },
    decor: ['progress', 'cursor', 'parallax', 'stamp'],
  },
  {
    slug: 'aurora', profile: 'app',
    name: { ar: 'شفق', en: 'Aurora' },
    blurb: { ar: 'كحلي عميق تتحرك فوقه أضواء بنفسجية وسماوية، وهاتفان يطفوان.', en: 'Deep navy under drifting violet and cyan light, with two floating phones.' },
    scheme: 'dark',
    palette: { bg: '#070B1A', surface: '#0F1530', ink: '#EEF1FF', muted: '#9AA3C7', accent: '#7C5CFF', accent2: '#22D3EE', line: '#1E2850', onAccent: '#FFFFFF' },
    fonts: { display: 'syne', body: 'dm-sans', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { nav: 'pill', hero: 'device', offer: 'bento' },
    decor: ['blobs', 'progress', 'icons'],
  },
  {
    slug: 'skyline', profile: 'realestate',
    name: { ar: 'أفق', en: 'Skyline' },
    blurb: { ar: 'خط طويل مضغوط وصور بعمق متحرك، والعقارات تمر أفقيًا كشريط.', en: 'Tall condensed type and layered parallax photos, with listings that scroll sideways like a reel.' },
    scheme: 'light',
    palette: { bg: '#F4F1EC', surface: '#FFFFFF', ink: '#171512', muted: '#6B655C', accent: '#E0592A', accent2: '#1E3A34', line: '#E2DCD2', onAccent: '#FFFFFF' },
    fonts: { display: 'big-shoulders-display', body: 'work-sans', displayAr: 'changa', bodyAr: 'tajawal' },
    layout: { nav: 'bar', hero: 'fullbleed', offer: 'strip', contact: 'split' },
    decor: ['parallax', 'progress'],
  },
  {
    slug: 'countdown', profile: 'conference',
    name: { ar: 'العدّ التنازلي', en: 'Countdown' },
    blurb: { ar: 'أصفر نيون على الأسود وعدّاد حيّ للأيام، كشاشة انتظار قبل الإطلاق.', en: 'Neon yellow on black with a live day counter, like a screen before launch.' },
    scheme: 'dark',
    palette: { bg: '#0A0A0A', surface: '#141414', ink: '#FAFAFA', muted: '#A1A1A1', accent: '#E8FF59', accent2: '#FF4FD8', line: '#262626', onAccent: '#0A0A0A' },
    fonts: { display: 'archivo', body: 'inter', displayAr: 'kufam', bodyAr: 'readex-pro' },
    layout: { nav: 'bar', extra: 'strip', schedule: 'timeline' },
    decor: ['progress', 'cursor', 'grid'],
  },
  {
    slug: 'mist', profile: 'perfume',
    name: { ar: 'رذاذ', en: 'Mist' },
    blurb: { ar: 'وردي ضبابي وأشكال لونية تتحوّل ببطء، والعطور تنساب أفقيًا.', en: 'Misty pink and slowly morphing colour, with perfumes that glide sideways.' },
    scheme: 'light',
    palette: { bg: '#F7F1F4', surface: '#FFFFFF', ink: '#2B1B2E', muted: '#7A6680', accent: '#B04A7A', accent2: '#E6B9A6', line: '#EADCE4', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'outfit', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { nav: 'pill', hero: 'centered', offer: 'strip', gallery: 'masonry', quotes: 'single', contact: 'card' },
    decor: ['blobs', 'parallax'],
  },
  {
    slug: 'saffron', profile: 'restaurant',
    name: { ar: 'زعفران', en: 'Saffron' },
    blurb: { ar: 'ليل دافئ ولون الزعفران، أطباق تنزلق متناوبة وصور تتحرك مع التمرير.', en: 'A warm night and saffron yellow, dishes sliding in turn and photos moving as you scroll.' },
    scheme: 'dark',
    palette: { bg: '#120D0A', surface: '#1C1511', ink: '#F6EBDD', muted: '#B6A390', accent: '#F2A23A', accent2: '#C2412D', line: '#33271F', onAccent: '#120D0A' },
    fonts: { display: 'dm-serif-display', body: 'dm-sans', displayAr: 'reem-kufi', bodyAr: 'tajawal' },
    layout: { nav: 'minimal', offer: 'zigzag' },
    decor: ['parallax', 'progress', 'cursor'],
  },
];
