import type { DesignInput } from './input';

export const artdeco: DesignInput[] = [
  {
    slug: 'gatsby', profile: 'wedding',
    name: { ar: 'غاتسبي', en: 'Gatsby' },
    blurb: { ar: 'أسود وذهب وأشعة شمس هندسية، دعوة عرس بروح حفلات العشرينات.', en: 'Black, gold and a geometric sunburst, a wedding invitation with twenties party spirit.' },
    scheme: 'dark',
    palette: { bg: '#0C0C0C', surface: '#161616', ink: '#F3E7C9', muted: '#B3A684', accent: '#D4AF37', accent2: '#8C7325', line: '#2F2A1E', onAccent: '#0C0C0C' },
    fonts: { display: 'poiret-one', body: 'josefin-sans', displayAr: 'reem-kufi', bodyAr: 'el-messiri' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'emerald', profile: 'hotel',
    name: { ar: 'زمرّد', en: 'Emerald' },
    blurb: { ar: 'أخضر زمردي وذهب وإطارات متدرجة الزوايا، لفندق كلاسيكي فخم.', en: 'Emerald green, gold and stepped-corner frames, for a grand classic hotel.' },
    scheme: 'dark',
    palette: { bg: '#0B2620', surface: '#10342C', ink: '#EFE4C8', muted: '#A9B5A3', accent: '#C9A85C', accent2: '#2F6B5B', line: '#1F4A40', onAccent: '#0B2620' },
    fonts: { display: 'limelight', body: 'josefin-sans', displayAr: 'el-messiri', bodyAr: 'almarai' },
    layout: { quotes: 'single' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'metropolis', profile: 'realestate',
    name: { ar: 'متروبوليس', en: 'Metropolis' },
    blurb: { ar: 'كحلي ونحاس وخطوط عمودية طويلة، كبرج سكني من نيويورك الثلاثينات.', en: 'Navy, brass and tall vertical lines, like a 1930s New York tower.' },
    scheme: 'dark',
    palette: { bg: '#0E1626', surface: '#152036', ink: '#EDE6D6', muted: '#A3A9B8', accent: '#C6A15B', accent2: '#6B7FA8', line: '#22304D', onAccent: '#0E1626' },
    fonts: { display: 'josefin-sans', body: 'josefin-sans', displayAr: 'reem-kufi', bodyAr: 'almarai' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'jazz', profile: 'music',
    name: { ar: 'جاز', en: 'Jazz' },
    blurb: { ar: 'نبيذي داكن وذهب ونوتات صامتة، مدرسة موسيقى بليالي نادي جاز: إشعاعات ذهبية، الدروس في قائمة منقّطة، وإطار مذهّب.', en: 'Deep wine, gold and silent notes, a music school with a jazz club\'s nights: gold sunbursts, lessons in a dotted list and a gilded frame.' },
    scheme: 'dark',
    palette: { bg: '#1A0E12', surface: '#26141A', ink: '#F2E2CC', muted: '#BFA48F', accent: '#D9A54A', accent2: '#9E2B3E', line: '#3A2129', onAccent: '#1A0E12' },
    fonts: { display: 'federo', body: 'josefin-sans', displayAr: 'aref-ruqaa', bodyAr: 'el-messiri' },
    layout: { offer: 'menu' },
    decor: ['divider-deco', 'sunburst'],
  },
  {
    slug: 'pavilion', profile: 'perfume',
    name: { ar: 'جناح العطر', en: 'Pavilion' },
    blurb: { ar: 'كريمي وأسود وذهب وحروف مزخرفة، كزجاجة عطر من باريس العشرينات.', en: 'Cream, black and gold with decorative capitals, like a perfume bottle from 1920s Paris.' },
    scheme: 'light',
    palette: { bg: '#F3EDE1', surface: '#FBF7EE', ink: '#1B1B1B', muted: '#6B655A', accent: '#1B1B1B', accent2: '#B8923D', line: '#DCD2BE', onAccent: '#F3EDE1' },
    fonts: { display: 'cinzel-decorative', body: 'josefin-sans', displayAr: 'reem-kufi', bodyAr: 'almarai' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'cinema', profile: 'conference',
    name: { ar: 'سينما', en: 'Cinema' },
    blurb: { ar: 'أحمر ستارة المسرح وذهب الأضواء، لمهرجان أو مؤتمر بروح الأفلام الكلاسيكية.', en: 'Curtain red and marquee gold, for a festival or conference with classic-film spirit.' },
    scheme: 'dark',
    palette: { bg: '#140608', surface: '#21090D', ink: '#F5E6C8', muted: '#C0A386', accent: '#E0B04A', accent2: '#B3192C', line: '#3A1418', onAccent: '#140608' },
    fonts: { display: 'limelight', body: 'josefin-sans', displayAr: 'lalezar', bodyAr: 'almarai' },
    layout: { extra: 'cards' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'supper-club', profile: 'restaurant',
    name: { ar: 'نادي العشاء', en: 'Supper Club' },
    blurb: { ar: 'أسود مخملي وذهبي وبنفسجي ملكي، نادي عشاء من العشرينات: إشعاع شمسي، إطار مذهّب، وقائمة بخطوط منقّطة.', en: 'Velvet black, gold and royal purple, a twenties supper club: a sunburst, a gilded frame and a dotted menu.' },
    scheme: 'dark',
    palette: { bg: '#0E0B14', surface: '#18131F', ink: '#F2EAD8', muted: '#B5A88F', accent: '#D4AF37', accent2: '#8E4BD0', line: '#2A2233', onAccent: '#0E0B14' },
    fonts: { display: 'marcellus-sc', body: 'josefin-sans', displayAr: 'aref-ruqaa', bodyAr: 'almarai' },
    layout: { offer: 'menu', quotes: 'single' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'bonbon', profile: 'sweets',
    name: { ar: 'بونبون', en: 'Bonbon' },
    blurb: { ar: 'عاجي وأسود وذهبي، علبة شوكولاتة من باريس العشرينات: خط إيطالي رشيق، إطار مزخرف، وحلويات في بطاقات.', en: 'Ivory, black and gold, a chocolate box from twenties Paris: a slender Italiana face, an ornate frame and sweets in cards.' },
    scheme: 'light',
    palette: { bg: '#F5EFE3', surface: '#FFFDF8', ink: '#1E1A16', muted: '#6B6257', accent: '#2B2B2B', accent2: '#B8902F', line: '#E3D8C4', onAccent: '#F5EFE3' },
    fonts: { display: 'italiana', body: 'josefin-sans', displayAr: 'reem-kufi', bodyAr: 'almarai' },
    layout: { offer: 'cards', gallery: 'gallery' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'chambers', profile: 'law',
    name: { ar: 'غرف المحاماة', en: 'Chambers' },
    blurb: { ar: 'كحلي ليلي وذهبي وعنابي، مكتب محاماة بعمارة الثلاثينات: صورة بجانب العنوان، خدمات كقائمة، وخطوات واضحة.', en: 'Night navy, gold and burgundy, a law firm in thirties architecture: a photo beside the headline, services as a list and clear steps.' },
    scheme: 'dark',
    palette: { bg: '#0D1626', surface: '#142036', ink: '#EDE6D6', muted: '#A7AFBF', accent: '#C6A15B', accent2: '#B04A4A', line: '#223048', onAccent: '#0D1626' },
    fonts: { display: 'federo', body: 'josefin-sans', displayAr: 'el-messiri', bodyAr: 'almarai' },
    layout: { hero: 'split', offer: 'list', process: 'steps' },
    decor: ['divider-deco', 'sunburst'],
  },
  {
    slug: 'jewel', profile: 'boutique',
    name: { ar: 'جوهرة', en: 'Jewel' },
    blurb: { ar: 'زمرّدي داكن وذهبي وياقوتي، دار مجوهرات من عصر الآرت ديكو: إطار ذهبي حول العنوان، قطع في بطاقات، وتفاصيل كقائمة.', en: 'Deep emerald, gold and ruby, an art deco jeweller: a gold frame around the headline, pieces in cards and details as a list.' },
    scheme: 'dark',
    palette: { bg: '#07231C', surface: '#0D3027', ink: '#F1EBDD', muted: '#A9BBAF', accent: '#D9B45A', accent2: '#C0475E', line: '#164338', onAccent: '#07231C' },
    fonts: { display: 'limelight', body: 'josefin-sans', displayAr: 'reem-kufi', bodyAr: 'almarai' },
    layout: { offer: 'cards', extra: 'list' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'voyage-1925', profile: 'travel',
    name: { ar: 'رحلة ١٩٢٥', en: 'Voyage 1925' },
    blurb: { ar: 'عاجي وأسود وذهبي باهت، مكتب سفر كملصق باخرة من العشرينات: خط بوايريه الرفيع، إشعاع خلف العنوان، وجدار صور.', en: 'Ivory, black and faded gold, a travel agency like a twenties steamship poster: slender Poiret lettering, a sunburst behind the headline and a wall of photos.' },
    scheme: 'light',
    palette: { bg: '#F4EFE6', surface: '#FFFFFF', ink: '#1A1A1A', muted: '#625C54', accent: '#1A1A1A', accent2: '#B8963E', line: '#E1D8C8', onAccent: '#F4EFE6' },
    fonts: { display: 'poiret-one', body: 'josefin-sans', displayAr: 'el-messiri', bodyAr: 'almarai' },
    layout: { gallery: 'masonry', pricing: 'pricing' },
    decor: ['sunburst', 'divider-deco'],
  },
  {
    slug: 'marquee-lights', profile: 'signage',
    name: { ar: 'أضواء المسرح', en: 'Marquee' },
    blurb: { ar: 'عنابي داكن وأصفر مصابيح وبرتقالي، لافتات بروح مداخل المسارح القديمة: عنوان في المنتصف وإشعاع ذهبي.', en: 'Deep burgundy, bulb yellow and orange, signs in the spirit of old theatre entrances: a centred headline and a golden sunburst.' },
    scheme: 'dark',
    palette: { bg: '#1A0710', surface: '#260C18', ink: '#F7E9D7', muted: '#C2A99A', accent: '#F2C14E', accent2: '#E4572E', line: '#3A1424', onAccent: '#1A0710' },
    fonts: { display: 'limelight', body: 'josefin-sans', displayAr: 'rakkas', bodyAr: 'almarai' },
    layout: { hero: 'centered', gallery: 'masonry', process: 'steps' },
    decor: ['sunburst', 'divider-deco'],
  },
];
