import type { DesignInput } from './input';

// Aurora: wide blurred colour fields drift behind a deep ground. Each design
// picks its own two lights (accent, accent2); the kit mixes a third.
export const aurora: DesignInput[] = [
  {
    slug: 'borealis', profile: 'conference',
    name: { ar: 'بوريالِس', en: 'Borealis' },
    blurb: { ar: 'كحلي عميق وفيروزي ووردي، مهرجان موسيقي تحت شفق يتحرك ببطء.', en: 'Deep navy, teal and pink, a music festival under a slowly moving aurora.' },
    scheme: 'dark',
    palette: { bg: '#0B0B1E', surface: '#14142C', ink: '#F4F4FF', muted: '#A9A9C8', accent: '#FF2E9A', accent2: '#00E0FF', line: '#24244A', onAccent: '#1A0010' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'readex-pro', bodyAr: 'readex-pro' },
    decor: ['progress'],
  },
  {
    slug: 'aurora-nebula', profile: 'app',
    name: { ar: 'سديم', en: 'Nebula' },
    blurb: { ar: 'بنفسجي ليلي وسماوي كهربائي، تطبيق موسيقى يتوهج خلفه سديم ملون.', en: 'Night violet and electric cyan, a music app with a coloured nebula glowing behind it.' },
    scheme: 'dark',
    palette: { bg: '#0E0820', surface: '#181030', ink: '#F5F0FF', muted: '#ADA2CC', accent: '#8B5CFF', accent2: '#22D3EE', line: '#2A1F4A', onAccent: '#FFFFFF' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { hero: 'device' },
  },
  {
    slug: 'gradient-ai', profile: 'software',
    name: { ar: 'ذكاء', en: 'Gradient' },
    blurb: { ar: 'أسود مزرق وأخضر زمردي وأزرق، منصة ذكاء اصطناعي بتدرج يتنفس خلف العنوان.', en: 'Bluish black, emerald and blue, an AI platform with a gradient that breathes behind the headline.' },
    scheme: 'dark',
    palette: { bg: '#070B14', surface: '#0F1524', ink: '#EEF3FF', muted: '#9AA6C0', accent: '#00FF9C', accent2: '#3B82F6', line: '#1B2438', onAccent: '#00140B' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic', accent: 'jetbrains-mono' },
    layout: { stats: 'big', extra: 'bento' },
    decor: ['grid'],
  },
  {
    slug: 'aurora-prism', profile: 'agency',
    name: { ar: 'موشور', en: 'Prism' },
    blurb: { ar: 'أبيض لؤلؤي وشفق وردي-برتقالي-بنفسجي، وكالة إبداعية بخلفية قزحية فاتحة.', en: 'Pearl white with a pink, orange and violet aurora, a creative agency on a light iridescent ground.' },
    scheme: 'light',
    palette: { bg: '#FBF8FF', surface: '#FFFFFF', ink: '#1A1430', muted: '#5D5674', accent: '#C2187A', accent2: '#FF8A3D', line: '#ECE6F6', onAccent: '#FFFFFF' },
    fonts: { display: 'syne', body: 'dm-sans', displayAr: 'reem-kufi', bodyAr: 'readex-pro' },
    layout: { hero: 'type', gallery: 'masonry' },
  },
  {
    slug: 'long-exposure', profile: 'photographer',
    name: { ar: 'تعريض طويل', en: 'Long exposure' },
    blurb: { ar: 'أسود سماء ليلية وأخضر شفق قطبي، مصور مناظر ليلية ونجوم.', en: 'Night-sky black and polar green, a photographer of night landscapes and stars.' },
    scheme: 'dark',
    palette: { bg: '#05090C', surface: '#0D151A', ink: '#EAF6F2', muted: '#93A8A2', accent: '#3CF2A5', accent2: '#7A5CFF', line: '#18242A', onAccent: '#00160C' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { hero: 'fullbleed', gallery: 'masonry' },
  },
  {
    slug: 'iris', profile: 'perfume',
    name: { ar: 'سوسن', en: 'Iris' },
    blurb: { ar: 'برقوقي داكن ووردي وذهبي، عطور مسائية يلفها ضباب ملون.', en: 'Dark plum, pink and gold, evening perfumes wrapped in a coloured haze.' },
    scheme: 'dark',
    palette: { bg: '#170A16', surface: '#22111F', ink: '#FBEFF6', muted: '#C2A5B8', accent: '#FF5FA2', accent2: '#FFC46B', line: '#3A2035', onAccent: '#24000F' },
    fonts: { display: 'italiana', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'centered' },
  },
  {
    slug: 'dawn', profile: 'wedding',
    name: { ar: 'فجر', en: 'Dawn' },
    blurb: { ar: 'سماء الفجر بالخوخي والليلكي والسماوي، زفاف عند شروق الشمس.', en: 'A dawn sky in peach, lilac and pale blue, a wedding at sunrise.' },
    scheme: 'light',
    palette: { bg: '#FFF7F3', surface: '#FFFFFF', ink: '#2E2236', muted: '#665A6E', accent: '#B5487A', accent2: '#7FA8FF', line: '#F0E3E6', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { schedule: 'timeline', about: 'split' },
  },
  {
    slug: 'afterglow', profile: 'gym',
    name: { ar: 'توهج', en: 'Afterglow' },
    blurb: { ar: 'أسود وأحمر ناري وبرتقالي، نادي ركوب دراجات داخلي تحت أضواء ملونة.', en: 'Black, fire red and orange, an indoor cycling club under coloured lights.' },
    scheme: 'dark',
    palette: { bg: '#0D0707', surface: '#1A0E0E', ink: '#FFF2EE', muted: '#C5A39C', accent: '#FF3D3D', accent2: '#FF9F1C', line: '#2E1717', onAccent: '#1A0000' },
    fonts: { display: 'archivo-black', body: 'archivo', displayAr: 'lalezar', bodyAr: 'cairo' },
    layout: { hero: 'fullbleed', pricing: 'pricing' },
  },
  {
    slug: 'aurora-lagoon', profile: 'hotel',
    name: { ar: 'بحيرة', en: 'Lagoon' },
    blurb: { ar: 'فيروزي عميق وأزرق ليلي، منتجع على البحر الأحمر تحت سماء ملونة.', en: 'Deep turquoise and night blue, a Red Sea resort under a coloured sky.' },
    scheme: 'dark',
    palette: { bg: '#04121A', surface: '#0A1E28', ink: '#E9F7FA', muted: '#93B1BA', accent: '#2EE6D6', accent2: '#4F7BFF', line: '#123241', onAccent: '#00201D' },
    fonts: { display: 'fraunces', body: 'outfit', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'fullbleed' },
  },
  {
    slug: 'holo', profile: 'boutique',
    name: { ar: 'هولو', en: 'Holo' },
    blurb: { ar: 'أبيض وقزحي هولوغرامي، متجر أحذية رياضية يلمع كغلاف هولوغرام.', en: 'White and holographic rainbow, a sneaker shop that shimmers like holographic foil.' },
    scheme: 'light',
    palette: { bg: '#F6F7FB', surface: '#FFFFFF', ink: '#14162A', muted: '#585B72', accent: '#5B3DF5', accent2: '#00C2D1', line: '#E5E7F0', onAccent: '#FFFFFF' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'lalezar', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { gallery: 'bento', hero: 'split' },
  },
  {
    slug: 'skyline-aurora', profile: 'realestate',
    name: { ar: 'أفق', en: 'Skyline' },
    blurb: { ar: 'كحلي ليلي وذهبي ووردي، أبراج سكنية تلمع تحت سماء المدينة.', en: 'Night navy, gold and pink, residential towers glowing under the city sky.' },
    scheme: 'dark',
    palette: { bg: '#0A0E1F', surface: '#121831', ink: '#F2F3FA', muted: '#A2A7C2', accent: '#FFB547', accent2: '#E84A9A', line: '#1F2746', onAccent: '#1E1200' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'fullbleed', offer: 'cards' },
  },
  {
    slug: 'spark', profile: 'academy',
    name: { ar: 'شرارة', en: 'Spark' },
    blurb: { ar: 'كحلي وأخضر نيون ووردي، أكاديمية برمجة للشباب بخلفية تتوهج.', en: 'Navy, neon green and pink, a coding academy for young people on a glowing ground.' },
    scheme: 'dark',
    palette: { bg: '#0A0D1C', surface: '#121729', ink: '#EFF2FF', muted: '#A1A8C6', accent: '#7CFF6B', accent2: '#FF4FD8', line: '#1E2440', onAccent: '#071A03' },
    fonts: { display: 'lexend', body: 'lexend', displayAr: 'zain', bodyAr: 'zain', accent: 'jetbrains-mono' },
    layout: { pricing: 'pricing', process: 'steps' },
  },
];
