import type { DesignInput } from './input';

// Bento: every section is a grid of rounded cards in different sizes. Light
// greys with one brand colour, or the same idea on near-black.
export const bento: DesignInput[] = [
  {
    slug: 'keynote-grid', profile: 'app',
    name: { ar: 'عرض', en: 'Showcase' },
    blurb: { ar: 'رمادي فاتح وأزرق آبل، ميزات التطبيق في بطاقات بأحجام مختلفة وهاتف في البطاقة الكبرى.', en: 'Light grey and Apple blue, the app\'s features in cards of different sizes and a phone in the big one.' },
    scheme: 'light',
    palette: { bg: '#F5F5F7', surface: '#FFFFFF', ink: '#1D1D1F', muted: '#5E5E66', accent: '#0071E3', accent2: '#34C759', line: '#E3E3E8', onAccent: '#FFFFFF' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'device' },
  },
  {
    slug: 'dashboard', profile: 'wallet',
    name: { ar: 'لوحة', en: 'Dashboard' },
    blurb: { ar: 'أسود عميق وبطاقات رمادية داكنة وأخضر نعناعي، كأن الصفحة لوحة تطبيق الميزانية نفسها: أرقام كبيرة وظروف واضحة.', en: 'Deep black, dark grey cards and mint green, as if the page were the budget app\'s own dashboard: big numbers and clear envelopes.' },
    scheme: 'dark',
    palette: { bg: '#0A0A0B', surface: '#161618', ink: '#F2F2F3', muted: '#9C9CA3', accent: '#3DDC97', accent2: '#5B8CFF', line: '#26262A', onAccent: '#06140D' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'readex-pro', bodyAr: 'ibm-plex-sans-arabic', accent: 'jetbrains-mono' },
    layout: { hero: 'centered', stats: 'big' },
    decor: ['grid'],
  },
  {
    slug: 'roastery', profile: 'cafe',
    name: { ar: 'محمصة', en: 'Roastery' },
    blurb: { ar: 'كريمي وبني قهوة وكهرماني، المحاصيل والأرقام والعنوان كلٌّ في بطاقته.', en: 'Cream, coffee brown and amber; the beans, the numbers and the address each in its own card.' },
    scheme: 'light',
    palette: { bg: '#F3F1EC', surface: '#FFFFFF', ink: '#1D1B18', muted: '#6A6258', accent: '#2C211A', accent2: '#E9A23B', line: '#E4DFD6', onAccent: '#F6EDE2' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { gallery: 'bento' },
  },
  {
    slug: 'floor-grid', profile: 'cowork',
    name: { ar: 'مخطط', en: 'Floorplan' },
    blurb: { ar: 'أبيض وزيتي وحجري، المكاتب والغرف وقاعات الاجتماعات في شبكة بطاقات كأنها غرف على مخطط الطابق.', en: 'White, olive and stone; desks, offices and meeting rooms in a grid of cards like rooms on a floor plan.' },
    scheme: 'light',
    palette: { bg: '#F2F1EE', surface: '#FFFFFF', ink: '#1F2320', muted: '#5F665F', accent: '#4F6B45', accent2: '#C9B79C', line: '#DEDDD7', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'fustat', bodyAr: 'fustat' },
    layout: { hero: 'fullbleed', about: 'columns' },
  },
  {
    slug: 'gears', profile: 'bikes',
    name: { ar: 'غيارات', en: 'Gears' },
    blurb: { ar: 'فحمي وبرتقالي نيون، الدراجات والجولات والأرقام في بطاقات قوية كشاشة عدّاد الدراجة.', en: 'Charcoal and neon orange; bikes, rides and figures in bold cards like the screen of a bike computer.' },
    scheme: 'dark',
    palette: { bg: '#111214', surface: '#1C1D20', ink: '#F4F4F5', muted: '#A1A1A8', accent: '#FF6A1A', accent2: '#D7FF3A', line: '#2A2B2F', onAccent: '#140700' },
    fonts: { display: 'archivo', body: 'archivo', displayAr: 'cairo', bodyAr: 'cairo' },
    layout: { hero: 'split', stats: 'big', pricing: 'pricing' },
  },
  {
    slug: 'summit-grid', profile: 'conference',
    name: { ar: 'جدول', en: 'Agenda' },
    blurb: { ar: 'أبيض وبنفسجي وليموني، المتحدثون والجلسات والعدّ التنازلي في شبكة واحدة مرتبة.', en: 'White, violet and lime; speakers, sessions and the countdown in one tidy grid.' },
    scheme: 'light',
    palette: { bg: '#F4F3F8', surface: '#FFFFFF', ink: '#17152A', muted: '#5D5A72', accent: '#5B3DF5', accent2: '#C6F432', line: '#E2E0EC', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'plus-jakarta-sans', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { hero: 'centered', schedule: 'timeline' },
  },
  {
    slug: 'setlist', profile: 'music',
    name: { ar: 'قائمة العزف', en: 'Setlist' },
    blurb: { ar: 'أبيض نقي وأحمر طماطم، الآلات والدروس والأسبوع في بطاقات كبيرة وصغيرة، كقائمة عزف ملصقة على المسرح.', en: 'Pure white and tomato red; instruments, lessons and the week in big and small cards, like a setlist taped to the stage.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F3F3F1', ink: '#151515', muted: '#5E5E5C', accent: '#E8432E', accent2: '#151515', line: '#E6E6E3', onAccent: '#FFFFFF' },
    fonts: { display: 'syne', body: 'inter', displayAr: 'reem-kufi', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'type', gallery: 'bento' },
  },
  {
    slug: 'itinerary', profile: 'travel',
    name: { ar: 'برنامج الرحلة', en: 'Itinerary' },
    blurb: { ar: 'رملي وأزرق بحري، الرحلات والخطوات والصور في بطاقات كصفحات برنامج رحلة محكم.', en: 'Sand and sea blue; trips, steps and photos in cards like the pages of a well-planned itinerary.' },
    scheme: 'light',
    palette: { bg: '#F1EEE8', surface: '#FFFFFF', ink: '#14232E', muted: '#55626B', accent: '#1F5673', accent2: '#D9A25F', line: '#E2DDD3', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'fullbleed' },
  },
  {
    slug: 'checkup', profile: 'clinic',
    name: { ar: 'فحص', en: 'Checkup' },
    blurb: { ar: 'أبيض وفيروزي هادئ، الخدمات والمواعيد والأطباء في بطاقات واضحة سهلة القراءة.', en: 'White and a calm teal; services, hours and doctors in clear, easy-to-read cards.' },
    scheme: 'light',
    palette: { bg: '#F2F6F7', surface: '#FFFFFF', ink: '#102A33', muted: '#4F666E', accent: '#0E7C86', accent2: '#7FD1C7', line: '#DCE7EA', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { contact: 'split' },
  },
  {
    slug: 'shelf-grid', profile: 'bookshop',
    name: { ar: 'رفوف', en: 'Shelves' },
    blurb: { ar: 'صفحات بيضاء وأصفر قلم تحديد وأزرق، مكتبة مرتبة كرفّ منظّم: العناوين الجديدة في بطاقات بأحجام مختلفة وتركيب من الكتب في الواجهة.', en: 'White pages, highlighter yellow and blue, a bookshop sorted like a tidy shelf: the new titles in cards of different sizes and a collage of books up top.' },
    scheme: 'light',
    palette: { bg: '#F6F5F0', surface: '#FFFFFF', ink: '#14213D', muted: '#56607A', accent: '#2B59C3', accent2: '#FFD23F', line: '#E3E1D8', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'lexend', displayAr: 'zain', bodyAr: 'zain' },
    layout: { hero: 'collage', pricing: 'pricing' },
  },
  {
    slug: 'capsule', profile: 'gallery',
    name: { ar: 'كبسولة', en: 'Capsule' },
    blurb: { ar: 'عاجي ووردي غباري وأسود، المعارض في بطاقات كمجموعة كبسولية مرتبة، تحت عنوان كغلاف مجلة.', en: 'Ivory, dusty pink and black; the exhibitions in cards like a tidy capsule collection, under a magazine-cover headline.' },
    scheme: 'light',
    palette: { bg: '#F6F2EE', surface: '#FFFFFF', ink: '#1C1717', muted: '#6B5F5C', accent: '#1C1717', accent2: '#E7B7B0', line: '#E7E0DA', onAccent: '#FFFFFF' },
    fonts: { display: 'instrument-serif', body: 'dm-sans', displayAr: 'markazi-text', bodyAr: 'readex-pro' },
    layout: { hero: 'editorial', gallery: 'bento' },
  },
  {
    slug: 'star-chart', profile: 'stars',
    name: { ar: 'خريطة النجوم', en: 'Star Chart' },
    blurb: { ar: 'أسود وأحمر كالضوء الذي يحفظ عين الراصد، صور السماء في بطاقات بأحجام مختلفة كخريطة نجوم.', en: 'Black and the red of an observer\'s torch; the sky photos in cards of different sizes like a star chart.' },
    scheme: 'dark',
    palette: { bg: '#0D0D0D', surface: '#1A1A1A', ink: '#F1EEEA', muted: '#A39E98', accent: '#E0453A', accent2: '#F1EEEA', line: '#2A2A2A', onAccent: '#FFFFFF' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic', accent: 'ibm-plex-mono' },
    layout: { hero: 'fullbleed', gallery: 'bento' },
  },
];
