import type { DesignInput } from './input';

export const brutalist: DesignInput[] = [
  {
    slug: 'raw', profile: 'agency',
    name: { ar: 'خام', en: 'Raw' },
    blurb: { ar: 'أبيض وأسود وأصفر صادم، حدود سميكة وظلال صلبة وعنوان يملأ الشاشة.', en: 'White, black and loud yellow, thick borders, hard shadows and a headline that fills the screen.' },
    scheme: 'light',
    palette: { bg: '#F2F2F2', surface: '#FFFFFF', ink: '#000000', muted: '#3D3D3D', accent: '#FFE600', accent2: '#FF3B00', line: '#000000', onAccent: '#000000' },
    fonts: { display: 'archivo-black', body: 'space-mono', displayAr: 'lalezar', bodyAr: 'ibm-plex-sans-arabic' },
  },
  {
    slug: 'concrete', profile: 'construction',
    name: { ar: 'خرسانة', en: 'Concrete' },
    blurb: { ar: 'رمادي إسمنتي وبرتقالي السلامة وخط مضغوط، كلافتة موقع بناء.', en: 'Cement grey, safety orange and condensed type, like a building-site board.' },
    scheme: 'light',
    palette: { bg: '#D9D9D6', surface: '#EDEDEA', ink: '#111111', muted: '#454545', accent: '#FF6B00', accent2: '#111111', line: '#111111', onAccent: '#111111' },
    fonts: { display: 'anton', body: 'archivo', displayAr: 'changa', bodyAr: 'tajawal' },
    decor: ['grid'],
  },
  {
    slug: 'loud', profile: 'gym',
    name: { ar: 'صاخب', en: 'Loud' },
    blurb: { ar: 'صفحة حمراء كاملة بخط أسود ضخم، طاقة لا تهدأ لنادٍ رياضي.', en: 'An all-red page with huge black type, relentless energy for a gym.' },
    scheme: 'light',
    palette: { bg: '#FF2D20', surface: '#FFFFFF', ink: '#000000', muted: '#1F0A08', accent: '#000000', accent2: '#FFFFFF', line: '#000000', onAccent: '#FFFFFF' },
    fonts: { display: 'bebas-neue', body: 'space-grotesk', displayAr: 'jomhuria', bodyAr: 'cairo' },
    layout: { hero: 'type', offer: 'cards', pricing: 'pricing' },
    css: 'html { --pop: var(--bg); }',
  },
  {
    slug: 'zine', profile: 'photographer',
    name: { ar: 'زين', en: 'Zine' },
    blurb: { ar: 'نسخة مصوّرة بالأبيض والأسود ولمسة وردية، كمجلة فنية مطبوعة في البيت.', en: 'Black-and-white photocopy with a pink touch, like a home-printed art zine.' },
    scheme: 'light',
    palette: { bg: '#EFEDE6', surface: '#FFFFFF', ink: '#0A0A0A', muted: '#3B3B3B', accent: '#FF2E93', accent2: '#0A0A0A', line: '#0A0A0A', onAccent: '#0A0A0A' },
    fonts: { display: 'rubik-mono-one', body: 'space-mono', displayAr: 'blaka', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { pricing: 'table' },
    decor: ['mono', 'grain'],
  },
  {
    slug: 'grid', profile: 'conference',
    name: { ar: 'شبكة', en: 'Grid' },
    blurb: { ar: 'حبر أزرق على الأبيض وشبكة مكشوفة، مؤتمر بإخراج ملصق سويسري خام.', en: 'Blue ink on white with an exposed grid, a conference styled like a raw Swiss poster.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F4F4', ink: '#0019FF', muted: '#3346FF', accent: '#0019FF', accent2: '#FF4D00', line: '#0019FF', onAccent: '#FFFFFF' },
    fonts: { display: 'dela-gothic-one', body: 'space-mono', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'type', extra: 'cards', pricing: 'pricing' },
    decor: ['grid'],
    css: 'html { --pop: var(--bg); }',
  },
  {
    slug: 'signal', profile: 'signage',
    name: { ar: 'إشارة', en: 'Signal' },
    blurb: { ar: 'أصفر تحذير وأشرطة مائلة وأسود عريض، كلافتة طريق لا يمكن تجاهلها.', en: 'Warning yellow, hazard stripes and wide black, like a road sign you can\'t ignore.' },
    scheme: 'light',
    palette: { bg: '#FFD60A', surface: '#FFFFFF', ink: '#0A0A0A', muted: '#2B2B2B', accent: '#0A0A0A', accent2: '#FF3B30', line: '#0A0A0A', onAccent: '#FFD60A' },
    fonts: { display: 'bebas-neue', body: 'archivo', displayAr: 'beiruti', bodyAr: 'cairo' },
    layout: { offer: 'cards' },
    decor: ['hazard'],
    css: 'html { --pop: var(--bg); }',
  },
];
