import type { DesignInput } from './input';

export const brutalist: DesignInput[] = [
  {
    slug: 'raw', profile: 'agency',
    name: { ar: 'خام', en: 'Raw' },
    blurb: { ar: 'أبيض وأسود وأصفر صادم، حدود سميكة وظلال صلبة وعنوان يملأ الشاشة.', en: 'White, black and loud yellow, thick borders, hard shadows and a headline that fills the screen.' },
    scheme: 'light',
    palette: { bg: '#F2F2F2', surface: '#FFFFFF', ink: '#000000', muted: '#3D3D3D', accent: '#FFE600', accent2: '#FF3B00', line: '#000000', onAccent: '#000000' },
    fonts: { display: 'archivo-black', body: 'space-mono', displayAr: 'lalezar', bodyAr: 'ibm-plex-sans-arabic' },
  },
  {
    slug: 'concrete', profile: 'construction',
    name: { ar: 'خرسانة', en: 'Concrete' },
    blurb: { ar: 'رمادي إسمنتي وبرتقالي السلامة وخط مضغوط، كلافتة موقع بناء.', en: 'Cement grey, safety orange and condensed type, like a building-site board.' },
    scheme: 'light',
    palette: { bg: '#D9D9D6', surface: '#EDEDEA', ink: '#111111', muted: '#454545', accent: '#FF6B00', accent2: '#111111', line: '#111111', onAccent: '#111111' },
    fonts: { display: 'anton', body: 'archivo', displayAr: 'changa', bodyAr: 'tajawal' },
    decor: ['grid'],
  },
  {
    slug: 'loud', profile: 'gym',
    name: { ar: 'صاخب', en: 'Loud' },
    blurb: { ar: 'صفحة حمراء كاملة بخط أسود ضخم، طاقة لا تهدأ لنادٍ رياضي.', en: 'An all-red page with huge black type, relentless energy for a gym.' },
    scheme: 'light',
    palette: { bg: '#FF2D20', surface: '#FFFFFF', ink: '#000000', muted: '#1F0A08', accent: '#000000', accent2: '#FFFFFF', line: '#000000', onAccent: '#FFFFFF' },
    fonts: { display: 'bebas-neue', body: 'space-grotesk', displayAr: 'jomhuria', bodyAr: 'cairo' },
    layout: { hero: 'type', offer: 'cards', pricing: 'pricing' },
    css: 'html { --pop: var(--bg); }',
  },
  {
    slug: 'zine', profile: 'photographer',
    name: { ar: 'زين', en: 'Zine' },
    blurb: { ar: 'نسخة مصوّرة بالأبيض والأسود ولمسة وردية، كمجلة فنية مطبوعة في البيت.', en: 'Black-and-white photocopy with a pink touch, like a home-printed art zine.' },
    scheme: 'light',
    palette: { bg: '#EFEDE6', surface: '#FFFFFF', ink: '#0A0A0A', muted: '#3B3B3B', accent: '#FF2E93', accent2: '#0A0A0A', line: '#0A0A0A', onAccent: '#0A0A0A' },
    fonts: { display: 'rubik-mono-one', body: 'space-mono', displayAr: 'blaka', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { pricing: 'table' },
    decor: ['mono', 'grain'],
  },
  {
    slug: 'grid', profile: 'conference',
    name: { ar: 'شبكة', en: 'Grid' },
    blurb: { ar: 'حبر أزرق على الأبيض وشبكة مكشوفة، مؤتمر بإخراج ملصق سويسري خام.', en: 'Blue ink on white with an exposed grid, a conference styled like a raw Swiss poster.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F4F4', ink: '#0019FF', muted: '#3346FF', accent: '#0019FF', accent2: '#FF4D00', line: '#0019FF', onAccent: '#FFFFFF' },
    fonts: { display: 'dela-gothic-one', body: 'space-mono', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'type', extra: 'cards', pricing: 'pricing' },
    decor: ['grid'],
    css: 'html { --pop: var(--bg); }',
  },
  {
    slug: 'signal', profile: 'signage',
    name: { ar: 'إشارة', en: 'Signal' },
    blurb: { ar: 'أصفر تحذير وأشرطة مائلة وأسود عريض، كلافتة طريق لا يمكن تجاهلها.', en: 'Warning yellow, hazard stripes and wide black, like a road sign you can\'t ignore.' },
    scheme: 'light',
    palette: { bg: '#FFD60A', surface: '#FFFFFF', ink: '#0A0A0A', muted: '#2B2B2B', accent: '#0A0A0A', accent2: '#FF3B30', line: '#0A0A0A', onAccent: '#FFD60A' },
    fonts: { display: 'bebas-neue', body: 'archivo', displayAr: 'beiruti', bodyAr: 'cairo' },
    layout: { offer: 'cards' },
    decor: ['hazard'],
    css: 'html { --pop: var(--bg); }',
  },
  {
    slug: 'street', profile: 'restaurant',
    name: { ar: 'شارع', en: 'Street' },
    blurb: { ar: 'أبيض مكسور وبرتقالي ناري وحدود سوداء سميكة، أكل شارع بلا مجاملة: عنوان بعرض الصفحة وقائمة كجدول.', en: 'Off-white, fire orange and thick black borders, street food without manners: a full-width headline and the menu as a table.' },
    scheme: 'light',
    palette: { bg: '#F4F1E8', surface: '#FFFFFF', ink: '#0B0B0B', muted: '#4D4A42', accent: '#FF4D00', accent2: '#00A86B', line: '#0B0B0B', onAccent: '#0B0B0B' },
    fonts: { display: 'anton', body: 'space-mono', displayAr: 'lalezar', bodyAr: 'cairo' },
    layout: { hero: 'type', gallery: 'gallery' },
    decor: ['grid'],
  },
  {
    slug: 'drop', profile: 'boutique',
    name: { ar: 'إصدار', en: 'Drop' },
    blurb: { ar: 'أبيض وأسود وفوشي صارخ، متجر ملابس شارع بإصدارات محدودة: عنوان كالملصق، قطع في بطاقات بحدود، وجدول المقاسات.', en: 'White, black and screaming magenta, a streetwear shop of limited drops: a poster headline, bordered product cards and a size table.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F2F2', ink: '#000000', muted: '#555555', accent: '#FF00A8', accent2: '#00E0FF', line: '#000000', onAccent: '#000000' },
    fonts: { display: 'archivo-black', body: 'space-mono', displayAr: 'beiruti', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'cards', extra: 'table' },
    decor: ['grid', 'mono'],
  },
  {
    slug: 'shell', profile: 'software',
    name: { ar: 'سطر أوامر', en: 'Shell' },
    blurb: { ar: 'رمادي إسمنتي وأزرق كهربائي وأصفر، شركة برمجيات تكتب بخط أحادي: عنوان ضخم، خدمات في جدول، وباقات بحدود.', en: 'Cement grey, electric blue and yellow, a software company that writes in monospace: a huge headline, services in a table and bordered plans.' },
    scheme: 'light',
    palette: { bg: '#E9E9E4', surface: '#FFFFFF', ink: '#111111', muted: '#4F4F4A', accent: '#2B2BFF', accent2: '#FFD60A', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'space-mono', body: 'space-mono', displayAr: 'changa', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'type', pricing: 'pricing' },
    decor: ['mono', 'grid'],
    css: 'html { --pop: var(--accent2); }',
  },
  {
    slug: 'loft', profile: 'realestate',
    name: { ar: 'لوفت', en: 'Loft' },
    blurb: { ar: 'إسمنت وأسود وبرتقالي تحذيري، شقق صناعية خام: حروف طويلة مضغوطة، العقارات في جدول، والنص في أعمدة.', en: 'Concrete, black and warning orange, raw industrial lofts: tall condensed letters, listings in a table and text in columns.' },
    scheme: 'light',
    palette: { bg: '#D4D2CC', surface: '#E6E4DF', ink: '#141414', muted: '#45433F', accent: '#141414', accent2: '#FF6B00', line: '#141414', onAccent: '#D4D2CC' },
    fonts: { display: 'big-shoulders-display', body: 'space-mono', displayAr: 'changa', bodyAr: 'cairo' },
    layout: { extra: 'cards' },
    decor: ['grid'],
    css: 'html { --pop: var(--accent2); }',
  },
  {
    slug: 'black-coffee', profile: 'cafe',
    name: { ar: 'قهوة سوداء', en: 'Black Coffee' },
    blurb: { ar: 'برتقالي كامل وأسود فقط، مقهى لا يعتذر: عنوان ضخم بعرض الصفحة، قائمة بخطوط سميكة، وصور في شبكة بحدود.', en: 'All orange and black, a café that does not apologise: a huge full-width headline, a heavy-ruled menu and photos in a bordered grid.' },
    scheme: 'light',
    palette: { bg: '#FF6B35', surface: '#FF8A5C', ink: '#0A0A0A', muted: '#3A1A0A', accent: '#0A0A0A', accent2: '#FFFFFF', line: '#0A0A0A', onAccent: '#FF6B35' },
    fonts: { display: 'bebas-neue', body: 'space-grotesk', displayAr: 'lalezar', bodyAr: 'tajawal' },
    layout: { hero: 'type', offer: 'menu', gallery: 'gallery' },
    decor: ['mono'],
    css: 'html { --pop: var(--bg); }',
  },
  {
    slug: 'interface', profile: 'app',
    name: { ar: 'واجهة', en: 'Interface' },
    blurb: { ar: 'أبيض وأسود وأخضر إشارة، تطبيق بلا تجميل: هاتفان بحدود سميكة، مزايا في بطاقات مربعة، وأسئلة في صفوف.', en: 'White, black and signal green, an app without make-up: two phones with thick borders, features in square cards and questions in rows.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F0F0F0', ink: '#000000', muted: '#4A4A4A', accent: '#00C853', accent2: '#FF1744', line: '#000000', onAccent: '#000000' },
    fonts: { display: 'space-grotesk', body: 'space-mono', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'device', offer: 'cards', pricing: 'pricing' },
    decor: ['mono', 'grid'],
  },
];
