import type { DesignInput } from './input';

export const classic: DesignInput[] = [
  {
    slug: 'andalus', profile: 'restaurant',
    name: { ar: 'أندلس', en: 'Andalus' },
    blurb: { ar: 'عاجي وعنابي وذهب خافت، قائمة طعام بنقاط موصولة وزخارف صغيرة.', en: 'Ivory, burgundy and muted gold, a dotted-leader menu and small ornaments.' },
    scheme: 'light',
    palette: { bg: '#F5EFE3', surface: '#FBF7EE', ink: '#2A1D17', muted: '#6F5E50', accent: '#7A1F2B', accent2: '#A88A55', line: '#DCCDB4', onAccent: '#FFF8EC' },
    fonts: { display: 'cormorant-garamond', body: 'eb-garamond', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'oxford', profile: 'law',
    name: { ar: 'أكسفورد', en: 'Oxford' },
    blurb: { ar: 'كحلي على ورق كريمي، قائمة مرقّمة رصينة ونموذج تواصل هادئ.', en: 'Navy on cream paper, a sober numbered list and a quiet contact form.' },
    scheme: 'light',
    palette: { bg: '#F7F4EC', surface: '#FFFFFF', ink: '#14213D', muted: '#5B6478', accent: '#1D3557', accent2: '#B08D57', line: '#D9D3C3', onAccent: '#F7F4EC' },
    fonts: { display: 'libre-baskerville', body: 'source-serif-4', displayAr: 'amiri', bodyAr: 'scheherazade-new' },
    layout: { nav: 'bar', hero: 'split', about: 'split', quotes: 'cards', contact: 'form' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'grand', profile: 'hotel',
    name: { ar: 'الفندق الكبير', en: 'Grand' },
    blurb: { ar: 'كحلي ليلي وذهب، صورة بعرض الشاشة وأحرف رومانية كبيرة.', en: 'Midnight navy and gold, a full-screen photo and Roman capitals.' },
    scheme: 'dark',
    palette: { bg: '#101A2B', surface: '#16233A', ink: '#F1E9D8', muted: '#A9A291', accent: '#C9A45C', accent2: '#8C6D3B', line: '#2B3A55', onAccent: '#101A2B' },
    fonts: { display: 'cinzel', body: 'cormorant-garamond', displayAr: 'el-messiri', bodyAr: 'amiri' },
    layout: { nav: 'split', hero: 'fullbleed', about: 'split', offer: 'zigzag', gallery: 'masonry', contact: 'card', footer: 'big' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'conservatoire', profile: 'music',
    name: { ar: 'كونسرفتوار', en: 'Conservatoire' },
    blurb: { ar: 'رقّ قديم بلون الدم الغامق وخط رقعة، مدرسة موسيقى ككونسرفتوار عريق: الدروس في بطاقات مؤطرة وكلمة المدير في أعمدة.', en: 'Old parchment, oxblood and Ruqaa script, a music school like a venerable conservatoire: lessons in framed cards and the director\'s word in columns.' },
    scheme: 'light',
    palette: { bg: '#F2EBDD', surface: '#FAF5EA', ink: '#2B2620', muted: '#6A6155', accent: '#6B1E1E', accent2: '#2F4A3A', line: '#D6CAB3', onAccent: '#FBF4E6' },
    fonts: { display: 'playfair-display', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'split', about: 'columns', offer: 'cards', quotes: 'cards' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'atelier', profile: 'gallery',
    name: { ar: 'أتيليه', en: 'Atelier' },
    blurb: { ar: 'فحمي وكريمي وأخضر مريمية، دار فنون بصورة عريضة تحت عنوان متمركز وكل معرض في بطاقة هادئة.', en: 'Charcoal, cream and sage, an art house with a wide photo under a centred title and each exhibition in a quiet card.' },
    scheme: 'light',
    palette: { bg: '#F4F1EA', surface: '#FFFFFF', ink: '#23211F', muted: '#6E6A62', accent: '#23211F', accent2: '#8A9A7B', line: '#DAD5CA', onAccent: '#F4F1EA' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'mirza', bodyAr: 'amiri' },
    layout: { hero: 'centered', about: 'split', offer: 'cards', extra: 'list', footer: 'simple' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'patisserie', profile: 'sweets',
    name: { ar: 'حلواني', en: 'Patisserie' },
    blurb: { ar: 'وردي باهت وفستقي وكاكاو، إطار أنيق حول العنوان كواجهة محل فرنسي.', en: 'Blush, pistachio and cocoa, an elegant frame around the title like a French shopfront.' },
    scheme: 'light',
    palette: { bg: '#F8EFEA', surface: '#FFF9F6', ink: '#3A2621', muted: '#7C6158', accent: '#A3485A', accent2: '#8DA36F', line: '#E7D5CC', onAccent: '#FFF6F2' },
    fonts: { display: 'libre-caslon-display', body: 'libre-caslon-text', displayAr: 'amiri', bodyAr: 'markazi-text' },
    layout: { offer: 'cards', contact: 'card' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'vellum', profile: 'wedding',
    name: { ar: 'رَقّ', en: 'Vellum' },
    blurb: { ar: 'عاجي وأخضر غامق وذهبي خافت، كبطاقة دعوة مطبوعة بالحروف: إطار مزدوج وفواصل زهرية وجدول اليوم بخط مذيّل.', en: 'Ivory, deep green and soft gold, like a letterpress invitation: a double frame, fleurons and the day\'s programme set in serif.' },
    scheme: 'light',
    palette: { bg: '#F7F2E8', surface: '#FFFDF8', ink: '#2B2320', muted: '#6E6258', accent: '#24483E', accent2: '#B8975A', line: '#E3D9C6', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'eb-garamond', displayAr: 'aref-ruqaa', bodyAr: 'scheherazade-new' },
    layout: { nav: 'center', schedule: 'timeline', contact: 'center' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'rosewater', profile: 'florist',
    name: { ar: 'ماء الورد', en: 'Rosewater' },
    blurb: { ar: 'ورق دافئ وبرقوقي عميق، عناوين بودوني عالية التباين، والباقات في بطاقات مؤطرة كزهور مجففة في ألبوم قديم.', en: 'Warm paper and deep plum, high-contrast Bodoni headings, and the bouquets in framed cards like pressed flowers in an old album.' },
    scheme: 'light',
    palette: { bg: '#F4EFE6', surface: '#FBF8F2', ink: '#2A211C', muted: '#6B5E52', accent: '#5B1A2E', accent2: '#B39B6B', line: '#E2D7C5', onAccent: '#FFFFFF' },
    fonts: { display: 'bodoni-moda', body: 'source-serif-4', displayAr: 'el-messiri', bodyAr: 'scheherazade-new' },
    layout: { hero: 'split', about: 'split', offer: 'cards', gallery: 'gallery' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'mariner', profile: 'dive',
    name: { ar: 'بحّار', en: 'Mariner' },
    blurb: { ar: 'كحلي وذهبي على عاجي، مركز غوص بروح بحرية: صورة بانورامية تحت عنوان متمركز، والدورات صفوف متناوبة كدفتر سفينة.', en: 'Navy and gold on ivory, a dive centre with a nautical air: a panoramic photo under a centred headline and courses in alternating rows like a ship\'s log.' },
    scheme: 'light',
    palette: { bg: '#F6F3EC', surface: '#FFFFFF', ink: '#1E2430', muted: '#5E6470', accent: '#1D3557', accent2: '#A8894F', line: '#DFD8C8', onAccent: '#FFFFFF' },
    fonts: { display: 'marcellus', body: 'source-serif-4', displayAr: 'el-messiri', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'centered', about: 'columns', offer: 'zigzag', extra: 'list' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'salon', profile: 'bookshop',
    name: { ar: 'صالون', en: 'Salon' },
    blurb: { ar: 'بنّي القهوة وذهبي، مكتبة كصالون أدبي قديم: العناوين في قائمة منقّطة، كلمة قارئ واحدة في كل مرة، وإطار رفيع حول كل صورة.', en: 'Coffee brown and gold, a bookshop like an old literary salon: titles in a dotted list, one reader\'s word at a time and a hairline frame around every photo.' },
    scheme: 'dark',
    palette: { bg: '#1B1612', surface: '#251E19', ink: '#F1E8DA', muted: '#B5A693', accent: '#C9A45C', accent2: '#9C4A3C', line: '#3A2F27', onAccent: '#1B1612' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'amiri', bodyAr: 'scheherazade-new' },
    layout: { offer: 'menu', quotes: 'single', contact: 'card', gallery: 'gallery' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'remedy', profile: 'vet',
    name: { ar: 'عافية', en: 'Remedy' },
    blurb: { ar: 'أخضر هادئ وذهبي على ورق بارد، كعيادة طبيب بيطري ريفي قديمة: نص واضح، خطوات مرقّمة للزيارة الأولى، وآراء في بطاقات.', en: 'Quiet green and gold on cool paper, like an old country vet\'s practice: clear text, numbered steps for the first visit and reviews in cards.' },
    scheme: 'light',
    palette: { bg: '#F5F6F2', surface: '#FFFFFF', ink: '#1F2A2A', muted: '#5B6866', accent: '#2F5D50', accent2: '#B08D57', line: '#DCE0D8', onAccent: '#FFFFFF' },
    fonts: { display: 'newsreader', body: 'source-serif-4', displayAr: 'markazi-text', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'split', pricing: 'table', quotes: 'cards' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'coachwork', profile: 'garage',
    name: { ar: 'هيكل', en: 'Coachwork' },
    blurb: { ar: 'بنّي داكن وعاجي وحروف سِنزل المنقوشة، ورشة سيارات كلاسيكية كصانع هياكل قديم: السيارات المرمّمة في جدار متفاوت وكل خدمة ببطاقة مؤطرة.', en: 'Dark brown, ivory and chiselled Cinzel capitals, a classic-car workshop like an old coachbuilder: restored cars on a mixed wall and each service in a framed card.' },
    scheme: 'light',
    palette: { bg: '#F3EFE7', surface: '#FFFFFF', ink: '#24201C', muted: '#6A635A', accent: '#4A2C2A', accent2: '#A68A64', line: '#DDD4C4', onAccent: '#FFFFFF' },
    fonts: { display: 'cinzel', body: 'eb-garamond', displayAr: 'lateef', bodyAr: 'amiri' },
    layout: { gallery: 'masonry', pricing: 'pricing', contact: 'center' },
    decor: ['divider-fleuron'],
  },
];
