import type { DesignInput } from './input';

export const classic: DesignInput[] = [
  {
    slug: 'andalus', profile: 'restaurant',
    name: { ar: 'أندلس', en: 'Andalus' },
    blurb: { ar: 'عاجي وعنابي وذهب خافت، قائمة طعام بنقاط موصولة وزخارف صغيرة.', en: 'Ivory, burgundy and muted gold, a dotted-leader menu and small ornaments.' },
    scheme: 'light',
    palette: { bg: '#F5EFE3', surface: '#FBF7EE', ink: '#2A1D17', muted: '#6F5E50', accent: '#7A1F2B', accent2: '#A88A55', line: '#DCCDB4', onAccent: '#FFF8EC' },
    fonts: { display: 'cormorant-garamond', body: 'eb-garamond', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'oxford', profile: 'law',
    name: { ar: 'أكسفورد', en: 'Oxford' },
    blurb: { ar: 'كحلي على ورق كريمي، قائمة مرقّمة رصينة ونموذج تواصل هادئ.', en: 'Navy on cream paper, a sober numbered list and a quiet contact form.' },
    scheme: 'light',
    palette: { bg: '#F7F4EC', surface: '#FFFFFF', ink: '#14213D', muted: '#5B6478', accent: '#1D3557', accent2: '#B08D57', line: '#D9D3C3', onAccent: '#F7F4EC' },
    fonts: { display: 'libre-baskerville', body: 'source-serif-4', displayAr: 'amiri', bodyAr: 'scheherazade-new' },
    layout: { nav: 'bar', hero: 'split', about: 'split', quotes: 'cards', contact: 'form' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'grand', profile: 'hotel',
    name: { ar: 'الفندق الكبير', en: 'Grand' },
    blurb: { ar: 'كحلي ليلي وذهب، صورة بعرض الشاشة وأحرف رومانية كبيرة.', en: 'Midnight navy and gold, a full-screen photo and Roman capitals.' },
    scheme: 'dark',
    palette: { bg: '#101A2B', surface: '#16233A', ink: '#F1E9D8', muted: '#A9A291', accent: '#C9A45C', accent2: '#8C6D3B', line: '#2B3A55', onAccent: '#101A2B' },
    fonts: { display: 'cinzel', body: 'cormorant-garamond', displayAr: 'el-messiri', bodyAr: 'amiri' },
    layout: { nav: 'split', hero: 'fullbleed', about: 'split', offer: 'zigzag', gallery: 'masonry', contact: 'card', footer: 'big' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'lyceum', profile: 'academy',
    name: { ar: 'ليسيوم', en: 'Lyceum' },
    blurb: { ar: 'رقّ قديم بلون الدم الغامق وخط رقعة، كأنه منشور جامعي عريق.', en: 'Old parchment, oxblood and Ruqaa script, like a venerable university prospectus.' },
    scheme: 'light',
    palette: { bg: '#F2EBDD', surface: '#FAF5EA', ink: '#2B2620', muted: '#6A6155', accent: '#6B1E1E', accent2: '#2F4A3A', line: '#D6CAB3', onAccent: '#FBF4E6' },
    fonts: { display: 'playfair-display', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'split', about: 'columns', offer: 'cards', quotes: 'cards' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'atelier', profile: 'boutique',
    name: { ar: 'أتيليه', en: 'Atelier' },
    blurb: { ar: 'فحمي وكريمي وأخضر مريمية، صورة عريضة تحت عنوان متمركز.', en: 'Charcoal, cream and sage, a wide photo under a centred title.' },
    scheme: 'light',
    palette: { bg: '#F4F1EA', surface: '#FFFFFF', ink: '#23211F', muted: '#6E6A62', accent: '#23211F', accent2: '#8A9A7B', line: '#DAD5CA', onAccent: '#F4F1EA' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'mirza', bodyAr: 'amiri' },
    layout: { hero: 'centered', about: 'split', offer: 'cards', extra: 'list', footer: 'simple' },
    decor: ['divider-fleuron'],
  },
  {
    slug: 'patisserie', profile: 'sweets',
    name: { ar: 'حلواني', en: 'Patisserie' },
    blurb: { ar: 'وردي باهت وفستقي وكاكاو، إطار أنيق حول العنوان كواجهة محل فرنسي.', en: 'Blush, pistachio and cocoa, an elegant frame around the title like a French shopfront.' },
    scheme: 'light',
    palette: { bg: '#F8EFEA', surface: '#FFF9F6', ink: '#3A2621', muted: '#7C6158', accent: '#A3485A', accent2: '#8DA36F', line: '#E7D5CC', onAccent: '#FFF6F2' },
    fonts: { display: 'libre-caslon-display', body: 'libre-caslon-text', displayAr: 'amiri', bodyAr: 'markazi-text' },
    layout: { offer: 'cards', contact: 'card' },
    decor: ['divider-fleuron'],
  },
];
