import type { DesignInput } from './input';

// Clay: puffy pastel shapes with inner and outer shadows, very round corners
// and bouncy motion. The kit builds the clay from the palette.
export const clay: DesignInput[] = [
  {
    slug: 'playdough', profile: 'academy',
    name: { ar: 'صلصال', en: 'Playdough' },
    blurb: { ar: 'خوخي وسماوي وليلكي، حروف وأرقام صلصالية منتفخة لروضة تتعلّم باللعب.', en: 'Peach, sky and lilac, puffy clay letters and numbers for a kindergarten that learns through play.' },
    scheme: 'light',
    palette: { bg: '#FBEFEA', surface: '#FFF8F4', ink: '#3B2A55', muted: '#6E5F84', accent: '#7C5CE0', accent2: '#FDBCB4', line: '#F1DCD3', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'baloo-bhaijaan-2', bodyAr: 'baloo-bhaijaan-2' },
    decor: ['blobs'],
  },
  {
    slug: 'posy', profile: 'florist',
    name: { ar: 'باقة صغيرة', en: 'Posy' },
    blurb: { ar: 'وردي فراولة ونعناعي وليموني، محل زهور تنتفخ بطاقاته كبتلات طرية، مع تركيب من الباقات.', en: 'Strawberry pink, mint and lemon, a florist whose cards puff up like soft petals, with a collage of bouquets.' },
    scheme: 'light',
    palette: { bg: '#FFF0F4', surface: '#FFFAFC', ink: '#4A1A33', muted: '#7D5266', accent: '#E8437A', accent2: '#B9F3C4', line: '#F7D6E2', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'lemonada', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'collage' },
    decor: ['blobs', 'sparkles'],
  },
  {
    slug: 'buddy', profile: 'app',
    name: { ar: 'رفيق', en: 'Buddy' },
    blurb: { ar: 'ليلكي وأصفر زبدة، هاتف صلصالي وأيقونات منتفخة لتطبيق ودود.', en: 'Lilac and butter yellow, a clay phone and puffy icons for a friendly app.' },
    scheme: 'light',
    palette: { bg: '#EFEAFF', surface: '#FAF8FF', ink: '#2A2150', muted: '#5F5786', accent: '#6A4CE0', accent2: '#FFE08A', line: '#DCD3F7', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro' },
    layout: { hero: 'device' },
    decor: ['blobs'],
  },
  {
    slug: 'brush-time', profile: 'clinic',
    name: { ar: 'ابتسامة', en: 'Brush time' },
    blurb: { ar: 'سماوي فاتح ونعناعي وأبيض، عيادة أسنان أطفال لا تخيف أحدًا.', en: 'Light sky, mint and white, a children\'s dental clinic that scares nobody.' },
    scheme: 'light',
    palette: { bg: '#EAF6FB', surface: '#F8FDFF', ink: '#173A4A', muted: '#4D6B78', accent: '#1B8DB5', accent2: '#A8EBD3', line: '#CFE7F0', onAccent: '#FFFFFF' },
    fonts: { display: 'nunito', body: 'nunito', displayAr: 'baloo-bhaijaan-2', bodyAr: 'tajawal' },
    layout: { contact: 'card' },
  },
  {
    slug: 'barnyard-clay', profile: 'farm',
    name: { ar: 'حظيرة', en: 'Barnyard' },
    blurb: { ar: 'أخضر عشبي وأحمر حظيرة وأصفر قش، مزرعة كلعبة صلصال للعائلة.', en: 'Grass green, barn red and straw yellow, a farm like a clay toy set for the family.' },
    scheme: 'light',
    palette: { bg: '#F0F7E6', surface: '#FBFEF6', ink: '#2C3A1C', muted: '#5D6B4B', accent: '#C9473A', accent2: '#F4D66B', line: '#DCE9C8', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { hero: 'split', gallery: 'gallery' },
    decor: ['blobs'],
  },
  {
    slug: 'squish', profile: 'gym',
    name: { ar: 'مرونة', en: 'Squish' },
    blurb: { ar: 'مرجاني وأزرق فاتح، صالة يوغا وبيلاتس ناعمة كالكرة المطاطية.', en: 'Coral and pale blue, a yoga and pilates studio as soft as an exercise ball.' },
    scheme: 'light',
    palette: { bg: '#FFF1EC', surface: '#FFFAF7', ink: '#3A2420', muted: '#735A54', accent: '#E9604A', accent2: '#BFD9FF', line: '#F5D9D0', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'outfit', displayAr: 'baloo-bhaijaan-2', bodyAr: 'readex-pro' },
    layout: { pricing: 'pricing' },
  },
  {
    slug: 'marshmallow', profile: 'cafe',
    name: { ar: 'خطمي', en: 'Marshmallow' },
    blurb: { ar: 'كاكاو فاتح ووردي خطمي، مقهى شوكولاتة ساخنة دافئ ومنتفخ.', en: 'Light cocoa and marshmallow pink, a warm, puffy hot-chocolate café.' },
    scheme: 'light',
    palette: { bg: '#F7EDE6', surface: '#FFF9F5', ink: '#3E2A20', muted: '#735D50', accent: '#8A5236', accent2: '#F7C6D3', line: '#ECDCD1', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'arch', offer: 'menu' },
    decor: ['blobs'],
  },
  {
    slug: 'party', profile: 'wedding',
    name: { ar: 'حفلة', en: 'Party' },
    blurb: { ar: 'ليلكي ونعناعي وذهبي فاتح، منظم حفلات بطاقاته كبالونات منتفخة.', en: 'Lilac, mint and pale gold, a party planner whose cards look like puffy balloons.' },
    scheme: 'light',
    palette: { bg: '#F4EEFB', surface: '#FCFAFF', ink: '#35264A', muted: '#6A5B7E', accent: '#9257C9', accent2: '#B8F0DA', line: '#E3D9F0', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'lemonada', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'centered' },
    decor: ['blobs', 'confetti'],
  },
  {
    slug: 'meetup', profile: 'conference',
    name: { ar: 'لقاء', en: 'Meetup' },
    blurb: { ar: 'أزرق سماوي وبرتقالي مشمشي، ملتقى طلابي ودود بشارات وبطاقات منتفخة.', en: 'Sky blue and apricot orange, a friendly student meetup with puffy badges and cards.' },
    scheme: 'light',
    palette: { bg: '#EAF3FF', surface: '#F8FBFF', ink: '#1B2C4D', muted: '#52627F', accent: '#2F6FE0', accent2: '#FFC59A', line: '#D2E1F7', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'dm-sans', displayAr: 'baloo-bhaijaan-2', bodyAr: 'readex-pro' },
    layout: { schedule: 'timeline' },
  },
  {
    slug: 'training-wheels', profile: 'bikes',
    name: { ar: 'عجلات التدريب', en: 'Training Wheels' },
    blurb: { ar: 'أصفر زبدة وأحمر كرزي وسماوي، محل دراجات للأطفال كأن رفوفه من الصلصال.', en: 'Butter yellow, cherry red and sky, a bike shop for children whose shelves look moulded from clay.' },
    scheme: 'light',
    palette: { bg: '#FFF7E3', surface: '#FFFDF6', ink: '#3A2A12', muted: '#6E5E44', accent: '#D8404F', accent2: '#A6DBF5', line: '#F2E5C2', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'reem-kufi-fun', bodyAr: 'tajawal' },
    layout: { gallery: 'masonry' },
    decor: ['blobs', 'sparkles'],
  },
  {
    slug: 'camp', profile: 'trails',
    name: { ar: 'مخيّم', en: 'Camp' },
    blurb: { ar: 'أخضر نعناعي وبرتقالي غروب، نادي مشي بخيام وبطاقات منتفخة، لعائلات تمشي أول درب لها.', en: 'Mint green and sunset orange, a hiking club with puffy tents and cards, for families walking their first trail.' },
    scheme: 'light',
    palette: { bg: '#EAF7F0', surface: '#F7FDF9', ink: '#183A2B', muted: '#4D6B5D', accent: '#E8743B', accent2: '#9EDFC0', line: '#D0EADD', onAccent: '#1A0B03' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'baloo-bhaijaan-2', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'fullbleed' },
  },
  {
    slug: 'pawprint', profile: 'vet',
    name: { ar: 'أثر مخلب', en: 'Pawprint' },
    blurb: { ar: 'بندوري وأصفر وأخضر خيار، عيادة بيطرية ودودة تبدو بطاقات خدماتها كألعاب صلصال طرية.', en: 'Tomato, yellow and cucumber green, a friendly vet clinic whose service cards look like soft clay toys.' },
    scheme: 'light',
    palette: { bg: '#FFF3E6', surface: '#FFFCF7', ink: '#3B2414', muted: '#715A48', accent: '#E04E2E', accent2: '#BDE38A', line: '#F3DFC8', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { offer: 'menu', hero: 'split' },
  },
];
