import type { DesignInput } from './input';

export const conventional: DesignInput[] = [
  {
    slug: 'corporate', profile: 'construction',
    name: { ar: 'مؤسسي', en: 'Corporate' },
    blurb: { ar: 'كحلي وبرتقالي وشريط معلومات علوي، موقع شركة واضح يعرف الزائر طريقه فيه فورًا.', en: 'Navy, orange and a top info bar, a clear company site every visitor finds their way around at once.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F6F9', ink: '#13294B', muted: '#5C6B82', accent: '#E07A1F', accent2: '#13294B', line: '#E1E6ED', onAccent: '#FFFFFF' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'cairo', bodyAr: 'cairo' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'care', profile: 'clinic',
    name: { ar: 'رعاية', en: 'Care' },
    blurb: { ar: 'أزرق طبي وأخضر مائي وأيقونات في دوائر، موقع عيادة مألوف ومريح.', en: 'Medical blue, aqua green and icons in circles, a familiar and reassuring clinic site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F8FB', ink: '#0B3B5C', muted: '#5A7487', accent: '#1689C2', accent2: '#2BB3A3', line: '#DCEAF2', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'lexend', displayAr: 'almarai', bodyAr: 'almarai' },
    layout: { hero: 'split' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'counsel', profile: 'law',
    name: { ar: 'استشارة', en: 'Counsel' },
    blurb: { ar: 'أخضر داكن وذهبي وعناوين مذيّلة، موقع مكتب محاماة تقليدي موثوق.', en: 'Dark green, gold and serif headings, a trustworthy traditional law-firm site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F4F0', ink: '#1F2A24', muted: '#5E6863', accent: '#1F4D3A', accent2: '#B08D4A', line: '#E3E1DA', onAccent: '#FFFFFF' },
    fonts: { display: 'libre-baskerville', body: 'inter', displayAr: 'amiri', bodyAr: 'cairo' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'estate', profile: 'realestate',
    name: { ar: 'عقار', en: 'Estate' },
    blurb: { ar: 'أزرق وأصفر وبطاقات عقارات بظلال خفيفة، موقع وسيط عقاري كلاسيكي.', en: 'Blue, yellow and lightly shadowed listing cards, a classic estate-agent site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F3F6FA', ink: '#0F2742', muted: '#5B6C80', accent: '#1E6FD9', accent2: '#F5A623', line: '#E0E7F0', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'plus-jakarta-sans', displayAr: 'tajawal', bodyAr: 'tajawal' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'institute', profile: 'academy',
    name: { ar: 'معهد', en: 'Institute' },
    blurb: { ar: 'عنابي وذهبي وبطاقات دورات واضحة، موقع معهد تدريب مألوف.', en: 'Maroon, gold and clear course cards, a familiar training-institute site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F8F5F2', ink: '#3B1220', muted: '#6E5A60', accent: '#8E1B3A', accent2: '#E3A72F', line: '#EBE3DD', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-sans', body: 'dm-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'split' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'services', profile: 'signage',
    name: { ar: 'خدمات', en: 'Services' },
    blurb: { ar: 'أحمر وفحمي وصورة رئيسية كبيرة وخدمات بأيقونات، موقع ورشة أو شركة خدمات.', en: 'Red, charcoal, a big hero photo and icon services, a site for a workshop or service company.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F5F5', ink: '#1D1D1F', muted: '#5F6368', accent: '#D32F2F', accent2: '#1D1D1F', line: '#E6E6E6', onAccent: '#FFFFFF' },
    fonts: { display: 'oswald', body: 'inter', displayAr: 'cairo', bodyAr: 'cairo' },
    decor: ['topbar', 'whatsapp', 'icons'],
  },
  {
    slug: 'family-table', profile: 'restaurant',
    name: { ar: 'مائدة العائلة', en: 'Family Table' },
    blurb: { ar: 'أبيض وأحمر وأصفر خردلي، مطعم عائلي واضح لكل الأعمار: شريط علوي بالهاتف، صورة كاملة، قائمة مرتبة، وزر واتساب.', en: 'White, red and mustard, a clear family restaurant for every age: a top bar with the phone, a full-screen photo, a tidy menu and a WhatsApp button.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F7F5F2', ink: '#1F1A17', muted: '#5E5650', accent: '#B3261E', accent2: '#E09F00', line: '#E8E2DC', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { offer: 'menu', gallery: 'gallery' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'business-stay', profile: 'hotel',
    name: { ar: 'إقامة عمل', en: 'Business Stay' },
    blurb: { ar: 'كحلي وكهرماني على أبيض، فندق لرجال وسيدات الأعمال: شريط علوي، صورة بجانب العنوان، خدمات بأيقونات، وحجز سريع.', en: 'Navy and amber on white, a hotel for business travellers: a top bar, a photo beside the headline, services with icons and quick booking.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F7FA', ink: '#14213D', muted: '#52607A', accent: '#FCA311', accent2: '#14213D', line: '#E3E8EF', onAccent: '#14213D' },
    fonts: { display: 'inter', body: 'inter', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'cards', extra: 'cards', gallery: 'gallery' },
    decor: ['topbar', 'whatsapp', 'icons'],
  },
  {
    slug: 'it-solutions', profile: 'software',
    name: { ar: 'حلول تقنية', en: 'IT Solutions' },
    blurb: { ar: 'أزرق مؤسسي وأخضر، شركة تقنية للشركات: شريط علوي، صورة كاملة بطبقة داكنة، خدمات بأيقونات، وباقات وأسئلة.', en: 'Corporate blue and green, a technology company for businesses: a top bar, a full-screen photo with a dark layer, services with icons, plans and an FAQ.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F3F6FB', ink: '#0F1E36', muted: '#4B5B73', accent: '#0A66C2', accent2: '#1C8A5A', line: '#DFE6F0', onAccent: '#FFFFFF' },
    fonts: { display: 'ibm-plex-sans', body: 'ibm-plex-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'cards' },
    decor: ['topbar', 'whatsapp', 'icons'],
  },
  {
    slug: 'fitness-center', profile: 'gym',
    name: { ar: 'مركز اللياقة', en: 'Fitness Center' },
    blurb: { ar: 'أبيض وبرتقالي وكحلي، مركز لياقة للحي: شريط علوي، صورة كاملة، برامج في بطاقات، جدول حصص، وباقات اشتراك.', en: 'White, orange and navy, a neighbourhood fitness centre: a top bar, a full-screen photo, programmes in cards, a class table and membership plans.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F5F5', ink: '#1A1A1A', muted: '#5C5C5C', accent: '#D45500', accent2: '#1B263B', line: '#E5E5E5', onAccent: '#FFFFFF' },
    fonts: { display: 'archivo', body: 'inter', displayAr: 'cairo', bodyAr: 'cairo' },
    layout: { offer: 'cards', schedule: 'table' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'co-op', profile: 'farm',
    name: { ar: 'تعاونية', en: 'Co-op' },
    blurb: { ar: 'أبيض وأخضر زراعي وأصفر قمحي، جمعية زراعية واضحة: شريط علوي، صورة بجانب العنوان، منتجات بأيقونات، وخطوات الطلب.', en: 'White, farm green and wheat yellow, a straightforward farming co-op: a top bar, a photo beside the headline, produce with icons and ordering steps.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F7F2', ink: '#1C2B1E', muted: '#55645A', accent: '#2E7D32', accent2: '#F9A825', line: '#E2E8E0', onAccent: '#FFFFFF' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'almarai', bodyAr: 'almarai' },
    layout: { hero: 'split', offer: 'cards', process: 'steps' },
    decor: ['topbar', 'whatsapp', 'icons'],
  },
  {
    slug: 'growth', profile: 'agency',
    name: { ar: 'نموّ', en: 'Growth' },
    blurb: { ar: 'أبيض وبنفسجي وبرتقالي، وكالة تسويق تشرح بوضوح: شريط علوي، صورة كاملة، خدمات بأيقونات، أعمال، وخطوات العمل.', en: 'White, purple and orange, a marketing agency that explains clearly: a top bar, a full-screen photo, services with icons, work and the steps of a project.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F3FF', ink: '#1E1B39', muted: '#5A5775', accent: '#5B3CC4', accent2: '#FF8A00', line: '#E6E3F3', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'plus-jakarta-sans', displayAr: 'cairo', bodyAr: 'cairo' },
    layout: { offer: 'cards', gallery: 'gallery', process: 'steps' },
    decor: ['topbar', 'whatsapp', 'icons'],
  },
];
