import type { DesignInput } from './input';

export const conventional: DesignInput[] = [
  {
    slug: 'corporate', profile: 'construction',
    name: { ar: 'مؤسسي', en: 'Corporate' },
    blurb: { ar: 'كحلي وبرتقالي وشريط معلومات علوي، موقع شركة واضح يعرف الزائر طريقه فيه فورًا.', en: 'Navy, orange and a top info bar, a clear company site every visitor finds their way around at once.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F6F9', ink: '#13294B', muted: '#5C6B82', accent: '#E07A1F', accent2: '#13294B', line: '#E1E6ED', onAccent: '#FFFFFF' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'cairo', bodyAr: 'cairo' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'care', profile: 'clinic',
    name: { ar: 'رعاية', en: 'Care' },
    blurb: { ar: 'أزرق طبي وأخضر مائي وأيقونات في دوائر، موقع عيادة مألوف ومريح.', en: 'Medical blue, aqua green and icons in circles, a familiar and reassuring clinic site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F8FB', ink: '#0B3B5C', muted: '#5A7487', accent: '#1689C2', accent2: '#2BB3A3', line: '#DCEAF2', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'lexend', displayAr: 'almarai', bodyAr: 'almarai' },
    layout: { hero: 'split' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'counsel', profile: 'law',
    name: { ar: 'استشارة', en: 'Counsel' },
    blurb: { ar: 'أخضر داكن وذهبي وعناوين مذيّلة، موقع مكتب محاماة تقليدي موثوق.', en: 'Dark green, gold and serif headings, a trustworthy traditional law-firm site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F4F0', ink: '#1F2A24', muted: '#5E6863', accent: '#1F4D3A', accent2: '#B08D4A', line: '#E3E1DA', onAccent: '#FFFFFF' },
    fonts: { display: 'libre-baskerville', body: 'inter', displayAr: 'amiri', bodyAr: 'cairo' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'estate', profile: 'realestate',
    name: { ar: 'عقار', en: 'Estate' },
    blurb: { ar: 'أزرق وأصفر وبطاقات عقارات بظلال خفيفة، موقع وسيط عقاري كلاسيكي.', en: 'Blue, yellow and lightly shadowed listing cards, a classic estate-agent site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F3F6FA', ink: '#0F2742', muted: '#5B6C80', accent: '#1E6FD9', accent2: '#F5A623', line: '#E0E7F0', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'plus-jakarta-sans', displayAr: 'tajawal', bodyAr: 'tajawal' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'institute', profile: 'academy',
    name: { ar: 'معهد', en: 'Institute' },
    blurb: { ar: 'عنابي وذهبي وبطاقات دورات واضحة، موقع معهد تدريب مألوف.', en: 'Maroon, gold and clear course cards, a familiar training-institute site.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F8F5F2', ink: '#3B1220', muted: '#6E5A60', accent: '#8E1B3A', accent2: '#E3A72F', line: '#EBE3DD', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-sans', body: 'dm-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'split' },
    decor: ['topbar', 'whatsapp'],
  },
  {
    slug: 'services', profile: 'signage',
    name: { ar: 'خدمات', en: 'Services' },
    blurb: { ar: 'أحمر وفحمي وصورة رئيسية كبيرة وخدمات بأيقونات، موقع ورشة أو شركة خدمات.', en: 'Red, charcoal, a big hero photo and icon services, a site for a workshop or service company.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F5F5', ink: '#1D1D1F', muted: '#5F6368', accent: '#D32F2F', accent2: '#1D1D1F', line: '#E6E6E6', onAccent: '#FFFFFF' },
    fonts: { display: 'oswald', body: 'inter', displayAr: 'cairo', bodyAr: 'cairo' },
    decor: ['topbar', 'whatsapp', 'icons'],
  },
];
