import type { DesignInput } from './input';

export const digital: DesignInput[] = [
  {
    slug: 'terminal', profile: 'software',
    name: { ar: 'طرفية', en: 'Terminal' },
    blurb: { ar: 'أخضر على الأسود وخط برمجي، نص يُكتب أمامك ونافذة طرفية.', en: 'Green on black in a coding font, text typed before your eyes and a terminal window.' },
    scheme: 'dark',
    palette: { bg: '#05070A', surface: '#0B1016', ink: '#D7FFE4', muted: '#7FA58C', accent: '#22F59A', accent2: '#2EC5FF', line: '#163525', onAccent: '#04140B' },
    fonts: { display: 'jetbrains-mono', body: 'ibm-plex-sans', displayAr: 'changa', bodyAr: 'ibm-plex-sans-arabic', accent: 'jetbrains-mono' },
    decor: ['grid', 'scanlines', 'typing'],
  },
  {
    slug: 'cyber', profile: 'conference',
    name: { ar: 'سايبر', en: 'Cyber' },
    blurb: { ar: 'أرجواني وسماوي متوهجان وزوايا تحديد، كواجهة لعبة خيال علمي.', en: 'Glowing magenta and cyan with targeting brackets, like a sci-fi game interface.' },
    scheme: 'dark',
    palette: { bg: '#07030F', surface: '#120A22', ink: '#F2E9FF', muted: '#A898C7', accent: '#FF2BD6', accent2: '#2BF3FF', line: '#2A1A47', onAccent: '#07030F' },
    fonts: { display: 'orbitron', body: 'chakra-petch', displayAr: 'handjet', bodyAr: 'readex-pro', accent: 'chakra-petch' },
    layout: { hero: 'centered', contact: 'center', footer: 'big' },
    decor: ['grid', 'scanlines', 'glow'],
  },
  {
    slug: 'metric', profile: 'app',
    name: { ar: 'مقياس', en: 'Metric' },
    blurb: { ar: 'كحلي ليلي وأزرق كهربائي ولوحة بيانات، كمنتج برمجي جاد.', en: 'Night navy, electric blue and a data dashboard, like a serious software product.' },
    scheme: 'dark',
    palette: { bg: '#0A0F1E', surface: '#111A2E', ink: '#E6ECFF', muted: '#8E9BC0', accent: '#4F7CFF', accent2: '#2DD4BF', line: '#1C2742', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'inter', displayAr: 'readex-pro', bodyAr: 'readex-pro', accent: 'ibm-plex-mono' },
    layout: { hero: 'device', offer: 'bento', contact: 'center' },
    decor: ['grid', 'icons', 'glow'],
  },
  {
    slug: 'pixel', profile: 'academy',
    name: { ar: 'بكسل', en: 'Pixel' },
    blurb: { ar: 'خطوط بكسلية وأصفر ألعاب قديمة وحدود متدرجة، لأكاديمية برمجة شابة.', en: 'Pixel type, arcade yellow and stepped borders, for a young coding academy.' },
    scheme: 'dark',
    palette: { bg: '#0E0E1A', surface: '#17172B', ink: '#F4F4FF', muted: '#A3A3C2', accent: '#FFD23F', accent2: '#3DDC97', line: '#2C2C4A', onAccent: '#0E0E1A' },
    fonts: { display: 'silkscreen', body: 'space-mono', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic', accent: 'silkscreen' },
    layout: { contact: 'form' },
    decor: ['scanlines', 'pixel'],
  },
  {
    slug: 'blueprint', profile: 'construction',
    name: { ar: 'مخطط', en: 'Blueprint' },
    blurb: { ar: 'أزرق المخططات الهندسية وخطوط بيضاء رفيعة، والصور كأنها مطبوعة على الورق الأزرق.', en: 'Engineering blueprint blue with fine white lines, and photos that look printed on cyanotype.' },
    scheme: 'dark',
    palette: { bg: '#0D3B66', surface: '#114677', ink: '#E8F1FF', muted: '#A9C3E3', accent: '#FFFFFF', accent2: '#F4D35E', line: '#3A6EA5', onAccent: '#0D3B66' },
    fonts: { display: 'space-mono', body: 'ibm-plex-sans', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic', accent: 'space-mono' },
    layout: { offer: 'table', contact: 'form' },
    decor: ['grid', 'blueprint'],
  },
  {
    slug: 'neon', profile: 'signage',
    name: { ar: 'نيون', en: 'Neon' },
    blurb: { ar: 'عنوان يتوهج كأنبوب نيون وردي على جدار ليلي، لورشة لافتات مضيئة.', en: 'A headline that glows like a pink neon tube on a night wall, for a sign workshop.' },
    scheme: 'dark',
    palette: { bg: '#0A0710', surface: '#140E1F', ink: '#FFF5FB', muted: '#B8A9C4', accent: '#FF3EA5', accent2: '#3EF0FF', line: '#2A1E38', onAccent: '#0A0710' },
    fonts: { display: 'audiowide', body: 'dm-sans', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'centered', footer: 'big' },
    decor: ['glow', 'neon'],
  },
  {
    slug: 'render', profile: 'agency',
    name: { ar: 'تصيير', en: 'Render' },
    blurb: { ar: 'أسود الشاشة ونعناعي نيون وبنفسجي، استوديو رقمي: سطر يُكتب أمامك، شبكة بينتو للخدمات، وجدار أعمال متوهّج.', en: 'Screen black, neon mint and violet, a digital studio: a line typing itself, a bento grid of services and a glowing wall of work.' },
    scheme: 'dark',
    palette: { bg: '#05060A', surface: '#0D0F17', ink: '#E9EDF7', muted: '#8E97AE', accent: '#7CFFCB', accent2: '#A855F7', line: '#1A1E2B', onAccent: '#05060A' },
    fonts: { display: 'space-grotesk', body: 'ibm-plex-sans', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic', accent: 'ibm-plex-mono' },
    layout: { hero: 'centered', offer: 'bento', gallery: 'masonry' },
    decor: ['grid', 'glow', 'typing'],
  },
  {
    slug: 'telemetry', profile: 'gym',
    name: { ar: 'قياس', en: 'Telemetry' },
    blurb: { ar: 'رمادي فحمي وسماوي ووردي، صالة ذكية تقرأ أرقامك: خطوط مسح خافتة، جدول الحصص، وباقات كلوحة بيانات.', en: 'Charcoal, cyan and pink, a smart gym that reads your numbers: faint scan lines, the class schedule and plans like a dashboard.' },
    scheme: 'dark',
    palette: { bg: '#080B0F', surface: '#10151C', ink: '#EAF2FA', muted: '#8D9AAB', accent: '#00E5FF', accent2: '#FF3D7F', line: '#1B232E', onAccent: '#080B0F' },
    fonts: { display: 'chakra-petch', body: 'inter', displayAr: 'changa', bodyAr: 'readex-pro', accent: 'jetbrains-mono' },
    layout: { schedule: 'table', offer: 'cards' },
    decor: ['grid', 'scanlines', 'glow'],
  },
  {
    slug: 'vitals', profile: 'clinic',
    name: { ar: 'مؤشرات', en: 'Vitals' },
    blurb: { ar: 'أبيض بارد وأزرق رقمي وأخضر طبي، عيادة تحجز أونلاين: شبكة دقيقة، أيقونات واضحة، وأسعار في جدول كالفاتورة.', en: 'Cool white, digital blue and medical green, a clinic you book online: a fine grid, clear icons and prices in a table like a statement.' },
    scheme: 'light',
    palette: { bg: '#F4F8FB', surface: '#FFFFFF', ink: '#0E1B2A', muted: '#4F5F72', accent: '#0066FF', accent2: '#00A383', line: '#DDE6EF', onAccent: '#FFFFFF' },
    fonts: { display: 'ibm-plex-sans', body: 'ibm-plex-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic', accent: 'ibm-plex-mono' },
    layout: { process: 'steps', pricing: 'table', contact: 'form' },
    decor: ['grid', 'icons'],
  },
  {
    slug: 'floorplan', profile: 'realestate',
    name: { ar: 'مخطط', en: 'Floorplan' },
    blurb: { ar: 'غرافيت وكهرماني وسماوي وخطوط مخطط هندسي، عقارات تُقرأ كالمخططات: صورة كاملة وأرقام بخط أحادي.', en: 'Graphite, amber and sky blue with drafting lines, property read like plans: a full-screen photo and figures in a monospace face.' },
    scheme: 'dark',
    palette: { bg: '#0F1115', surface: '#171A21', ink: '#ECEFF4', muted: '#9097A3', accent: '#FFB000', accent2: '#4CC9F0', line: '#232733', onAccent: '#0F1115' },
    fonts: { display: 'rajdhani', body: 'inter', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic', accent: 'space-mono' },
    layout: { hero: 'fullbleed', offer: 'cards', extra: 'list', contact: 'split' },
    decor: ['grid', 'blueprint'],
  },
  {
    slug: 'byte', profile: 'cafe',
    name: { ar: 'بايت', en: 'Byte' },
    blurb: { ar: 'بنفسجي ليلي وكهرماني وخط برمجي، مقهى للألعاب والعمل: عنوان يُكتب حرفًا حرفًا، قائمة واضحة، وتوهج خافت.', en: 'Night purple, amber and a coding face, a café for gaming and work: a headline typed letter by letter, a clear menu and a soft glow.' },
    scheme: 'dark',
    palette: { bg: '#0D0718', surface: '#160D26', ink: '#F1EAFF', muted: '#A596C2', accent: '#FFA62B', accent2: '#6C63FF', line: '#2A1D40', onAccent: '#0D0718' },
    fonts: { display: 'jetbrains-mono', body: 'dm-sans', displayAr: 'handjet', bodyAr: 'tajawal' },
    layout: { hero: 'centered', offer: 'menu', gallery: 'bento' },
    decor: ['scanlines', 'glow', 'typing'],
  },
  {
    slug: 'resolution', profile: 'photographer',
    name: { ar: 'دقّة', en: 'Resolution' },
    blurb: { ar: 'أسود وأحمر تسجيل وأخضر، مصوّر بعين رقمية: بيانات الصورة بخط أحادي، جدار أعمال، وباقات في جدول.', en: 'Black, record red and green, a photographer with a digital eye: shot data in a monospace face, a wall of work and packages in a table.' },
    scheme: 'dark',
    palette: { bg: '#0A0A0A', surface: '#141414', ink: '#F5F5F5', muted: '#9E9E9E', accent: '#FF3B30', accent2: '#34C759', line: '#222222', onAccent: '#FFFFFF' },
    fonts: { display: 'ibm-plex-mono', body: 'ibm-plex-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic', accent: 'ibm-plex-mono' },
    layout: { gallery: 'masonry', pricing: 'table', quotes: 'single' },
    decor: ['grid', 'scanlines'],
  },
];
