import type { DesignInput } from './input';

export const digital: DesignInput[] = [
  {
    slug: 'terminal', profile: 'software',
    name: { ar: 'طرفية', en: 'Terminal' },
    blurb: { ar: 'أخضر على الأسود وخط برمجي، نص يُكتب أمامك ونافذة طرفية.', en: 'Green on black in a coding font, text typed before your eyes and a terminal window.' },
    scheme: 'dark',
    palette: { bg: '#05070A', surface: '#0B1016', ink: '#D7FFE4', muted: '#7FA58C', accent: '#22F59A', accent2: '#2EC5FF', line: '#163525', onAccent: '#04140B' },
    fonts: { display: 'jetbrains-mono', body: 'ibm-plex-sans', displayAr: 'changa', bodyAr: 'ibm-plex-sans-arabic', accent: 'jetbrains-mono' },
    decor: ['grid', 'scanlines', 'typing'],
  },
  {
    slug: 'cyber', profile: 'conference',
    name: { ar: 'سايبر', en: 'Cyber' },
    blurb: { ar: 'أرجواني وسماوي متوهجان وزوايا تحديد، كواجهة لعبة خيال علمي.', en: 'Glowing magenta and cyan with targeting brackets, like a sci-fi game interface.' },
    scheme: 'dark',
    palette: { bg: '#07030F', surface: '#120A22', ink: '#F2E9FF', muted: '#A898C7', accent: '#FF2BD6', accent2: '#2BF3FF', line: '#2A1A47', onAccent: '#07030F' },
    fonts: { display: 'orbitron', body: 'chakra-petch', displayAr: 'handjet', bodyAr: 'readex-pro', accent: 'chakra-petch' },
    layout: { hero: 'centered', contact: 'center', footer: 'big' },
    decor: ['grid', 'scanlines', 'glow'],
  },
  {
    slug: 'metric', profile: 'app',
    name: { ar: 'مقياس', en: 'Metric' },
    blurb: { ar: 'كحلي ليلي وأزرق كهربائي ولوحة بيانات، كمنتج برمجي جاد.', en: 'Night navy, electric blue and a data dashboard, like a serious software product.' },
    scheme: 'dark',
    palette: { bg: '#0A0F1E', surface: '#111A2E', ink: '#E6ECFF', muted: '#8E9BC0', accent: '#4F7CFF', accent2: '#2DD4BF', line: '#1C2742', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'inter', displayAr: 'readex-pro', bodyAr: 'readex-pro', accent: 'ibm-plex-mono' },
    layout: { hero: 'device', offer: 'bento', contact: 'center' },
    decor: ['grid', 'icons', 'glow'],
  },
  {
    slug: 'pixel', profile: 'academy',
    name: { ar: 'بكسل', en: 'Pixel' },
    blurb: { ar: 'خطوط بكسلية وأصفر ألعاب قديمة وحدود متدرجة، لأكاديمية برمجة شابة.', en: 'Pixel type, arcade yellow and stepped borders, for a young coding academy.' },
    scheme: 'dark',
    palette: { bg: '#0E0E1A', surface: '#17172B', ink: '#F4F4FF', muted: '#A3A3C2', accent: '#FFD23F', accent2: '#3DDC97', line: '#2C2C4A', onAccent: '#0E0E1A' },
    fonts: { display: 'silkscreen', body: 'space-mono', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic', accent: 'silkscreen' },
    layout: { contact: 'form' },
    decor: ['scanlines', 'pixel'],
  },
  {
    slug: 'blueprint', profile: 'construction',
    name: { ar: 'مخطط', en: 'Blueprint' },
    blurb: { ar: 'أزرق المخططات الهندسية وخطوط بيضاء رفيعة، والصور كأنها مطبوعة على الورق الأزرق.', en: 'Engineering blueprint blue with fine white lines, and photos that look printed on cyanotype.' },
    scheme: 'dark',
    palette: { bg: '#0D3B66', surface: '#114677', ink: '#E8F1FF', muted: '#A9C3E3', accent: '#FFFFFF', accent2: '#F4D35E', line: '#3A6EA5', onAccent: '#0D3B66' },
    fonts: { display: 'space-mono', body: 'ibm-plex-sans', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic', accent: 'space-mono' },
    layout: { offer: 'table', contact: 'form' },
    decor: ['grid', 'blueprint'],
  },
  {
    slug: 'neon', profile: 'signage',
    name: { ar: 'نيون', en: 'Neon' },
    blurb: { ar: 'عنوان يتوهج كأنبوب نيون وردي على جدار ليلي، لورشة لافتات مضيئة.', en: 'A headline that glows like a pink neon tube on a night wall, for a sign workshop.' },
    scheme: 'dark',
    palette: { bg: '#0A0710', surface: '#140E1F', ink: '#FFF5FB', muted: '#B8A9C4', accent: '#FF3EA5', accent2: '#3EF0FF', line: '#2A1E38', onAccent: '#0A0710' },
    fonts: { display: 'audiowide', body: 'dm-sans', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'centered', footer: 'big' },
    decor: ['glow', 'neon'],
  },
];
