import type { DesignInput } from './input';

export const editorial: DesignInput[] = [
  {
    slug: 'daily', profile: 'restaurant',
    name: { ar: 'اليومية', en: 'The Daily' },
    blurb: { ar: 'مطعم يقدّم نفسه كصفحة جريدة: ترويسة وأعمدة وقائمة طعام كأخبار اليوم.', en: 'A restaurant presented as a newspaper page: masthead, columns and a menu set like the day\'s news.' },
    scheme: 'light',
    palette: { bg: '#F4F1EA', surface: '#EBE6DB', ink: '#141414', muted: '#5C5A55', accent: '#C0261C', accent2: '#141414', line: '#CFC9BC', onAccent: '#FFFFFF' },
    fonts: { display: 'playfair-display', body: 'source-serif-4', displayAr: 'markazi-text', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu' },
    decor: ['mono'],
  },
  {
    slug: 'issue', profile: 'agency',
    name: { ar: 'العدد ٧', en: 'Issue 07' },
    blurb: { ar: 'استوديو تصميم كأنه مجلة فنية: عناوين ضخمة وبرتقالي واحد ومساحات بيضاء.', en: 'A design studio as an art magazine: huge headlines, one orange and white space.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F2F0', ink: '#0D0D0D', muted: '#6B6B66', accent: '#FF4F00', accent2: '#0D0D0D', line: '#DADAD5', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'newsreader', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'list', process: 'list' },
  },
  {
    slug: 'column', profile: 'law',
    name: { ar: 'عمود', en: 'Column' },
    blurb: { ar: 'مكتب محاماة بلغة الصحف الرصينة: أعمدة نص وخطوط فاصلة وأحمر داكن.', en: 'A law firm in the language of serious papers: text columns, rules and a dark red.' },
    scheme: 'light',
    palette: { bg: '#F7F5EF', surface: '#EEEAE0', ink: '#1A1A1A', muted: '#5F5D57', accent: '#7A1E1E', accent2: '#1A1A1A', line: '#D3CEC2', onAccent: '#FFFFFF' },
    fonts: { display: 'newsreader', body: 'newsreader', displayAr: 'noto-naskh-arabic', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'list', process: 'list' },
  },
  {
    slug: 'review', profile: 'photographer',
    name: { ar: 'مراجعة', en: 'Review' },
    blurb: { ar: 'مجلة تصوير داكنة: صور بالأبيض والأسود وعناوين رفيعة ولمسة حمراء.', en: 'A dark photography magazine: black-and-white pictures, fine headlines and a touch of red.' },
    scheme: 'dark',
    palette: { bg: '#111111', surface: '#1A1A1A', ink: '#F2F2F2', muted: '#9B9B9B', accent: '#E5383B', accent2: '#F2F2F2', line: '#2E2E2E', onAccent: '#FFFFFF' },
    fonts: { display: 'instrument-serif', body: 'inter', displayAr: 'markazi-text', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { pricing: 'table' },
    decor: ['mono'],
  },
  {
    slug: 'broadsheet', profile: 'conference',
    name: { ar: 'صحيفة', en: 'Broadsheet' },
    blurb: { ar: 'مؤتمر بإخراج صحيفة كبيرة: برنامج كجدول أخبار وأزرق واحد.', en: 'A conference laid out like a broadsheet: an agenda like a news table and a single blue.' },
    scheme: 'light',
    palette: { bg: '#F2EFE6', surface: '#E8E3D6', ink: '#111111', muted: '#5A574F', accent: '#0047AB', accent2: '#111111', line: '#C9C2B1', onAccent: '#FFFFFF' },
    fonts: { display: 'libre-caslon-display', body: 'libre-caslon-text', displayAr: 'amiri', bodyAr: 'amiri' },
    layout: { extra: 'cards', schedule: 'table' },
    decor: ['mono'],
  },
  {
    slug: 'folio', profile: 'boutique',
    name: { ar: 'فوليو', en: 'Folio' },
    blurb: { ar: 'متجر أزياء كمجلة موضة: خط ديدون أنيق وصور كبيرة وتعليقات صغيرة.', en: 'A fashion shop as a fashion magazine: an elegant Didone, big pictures and small captions.' },
    scheme: 'light',
    palette: { bg: '#FAF7F2', surface: '#F0EBE3', ink: '#1C1A17', muted: '#6E6860', accent: '#B4532A', accent2: '#1C1A17', line: '#DDD6CB', onAccent: '#FFFFFF' },
    fonts: { display: 'bodoni-moda', body: 'lora', displayAr: 'el-messiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'cards', extra: 'list' },
  },
];
