import type { DesignInput } from './input';

export const editorial: DesignInput[] = [
  {
    slug: 'daily', profile: 'restaurant',
    name: { ar: 'اليومية', en: 'The Daily' },
    blurb: { ar: 'مطعم يقدّم نفسه كصفحة جريدة: ترويسة وأعمدة وقائمة طعام كأخبار اليوم.', en: 'A restaurant presented as a newspaper page: masthead, columns and a menu set like the day\'s news.' },
    scheme: 'light',
    palette: { bg: '#F4F1EA', surface: '#EBE6DB', ink: '#141414', muted: '#5C5A55', accent: '#C0261C', accent2: '#141414', line: '#CFC9BC', onAccent: '#FFFFFF' },
    fonts: { display: 'playfair-display', body: 'source-serif-4', displayAr: 'markazi-text', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu' },
    decor: ['mono'],
  },
  {
    slug: 'issue', profile: 'agency',
    name: { ar: 'العدد ٧', en: 'Issue 07' },
    blurb: { ar: 'استوديو تصميم كأنه مجلة فنية: عناوين ضخمة وبرتقالي واحد ومساحات بيضاء.', en: 'A design studio as an art magazine: huge headlines, one orange and white space.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F2F0', ink: '#0D0D0D', muted: '#6B6B66', accent: '#FF4F00', accent2: '#0D0D0D', line: '#DADAD5', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'newsreader', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'list', process: 'list' },
  },
  {
    slug: 'column', profile: 'law',
    name: { ar: 'عمود', en: 'Column' },
    blurb: { ar: 'مكتب محاماة بلغة الصحف الرصينة: أعمدة نص وخطوط فاصلة وأحمر داكن.', en: 'A law firm in the language of serious papers: text columns, rules and a dark red.' },
    scheme: 'light',
    palette: { bg: '#F7F5EF', surface: '#EEEAE0', ink: '#1A1A1A', muted: '#5F5D57', accent: '#7A1E1E', accent2: '#1A1A1A', line: '#D3CEC2', onAccent: '#FFFFFF' },
    fonts: { display: 'newsreader', body: 'newsreader', displayAr: 'noto-naskh-arabic', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'list', process: 'list' },
  },
  {
    slug: 'review', profile: 'photographer',
    name: { ar: 'مراجعة', en: 'Review' },
    blurb: { ar: 'مجلة تصوير داكنة: صور بالأبيض والأسود وعناوين رفيعة ولمسة حمراء.', en: 'A dark photography magazine: black-and-white pictures, fine headlines and a touch of red.' },
    scheme: 'dark',
    palette: { bg: '#111111', surface: '#1A1A1A', ink: '#F2F2F2', muted: '#9B9B9B', accent: '#E5383B', accent2: '#F2F2F2', line: '#2E2E2E', onAccent: '#FFFFFF' },
    fonts: { display: 'instrument-serif', body: 'inter', displayAr: 'markazi-text', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { pricing: 'table' },
    decor: ['mono'],
  },
  {
    slug: 'broadsheet', profile: 'conference',
    name: { ar: 'صحيفة', en: 'Broadsheet' },
    blurb: { ar: 'مؤتمر بإخراج صحيفة كبيرة: برنامج كجدول أخبار وأزرق واحد.', en: 'A conference laid out like a broadsheet: an agenda like a news table and a single blue.' },
    scheme: 'light',
    palette: { bg: '#F2EFE6', surface: '#E8E3D6', ink: '#111111', muted: '#5A574F', accent: '#0047AB', accent2: '#111111', line: '#C9C2B1', onAccent: '#FFFFFF' },
    fonts: { display: 'libre-caslon-display', body: 'libre-caslon-text', displayAr: 'amiri', bodyAr: 'amiri' },
    layout: { extra: 'cards', schedule: 'table' },
    decor: ['mono'],
  },
  {
    slug: 'folio', profile: 'boutique',
    name: { ar: 'فوليو', en: 'Folio' },
    blurb: { ar: 'متجر أزياء كمجلة موضة: خط ديدون أنيق وصور كبيرة وتعليقات صغيرة.', en: 'A fashion shop as a fashion magazine: an elegant Didone, big pictures and small captions.' },
    scheme: 'light',
    palette: { bg: '#FAF7F2', surface: '#F0EBE3', ink: '#1C1A17', muted: '#6E6860', accent: '#B4532A', accent2: '#1C1A17', line: '#DDD6CB', onAccent: '#FFFFFF' },
    fonts: { display: 'bodoni-moda', body: 'lora', displayAr: 'el-messiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'cards', extra: 'list' },
  },
  {
    slug: 'travelogue', profile: 'hotel',
    name: { ar: 'رحلات', en: 'Travelogue' },
    blurb: { ar: 'ورق مجلة سفر وأزرق بحري وأحمر طوبي، غلاف بعنوان ضخم فوق خط فاصل، الغرف كقائمة مرقّمة، وصور في جدار.', en: 'Travel-magazine paper, sea blue and brick red, a cover with a huge headline over a rule, rooms as a numbered list and photos on a wall.' },
    scheme: 'light',
    palette: { bg: '#F5F2EA', surface: '#FFFFFF', ink: '#1E1B16', muted: '#6A645A', accent: '#1F5A7A', accent2: '#C24E2A', line: '#E0DACD', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-serif-display', body: 'source-serif-4', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { gallery: 'masonry' },
    decor: ['mono'],
  },
  {
    slug: 'supplement', profile: 'realestate',
    name: { ar: 'ملحق', en: 'Supplement' },
    blurb: { ar: 'أبيض الصحيفة وأحمر وكحلي، ملحق العقارات الأسبوعي: عناوين بودوني، العروض في قائمة كالإعلانات المبوّبة.', en: 'Newsprint white, red and navy, the weekly property supplement: Bodoni headlines and listings in a list like classified ads.' },
    scheme: 'light',
    palette: { bg: '#FAFAF8', surface: '#FFFFFF', ink: '#121212', muted: '#5E5E5A', accent: '#C8102E', accent2: '#1F3A5F', line: '#E3E3DE', onAccent: '#FFFFFF' },
    fonts: { display: 'bodoni-moda', body: 'newsreader', displayAr: 'reem-kufi', bodyAr: 'noto-naskh-arabic' },
    layout: { extra: 'cards' },
    decor: ['mono'],
  },
  {
    slug: 'journal', profile: 'academy',
    name: { ar: 'دورية', en: 'Journal' },
    blurb: { ar: 'ورق مجلة علمية وحبر أخضر وأحمر، أكاديمية تكتب كمحرّر: أعمدة نصية، دورات وخطوات في قوائم، وأسعار في جدول.', en: 'Journal paper, green and red ink, an academy that writes like an editor: text in columns, courses and steps in lists, prices in a table.' },
    scheme: 'light',
    palette: { bg: '#F3F0E8', surface: '#FBF9F4', ink: '#222018', muted: '#646058', accent: '#3A5A40', accent2: '#A4462E', line: '#DDD7C9', onAccent: '#FFFFFF' },
    fonts: { display: 'eb-garamond', body: 'eb-garamond', displayAr: 'scheherazade-new', bodyAr: 'noto-naskh-arabic' },
    layout: { process: 'list', pricing: 'table' },
    decor: ['mono'],
  },
  {
    slug: 'cover-story', profile: 'perfume',
    name: { ar: 'قصة الغلاف', en: 'Cover Story' },
    blurb: { ar: 'وردي ورقي وأحمر وردي وذهبي، صفحات الجمال في مجلة أنيقة: عنوان بخط الرقعة، العطور في بطاقات، وصور في شبكة.', en: 'Paper pink, rose red and gold, the beauty pages of a fine magazine: a Ruqaa headline, perfumes in cards and photos in a grid.' },
    scheme: 'light',
    palette: { bg: '#FBF6F2', surface: '#FFFFFF', ink: '#2A1E22', muted: '#6F5F65', accent: '#9C2C4A', accent2: '#C9A27E', line: '#EADFD9', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'inter', displayAr: 'aref-ruqaa', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'cards', gallery: 'gallery' },
  },
  {
    slug: 'almanac', profile: 'farm',
    name: { ar: 'تقويم', en: 'Almanac' },
    blurb: { ar: 'ورق طيني وبنّي وأخضر حقلي، تقويم المزارع: المواسم في قائمة مرقّمة، خطوات الزرع كفهرس، وأرقام بخط أحادي.', en: 'Clay paper, brown and field green, the farmer\'s almanac: the seasons in a numbered list, the growing steps like an index and figures in monospace.' },
    scheme: 'light',
    palette: { bg: '#F2EFE4', surface: '#FAF8F1', ink: '#24261C', muted: '#5F6152', accent: '#6B4F1D', accent2: '#4C6A33', line: '#DCD8C6', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'lora', displayAr: 'markazi-text', bodyAr: 'noto-naskh-arabic' },
    layout: { process: 'list' },
    decor: ['mono'],
  },
  {
    slug: 'op-ed', profile: 'cafe',
    name: { ar: 'افتتاحية', en: 'Op-Ed' },
    blurb: { ar: 'ليل دافئ وطوبي وأخضر مريمية، مقهى يُقرأ كصفحة الرأي: عنوان كبير فوق خط، قائمة منقّطة، وصور في جدار.', en: 'A warm night, brick and sage, a café that reads like the opinion page: a big headline over a rule, a dotted menu and a wall of photos.' },
    scheme: 'dark',
    palette: { bg: '#15120F', surface: '#1E1A16', ink: '#F1EAE0', muted: '#ADA295', accent: '#E2725B', accent2: '#8FA889', line: '#2E2822', onAccent: '#15120F' },
    fonts: { display: 'playfair-display', body: 'source-serif-4', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu', extra: 'list', gallery: 'masonry' },
    decor: ['mono'],
  },
];
