import type { DesignInput } from './input';

export const geometric: DesignInput[] = [
  {
    slug: 'bauhaus', profile: 'academy',
    name: { ar: 'باوهاوس', en: 'Bauhaus' },
    blurb: { ar: 'أحمر وأصفر وأزرق وأسود، دوائر ومربعات ومثلثات كملصق من مدرسة باوهاوس.', en: 'Red, yellow, blue and black with circles, squares and triangles, like a Bauhaus school poster.' },
    scheme: 'light',
    palette: { bg: '#F3EFE6', surface: '#FFFFFF', ink: '#111111', muted: '#4A4A4A', accent: '#E63B2E', accent2: '#1D4ED8', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    decor: ['shapes'],
    css: 'html { --accent3: #F4C430; }',
  },
  {
    slug: 'swiss', profile: 'gallery',
    name: { ar: 'سويسري', en: 'Swiss' },
    blurb: { ar: 'أحمر وأسود على الأبيض وشبكة صارمة ومحاذاة واحدة، صالة عرض تعلّق معارضها كملصقات الأسلوب الدولي.', en: 'Red and black on white, a strict grid and one alignment, a gallery that hangs its exhibitions like International Style posters.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F2F2', ink: '#000000', muted: '#555555', accent: '#FF0000', accent2: '#000000', line: '#000000', onAccent: '#FFFFFF' },
    fonts: { display: 'work-sans', body: 'work-sans', displayAr: 'alexandria', bodyAr: 'noto-sans-arabic' },
    layout: { offer: 'list' },
    decor: ['grid'],
  },
  {
    slug: 'mondrian', profile: 'photographer',
    name: { ar: 'موندريان', en: 'Mondrian' },
    blurb: { ar: 'معرض صور داخل مستطيلات بخطوط سوداء سميكة وكتل لونية، تحية لموندريان.', en: 'A gallery inside rectangles with thick black lines and colour blocks, a nod to Mondrian.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F7F7F7', ink: '#111111', muted: '#555555', accent: '#D62828', accent2: '#1D3D9E', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'archivo', body: 'archivo', displayAr: 'cairo', bodyAr: 'cairo' },
    layout: { hero: 'split' },
    decor: ['mondrian'],
    css: 'html { --accent3: #F7C531; }',
  },
  {
    slug: 'module', profile: 'construction',
    name: { ar: 'وحدة', en: 'Module' },
    blurb: { ar: 'رمادي وبرتقالي وأزرق، وحدات بناء هندسية وشبكة ظاهرة لشركة مقاولات.', en: 'Grey, orange and blue, geometric building modules and a visible grid for a contractor.' },
    scheme: 'light',
    palette: { bg: '#ECEAE5', surface: '#FFFFFF', ink: '#1B1B1B', muted: '#555555', accent: '#F26B1D', accent2: '#2B59C3', line: '#1B1B1B', onAccent: '#FFFFFF' },
    fonts: { display: 'oswald', body: 'ibm-plex-sans', displayAr: 'noto-kufi-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'poster' },
    decor: ['shapes', 'grid'],
  },
  {
    slug: 'circle', profile: 'gym',
    name: { ar: 'دائرة', en: 'Circle' },
    blurb: { ar: 'أزرق قوي وبرتقالي وصورة داخل دائرة كبيرة، لنادٍ رياضي واثق.', en: 'Strong blue, orange and a photo inside a big circle, for a confident gym.' },
    scheme: 'light',
    palette: { bg: '#FFF9EF', surface: '#FFFFFF', ink: '#101010', muted: '#4A4A4A', accent: '#2B50E8', accent2: '#FF4F1F', line: '#101010', onAccent: '#FFFFFF' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'kufam', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'split', schedule: 'table' },
    decor: ['shapes', 'circle-img'],
  },
  {
    slug: 'block', profile: 'realestate',
    name: { ar: 'بلوك', en: 'Block' },
    blurb: { ar: 'أصفر وأخضر داكن وكتل لونية مستطيلة، لعقارات بطابع معماري حديث.', en: 'Yellow, dark green and rectangular colour blocks, for real estate with a modern architectural feel.' },
    scheme: 'light',
    palette: { bg: '#F6F4EF', surface: '#FFFFFF', ink: '#161616', muted: '#555555', accent: '#F4C430', accent2: '#2F5D50', line: '#161616', onAccent: '#161616' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    decor: ['shapes'],
  },
  {
    slug: 'chainring', profile: 'bikes',
    name: { ar: 'ترس السلسلة', en: 'Chainring' },
    blurb: { ar: 'ورق فاتح وأحمر وأزرق وأصفر، محل دراجات بشبكة باوهاوس: دوائر ومثلثات حول الصورة، قائمة أسعار مرتبة، وصور في شبكة.', en: 'Pale paper, red, blue and yellow, a bike shop on a Bauhaus grid: circles and triangles around the photo, an orderly price list and photos in a grid.' },
    scheme: 'light',
    palette: { bg: '#F5F1E8', surface: '#FFFFFF', ink: '#1A1A1A', muted: '#5F5B54', accent: '#E63B2E', accent2: '#1D4ED8', line: '#D9D3C7', onAccent: '#FFFFFF' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'beiruti', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'split', offer: 'menu', gallery: 'gallery' },
    decor: ['shapes'],
    css: 'html { --accent3: #F4C430; }',
  },
  {
    slug: 'quadrant', profile: 'cafe',
    name: { ar: 'ربع دائرة', en: 'Quadrant' },
    blurb: { ar: 'أبيض وأسود وبرتقالي، مقهى من مربعات وأرباع دوائر: عنوان ضخم بعرض الصفحة، قائمة واضحة، وصور في شبكة بينتو.', en: 'White, black and orange, a café of squares and quarter circles: a huge full-width headline, a clear menu and photos in a bento grid.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F4F4', ink: '#111111', muted: '#5A5A5A', accent: '#F26B1D', accent2: '#0F7B5F', line: '#E2E2E2', onAccent: '#111111' },
    fonts: { display: 'archivo', body: 'inter', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { offer: 'menu', gallery: 'bento' },
    decor: ['shapes', 'grid'],
  },
  {
    slug: 'vector', profile: 'software',
    name: { ar: 'متّجه', en: 'Vector' },
    blurb: { ar: 'رمادي فاتح وأزرق وأصفر وأحمر، شركة برمجيات بلغة الرسم الهندسي: شبكة دقيقة، أشكال أساسية، وباقات مرتبة.', en: 'Light grey, blue, yellow and red, a software company in the language of technical drawing: a fine grid, basic shapes and orderly plans.' },
    scheme: 'light',
    palette: { bg: '#F3F4F6', surface: '#FFFFFF', ink: '#0F172A', muted: '#4B5563', accent: '#2563EB', accent2: '#F59E0B', line: '#D1D5DB', onAccent: '#FFFFFF' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { offer: 'cards' },
    decor: ['grid', 'shapes'],
    css: 'html { --accent3: #EF4444; }',
  },
  {
    slug: 'corner', profile: 'cowork',
    name: { ar: 'زاوية', en: 'Corner' },
    blurb: { ar: 'كريمي وأحمر قانٍ وفيروزي، مساحة عمل بأشكال مقصوصة: صور في دوائر، عنوان عريض، والمساحات في بطاقات.', en: 'Cream, deep red and teal, a coworking space of cut shapes: photos in circles, a wide headline and the spaces in cards.' },
    scheme: 'light',
    palette: { bg: '#FFF9F0', surface: '#FFFFFF', ink: '#1E1B18', muted: '#625D56', accent: '#C81E36', accent2: '#1B998B', line: '#ECE4D8', onAccent: '#FFFFFF' },
    fonts: { display: 'unbounded', body: 'work-sans', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'split', offer: 'cards', extra: 'list' },
    decor: ['shapes', 'circle-img'],
  },
  {
    slug: 'axis', profile: 'conference',
    name: { ar: 'محور', en: 'Axis' },
    blurb: { ar: 'أبيض وأسود وبرتقالي أحمر وأزرق، مؤتمر على شبكة سويسرية: عنوان ضخم، متحدثون في بطاقات، وبرنامج في جدول.', en: 'White, black, red-orange and blue, a conference on a Swiss grid: a huge headline, speakers in cards and the programme in a table.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F5F5', ink: '#000000', muted: '#555555', accent: '#FF3C00', accent2: '#0047FF', line: '#DDDDDD', onAccent: '#000000' },
    fonts: { display: 'oswald', body: 'inter', displayAr: 'alexandria', bodyAr: 'noto-sans-arabic' },
    layout: { extra: 'cards', schedule: 'table' },
    decor: ['grid'],
  },
  {
    slug: 'primary', profile: 'signage',
    name: { ar: 'ألوان أساسية', en: 'Primary' },
    blurb: { ar: 'أزرق وأحمر وأصفر على ورق فاتح، ورشة لافتات بلغة موندريان: مستطيلات ملونة، عنوان كالملصق، وأعمال في شبكة.', en: 'Blue, red and yellow on pale paper, a sign workshop speaking Mondrian: coloured rectangles, a poster headline and work in a grid.' },
    scheme: 'light',
    palette: { bg: '#F7F3EA', surface: '#FFFFFF', ink: '#111111', muted: '#57534C', accent: '#1D4ED8', accent2: '#E63B2E', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'archivo', body: 'ibm-plex-sans', displayAr: 'cairo', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'poster', offer: 'cards', gallery: 'gallery', process: 'steps' },
    decor: ['mondrian'],
    css: 'html { --accent3: #F4C430; }',
  },
];
