import type { DesignInput } from './input';

export const geometric: DesignInput[] = [
  {
    slug: 'bauhaus', profile: 'academy',
    name: { ar: 'باوهاوس', en: 'Bauhaus' },
    blurb: { ar: 'أحمر وأصفر وأزرق وأسود، دوائر ومربعات ومثلثات كملصق من مدرسة باوهاوس.', en: 'Red, yellow, blue and black with circles, squares and triangles, like a Bauhaus school poster.' },
    scheme: 'light',
    palette: { bg: '#F3EFE6', surface: '#FFFFFF', ink: '#111111', muted: '#4A4A4A', accent: '#E63B2E', accent2: '#1D4ED8', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    decor: ['shapes'],
    css: 'html { --accent3: #F4C430; }',
  },
  {
    slug: 'swiss', profile: 'agency',
    name: { ar: 'سويسري', en: 'Swiss' },
    blurb: { ar: 'أحمر وأسود على الأبيض وشبكة صارمة ومحاذاة واحدة، الأسلوب الدولي بأنقى صوره.', en: 'Red and black on white, a strict grid and one alignment: the International Style at its purest.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F2F2F2', ink: '#000000', muted: '#555555', accent: '#FF0000', accent2: '#000000', line: '#000000', onAccent: '#FFFFFF' },
    fonts: { display: 'work-sans', body: 'work-sans', displayAr: 'alexandria', bodyAr: 'noto-sans-arabic' },
    layout: { offer: 'list' },
    decor: ['grid'],
  },
  {
    slug: 'mondrian', profile: 'photographer',
    name: { ar: 'موندريان', en: 'Mondrian' },
    blurb: { ar: 'معرض صور داخل مستطيلات بخطوط سوداء سميكة وكتل لونية، تحية لموندريان.', en: 'A gallery inside rectangles with thick black lines and colour blocks, a nod to Mondrian.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F7F7F7', ink: '#111111', muted: '#555555', accent: '#D62828', accent2: '#1D3D9E', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'archivo', body: 'archivo', displayAr: 'cairo', bodyAr: 'cairo' },
    layout: { hero: 'split' },
    decor: ['mondrian'],
    css: 'html { --accent3: #F7C531; }',
  },
  {
    slug: 'module', profile: 'construction',
    name: { ar: 'وحدة', en: 'Module' },
    blurb: { ar: 'رمادي وبرتقالي وأزرق، وحدات بناء هندسية وشبكة ظاهرة لشركة مقاولات.', en: 'Grey, orange and blue, geometric building modules and a visible grid for a contractor.' },
    scheme: 'light',
    palette: { bg: '#ECEAE5', surface: '#FFFFFF', ink: '#1B1B1B', muted: '#555555', accent: '#F26B1D', accent2: '#2B59C3', line: '#1B1B1B', onAccent: '#FFFFFF' },
    fonts: { display: 'oswald', body: 'ibm-plex-sans', displayAr: 'noto-kufi-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'poster' },
    decor: ['shapes', 'grid'],
  },
  {
    slug: 'circle', profile: 'gym',
    name: { ar: 'دائرة', en: 'Circle' },
    blurb: { ar: 'أزرق قوي وبرتقالي وصورة داخل دائرة كبيرة، لنادٍ رياضي واثق.', en: 'Strong blue, orange and a photo inside a big circle, for a confident gym.' },
    scheme: 'light',
    palette: { bg: '#FFF9EF', surface: '#FFFFFF', ink: '#101010', muted: '#4A4A4A', accent: '#2B50E8', accent2: '#FF4F1F', line: '#101010', onAccent: '#FFFFFF' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'kufam', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'split', schedule: 'table' },
    decor: ['shapes', 'circle-img'],
  },
  {
    slug: 'block', profile: 'realestate',
    name: { ar: 'بلوك', en: 'Block' },
    blurb: { ar: 'أصفر وأخضر داكن وكتل لونية مستطيلة، لعقارات بطابع معماري حديث.', en: 'Yellow, dark green and rectangular colour blocks, for real estate with a modern architectural feel.' },
    scheme: 'light',
    palette: { bg: '#F6F4EF', surface: '#FFFFFF', ink: '#161616', muted: '#555555', accent: '#F4C430', accent2: '#2F5D50', line: '#161616', onAccent: '#161616' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    decor: ['shapes'],
  },
];
