import type { DesignInput } from './input';

export const glass: DesignInput[] = [
  {
    slug: 'prism', profile: 'app',
    name: { ar: 'منشور', en: 'Prism' },
    blurb: { ar: 'بطاقات زجاجية فوق بنفسجي وسماوي متوهج، لتطبيق مالي حديث.', en: 'Glass cards over glowing violet and cyan, for a modern finance app.' },
    scheme: 'dark',
    palette: { bg: '#0B0A1F', surface: '#16143A', ink: '#F3F1FF', muted: '#A7A3CF', accent: '#8B5CF6', accent2: '#22D3EE', line: '#2B2860', onAccent: '#FFFFFF' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'readex-pro', bodyAr: 'readex-pro' },
    layout: { hero: 'device' },
    decor: ['blobs', 'icons'],
  },
  {
    slug: 'frost', profile: 'clinic',
    name: { ar: 'صقيع', en: 'Frost' },
    blurb: { ar: 'زجاج أبيض ضبابي وأزرق جليدي، عيادة تبدو نظيفة كالضوء.', en: 'Frosted white glass and icy blue, a clinic that feels as clean as light.' },
    scheme: 'light',
    palette: { bg: '#EEF4FA', surface: '#FFFFFF', ink: '#0E2238', muted: '#566A80', accent: '#2F80ED', accent2: '#7FD1E6', line: '#D5E2F0', onAccent: '#FFFFFF' },
    fonts: { display: 'urbanist', body: 'urbanist', displayAr: 'zain', bodyAr: 'zain' },
    decor: ['blobs', 'icons'],
  },
  {
    slug: 'nebula', profile: 'software',
    name: { ar: 'سديم', en: 'Nebula' },
    blurb: { ar: 'فضاء عميق تسبح فيه سحب وردية وزرقاء، وبطاقات من زجاج داكن.', en: 'Deep space with drifting pink and blue clouds, and dark glass cards.' },
    scheme: 'dark',
    palette: { bg: '#070512', surface: '#120C2A', ink: '#F0ECFF', muted: '#9C95C2', accent: '#F472B6', accent2: '#60A5FA', line: '#241B4D', onAccent: '#0B0716' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'bento' },
    decor: ['blobs', 'icons', 'grid'],
  },
  {
    slug: 'lagoon', profile: 'hotel',
    name: { ar: 'بحيرة', en: 'Lagoon' },
    blurb: { ar: 'ماء فيروزي ومرجان فاتح وزجاج فوق صورة البحر، لمنتجع هادئ.', en: 'Turquoise water, soft coral and glass over a sea photo, for a calm resort.' },
    scheme: 'light',
    palette: { bg: '#E8F6F5', surface: '#FFFFFF', ink: '#0B3B3C', muted: '#4A7473', accent: '#0E9594', accent2: '#F59E8B', line: '#CBE7E5', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { hero: 'fullbleed', offer: 'cards', cta: 'image' },
    decor: ['blobs'],
  },
  {
    slug: 'halo', profile: 'perfume',
    name: { ar: 'هالة', en: 'Halo' },
    blurb: { ar: 'خوخي ووردي ناعمان وتوهج دافئ، لعطور خفيفة عصرية.', en: 'Soft peach and pink with a warm glow, for light modern scents.' },
    scheme: 'light',
    palette: { bg: '#FBF0EE', surface: '#FFFFFF', ink: '#3A1F2B', muted: '#86626E', accent: '#D9506F', accent2: '#F6B38E', line: '#F1DAD6', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'split', offer: 'cards' },
    decor: ['blobs'],
  },
  {
    slug: 'orbit', profile: 'conference',
    name: { ar: 'مدار', en: 'Orbit' },
    blurb: { ar: 'ليل أزرق وبنفسجي وزجاج متوهج وعدّاد للأيام، لمؤتمر تقني كبير.', en: 'Blue-violet night, glowing glass and a day counter, for a big tech conference.' },
    scheme: 'dark',
    palette: { bg: '#050816', surface: '#0D1430', ink: '#EAF0FF', muted: '#93A1C9', accent: '#6D5DFC', accent2: '#FF7AC6', line: '#1B2550', onAccent: '#FFFFFF' },
    fonts: { display: 'syne', body: 'dm-sans', displayAr: 'kufam', bodyAr: 'readex-pro' },
    layout: { extra: 'cards' },
    decor: ['blobs', 'grid'],
  },
  {
    slug: 'mirage', profile: 'agency',
    name: { ar: 'سراب', en: 'Mirage' },
    blurb: { ar: 'كحلي ليلي وسماوي ووردي، ألواح زجاجية فوق أضواء تتحرك ببطء: عنوان في المنتصف، خدمات في شبكة بينتو، وأعمال في جدار.', en: 'Night navy, sky blue and pink, glass panels over slowly moving light: a centred headline, services in a bento grid and work on a wall.' },
    scheme: 'dark',
    palette: { bg: '#0A0F1F', surface: '#121A33', ink: '#EEF2FF', muted: '#9AA5C8', accent: '#38BDF8', accent2: '#F472B6', line: '#1E2A4A', onAccent: '#0A0F1F' },
    fonts: { display: 'plus-jakarta-sans', body: 'inter', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { gallery: 'masonry' },
    decor: ['blobs', 'grid'],
  },
  {
    slug: 'skylight', profile: 'realestate',
    name: { ar: 'منوَر', en: 'Skylight' },
    blurb: { ar: 'سماوي فاتح وأزرق وفيروزي، عقارات خلف زجاج مصقول: صورة كاملة، بطاقات شفافة للعروض، وتفاصيل في شبكة بينتو.', en: 'Pale sky, blue and teal, property behind frosted glass: a full-screen photo, translucent listing cards and details in a bento grid.' },
    scheme: 'light',
    palette: { bg: '#EEF3F8', surface: '#FFFFFF', ink: '#142233', muted: '#536477', accent: '#2563EB', accent2: '#14B8A6', line: '#D9E2EC', onAccent: '#FFFFFF' },
    fonts: { display: 'sora', body: 'dm-sans', displayAr: 'almarai', bodyAr: 'almarai' },
    layout: { hero: 'fullbleed', offer: 'cards', extra: 'bento' },
    decor: ['blobs'],
  },
  {
    slug: 'lumen', profile: 'academy',
    name: { ar: 'ضياء', en: 'Lumen' },
    blurb: { ar: 'خزامى فاتح وبنفسجي وسماوي، أكاديمية تحت ضوء ناعم: صورة بجانب العنوان، دورات في بطاقات زجاجية، وخطوات بأيقونات.', en: 'Pale lavender, violet and cyan, an academy in soft light: a photo beside the headline, courses in glass cards and steps with icons.' },
    scheme: 'light',
    palette: { bg: '#F3F1FF', surface: '#FFFFFF', ink: '#1E1838', muted: '#5E5880', accent: '#6D28D9', accent2: '#06B6D4', line: '#E2DEF7', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'split', offer: 'cards', process: 'steps' },
    decor: ['blobs', 'icons'],
  },
  {
    slug: 'opal', profile: 'wedding',
    name: { ar: 'لؤلؤ', en: 'Opal' },
    blurb: { ar: 'أبيض لؤلؤي ووردي وأزرق رمادي، دعوة عرس من زجاج ناعم: الاسمان بخط الرقعة، برنامج اليوم بخط زمني، وصور في جدار.', en: 'Pearl white, rose and grey-blue, a wedding invitation in soft glass: both names in Ruqaa, the day\'s programme as a timeline and photos on a wall.' },
    scheme: 'light',
    palette: { bg: '#F8F4F6', surface: '#FFFFFF', ink: '#2C2230', muted: '#6E6274', accent: '#A8737E', accent2: '#9DB4C0', line: '#EBE1E6', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'aref-ruqaa', bodyAr: 'readex-pro' },
    layout: { nav: 'pill', schedule: 'timeline', gallery: 'masonry' },
    decor: ['blobs'],
  },
  {
    slug: 'breathe', profile: 'gym',
    name: { ar: 'تنفّس', en: 'Breathe' },
    blurb: { ar: 'نعناعي فاتح وأخضر زمردي وكهرماني، استوديو يوغا وبيلاتس: صورة بجانب العنوان، حصص في جدول زجاجي، وباقات هادئة.', en: 'Pale mint, emerald and amber, a yoga and pilates studio: a photo beside the headline, classes in a glass table and calm plans.' },
    scheme: 'light',
    palette: { bg: '#EDF8F4', surface: '#FFFFFF', ink: '#12302A', muted: '#4F6B64', accent: '#0B8A6B', accent2: '#F59E0B', line: '#D6EBE4', onAccent: '#FFFFFF' },
    fonts: { display: 'urbanist', body: 'urbanist', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'cards', schedule: 'table' },
    decor: ['blobs'],
  },
  {
    slug: 'frappe', profile: 'cafe',
    name: { ar: 'فرابيه', en: 'Frappé' },
    blurb: { ar: 'كاكاو داكن وكهرماني وليلكي، مقهى خلف زجاج مضيء: عنوان في المنتصف، قائمة في لوح شفاف، وصور في شبكة بينتو.', en: 'Dark cocoa, amber and lilac, a café behind glowing glass: a centred headline, the menu on a translucent panel and photos in a bento grid.' },
    scheme: 'dark',
    palette: { bg: '#140D0A', surface: '#22160F', ink: '#F7EDE4', muted: '#BFA999', accent: '#F59E0B', accent2: '#A78BFA', line: '#33231A', onAccent: '#140D0A' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'menu', gallery: 'bento' },
    decor: ['blobs'],
  },
];
