import type { DesignInput } from './input';

export const glass: DesignInput[] = [
  {
    slug: 'prism', profile: 'app',
    name: { ar: 'منشور', en: 'Prism' },
    blurb: { ar: 'بطاقات زجاجية فوق بنفسجي وسماوي متوهج، لتطبيق مالي حديث.', en: 'Glass cards over glowing violet and cyan, for a modern finance app.' },
    scheme: 'dark',
    palette: { bg: '#0B0A1F', surface: '#16143A', ink: '#F3F1FF', muted: '#A7A3CF', accent: '#8B5CF6', accent2: '#22D3EE', line: '#2B2860', onAccent: '#FFFFFF' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'readex-pro', bodyAr: 'readex-pro' },
    layout: { hero: 'device' },
    decor: ['blobs', 'icons'],
  },
  {
    slug: 'frost', profile: 'clinic',
    name: { ar: 'صقيع', en: 'Frost' },
    blurb: { ar: 'زجاج أبيض ضبابي وأزرق جليدي، عيادة تبدو نظيفة كالضوء.', en: 'Frosted white glass and icy blue, a clinic that feels as clean as light.' },
    scheme: 'light',
    palette: { bg: '#EEF4FA', surface: '#FFFFFF', ink: '#0E2238', muted: '#566A80', accent: '#2F80ED', accent2: '#7FD1E6', line: '#D5E2F0', onAccent: '#FFFFFF' },
    fonts: { display: 'urbanist', body: 'urbanist', displayAr: 'zain', bodyAr: 'zain' },
    decor: ['blobs', 'icons'],
  },
  {
    slug: 'nebula', profile: 'software',
    name: { ar: 'سديم', en: 'Nebula' },
    blurb: { ar: 'فضاء عميق تسبح فيه سحب وردية وزرقاء، وبطاقات من زجاج داكن.', en: 'Deep space with drifting pink and blue clouds, and dark glass cards.' },
    scheme: 'dark',
    palette: { bg: '#070512', surface: '#120C2A', ink: '#F0ECFF', muted: '#9C95C2', accent: '#F472B6', accent2: '#60A5FA', line: '#241B4D', onAccent: '#0B0716' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'bento' },
    decor: ['blobs', 'icons', 'grid'],
  },
  {
    slug: 'lagoon', profile: 'hotel',
    name: { ar: 'بحيرة', en: 'Lagoon' },
    blurb: { ar: 'ماء فيروزي ومرجان فاتح وزجاج فوق صورة البحر، لمنتجع هادئ.', en: 'Turquoise water, soft coral and glass over a sea photo, for a calm resort.' },
    scheme: 'light',
    palette: { bg: '#E8F6F5', surface: '#FFFFFF', ink: '#0B3B3C', muted: '#4A7473', accent: '#0E9594', accent2: '#F59E8B', line: '#CBE7E5', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { hero: 'fullbleed', offer: 'cards', cta: 'image' },
    decor: ['blobs'],
  },
  {
    slug: 'halo', profile: 'perfume',
    name: { ar: 'هالة', en: 'Halo' },
    blurb: { ar: 'خوخي ووردي ناعمان وتوهج دافئ، لعطور خفيفة عصرية.', en: 'Soft peach and pink with a warm glow, for light modern scents.' },
    scheme: 'light',
    palette: { bg: '#FBF0EE', surface: '#FFFFFF', ink: '#3A1F2B', muted: '#86626E', accent: '#D9506F', accent2: '#F6B38E', line: '#F1DAD6', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'split', offer: 'cards' },
    decor: ['blobs'],
  },
  {
    slug: 'orbit', profile: 'conference',
    name: { ar: 'مدار', en: 'Orbit' },
    blurb: { ar: 'ليل أزرق وبنفسجي وزجاج متوهج وعدّاد للأيام، لمؤتمر تقني كبير.', en: 'Blue-violet night, glowing glass and a day counter, for a big tech conference.' },
    scheme: 'dark',
    palette: { bg: '#050816', surface: '#0D1430', ink: '#EAF0FF', muted: '#93A1C9', accent: '#6D5DFC', accent2: '#FF7AC6', line: '#1B2550', onAccent: '#FFFFFF' },
    fonts: { display: 'syne', body: 'dm-sans', displayAr: 'kufam', bodyAr: 'readex-pro' },
    layout: { extra: 'cards' },
    decor: ['blobs', 'grid'],
  },
];
