import type { DesignInput } from './input';

export const handdrawn: DesignInput[] = [
  {
    slug: 'notebook', profile: 'academy',
    name: { ar: 'دفتر', en: 'Notebook' },
    blurb: { ar: 'ورق دفتر مسطّر وحبر أزرق وشريط لاصق، كدفتر طالب نشيط.', en: 'Ruled notebook paper, blue ink and tape, like a keen student\'s notebook.' },
    scheme: 'light',
    palette: { bg: '#FDFBF5', surface: '#FFFFFF', ink: '#23395B', muted: '#5E6F8A', accent: '#E4572E', accent2: '#4CB944', line: '#23395B', onAccent: '#FFFFFF' },
    fonts: { display: 'patrick-hand', body: 'nunito', displayAr: 'playpen-sans-arabic', bodyAr: 'tajawal' },
    decor: ['notebook', 'tape', 'divider-scribble'],
  },
  {
    slug: 'sketch', profile: 'agency',
    name: { ar: 'سكتش', en: 'Sketch' },
    blurb: { ar: 'حدود مرسومة بقلم وأوراق لاصقة على ورق مربعات، لاستوديو يحب الأفكار الأولى.', en: 'Pen-drawn borders and sticky notes on graph paper, for a studio that loves first ideas.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#FAFAF7', ink: '#1A1A1A', muted: '#5C5C5C', accent: '#2D5BFF', accent2: '#FFCF33', line: '#1A1A1A', onAccent: '#FFFFFF' },
    fonts: { display: 'caveat', body: 'dm-sans', displayAr: 'vibes', bodyAr: 'readex-pro' },
    layout: { hero: 'collage', footer: 'simple' },
    decor: ['tape', 'divider-scribble', 'graph'],
  },
  {
    slug: 'chalk', profile: 'restaurant',
    name: { ar: 'طباشير', en: 'Chalk' },
    blurb: { ar: 'سبورة خضراء وطباشير أبيض وأصفر، وقائمة طعام مكتوبة باليد.', en: 'A green chalkboard in white and yellow chalk, with a handwritten menu.' },
    scheme: 'dark',
    palette: { bg: '#1F2D27', surface: '#26372F', ink: '#F4F1E8', muted: '#B9C2B8', accent: '#F7D774', accent2: '#F28B82', line: '#55675C', onAccent: '#1F2D27' },
    fonts: { display: 'kalam', body: 'kalam', displayAr: 'marhey', bodyAr: 'playpen-sans-arabic' },
    layout: { nav: 'center', hero: 'framed', offer: 'menu' },
    decor: ['chalk'],
  },
  {
    slug: 'scrapbook', profile: 'wedding',
    name: { ar: 'ألبوم', en: 'Scrapbook' },
    blurb: { ar: 'صور مثبتة بشريط لاصق وكتابة بخط اليد، كألبوم ذكريات لعروسين.', en: 'Taped-in photos and handwriting, like a couple\'s memory album.' },
    scheme: 'light',
    palette: { bg: '#FBF6EF', surface: '#FFFFFF', ink: '#3B2F2F', muted: '#7A6A6A', accent: '#D96C6C', accent2: '#8FB8A8', line: '#3B2F2F', onAccent: '#FFFFFF' },
    fonts: { display: 'gloria-hallelujah', body: 'nunito', displayAr: 'aref-ruqaa', bodyAr: 'tajawal' },
    layout: { nav: 'center', hero: 'collage' },
    decor: ['tape', 'divider-scribble'],
  },
  {
    slug: 'doodle', profile: 'app',
    name: { ar: 'خربشة', en: 'Doodle' },
    blurb: { ar: 'خطوط قلم عريض وألوان مرحة وهاتف مرسوم، لتطبيق ودود.', en: 'Thick marker lines, cheerful colours and a drawn phone, for a friendly app.' },
    scheme: 'light',
    palette: { bg: '#FFFDF7', surface: '#FFFFFF', ink: '#1E1E1E', muted: '#5A5A5A', accent: '#FF6B6B', accent2: '#4ECDC4', line: '#1E1E1E', onAccent: '#1E1E1E' },
    fonts: { display: 'permanent-marker', body: 'dm-sans', displayAr: 'lemonada', bodyAr: 'readex-pro' },
    layout: { hero: 'device', contact: 'center' },
    decor: ['graph', 'icons', 'divider-scribble'],
  },
  {
    slug: 'craft', profile: 'boutique',
    name: { ar: 'حِرفة', en: 'Craft' },
    blurb: { ar: 'ورق كرافت بني وأختام وخيوط، لمتجر مشغولات يدوية.', en: 'Brown kraft paper, stamps and string, for a handmade goods shop.' },
    scheme: 'light',
    palette: { bg: '#D9C3A0', surface: '#EADBC2', ink: '#2E2216', muted: '#5C4A36', accent: '#8B2E1E', accent2: '#2E4A3A', line: '#2E2216', onAccent: '#F4E9D6' },
    fonts: { display: 'patrick-hand', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    decor: ['tape', 'grain', 'stamp'],
  },
  {
    slug: 'sketchbook', profile: 'cafe',
    name: { ar: 'دفتر رسم', en: 'Sketchbook' },
    blurb: { ar: 'ورق أبيض وبرتقالي وأخضر، مقهى مرسوم في دفتر: صور ملصقة بشريط لاصق، قائمة بخط اليد، وخربشات بين الأقسام.', en: 'White paper, orange and green, a café drawn in a sketchbook: photos stuck down with tape, a handwritten menu and scribbles between sections.' },
    scheme: 'light',
    palette: { bg: '#FFFDF6', surface: '#FFFFFF', ink: '#2B2622', muted: '#6A625A', accent: '#D9603B', accent2: '#4C8C7A', line: '#ECE5D6', onAccent: '#FFFFFF' },
    fonts: { display: 'kalam', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { hero: 'collage', offer: 'menu', gallery: 'gallery' },
    decor: ['tape', 'divider-scribble'],
  },
  {
    slug: 'frosting', profile: 'sweets',
    name: { ar: 'كريمة', en: 'Frosting' },
    blurb: { ar: 'وردي فاتح وفوشي وأصفر، حلويات مرسومة بقلم ملون: عنوان بخط اليد، حلويات في بطاقات بشريط لاصق، وخطوات الطلب.', en: 'Light pink, fuchsia and yellow, sweets drawn in coloured pencil: a handwritten headline, sweets in taped cards and the ordering steps.' },
    scheme: 'light',
    palette: { bg: '#FFF7F2', surface: '#FFFFFF', ink: '#3B2025', muted: '#7B5D62', accent: '#E05780', accent2: '#F2B134', line: '#F3E2DA', onAccent: '#FFFFFF' },
    fonts: { display: 'gloria-hallelujah', body: 'nunito', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'cards', process: 'steps' },
    decor: ['tape', 'divider-scribble'],
  },
  {
    slug: 'garden-journal', profile: 'farm',
    name: { ar: 'دفتر الحديقة', en: 'Garden Journal' },
    blurb: { ar: 'ورق مسطّر وأخضر ورقي وبرتقالي، مزرعة تكتب يومياتها: خطوط الدفتر، منتجات في بطاقات، ومراحل الزرع بخط اليد.', en: 'Ruled paper, leaf green and orange, a farm keeping its diary: notebook lines, produce in cards and the growing stages in handwriting.' },
    scheme: 'light',
    palette: { bg: '#F7F5EC', surface: '#FFFFFF', ink: '#263224', muted: '#5C6956', accent: '#4F7A3A', accent2: '#D98E32', line: '#E4E4D5', onAccent: '#FFFFFF' },
    fonts: { display: 'patrick-hand', body: 'lora', displayAr: 'playpen-sans-arabic', bodyAr: 'readex-pro' },
    layout: { hero: 'split', offer: 'cards', process: 'steps' },
    decor: ['notebook', 'divider-scribble'],
  },
  {
    slug: 'kind-care', profile: 'clinic',
    name: { ar: 'رعاية لطيفة', en: 'Kind Care' },
    blurb: { ar: 'أبيض مزرق وأزرق وبرتقالي، عيادة تشرح بالرسم: ورق مربعات خفيف، أيقونات مرسومة، وأسئلة شائعة بلغة بسيطة.', en: 'Bluish white, blue and orange, a clinic that explains with drawings: light graph paper, drawn icons and an FAQ in plain words.' },
    scheme: 'light',
    palette: { bg: '#F5FAFF', surface: '#FFFFFF', ink: '#1D2F40', muted: '#536577', accent: '#3B78B4', accent2: '#F28C38', line: '#DCE7F2', onAccent: '#FFFFFF' },
    fonts: { display: 'caveat', body: 'nunito', displayAr: 'playpen-sans-arabic', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'cards', process: 'steps' },
    decor: ['graph', 'icons', 'divider-scribble'],
  },
  {
    slug: 'travel-journal', profile: 'hotel',
    name: { ar: 'يوميات سفر', en: 'Travel Journal' },
    blurb: { ar: 'ورق كرافت وأحمر طوبي وأزرق بحري، فندق في دفتر رحلات: صور ملصقة، عنوان بقلم عريض، وغرف في بطاقات.', en: 'Kraft paper, brick red and sea blue, a hotel in a travel diary: stuck-in photos, a thick-marker headline and rooms in cards.' },
    scheme: 'light',
    palette: { bg: '#F4EEE2', surface: '#FFFDF8', ink: '#2E261E', muted: '#6B5E50', accent: '#B5523B', accent2: '#3E7C8C', line: '#E2D7C4', onAccent: '#FFFFFF' },
    fonts: { display: 'permanent-marker', body: 'lora', displayAr: 'lemonada', bodyAr: 'amiri' },
    layout: { hero: 'collage', offer: 'cards', gallery: 'masonry' },
    decor: ['tape', 'divider-scribble'],
  },
  {
    slug: 'lettering', profile: 'signage',
    name: { ar: 'خط اليد', en: 'Lettering' },
    blurb: { ar: 'لوح أردوازي وأصفر طباشير ومرجاني، ورشة كتابة يدوية: كل شيء بالطباشير، إطار حول العنوان، وأعمال في جدار.', en: 'Slate, chalk yellow and coral, a hand-lettering workshop: everything in chalk, a frame around the headline and work on a wall.' },
    scheme: 'dark',
    palette: { bg: '#20262B', surface: '#2A3137', ink: '#F3F0E8', muted: '#B4B9BC', accent: '#F2C14E', accent2: '#E07A5F', line: '#3A4248', onAccent: '#20262B' },
    fonts: { display: 'permanent-marker', body: 'nunito', displayAr: 'vibes', bodyAr: 'tajawal' },
    layout: { hero: 'framed', offer: 'cards', gallery: 'masonry', process: 'steps' },
    decor: ['chalk'],
  },
];
