import type { DesignInput } from './input';

export const handdrawn: DesignInput[] = [
  {
    slug: 'notebook', profile: 'academy',
    name: { ar: 'دفتر', en: 'Notebook' },
    blurb: { ar: 'ورق دفتر مسطّر وحبر أزرق وشريط لاصق، كدفتر طالب نشيط.', en: 'Ruled notebook paper, blue ink and tape, like a keen student\'s notebook.' },
    scheme: 'light',
    palette: { bg: '#FDFBF5', surface: '#FFFFFF', ink: '#23395B', muted: '#5E6F8A', accent: '#E4572E', accent2: '#4CB944', line: '#23395B', onAccent: '#FFFFFF' },
    fonts: { display: 'patrick-hand', body: 'nunito', displayAr: 'playpen-sans-arabic', bodyAr: 'tajawal' },
    decor: ['notebook', 'tape', 'divider-scribble'],
  },
  {
    slug: 'sketch', profile: 'agency',
    name: { ar: 'سكتش', en: 'Sketch' },
    blurb: { ar: 'حدود مرسومة بقلم وأوراق لاصقة على ورق مربعات، لاستوديو يحب الأفكار الأولى.', en: 'Pen-drawn borders and sticky notes on graph paper, for a studio that loves first ideas.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#FAFAF7', ink: '#1A1A1A', muted: '#5C5C5C', accent: '#2D5BFF', accent2: '#FFCF33', line: '#1A1A1A', onAccent: '#FFFFFF' },
    fonts: { display: 'caveat', body: 'dm-sans', displayAr: 'vibes', bodyAr: 'readex-pro' },
    layout: { hero: 'collage', footer: 'simple' },
    decor: ['tape', 'divider-scribble', 'graph'],
  },
  {
    slug: 'chalk', profile: 'restaurant',
    name: { ar: 'طباشير', en: 'Chalk' },
    blurb: { ar: 'سبورة خضراء وطباشير أبيض وأصفر، وقائمة طعام مكتوبة باليد.', en: 'A green chalkboard in white and yellow chalk, with a handwritten menu.' },
    scheme: 'dark',
    palette: { bg: '#1F2D27', surface: '#26372F', ink: '#F4F1E8', muted: '#B9C2B8', accent: '#F7D774', accent2: '#F28B82', line: '#55675C', onAccent: '#1F2D27' },
    fonts: { display: 'kalam', body: 'kalam', displayAr: 'marhey', bodyAr: 'playpen-sans-arabic' },
    layout: { nav: 'center', hero: 'framed', offer: 'menu' },
    decor: ['chalk'],
  },
  {
    slug: 'scrapbook', profile: 'wedding',
    name: { ar: 'ألبوم', en: 'Scrapbook' },
    blurb: { ar: 'صور مثبتة بشريط لاصق وكتابة بخط اليد، كألبوم ذكريات لعروسين.', en: 'Taped-in photos and handwriting, like a couple\'s memory album.' },
    scheme: 'light',
    palette: { bg: '#FBF6EF', surface: '#FFFFFF', ink: '#3B2F2F', muted: '#7A6A6A', accent: '#D96C6C', accent2: '#8FB8A8', line: '#3B2F2F', onAccent: '#FFFFFF' },
    fonts: { display: 'gloria-hallelujah', body: 'nunito', displayAr: 'aref-ruqaa', bodyAr: 'tajawal' },
    layout: { nav: 'center', hero: 'collage' },
    decor: ['tape', 'divider-scribble'],
  },
  {
    slug: 'doodle', profile: 'app',
    name: { ar: 'خربشة', en: 'Doodle' },
    blurb: { ar: 'خطوط قلم عريض وألوان مرحة وهاتف مرسوم، لتطبيق ودود.', en: 'Thick marker lines, cheerful colours and a drawn phone, for a friendly app.' },
    scheme: 'light',
    palette: { bg: '#FFFDF7', surface: '#FFFFFF', ink: '#1E1E1E', muted: '#5A5A5A', accent: '#FF6B6B', accent2: '#4ECDC4', line: '#1E1E1E', onAccent: '#1E1E1E' },
    fonts: { display: 'permanent-marker', body: 'dm-sans', displayAr: 'lemonada', bodyAr: 'readex-pro' },
    layout: { hero: 'device', contact: 'center' },
    decor: ['graph', 'icons', 'divider-scribble'],
  },
  {
    slug: 'craft', profile: 'boutique',
    name: { ar: 'حِرفة', en: 'Craft' },
    blurb: { ar: 'ورق كرافت بني وأختام وخيوط، لمتجر مشغولات يدوية.', en: 'Brown kraft paper, stamps and string, for a handmade goods shop.' },
    scheme: 'light',
    palette: { bg: '#D9C3A0', surface: '#EADBC2', ink: '#2E2216', muted: '#5C4A36', accent: '#8B2E1E', accent2: '#2E4A3A', line: '#2E2216', onAccent: '#F4E9D6' },
    fonts: { display: 'patrick-hand', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    decor: ['tape', 'grain', 'stamp'],
  },
];
