import type { DesignInput } from './input';

export const heritage: DesignInput[] = [
  {
    slug: 'tatreez', profile: 'boutique',
    name: { ar: 'تطريز', en: 'Tatreez' },
    blurb: { ar: 'أحمر التطريز الفلسطيني على الكريمي، شرائط غرز متصالبة وصور داخل أقواس.', en: 'Palestinian embroidery red on cream, cross-stitch bands and photos inside arches.' },
    scheme: 'light',
    palette: { bg: '#F6EFE3', surface: '#FFF9F0', ink: '#2A1A14', muted: '#6E5A4C', accent: '#A61E22', accent2: '#1F3B2D', line: '#DFCDB5', onAccent: '#FFF6EA' },
    fonts: { display: 'marcellus', body: 'lora', displayAr: 'reem-kufi', bodyAr: 'noto-naskh-arabic' },
    decor: ['tatreez', 'divider-star8', 'pattern'],
  },
  {
    slug: 'mashrabiya', profile: 'restaurant',
    name: { ar: 'مشربية', en: 'Mashrabiya' },
    blurb: { ar: 'خشب داكن ونحاس ونقش هندسي خلف كل قسم، كمطعم في بيت دمشقي.', en: 'Dark wood, brass and a geometric lattice behind every section, like a restaurant in a Damascene house.' },
    scheme: 'dark',
    palette: { bg: '#1E1410', surface: '#2A1C16', ink: '#F2E3CC', muted: '#BFA88A', accent: '#C99A4B', accent2: '#7A2E1F', line: '#45302A', onAccent: '#1E1410' },
    fonts: { display: 'marcellus-sc', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { offer: 'menu', cta: 'image', contact: 'card' },
    decor: ['pattern', 'divider-star8', 'star'],
  },
  {
    slug: 'zellige', profile: 'hotel',
    name: { ar: 'زليج', en: 'Zellige' },
    blurb: { ar: 'أزرق البلاط المغربي وطين دافئ، نجوم ثمانية وأقواس بيضاء كرياض مراكشي.', en: 'Moroccan tile blue and warm clay, eight-point stars and white arches like a riad.' },
    scheme: 'light',
    palette: { bg: '#F4F7F7', surface: '#FFFFFF', ink: '#10324A', muted: '#4F6B7D', accent: '#0F6E8C', accent2: '#C8553D', line: '#D3E1E6', onAccent: '#FFFFFF' },
    fonts: { display: 'marcellus', body: 'source-serif-4', displayAr: 'el-messiri', bodyAr: 'scheherazade-new' },
    layout: { gallery: 'masonry', quotes: 'cards', contact: 'card' },
    decor: ['pattern', 'divider-star8', 'zellige'],
  },
  {
    slug: 'khatt', profile: 'academy',
    name: { ar: 'خطّ', en: 'Khatt' },
    blurb: { ar: 'حبر أسود وذهب على ورق، وخط كوفي قديم، كمدرسة خط وفنون.', en: 'Black ink and gold on paper with an old Kufic hand, like a school of calligraphy.' },
    scheme: 'light',
    palette: { bg: '#F1EADB', surface: '#FAF4E7', ink: '#1D1A16', muted: '#5F584D', accent: '#1D1A16', accent2: '#B8892E', line: '#D4C7AE', onAccent: '#F1EADB' },
    fonts: { display: 'cinzel', body: 'lora', displayAr: 'qahiri', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'framed', quotes: 'single' },
    decor: ['divider-star8', 'star'],
    // Qahiri is a historical Kufi: striking in headlines, hard to read small.
    css: 'html[lang="ar"] h3, html[lang="ar"] .faq__item summary, html[lang="ar"] .quote blockquote, html[lang="ar"] .about__quote, html[lang="ar"] .stat__value, html[lang="ar"] .plan__amount, html[lang="ar"] .card__price, html[lang="ar"] .step__num, html[lang="ar"] .brand, html[lang="ar"] .menu__title, html[lang="ar"] .countdown__num { font-family: var(--font-body); font-weight: 700; } html[lang="ar"] .hero__title { font-size: clamp(3.2rem, 7.4vw, 6.4rem); }',
  },
  {
    slug: 'diwan', profile: 'cafe',
    name: { ar: 'ديوان', en: 'Diwan' },
    blurb: { ar: 'أحمر قرمزي وذهب ونقوش، كمقهى شعبي قديم بجلسات عربية.', en: 'Crimson, gold and patterns, like an old coffee house with floor seating.' },
    scheme: 'dark',
    palette: { bg: '#2A0F12', surface: '#36161A', ink: '#F4E4C8', muted: '#CDAE8E', accent: '#D8A657', accent2: '#3E6B4E', line: '#4D2328', onAccent: '#2A0F12' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'amiri', bodyAr: 'amiri' },
    layout: { hero: 'framed', offer: 'menu', contact: 'card' },
    decor: ['pattern', 'divider-star8'],
  },
  {
    slug: 'qandil', profile: 'sweets',
    name: { ar: 'قنديل', en: 'Qandil' },
    blurb: { ar: 'ليل نيلي وذهب الفوانيس، نجوم تلمع وأقواس، بروح ليالي رمضان.', en: 'Indigo night and lantern gold, twinkling stars and arches, in the spirit of Ramadan nights.' },
    scheme: 'dark',
    palette: { bg: '#0F1433', surface: '#171D45', ink: '#F5ECD7', muted: '#B5B3C9', accent: '#E3B04B', accent2: '#C2457A', line: '#262E61', onAccent: '#0F1433' },
    fonts: { display: 'cormorant-garamond', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { quotes: 'single', contact: 'card' },
    decor: ['star', 'divider-star8', 'sparkles'],
  },
  {
    slug: 'bakhoor', profile: 'perfume',
    name: { ar: 'بخور', en: 'Bakhoor' },
    blurb: { ar: 'خشب العود الداكن وذهبي ونجوم ثمانية، عطّار من زمن القوافل: صورة في قوس، نقش خافت، وعطور في بطاقات.', en: 'Dark oud wood, gold and eight-pointed stars, a perfumer from the caravan days: a photo in an arch, a faint pattern and perfumes in cards.' },
    scheme: 'dark',
    palette: { bg: '#1A0F0A', surface: '#24160F', ink: '#F3E6D0', muted: '#BFA88A', accent: '#D4A24C', accent2: '#A0452F', line: '#3A271B', onAccent: '#1A0F0A' },
    fonts: { display: 'cinzel', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { gallery: 'masonry', contact: 'card' },
    decor: ['pattern', 'divider-star8', 'star'],
  },
  {
    slug: 'henna', profile: 'wedding',
    name: { ar: 'حنّاء', en: 'Henna' },
    blurb: { ar: 'أحمر الحنّاء وذهبي على ورق دافئ، كليلة الحنّاء: حافة تطريز، جدول السهرة بخط زمني، وصور الأحبّة في شبكة.', en: 'Henna red and gold on warm paper, like a henna night: an embroidered edge, the evening\'s timeline and photos of loved ones in a grid.' },
    scheme: 'light',
    palette: { bg: '#F7EFE6', surface: '#FFF9F2', ink: '#3A1F18', muted: '#74574A', accent: '#9E3D22', accent2: '#C9A227', line: '#E8D9C6', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'lora', displayAr: 'el-messiri', bodyAr: 'scheherazade-new' },
    layout: { nav: 'center', schedule: 'timeline', gallery: 'gallery', contact: 'card' },
    decor: ['tatreez', 'divider-star8'],
  },
  {
    slug: 'olive-press', profile: 'farm',
    name: { ar: 'معصرة', en: 'Olive Press' },
    blurb: { ar: 'زيتوني وكهرماني على حجر فاتح، كمعصرة القرية القديمة: قوس فوق الصورة، نقش هادئ، ومراحل العصر بخطوات.', en: 'Olive and amber on pale stone, like the old village press: an arch over the photo, a quiet pattern and the pressing in numbered steps.' },
    scheme: 'light',
    palette: { bg: '#F1EEE2', surface: '#FAF8F0', ink: '#26301E', muted: '#5E6852', accent: '#556B2F', accent2: '#B8862B', line: '#DDD9C8', onAccent: '#FFFFFF' },
    fonts: { display: 'marcellus-sc', body: 'source-serif-4', displayAr: 'mirza', bodyAr: 'noto-naskh-arabic' },
    layout: { process: 'steps', quotes: 'single' },
    decor: ['pattern', 'divider-star8'],
  },
  {
    slug: 'courtyard', profile: 'realestate',
    name: { ar: 'حوش', en: 'Courtyard' },
    blurb: { ar: 'فيروزي عميق ونحاسي وزليج، بيوت قديمة رُمّمت حول فناء: إطار مزخرف، اقتباس كبير، وبيوت في صفوف متناوبة.', en: 'Deep teal, copper and zellige, old houses restored around a courtyard: an ornate frame, a large quote and homes in alternating rows.' },
    scheme: 'light',
    palette: { bg: '#F3EEE4', surface: '#FFFFFF', ink: '#2A2522', muted: '#67605A', accent: '#0F5257', accent2: '#C17C3A', line: '#E2DACB', onAccent: '#FFFFFF' },
    fonts: { display: 'marcellus', body: 'lora', displayAr: 'el-messiri', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'framed', about: 'quote', offer: 'zigzag', extra: 'list' },
    decor: ['zellige', 'divider-star8'],
  },
  {
    slug: 'calligrapher', profile: 'signage',
    name: { ar: 'خطّاط', en: 'Calligrapher' },
    blurb: { ar: 'أزرق الليل وذهبي وأحمر قانٍ، ورشة لافتات بخط اليد: عنوان بخط الرقعة، نجوم ثمانية، وأعمال في جدار.', en: 'Night blue, gold and deep red, a hand-lettered sign workshop: a Ruqaa headline, eight-pointed stars and work on a wall.' },
    scheme: 'dark',
    palette: { bg: '#0F1B2B', surface: '#172538', ink: '#F2ECDF', muted: '#AEB7C4', accent: '#E0B04B', accent2: '#C2504A', line: '#24344A', onAccent: '#0F1B2B' },
    fonts: { display: 'italiana', body: 'eb-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { gallery: 'masonry', process: 'steps' },
    decor: ['star', 'divider-star8', 'pattern'],
  },
  {
    slug: 'alleys', profile: 'photographer',
    name: { ar: 'أزقّة', en: 'Alleys' },
    blurb: { ar: 'حجر القدس الدافئ وصدئي وفيروزي، مصوّر الحارات القديمة: صورة في قوس، جدار صور، وباقات في جدول بخطوط.', en: 'Warm Jerusalem stone, rust and teal, a photographer of old quarters: a photo in an arch, a wall of pictures and packages in a ruled table.' },
    scheme: 'light',
    palette: { bg: '#EFE7DA', surface: '#F8F3EA', ink: '#2B2118', muted: '#6E5F4E', accent: '#8C3B1F', accent2: '#2E5E5A', line: '#DCCFBC', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'eb-garamond', displayAr: 'reem-kufi', bodyAr: 'amiri' },
    layout: { gallery: 'masonry', pricing: 'table', quotes: 'single' },
    decor: ['pattern', 'divider-star8'],
  },
];
