import type { DesignInput } from './input';

export const heritage: DesignInput[] = [
  {
    slug: 'tatreez', profile: 'boutique',
    name: { ar: 'تطريز', en: 'Tatreez' },
    blurb: { ar: 'أحمر التطريز الفلسطيني على الكريمي، شرائط غرز متصالبة وصور داخل أقواس.', en: 'Palestinian embroidery red on cream, cross-stitch bands and photos inside arches.' },
    scheme: 'light',
    palette: { bg: '#F6EFE3', surface: '#FFF9F0', ink: '#2A1A14', muted: '#6E5A4C', accent: '#A61E22', accent2: '#1F3B2D', line: '#DFCDB5', onAccent: '#FFF6EA' },
    fonts: { display: 'marcellus', body: 'lora', displayAr: 'reem-kufi', bodyAr: 'noto-naskh-arabic' },
    decor: ['tatreez', 'divider-star8', 'pattern'],
  },
  {
    slug: 'mashrabiya', profile: 'restaurant',
    name: { ar: 'مشربية', en: 'Mashrabiya' },
    blurb: { ar: 'خشب داكن ونحاس ونقش هندسي خلف كل قسم، كمطعم في بيت دمشقي.', en: 'Dark wood, brass and a geometric lattice behind every section, like a restaurant in a Damascene house.' },
    scheme: 'dark',
    palette: { bg: '#1E1410', surface: '#2A1C16', ink: '#F2E3CC', muted: '#BFA88A', accent: '#C99A4B', accent2: '#7A2E1F', line: '#45302A', onAccent: '#1E1410' },
    fonts: { display: 'marcellus-sc', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { offer: 'menu', cta: 'image', contact: 'card' },
    decor: ['pattern', 'divider-star8', 'star'],
  },
  {
    slug: 'zellige', profile: 'hotel',
    name: { ar: 'زليج', en: 'Zellige' },
    blurb: { ar: 'أزرق البلاط المغربي وطين دافئ، نجوم ثمانية وأقواس بيضاء كرياض مراكشي.', en: 'Moroccan tile blue and warm clay, eight-point stars and white arches like a riad.' },
    scheme: 'light',
    palette: { bg: '#F4F7F7', surface: '#FFFFFF', ink: '#10324A', muted: '#4F6B7D', accent: '#0F6E8C', accent2: '#C8553D', line: '#D3E1E6', onAccent: '#FFFFFF' },
    fonts: { display: 'marcellus', body: 'source-serif-4', displayAr: 'el-messiri', bodyAr: 'scheherazade-new' },
    layout: { gallery: 'masonry', quotes: 'cards', contact: 'card' },
    decor: ['pattern', 'divider-star8', 'zellige'],
  },
  {
    slug: 'khatt', profile: 'academy',
    name: { ar: 'خطّ', en: 'Khatt' },
    blurb: { ar: 'حبر أسود وذهب على ورق، وخط كوفي قديم، كمدرسة خط وفنون.', en: 'Black ink and gold on paper with an old Kufic hand, like a school of calligraphy.' },
    scheme: 'light',
    palette: { bg: '#F1EADB', surface: '#FAF4E7', ink: '#1D1A16', muted: '#5F584D', accent: '#1D1A16', accent2: '#B8892E', line: '#D4C7AE', onAccent: '#F1EADB' },
    fonts: { display: 'cinzel', body: 'lora', displayAr: 'qahiri', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'framed', quotes: 'single' },
    decor: ['divider-star8', 'star'],
    // Qahiri is a historical Kufi: striking in headlines, hard to read small.
    css: 'html[lang="ar"] h3, html[lang="ar"] .faq__item summary, html[lang="ar"] .quote blockquote, html[lang="ar"] .about__quote, html[lang="ar"] .stat__value, html[lang="ar"] .plan__amount, html[lang="ar"] .card__price, html[lang="ar"] .step__num, html[lang="ar"] .brand, html[lang="ar"] .menu__title, html[lang="ar"] .countdown__num { font-family: var(--font-body); font-weight: 700; } html[lang="ar"] .hero__title { font-size: clamp(3.2rem, 7.4vw, 6.4rem); }',
  },
  {
    slug: 'diwan', profile: 'cafe',
    name: { ar: 'ديوان', en: 'Diwan' },
    blurb: { ar: 'أحمر قرمزي وذهب ونقوش، كمقهى شعبي قديم بجلسات عربية.', en: 'Crimson, gold and patterns, like an old coffee house with floor seating.' },
    scheme: 'dark',
    palette: { bg: '#2A0F12', surface: '#36161A', ink: '#F4E4C8', muted: '#CDAE8E', accent: '#D8A657', accent2: '#3E6B4E', line: '#4D2328', onAccent: '#2A0F12' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'amiri', bodyAr: 'amiri' },
    layout: { hero: 'framed', offer: 'menu', contact: 'card' },
    decor: ['pattern', 'divider-star8'],
  },
  {
    slug: 'qandil', profile: 'sweets',
    name: { ar: 'قنديل', en: 'Qandil' },
    blurb: { ar: 'ليل نيلي وذهب الفوانيس، نجوم تلمع وأقواس، بروح ليالي رمضان.', en: 'Indigo night and lantern gold, twinkling stars and arches, in the spirit of Ramadan nights.' },
    scheme: 'dark',
    palette: { bg: '#0F1433', surface: '#171D45', ink: '#F5ECD7', muted: '#B5B3C9', accent: '#E3B04B', accent2: '#C2457A', line: '#262E61', onAccent: '#0F1433' },
    fonts: { display: 'cormorant-garamond', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { quotes: 'single', contact: 'card' },
    decor: ['star', 'divider-star8', 'sparkles'],
  },
];
