import type { DesignInput } from './input';

// Each design is built on one signature interaction (the hero), two designs per
// interaction, and most add a pinned moment further down: a statement that
// lights up word by word (about: scrub) or a rail of cards (rail).
export const interactive: DesignInput[] = [
  {
    slug: 'swell', profile: 'dive',
    name: { ar: 'مدّ', en: 'Swell' },
    blurb: { ar: 'رذاذ البحر وغروب برتقالي؛ صورة ما تحت الماء تكبر مع التمرير حتى تملأ الشاشة، ثم جملة عن البحر تُضاء كلمة كلمة.', en: 'Sea mist and a sunset orange; the underwater photo grows with the scroll until it fills the screen, then a line about the sea lights up word by word.' },
    scheme: 'light',
    palette: { bg: '#E6EFF1', surface: '#FFFFFF', ink: '#0C2A36', muted: '#4A6670', accent: '#E8743B', accent2: '#0F6E83', line: '#CBDDE2', onAccent: '#1A0B03' },
    fonts: { display: 'fraunces', body: 'outfit', displayAr: 'aref-ruqaa', bodyAr: 'readex-pro' },
    layout: { hero: 'zoom', about: 'scrub', offer: 'rail' },
    decor: ['progress', 'cursor'],
  },
  {
    slug: 'vista', profile: 'realestate',
    name: { ar: 'إطلالة', en: 'Vista' },
    blurb: { ar: 'أخضر داكن كالليل وذهبي رملي؛ الشقة تنفتح أمامك مع التمرير، والعقارات تمر في شريط جانبي.', en: 'Night-dark green and sand gold; the apartment opens up as you scroll, and the listings pass by on a sideways rail.' },
    scheme: 'dark',
    palette: { bg: '#101614', surface: '#18201D', ink: '#EEF2EC', muted: '#9DAAA2', accent: '#D9B26F', accent2: '#6E8F7D', line: '#26302C', onAccent: '#14100A' },
    fonts: { display: 'syne', body: 'manrope', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'bar', hero: 'zoom', about: 'overlap', offer: 'rail', extra: 'cards' },
    decor: ['progress', 'cursor'],
  },
  {
    slug: 'strata', profile: 'agency',
    name: { ar: 'طبقات', en: 'Strata' },
    blurb: { ar: 'أصفر صارخ وأسود وبرتقالي؛ صور الأعمال تطفو بأعماق مختلفة وتلحق الفأرة، والمشاريع تمر أفقيًا.', en: 'Loud yellow, black and vermilion; work samples float at different depths and chase the mouse, and projects slide past sideways.' },
    scheme: 'light',
    palette: { bg: '#FFD84D', surface: '#FFE68A', ink: '#141414', muted: '#4D4318', accent: '#FF5A36', accent2: '#3B2FE0', line: '#E5BF33', onAccent: '#141414' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'lalezar', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'minimal', hero: 'layers', about: 'scrub', gallery: 'rail' },
    decor: ['progress', 'cursor'],
    css: '.hero--layers { --layers-shadow: 0 26px 50px -24px rgba(20, 20, 20, .5); }',
  },
  {
    slug: 'confetti', profile: 'boutique',
    name: { ar: 'قصاصات', en: 'Confetti' },
    blurb: { ar: 'وردي هادئ وتوتي؛ قطع المحل متناثرة حول العنوان كقصاصات تميل مع حركة الفأرة.', en: 'Soft blush and raspberry; pieces from the shop are scattered around the headline like cut-outs that sway with the mouse.' },
    scheme: 'light',
    palette: { bg: '#F7E9E4', surface: '#FFFFFF', ink: '#2A1A1F', muted: '#6E5560', accent: '#C2185B', accent2: '#F2A65A', line: '#EAD6CF', onAccent: '#FFFFFF' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'marhey', bodyAr: 'readex-pro' },
    layout: { hero: 'layers', about: 'split', offer: 'bento', quotes: 'cards' },
    decor: ['progress'],
  },
  {
    slug: 'dusk', profile: 'perfume',
    name: { ar: 'عتمة', en: 'Dusk' },
    blurb: { ar: 'واجهة معتمة يحمل فيها المؤشر ضوءًا يكشف الألوان والعنوان الذهبي، والعطور تمر في شريط مع التمرير.', en: 'A dark hero where the pointer carries a light that reveals the colour and the golden headline; the perfumes pass on a rail as you scroll.' },
    scheme: 'dark',
    palette: { bg: '#0D0A10', surface: '#17121C', ink: '#EFE7F4', muted: '#A99BB4', accent: '#E9C46A', accent2: '#8E5BD9', line: '#2A2131', onAccent: '#1A1206' },
    fonts: { display: 'italiana', body: 'manrope', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { nav: 'minimal', hero: 'spotlight', about: 'scrub', offer: 'rail' },
    decor: ['cursor'],
  },
  {
    slug: 'keynote', profile: 'conference',
    name: { ar: 'منصّة', en: 'Keynote' },
    blurb: { ar: 'أسود المسرح ووردي ساخن؛ الضوء يتبع المؤشر فوق القاعة، والمتحدثون يمرون أفقيًا قبل البرنامج.', en: 'Stage black and hot pink; a spotlight follows the pointer over the hall, and the speakers pass sideways before the programme.' },
    scheme: 'dark',
    palette: { bg: '#08080C', surface: '#12121A', ink: '#F4F4F6', muted: '#9E9EAE', accent: '#FF3D6E', accent2: '#3DDCFF', line: '#22222E', onAccent: '#0A0A0E' },
    fonts: { display: 'dela-gothic-one', body: 'inter-tight', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'bar', hero: 'spotlight', about: 'quote', extra: 'rail', schedule: 'timeline' },
    decor: ['progress', 'cursor'],
  },
  {
    slug: 'trace', profile: 'trails',
    name: { ar: 'أثر', en: 'Trace' },
    blurb: { ar: 'أبيض الورق وحبر أسود؛ حرّك الفأرة فتتساقط صور الدرب خلفها وتتلاشى كآثار الأقدام، والاسم ينقلب لونه فوقها.', en: 'Paper white and black ink; move the mouse and trail photos drop behind it and fade like footprints, the name inverting over them.' },
    scheme: 'light',
    palette: { bg: '#F6F5F2', surface: '#FFFFFF', ink: '#111111', muted: '#5E5A55', accent: '#1B1B1B', accent2: '#C84B31', line: '#E2DFD9', onAccent: '#F6F5F2' },
    fonts: { display: 'instrument-serif', body: 'inter-tight', displayAr: 'markazi-text', bodyAr: 'readex-pro' },
    layout: { nav: 'minimal', hero: 'trail', about: 'scrub', gallery: 'masonry', pricing: 'table' },
    decor: ['cursor'],
  },
  {
    slug: 'sprinkle', profile: 'sweets',
    name: { ar: 'رشّة', en: 'Sprinkle' },
    blurb: { ar: 'وردي السكّر وأصفر الكراميل؛ الحلويات تتبع الفأرة وتتساقط كالرشّة، والقائمة بطاقات مرحة.', en: 'Sugar pink and caramel yellow; the sweets follow the mouse and fall like sprinkles, and the menu is a set of cheerful cards.' },
    scheme: 'light',
    palette: { bg: '#FFF0F3', surface: '#FFFFFF', ink: '#3A1626', muted: '#7D5868', accent: '#E8467C', accent2: '#F5B83D', line: '#F4D7DF', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'outfit', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { hero: 'trail', about: 'overlap', offer: 'cards', process: 'steps', quotes: 'cards' },
    decor: ['progress'],
    radius: 28,
  },
  {
    slug: 'tilt', profile: 'app',
    name: { ar: 'ميل', en: 'Tilt' },
    blurb: { ar: 'بنفسجي ليلي وفيروزي؛ الهاتف يميل نحو المؤشر ويلمع سطحه، وبطاقات صغيرة تطفو حوله.', en: 'Night violet and turquoise; the phone leans toward the pointer with a moving shine, small cards floating around it.' },
    scheme: 'dark',
    palette: { bg: '#0E0B1F', surface: '#17132E', ink: '#F1EEFF', muted: '#A49FC7', accent: '#8B5CF6', accent2: '#2DD4BF', line: '#262046', onAccent: '#FFFFFF' },
    fonts: { display: 'sora', body: 'dm-sans', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { hero: 'tilt', offer: 'bento', process: 'steps' },
    decor: ['progress', 'cursor', 'blobs'],
  },
  {
    slug: 'surge', profile: 'bikes',
    name: { ar: 'اندفاع', en: 'Surge' },
    blurb: { ar: 'أسود وأحمر ناري وخط عريض مضغوط؛ صورة الدرّاجة تميل مع المؤشر، وشعار المحل يُضاء مع النزول.', en: 'Black, fiery red and tall condensed type; the rider\'s photo tilts with the pointer, and the shop\'s motto lights up as you go down.' },
    scheme: 'dark',
    palette: { bg: '#0B0B0B', surface: '#161616', ink: '#F5F5F0', muted: '#A3A39A', accent: '#FF3B1F', accent2: '#FFD400', line: '#262626', onAccent: '#0B0B0B' },
    fonts: { display: 'anton', body: 'archivo', displayAr: 'changa', bodyAr: 'tajawal' },
    layout: { nav: 'bar', hero: 'tilt', about: 'scrub', offer: 'rail', schedule: 'table' },
    decor: ['progress', 'cursor'],
    radius: 6,
  },
  {
    slug: 'doors', profile: 'restaurant',
    name: { ar: 'أبواب', en: 'Doors' },
    blurb: { ar: 'بابان بلون النبيذ يحملان اسم المطعم وينفتحان مع التمرير على المائدة، وصور الأطباق تمر في شريط.', en: 'Two wine-red doors carrying the restaurant\'s name open onto the table as you scroll, and photos of the dishes pass on a rail.' },
    scheme: 'dark',
    palette: { bg: '#120D0B', surface: '#1C1512', ink: '#F6EBDD', muted: '#B9A591', accent: '#E3A72F', accent2: '#7A1F2B', line: '#2E231E', onAccent: '#1B1206' },
    fonts: { display: 'dm-serif-display', body: 'dm-sans', displayAr: 'rakkas', bodyAr: 'tajawal' },
    layout: { nav: 'minimal', hero: 'curtain', about: 'split', offer: 'menu', gallery: 'rail' },
    decor: ['progress', 'cursor'],
    css: '.hero--curtain { --curtain-1: #7A1F2B; --curtain-2: #5E1520; --curtain-ink: #F4D9A9; --curtain-knob: #E3A72F; }',
  },
  {
    slug: 'vow', profile: 'wedding',
    name: { ar: 'وعد', en: 'Vow' },
    blurb: { ar: 'أخضر المريمية وذهبي عتيق؛ ستارة تحمل الاسمين تنفتح على صورة العرس، ثم وعد يُقرأ كلمة كلمة.', en: 'Sage green and antique gold; a curtain bearing both names opens onto the wedding photo, then a vow is read word by word.' },
    scheme: 'light',
    palette: { bg: '#EEF1EA', surface: '#FFFFFF', ink: '#23302A', muted: '#5D6B63', accent: '#8A6A3B', accent2: '#C9A27E', line: '#DDE3D8', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'manrope', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { nav: 'center', hero: 'curtain', about: 'scrub', schedule: 'timeline', gallery: 'masonry' },
    decor: ['progress'],
    css: '.hero--curtain { --curtain-1: #5E7A68; --curtain-2: #4C6656; --curtain-ink: #F3EEE4; --curtain-knob: #C9A27E; }',
  },
];
