import type { DesignInput } from './input';

export const luxury: DesignInput[] = [
  {
    slug: 'noir', profile: 'perfume',
    name: { ar: 'نوار', en: 'Noir' },
    blurb: { ar: 'أسود دافئ وذهب وخط ديدون رفيع، عطور تظهر واحدًا تلو الآخر.', en: 'Warm black, gold and a hairline Didone, perfumes revealed one at a time.' },
    scheme: 'dark',
    palette: { bg: '#0B0A08', surface: '#151310', ink: '#EFE6D2', muted: '#A79C86', accent: '#C9A45C', accent2: '#6B5530', line: '#2A251C', onAccent: '#0B0A08' },
    fonts: { display: 'bodoni-moda', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
  },
  {
    slug: 'gala', profile: 'music',
    name: { ar: 'حفلة', en: 'Gala' },
    blurb: { ar: 'عاجي وذهب شمبانيا وخط يدوي، مدرسة موسيقى بثياب حفلة الشتاء: عنوان في إطار، واقتباس واحد كبير.', en: 'Ivory, champagne gold and a script hand, a music school dressed for its winter concert: a framed headline and one large quote.' },
    scheme: 'light',
    palette: { bg: '#F8F3EA', surface: '#FFFCF6', ink: '#2E2A24', muted: '#857C6E', accent: '#B08D52', accent2: '#D9C4A0', line: '#E9DFCC', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri', accent: 'great-vibes' },
    layout: { nav: 'center', hero: 'framed', about: 'quote' },
    decor: ['divider-fleuron', 'script-title'],
  },
  {
    slug: 'marble', profile: 'cowork',
    name: { ar: 'رخام', en: 'Marble' },
    blurb: { ar: 'عروق رخام فاتحة ونحاس وخط مذيّل كبير، مكاتب تنفيذية بالشهر: ما تشمله العضوية في قائمة هادئة ومساحة واسعة.', en: 'Pale marble veins, brass and a large serif, executive offices by the month: what\'s included in a quiet list, with plenty of air.' },
    scheme: 'light',
    palette: { bg: '#F4F2EF', surface: '#FFFFFF', ink: '#1C1B19', muted: '#726E67', accent: '#1C1B19', accent2: '#B89B6A', line: '#E3DED6', onAccent: '#F4F2EF' },
    fonts: { display: 'playfair-display', body: 'work-sans', displayAr: 'el-messiri', bodyAr: 'almarai' },
    layout: { extra: 'list' },
    decor: ['marble'],
  },
  {
    slug: 'velvet', profile: 'restaurant',
    name: { ar: 'مخمل', en: 'Velvet' },
    blurb: { ar: 'عنابي مخملي وذهب وصور داكنة، لمطعم عشاء فاخر.', en: 'Velvet burgundy, gold and dark photography, for a fine-dining room.' },
    scheme: 'dark',
    palette: { bg: '#1E0B10', surface: '#2A1218', ink: '#F3E3D3', muted: '#C3A79A', accent: '#D4A55A', accent2: '#8E2A3A', line: '#3D1D24', onAccent: '#1E0B10' },
    fonts: { display: 'playfair-display-sc', body: 'cormorant-garamond', displayAr: 'el-messiri', bodyAr: 'amiri' },
    layout: { offer: 'menu' },
  },
  {
    slug: 'suite', profile: 'hotel',
    name: { ar: 'جناح', en: 'Suite' },
    blurb: { ar: 'أخضر بترولي داكن ونحاس وكوفي أنيق، لفندق خمس نجوم.', en: 'Deep petrol green, brass and an elegant Kufi, for a five-star hotel.' },
    scheme: 'dark',
    palette: { bg: '#0F1A1F', surface: '#16252C', ink: '#ECE6DA', muted: '#9FA7A3', accent: '#C2A36B', accent2: '#4F6F6A', line: '#24363E', onAccent: '#0F1A1F' },
    fonts: { display: 'marcellus', body: 'cormorant', displayAr: 'reem-kufi', bodyAr: 'amiri' },
    layout: { extra: 'cards' },
  },
  {
    slug: 'regent', profile: 'law',
    name: { ar: 'ريجنت', en: 'Regent' },
    blurb: { ar: 'فحمي داكن وذهب قديم وقائمة مرقّمة، لمكتب محاماة كبير.', en: 'Deep charcoal, old gold and a numbered list, for a major law firm.' },
    scheme: 'dark',
    palette: { bg: '#101418', surface: '#171D23', ink: '#E9E3D6', muted: '#9CA3A8', accent: '#B9975B', accent2: '#5A6B7A', line: '#262E36', onAccent: '#101418' },
    fonts: { display: 'playfair-display', body: 'source-serif-4', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'list' },
  },
  {
    slug: 'bloom', profile: 'florist',
    name: { ar: 'تفتّح', en: 'Bloom' },
    blurb: { ar: 'عاجي وأسود وذهبي خافت، محل زهور بخط بودوني كدار أزياء: صورة طويلة بجانب العنوان ومسافات سخية حول كل باقة.', en: 'Ivory, black and muted gold, a florist in Bodoni like a couture house: a tall photo beside the headline and generous space around every bouquet.' },
    scheme: 'light',
    palette: { bg: '#F6F2EC', surface: '#FFFFFF', ink: '#1A1714', muted: '#6E655B', accent: '#1A1714', accent2: '#B08D57', line: '#E4DCD0', onAccent: '#F6F2EC' },
    fonts: { display: 'bodoni-moda', body: 'cormorant-garamond', displayAr: 'el-messiri', bodyAr: 'amiri' },
    layout: { hero: 'split', extra: 'list' },
  },
  {
    slug: 'praline', profile: 'sweets',
    name: { ar: 'برالين', en: 'Praline' },
    blurb: { ar: 'شوكولاتة داكنة وذهبي وأحمر توتي، صانع حلويات فاخر: صورة كاملة، أصناف في صفوف متناوبة، وجدار صور.', en: 'Dark chocolate, gold and berry red, a fine confectioner: a full-screen photo, sweets in alternating rows and a wall of pictures.' },
    scheme: 'dark',
    palette: { bg: '#1C120E', surface: '#261913', ink: '#F2E6D9', muted: '#BCA894', accent: '#C9A35E', accent2: '#A34A38', line: '#3A2A21', onAccent: '#1C120E' },
    fonts: { display: 'playfair-display', body: 'cormorant', displayAr: 'reem-kufi', bodyAr: 'amiri' },
    layout: { gallery: 'masonry', contact: 'card' },
  },
  {
    slug: 'aura', profile: 'clinic',
    name: { ar: 'هالة', en: 'Aura' },
    blurb: { ar: 'عاجي وردي ولون الرمال، عيادة تجميل هادئة الفخامة: عنوان في المنتصف فوق صورة عريضة، خطوات، وباقات.', en: 'Rosy ivory and sand, an aesthetic clinic with quiet luxury: a centred headline over a wide photo, steps and plans.' },
    scheme: 'light',
    palette: { bg: '#F7F1EE', surface: '#FFFFFF', ink: '#2A1F1C', muted: '#74645E', accent: '#8F6A5A', accent2: '#C8A97E', line: '#E8DDD7', onAccent: '#FFFFFF' },
    fonts: { display: 'marcellus', body: 'work-sans', displayAr: 'reem-kufi', bodyAr: 'almarai' },
    layout: { hero: 'centered', offer: 'cards', process: 'steps' },
  },
  {
    slug: 'gilt', profile: 'photographer',
    name: { ar: 'إطار مذهّب', en: 'Gilt' },
    blurb: { ar: 'أسود المعرض وذهبي، مصوّر يعرض أعماله كلوحات: عنوان في إطار، جدار صور متفاوت، وباقات في جدول أنيق.', en: 'Gallery black and gold, a photographer who hangs his work like paintings: a framed headline, a mixed wall of pictures and packages in a fine table.' },
    scheme: 'dark',
    palette: { bg: '#0B0B0B', surface: '#151515', ink: '#F2EFE9', muted: '#A39E95', accent: '#C5A572', accent2: '#8C7656', line: '#262421', onAccent: '#0B0B0B' },
    fonts: { display: 'cinzel', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { hero: 'framed', gallery: 'masonry', pricing: 'table', quotes: 'single' },
  },
  {
    slug: 'grand-tour', profile: 'travel',
    name: { ar: 'الرحلة الكبرى', en: 'Grand Tour' },
    blurb: { ar: 'أخضر زمردي عميق وذهبي وعنابي، مكتب سفر كقطار نوم قديم: صورة كاملة، رحلات في قائمة أنيقة منقّطة، وكلمة مسافر واحدة.', en: 'Deep emerald, gold and burgundy, a travel agency like an old sleeper train: a full-screen photo, trips in an elegant dotted list and one traveller\'s word at a time.' },
    scheme: 'dark',
    palette: { bg: '#0E1F1A', surface: '#152922', ink: '#EEE7D8', muted: '#A9B2A0', accent: '#C9A45C', accent2: '#A33A45', line: '#24382F', onAccent: '#0E1F1A' },
    fonts: { display: 'marcellus', body: 'cormorant', displayAr: 'el-messiri', bodyAr: 'amiri' },
    layout: { offer: 'menu', quotes: 'single' },
  },
  {
    slug: 'members', profile: 'gym',
    name: { ar: 'أعضاء', en: 'Members' },
    blurb: { ar: 'فحمي وذهبي وأخضر رمادي، نادٍ رياضي خاص للأعضاء: صورة كاملة، برامج في صفوف متناوبة، وجدول حصص هادئ.', en: 'Charcoal, gold and grey-green, a private members\' gym: a full-screen photo, programmes in alternating rows and a calm class table.' },
    scheme: 'dark',
    palette: { bg: '#121212', surface: '#1B1B1B', ink: '#F0ECE4', muted: '#A8A296', accent: '#B9975B', accent2: '#7D8C80', line: '#2B2B2B', onAccent: '#121212' },
    fonts: { display: 'bodoni-moda', body: 'work-sans', displayAr: 'aref-ruqaa', bodyAr: 'almarai' },
    layout: { schedule: 'table' },
  },
];
