import type { DesignInput } from './input';

export const luxury: DesignInput[] = [
  {
    slug: 'noir', profile: 'perfume',
    name: { ar: 'نوار', en: 'Noir' },
    blurb: { ar: 'أسود دافئ وذهب وخط ديدون رفيع، عطور تظهر واحدًا تلو الآخر.', en: 'Warm black, gold and a hairline Didone, perfumes revealed one at a time.' },
    scheme: 'dark',
    palette: { bg: '#0B0A08', surface: '#151310', ink: '#EFE6D2', muted: '#A79C86', accent: '#C9A45C', accent2: '#6B5530', line: '#2A251C', onAccent: '#0B0A08' },
    fonts: { display: 'bodoni-moda', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
  },
  {
    slug: 'champagne', profile: 'wedding',
    name: { ar: 'شمبانيا', en: 'Champagne' },
    blurb: { ar: 'عاجي وذهب شمبانيا وأسماء بخط يدوي، دعوة عرس فاخرة.', en: 'Ivory, champagne gold and names in a script hand, a luxurious wedding invitation.' },
    scheme: 'light',
    palette: { bg: '#F8F3EA', surface: '#FFFCF6', ink: '#2E2A24', muted: '#857C6E', accent: '#B08D52', accent2: '#D9C4A0', line: '#E9DFCC', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'eb-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri', accent: 'great-vibes' },
    layout: { nav: 'center', hero: 'framed', about: 'quote' },
    decor: ['divider-fleuron', 'script-title'],
  },
  {
    slug: 'marble', profile: 'realestate',
    name: { ar: 'رخام', en: 'Marble' },
    blurb: { ar: 'عروق رخام فاتحة ونحاس وخط مذيّل كبير، لفلل وشقق راقية.', en: 'Pale marble veins, brass and a large serif, for fine villas and apartments.' },
    scheme: 'light',
    palette: { bg: '#F4F2EF', surface: '#FFFFFF', ink: '#1C1B19', muted: '#726E67', accent: '#1C1B19', accent2: '#B89B6A', line: '#E3DED6', onAccent: '#F4F2EF' },
    fonts: { display: 'playfair-display', body: 'work-sans', displayAr: 'el-messiri', bodyAr: 'almarai' },
    layout: { extra: 'list' },
    decor: ['marble'],
  },
  {
    slug: 'velvet', profile: 'restaurant',
    name: { ar: 'مخمل', en: 'Velvet' },
    blurb: { ar: 'عنابي مخملي وذهب وصور داكنة، لمطعم عشاء فاخر.', en: 'Velvet burgundy, gold and dark photography, for a fine-dining room.' },
    scheme: 'dark',
    palette: { bg: '#1E0B10', surface: '#2A1218', ink: '#F3E3D3', muted: '#C3A79A', accent: '#D4A55A', accent2: '#8E2A3A', line: '#3D1D24', onAccent: '#1E0B10' },
    fonts: { display: 'playfair-display-sc', body: 'cormorant-garamond', displayAr: 'el-messiri', bodyAr: 'amiri' },
    layout: { offer: 'menu' },
  },
  {
    slug: 'suite', profile: 'hotel',
    name: { ar: 'جناح', en: 'Suite' },
    blurb: { ar: 'أخضر بترولي داكن ونحاس وكوفي أنيق، لفندق خمس نجوم.', en: 'Deep petrol green, brass and an elegant Kufi, for a five-star hotel.' },
    scheme: 'dark',
    palette: { bg: '#0F1A1F', surface: '#16252C', ink: '#ECE6DA', muted: '#9FA7A3', accent: '#C2A36B', accent2: '#4F6F6A', line: '#24363E', onAccent: '#0F1A1F' },
    fonts: { display: 'marcellus', body: 'cormorant', displayAr: 'reem-kufi', bodyAr: 'amiri' },
    layout: { extra: 'cards' },
  },
  {
    slug: 'regent', profile: 'law',
    name: { ar: 'ريجنت', en: 'Regent' },
    blurb: { ar: 'فحمي داكن وذهب قديم وقائمة مرقّمة، لمكتب محاماة كبير.', en: 'Deep charcoal, old gold and a numbered list, for a major law firm.' },
    scheme: 'dark',
    palette: { bg: '#101418', surface: '#171D23', ink: '#E9E3D6', muted: '#9CA3A8', accent: '#B9975B', accent2: '#5A6B7A', line: '#262E36', onAccent: '#101418' },
    fonts: { display: 'playfair-display', body: 'source-serif-4', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'list' },
  },
];
