import type { DesignInput } from './input';

export const minimal: DesignInput[] = [
  {
    slug: 'blank', profile: 'gallery',
    name: { ar: 'فراغ', en: 'Blank' },
    blurb: { ar: 'أبيض وأسود وصور بلا ألوان، صالة عرض بيضاء تترك الأعمال تتكلم.', en: 'White, black and colourless photos, a white-cube gallery where the works do the talking.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F4F4F2', ink: '#111111', muted: '#7C7C77', accent: '#111111', accent2: '#B5B5B0', line: '#E6E6E3', onAccent: '#FFFFFF' },
    fonts: { display: 'inter', body: 'inter', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    decor: ['mono'],
  },
  {
    slug: 'sukun', profile: 'clinic',
    name: { ar: 'سكون', en: 'Sukun' },
    blurb: { ar: 'بيج هادئ وأخضر مريمية، قوائم بدل البطاقات ومسافات تتنفس.', en: 'Quiet beige and sage, lists instead of cards and room to breathe.' },
    scheme: 'light',
    palette: { bg: '#F6F3EE', surface: '#EFEAE2', ink: '#2C2A26', muted: '#827C71', accent: '#5F806B', accent2: '#C9B79C', line: '#E0D9CD', onAccent: '#FFFFFF' },
    fonts: { display: 'instrument-serif', body: 'dm-sans', displayAr: 'mada', bodyAr: 'mada' },
  },
  {
    slug: 'essence', profile: 'florist',
    name: { ar: 'جوهر', en: 'Essence' },
    blurb: { ar: 'رمادي حجري وخط رفيع طويل، كل باقة في مساحتها الخاصة، كغصن واحد في مزهرية.', en: 'Stone grey and a tall thin face, each bouquet in its own space, the way a single stem stands in a vase.' },
    scheme: 'light',
    palette: { bg: '#F2F0EB', surface: '#E9E6DF', ink: '#1A1A18', muted: '#7D7A72', accent: '#1A1A18', accent2: '#A39E92', line: '#DCD8CF', onAccent: '#F2F0EB' },
    fonts: { display: 'italiana', body: 'inter', displayAr: 'markazi-text', bodyAr: 'mada' },
    layout: { hero: 'split', offer: 'cards' },
  },
  {
    slug: 'nordic', profile: 'cowork',
    name: { ar: 'شمالي', en: 'Nordic' },
    blurb: { ar: 'خشب فاتح وأبيض دافئ وخط واحد، مساحة عمل هادئة على الطريقة الإسكندنافية: صورة بجانب العنوان ولا شيء يشتت.', en: 'Light oak, warm white and one typeface, a quiet coworking space in the Scandinavian way: a photo beside the headline and nothing to distract.' },
    scheme: 'light',
    palette: { bg: '#F7F5F0', surface: '#EFEBE3', ink: '#24221F', muted: '#7A756C', accent: '#9A6B47', accent2: '#6E7F72', line: '#E3DED4', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-sans', body: 'dm-sans', displayAr: 'vazirmatn', bodyAr: 'vazirmatn' },
    layout: { hero: 'split' },
  },
  {
    slug: 'score', profile: 'music',
    name: { ar: 'نوتة', en: 'Score' },
    blurb: { ar: 'أبيض كورقة نوتة جديدة ولون دافئ واحد، مدرسة موسيقى بلا زخرفة: صمت كثير بين السطور واقتباس واحد كبير.', en: 'White like a fresh score and one warm colour, a music school without a single ornament: plenty of silence between the lines and one large quote.' },
    scheme: 'light',
    palette: { bg: '#FBFAF7', surface: '#F3F0EA', ink: '#2B2A28', muted: '#85817A', accent: '#9C7C5B', accent2: '#C8B9A6', line: '#E7E2D9', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'inter', displayAr: 'amiri', bodyAr: 'mada' },
    layout: { about: 'quote' },
  },
  {
    slug: 'frame', profile: 'realestate',
    name: { ar: 'إطار', en: 'Frame' },
    blurb: { ar: 'أبيض ناصع وعنوان ضخم رفيع وصور كبيرة، كمجلة معمارية.', en: 'Bright white, a huge thin headline and big photos, like an architecture journal.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F5F5F3', ink: '#0F0F0F', muted: '#7A7A75', accent: '#0F0F0F', accent2: '#C4A484', line: '#EBEBE8', onAccent: '#FFFFFF' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'type', offer: 'cards', about: 'columns' },
  },
  {
    slug: 'route', profile: 'travel',
    name: { ar: 'مسار', en: 'Route' },
    blurb: { ar: 'أبيض هادئ وأحمر واحد، مكتب سفر يترك المدينة تتكلم: صورة بجانب العنوان، رحلات في قائمة بخطوط رفيعة، ومسافات واسعة.', en: 'Quiet white and a single red, a travel agency that lets the city speak: a photo beside the headline, trips in a hairline list and wide spacing.' },
    scheme: 'light',
    palette: { bg: '#FAFAF7', surface: '#FFFFFF', ink: '#1B1B19', muted: '#6D6C66', accent: '#B23A2B', accent2: '#8A8A80', line: '#E7E6E0', onAccent: '#FFFFFF' },
    fonts: { display: 'newsreader', body: 'inter', displayAr: 'noto-naskh-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'split', offer: 'menu', gallery: 'gallery' },
  },
  {
    slug: 'thread', profile: 'boutique',
    name: { ar: 'خيط', en: 'Thread' },
    blurb: { ar: 'رمادي دافئ وأسود فقط، متجر ملابس كدليل قياسات: عنوان ضخم رفيع، بطاقات بلا زخرفة، وقائمة للمجموعات.', en: 'Warm grey and black only, a clothing shop like a size guide: a huge light headline, unadorned cards and a list of collections.' },
    scheme: 'light',
    palette: { bg: '#F5F4F0', surface: '#FFFFFF', ink: '#1D1C1A', muted: '#6A6862', accent: '#1D1C1A', accent2: '#A3907A', line: '#E2E0DA', onAccent: '#F5F4F0' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'readex-pro', bodyAr: 'readex-pro' },
    layout: { hero: 'type', offer: 'cards', extra: 'list' },
  },
  {
    slug: 'stillness', profile: 'hotel',
    name: { ar: 'سكينة', en: 'Stillness' },
    blurb: { ar: 'رمادي حجري وأخضر مريمية، فندق للهدوء: صورة بانورامية، اقتباس كبير وحيد، وغرف في بطاقات متباعدة.', en: 'Stone grey and sage, a hotel for quiet: a panoramic photo, one large quote and rooms in widely spaced cards.' },
    scheme: 'light',
    palette: { bg: '#F4F2EE', surface: '#FFFFFF', ink: '#23211E', muted: '#6E6A64', accent: '#5C6B5A', accent2: '#B5A58E', line: '#E3DFD8', onAccent: '#FFFFFF' },
    fonts: { display: 'eb-garamond', body: 'inter', displayAr: 'amiri', bodyAr: 'vazirmatn' },
    layout: { about: 'quote', offer: 'cards', gallery: 'masonry' },
  },
  {
    slug: 'statement', profile: 'law',
    name: { ar: 'بيان', en: 'Statement' },
    blurb: { ar: 'أبيض وأسود بلا لون آخر، مكتب محاماة يقول ما يلزم فقط: عنوان بعرض الصفحة، خدمات وخطوات كقوائم مرقّمة.', en: 'Black and white with no other colour, a law firm that says only what is needed: a full-width headline, services and steps as numbered lists.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F6F6F6', ink: '#111111', muted: '#666666', accent: '#111111', accent2: '#9B9B9B', line: '#E5E5E5', onAccent: '#FFFFFF' },
    fonts: { display: 'work-sans', body: 'work-sans', displayAr: 'noto-sans-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { hero: 'type', offer: 'list', process: 'list' },
    decor: ['mono'],
  },
  {
    slug: 'calm', profile: 'vet',
    name: { ar: 'هدوء', en: 'Calm' },
    blurb: { ar: 'أبيض رمادي وأزرق واحد، عيادة بيطرية تبقي كل شيء هادئًا: عنوان في المنتصف، خدمات كقائمة، والزيارة الأولى خطوة خطوة.', en: 'Grey-white and a single blue, a vet clinic that keeps everything calm: a centred headline, services as a list and the first visit step by step.' },
    scheme: 'light',
    palette: { bg: '#F7F7F5', surface: '#FFFFFF', ink: '#161616', muted: '#6B6B67', accent: '#2B59FF', accent2: '#BDBDB7', line: '#E4E4E0', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'plus-jakarta-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { offer: 'list', gallery: 'gallery', process: 'list' },
  },
  {
    slug: 'margin', profile: 'bookshop',
    name: { ar: 'هامش', en: 'Margin' },
    blurb: { ar: 'ورق أبيض وبرتقالي واحد كملاحظة بالقلم في الهامش، مكتبة تُقرأ ككتاب معتنى به: العناوين والأمسيات في قوائم.', en: 'White paper and one orange like a pencil note in the margin, a bookshop that reads like a well-kept book: titles and evenings in lists.' },
    scheme: 'light',
    palette: { bg: '#FBFAF7', surface: '#FFFFFF', ink: '#1E1E1C', muted: '#6C6B66', accent: '#C2410C', accent2: '#A8A29E', line: '#E8E6E1', onAccent: '#FFFFFF' },
    fonts: { display: 'source-serif-4', body: 'inter', displayAr: 'noto-naskh-arabic', bodyAr: 'mada' },
    layout: { hero: 'split', offer: 'list', process: 'list', pricing: 'table' },
    decor: ['mono'],
  },
];
