import type { DesignInput } from './input';

export const modern: DesignInput[] = [
  {
    slug: 'bento', profile: 'agency',
    name: { ar: 'بينتو', en: 'Bento' },
    blurb: { ar: 'أبيض وأزرق كهربائي، شبكة بينتو للخدمات وقائمة طافية على شكل حبة.', en: 'White and electric blue, a bento grid of services and a floating pill menu.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F3F5F9', ink: '#0B1220', muted: '#5A6478', accent: '#2F5BFF', accent2: '#FF7A59', line: '#E3E7EF', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'inter', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'pill', about: 'overlap', offer: 'bento' },
  },
  {
    slug: 'pulse', profile: 'gym',
    name: { ar: 'نبض', en: 'Pulse' },
    blurb: { ar: 'أسود وأخضر ليموني، عنوان ضخم وجدول حصص كجدول مواعيد رقمي.', en: 'Black and lime, a giant headline and a class timetable like a departures board.' },
    scheme: 'dark',
    palette: { bg: '#0C0D0F', surface: '#17191D', ink: '#F4F6F2', muted: '#9AA09A', accent: '#C6FF3D', accent2: '#3DD9FF', line: '#2A2D33', onAccent: '#0C0D0F' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'cairo', bodyAr: 'tajawal' },
    layout: { hero: 'type', schedule: 'table', footer: 'big' },
  },
  {
    slug: 'shifa', profile: 'clinic',
    name: { ar: 'شفاء', en: 'Shifa' },
    blurb: { ar: 'أبيض نظيف وتركواز هادئ، بطاقات ناعمة تبعث على الاطمئنان.', en: 'Clean white and calm teal, soft cards that put patients at ease.' },
    scheme: 'light',
    palette: { bg: '#F7FAFA', surface: '#FFFFFF', ink: '#0E2A30', muted: '#557077', accent: '#0E8C8C', accent2: '#9BE3D2', line: '#DCE8E8', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { contact: 'form' },
  },
  {
    slug: 'sakan', profile: 'realestate',
    name: { ar: 'سكن', en: 'Sakan' },
    blurb: { ar: 'رمادي دافئ وطيني، صورة رئيسية كبيرة وبطاقات عقارات واضحة.', en: 'Warm grey and terracotta, a big hero photo and clear listing cards.' },
    scheme: 'light',
    palette: { bg: '#F6F3EF', surface: '#FFFFFF', ink: '#1E1B18', muted: '#6D665E', accent: '#C2562F', accent2: '#2E4A42', line: '#E5DED5', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'readex-pro', bodyAr: 'readex-pro' },
    layout: { hero: 'fullbleed' },
  },
  {
    slug: 'mishwar', profile: 'app',
    name: { ar: 'مشوار', en: 'Mishwar' },
    blurb: { ar: 'خزامى ونيلي، هاتفان يعرضان التطبيق وشبكة مزايا بأيقونات.', en: 'Lavender and indigo, two phones showing the app and a grid of icon features.' },
    scheme: 'light',
    palette: { bg: '#F6F4FF', surface: '#FFFFFF', ink: '#1A1640', muted: '#625D86', accent: '#5B3DF5', accent2: '#FFB547', line: '#E4E0F7', onAccent: '#FFFFFF' },
    fonts: { display: 'sora', body: 'dm-sans', displayAr: 'zain', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'pill', hero: 'device', offer: 'bento', contact: 'center' },
    decor: ['icons'],
  },
  {
    slug: 'nord', profile: 'software',
    name: { ar: 'نورد', en: 'Nord' },
    blurb: { ar: 'أبيض مطفأ وأسود ونعناعي، عنوان متمركز وكل شيء في مكانه.', en: 'Off-white, black and mint, a centred headline and everything in its place.' },
    scheme: 'light',
    palette: { bg: '#FAFAF7', surface: '#FFFFFF', ink: '#111111', muted: '#63635E', accent: '#111111', accent2: '#34D399', line: '#E7E7E1', onAccent: '#FFFFFF' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'beiruti', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'centered', contact: 'form', footer: 'big' },
    css: 'html { --stat-on-dark: var(--accent2); }',
  },
  {
    slug: 'plate', profile: 'restaurant',
    name: { ar: 'صحن', en: 'Plate' },
    blurb: { ar: 'أبيض دافئ وأحمر طماطم وأخضر ريحان، مطعم عصري واضح: صورة الطبق بجانب العنوان، بطاقات أطباق بالصور، وجدار صور.', en: 'Warm white, tomato red and basil green, a clear modern restaurant: the dish beside the headline, photo cards for the menu and a wall of pictures.' },
    scheme: 'light',
    palette: { bg: '#FAF8F5', surface: '#FFFFFF', ink: '#1A1A1A', muted: '#66625C', accent: '#D6492A', accent2: '#2E7D5B', line: '#EAE5DE', onAccent: '#FFFFFF' },
    fonts: { display: 'figtree', body: 'figtree', displayAr: 'fustat', bodyAr: 'noto-sans-arabic' },
    layout: { offer: 'cards', gallery: 'masonry', contact: 'card' },
  },
  {
    slug: 'roast', profile: 'cafe',
    name: { ar: 'تحميص', en: 'Roast' },
    blurb: { ar: 'فحمي وعسلي وأخضر نعناعي، مقهى مختص ليلي: شريط تنقّل عائم، قائمة واضحة، وشبكة بينتو للصور.', en: 'Charcoal, honey and mint, a specialty café at night: a floating nav pill, a clear menu and a bento grid of photos.' },
    scheme: 'dark',
    palette: { bg: '#121212', surface: '#1C1C1C', ink: '#F5F2EC', muted: '#A8A39B', accent: '#F0B429', accent2: '#3EB489', line: '#2A2A2A', onAccent: '#121212' },
    fonts: { display: 'inter-tight', body: 'inter', displayAr: 'noto-kufi-arabic', bodyAr: 'noto-sans-arabic' },
    layout: { nav: 'pill', hero: 'centered', offer: 'menu', extra: 'cards', gallery: 'bento' },
  },
  {
    slug: 'syllabus', profile: 'academy',
    name: { ar: 'منهج', en: 'Syllabus' },
    blurb: { ar: 'أزرق كهربائي وبرتقالي على أبيض مائل للزرقة، أكاديمية رقمية: بطاقات دورات، خطوات مرقّمة، وباقات واضحة.', en: 'Electric blue and orange on a bluish white, a digital academy: course cards, numbered steps and clear plans.' },
    scheme: 'light',
    palette: { bg: '#F5F7FF', surface: '#FFFFFF', ink: '#141B34', muted: '#5A6385', accent: '#3D5AFE', accent2: '#FF8A3D', line: '#E3E7F5', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'inter', displayAr: 'almarai', bodyAr: 'almarai' },
    layout: { nav: 'bar', offer: 'cards', process: 'steps' },
    decor: ['icons'],
  },
  {
    slug: 'summit', profile: 'conference',
    name: { ar: 'ملتقى', en: 'Summit' },
    blurb: { ar: 'رمادي ليلي وأزرق ووردي، مؤتمر تقني بخط ضخم: عنوان بعرض الصفحة، بطاقات المتحدثين، وبرنامج في جدول.', en: 'Night grey, blue and pink, a tech conference in huge type: a full-width headline, speaker cards and the programme in a table.' },
    scheme: 'dark',
    palette: { bg: '#0D1117', surface: '#161B22', ink: '#F0F3F6', muted: '#9BA5B1', accent: '#58A6FF', accent2: '#F778BA', line: '#262C36', onAccent: '#0D1117' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'alexandria', bodyAr: 'readex-pro' },
    layout: { hero: 'type', extra: 'cards', schedule: 'table' },
  },
  {
    slug: 'charter', profile: 'law',
    name: { ar: 'ميثاق', en: 'Charter' },
    blurb: { ar: 'أبيض حجري وأخضر عميق وذهبي، مكتب محاماة حديث بلا زخرفة: صورة تتداخل معها بطاقة، خدمات كقائمة، وأسئلة شائعة.', en: 'Stone white, deep green and gold, a modern law firm without ornament: a photo with an overlapping card, services as a list and an FAQ.' },
    scheme: 'light',
    palette: { bg: '#F7F7F5', surface: '#FFFFFF', ink: '#1C1F24', muted: '#5C626B', accent: '#0B5D4E', accent2: '#C8A96A', line: '#E6E6E1', onAccent: '#FFFFFF' },
    fonts: { display: 'ibm-plex-sans', body: 'ibm-plex-sans', displayAr: 'ibm-plex-sans-arabic', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { about: 'overlap', offer: 'list', process: 'steps' },
  },
  {
    slug: 'stay', profile: 'hotel',
    name: { ar: 'إقامة', en: 'Stay' },
    blurb: { ar: 'أبيض مخضر وبرتقالي غروب وفيروزي، فندق صغير عصري: صورة بملء الشاشة، غرف في شبكة بينتو، ودعوة على صورة.', en: 'Greenish white, sunset orange and teal, a small modern hotel: a full-screen photo, rooms in a bento grid and an invitation over a photo.' },
    scheme: 'light',
    palette: { bg: '#F4F6F5', surface: '#FFFFFF', ink: '#17201D', muted: '#5A6662', accent: '#FF6A3D', accent2: '#1F6F78', line: '#E1E6E4', onAccent: '#1A0E08' },
    fonts: { display: 'work-sans', body: 'work-sans', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { nav: 'pill', hero: 'fullbleed', offer: 'bento', gallery: 'masonry', cta: 'image' },
  },
];
