import type { DesignInput } from './input';

export const modern: DesignInput[] = [
  {
    slug: 'bento', profile: 'agency',
    name: { ar: 'بينتو', en: 'Bento' },
    blurb: { ar: 'أبيض وأزرق كهربائي، شبكة بينتو للخدمات وقائمة طافية على شكل حبة.', en: 'White and electric blue, a bento grid of services and a floating pill menu.' },
    scheme: 'light',
    palette: { bg: '#FFFFFF', surface: '#F3F5F9', ink: '#0B1220', muted: '#5A6478', accent: '#2F5BFF', accent2: '#FF7A59', line: '#E3E7EF', onAccent: '#FFFFFF' },
    fonts: { display: 'plus-jakarta-sans', body: 'inter', displayAr: 'alexandria', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'pill', about: 'overlap', offer: 'bento' },
  },
  {
    slug: 'pulse', profile: 'gym',
    name: { ar: 'نبض', en: 'Pulse' },
    blurb: { ar: 'أسود وأخضر ليموني، عنوان ضخم وجدول حصص كجدول مواعيد رقمي.', en: 'Black and lime, a giant headline and a class timetable like a departures board.' },
    scheme: 'dark',
    palette: { bg: '#0C0D0F', surface: '#17191D', ink: '#F4F6F2', muted: '#9AA09A', accent: '#C6FF3D', accent2: '#3DD9FF', line: '#2A2D33', onAccent: '#0C0D0F' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'cairo', bodyAr: 'tajawal' },
    layout: { hero: 'type', schedule: 'table', footer: 'big' },
  },
  {
    slug: 'shifa', profile: 'clinic',
    name: { ar: 'شفاء', en: 'Shifa' },
    blurb: { ar: 'أبيض نظيف وتركواز هادئ، بطاقات ناعمة تبعث على الاطمئنان.', en: 'Clean white and calm teal, soft cards that put patients at ease.' },
    scheme: 'light',
    palette: { bg: '#F7FAFA', surface: '#FFFFFF', ink: '#0E2A30', muted: '#557077', accent: '#0E8C8C', accent2: '#9BE3D2', line: '#DCE8E8', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'tajawal', bodyAr: 'tajawal' },
    layout: { contact: 'form' },
  },
  {
    slug: 'sakan', profile: 'realestate',
    name: { ar: 'سكن', en: 'Sakan' },
    blurb: { ar: 'رمادي دافئ وطيني، صورة رئيسية كبيرة وبطاقات عقارات واضحة.', en: 'Warm grey and terracotta, a big hero photo and clear listing cards.' },
    scheme: 'light',
    palette: { bg: '#F6F3EF', surface: '#FFFFFF', ink: '#1E1B18', muted: '#6D665E', accent: '#C2562F', accent2: '#2E4A42', line: '#E5DED5', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'readex-pro', bodyAr: 'readex-pro' },
    layout: { hero: 'fullbleed' },
  },
  {
    slug: 'mishwar', profile: 'app',
    name: { ar: 'مشوار', en: 'Mishwar' },
    blurb: { ar: 'خزامى ونيلي، هاتفان يعرضان التطبيق وشبكة مزايا بأيقونات.', en: 'Lavender and indigo, two phones showing the app and a grid of icon features.' },
    scheme: 'light',
    palette: { bg: '#F6F4FF', surface: '#FFFFFF', ink: '#1A1640', muted: '#625D86', accent: '#5B3DF5', accent2: '#FFB547', line: '#E4E0F7', onAccent: '#FFFFFF' },
    fonts: { display: 'sora', body: 'dm-sans', displayAr: 'zain', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { nav: 'pill', hero: 'device', offer: 'bento', contact: 'center' },
    decor: ['icons'],
  },
  {
    slug: 'nord', profile: 'software',
    name: { ar: 'نورد', en: 'Nord' },
    blurb: { ar: 'أبيض مطفأ وأسود ونعناعي، عنوان متمركز وكل شيء في مكانه.', en: 'Off-white, black and mint, a centred headline and everything in its place.' },
    scheme: 'light',
    palette: { bg: '#FAFAF7', surface: '#FFFFFF', ink: '#111111', muted: '#63635E', accent: '#111111', accent2: '#34D399', line: '#E7E7E1', onAccent: '#FFFFFF' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'beiruti', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'centered', contact: 'form', footer: 'big' },
    css: 'html { --stat-on-dark: var(--accent2); }',
  },
];
