import type { DesignInput } from './input';

export const organic: DesignInput[] = [
  {
    slug: 'zaytoun', profile: 'farm',
    name: { ar: 'زيتون', en: 'Zaytoun' },
    blurb: { ar: 'أخضر زيتوني وذهب الزيت وأوراق مرسومة، لمزرعة تبيع من أرضها.', en: 'Olive green, oil gold and drawn leaves, for a farm selling from its own land.' },
    scheme: 'light',
    palette: { bg: '#F2F0E6', surface: '#FBFAF4', ink: '#27311F', muted: '#646B57', accent: '#5C7A2E', accent2: '#C89B3C', line: '#DCD9C8', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'harmattan' },
    decor: ['leaves', 'grain', 'divider-leaf'],
  },
  {
    slug: 'maramiya', profile: 'clinic',
    name: { ar: 'مريمية', en: 'Maramiya' },
    blurb: { ar: 'أخضر المريمية وبيج دافئ وأشكال ناعمة، لعيادة تبعث على الراحة.', en: 'Sage green, warm beige and soft shapes, for a clinic that feels restful.' },
    scheme: 'light',
    palette: { bg: '#EEF1EA', surface: '#FFFFFF', ink: '#23302A', muted: '#5E6B62', accent: '#4A735E', accent2: '#E3C9A8', line: '#D9DFD4', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'work-sans', displayAr: 'amiri', bodyAr: 'mada' },
    decor: ['leaves', 'divider-leaf'],
  },
  {
    slug: 'terra', profile: 'cafe',
    name: { ar: 'تراب', en: 'Terra' },
    blurb: { ar: 'ألوان الفخار والطين وأمواج ناعمة، لمقهى دافئ قريب من الأرض.', en: 'Clay and terracotta with soft waves, for a warm, earthy cafe.' },
    scheme: 'light',
    palette: { bg: '#F4EBE1', surface: '#FFF8F0', ink: '#3B2418', muted: '#7D5F4E', accent: '#A84E28', accent2: '#8C9A6B', line: '#E6D5C3', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-serif-display', body: 'work-sans', displayAr: 'aref-ruqaa', bodyAr: 'harmattan' },
    decor: ['grain', 'divider-wave'],
  },
  {
    slug: 'bustan', profile: 'wedding',
    name: { ar: 'بستان', en: 'Bustan' },
    blurb: { ar: 'عرس في حديقة: أخضر هادئ ووردي فاتح وأقواس من أغصان.', en: 'A garden wedding: quiet green, pale pink and arches of branches.' },
    scheme: 'light',
    palette: { bg: '#F5F3EC', surface: '#FFFFFF', ink: '#2C3527', muted: '#6B7364', accent: '#6E8250', accent2: '#E9B8A7', line: '#E2E1D5', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { nav: 'center', contact: 'card' },
    decor: ['leaves', 'divider-leaf'],
  },
  {
    slug: 'shahd', profile: 'sweets',
    name: { ar: 'شهد', en: 'Shahd' },
    blurb: { ar: 'لون العسل وخلايا سداسية، لمخبز حلويات طبيعي.', en: 'Honey colours and hexagon cells, for a natural bakery.' },
    scheme: 'light',
    palette: { bg: '#FBF3E4', surface: '#FFFAF0', ink: '#3A2A12', muted: '#7A6544', accent: '#C27A0E', accent2: '#8A6B3B', line: '#EAD9B8', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'harmattan' },
    decor: ['grain', 'honeycomb'],
  },
  {
    slug: 'linen', profile: 'boutique',
    name: { ar: 'كتّان', en: 'Linen' },
    blurb: { ar: 'بيج الكتّان وأخضر باهت وصور داخل أقواس، لملابس من خيوط طبيعية.', en: 'Linen beige, faded green and arched photos, for clothes made of natural fibres.' },
    scheme: 'light',
    palette: { bg: '#F1EEE7', surface: '#FAF8F3', ink: '#2E2B26', muted: '#706A60', accent: '#8A6E4B', accent2: '#A7B39A', line: '#DFDAD0', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'work-sans', displayAr: 'amiri', bodyAr: 'mada' },
    decor: ['grain', 'divider-leaf'],
  },
];
