import type { DesignInput } from './input';

export const organic: DesignInput[] = [
  {
    slug: 'zaytoun', profile: 'farm',
    name: { ar: 'زيتون', en: 'Zaytoun' },
    blurb: { ar: 'أخضر زيتوني وذهب الزيت وأوراق مرسومة، لمزرعة تبيع من أرضها.', en: 'Olive green, oil gold and drawn leaves, for a farm selling from its own land.' },
    scheme: 'light',
    palette: { bg: '#F2F0E6', surface: '#FBFAF4', ink: '#27311F', muted: '#646B57', accent: '#5C7A2E', accent2: '#C89B3C', line: '#DCD9C8', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'harmattan' },
    decor: ['leaves', 'grain', 'divider-leaf'],
  },
  {
    slug: 'maramiya', profile: 'clinic',
    name: { ar: 'مريمية', en: 'Maramiya' },
    blurb: { ar: 'أخضر المريمية وبيج دافئ وأشكال ناعمة، لعيادة تبعث على الراحة.', en: 'Sage green, warm beige and soft shapes, for a clinic that feels restful.' },
    scheme: 'light',
    palette: { bg: '#EEF1EA', surface: '#FFFFFF', ink: '#23302A', muted: '#5E6B62', accent: '#4A735E', accent2: '#E3C9A8', line: '#D9DFD4', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'work-sans', displayAr: 'amiri', bodyAr: 'mada' },
    decor: ['leaves', 'divider-leaf'],
  },
  {
    slug: 'terra', profile: 'cafe',
    name: { ar: 'تراب', en: 'Terra' },
    blurb: { ar: 'ألوان الفخار والطين وأمواج ناعمة، لمقهى دافئ قريب من الأرض.', en: 'Clay and terracotta with soft waves, for a warm, earthy cafe.' },
    scheme: 'light',
    palette: { bg: '#F4EBE1', surface: '#FFF8F0', ink: '#3B2418', muted: '#7D5F4E', accent: '#A84E28', accent2: '#8C9A6B', line: '#E6D5C3', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-serif-display', body: 'work-sans', displayAr: 'aref-ruqaa', bodyAr: 'harmattan' },
    decor: ['grain', 'divider-wave'],
  },
  {
    slug: 'bustan', profile: 'wedding',
    name: { ar: 'بستان', en: 'Bustan' },
    blurb: { ar: 'عرس في حديقة: أخضر هادئ ووردي فاتح وأقواس من أغصان.', en: 'A garden wedding: quiet green, pale pink and arches of branches.' },
    scheme: 'light',
    palette: { bg: '#F5F3EC', surface: '#FFFFFF', ink: '#2C3527', muted: '#6B7364', accent: '#6E8250', accent2: '#E9B8A7', line: '#E2E1D5', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { nav: 'center', contact: 'card' },
    decor: ['leaves', 'divider-leaf'],
  },
  {
    slug: 'shahd', profile: 'sweets',
    name: { ar: 'شهد', en: 'Shahd' },
    blurb: { ar: 'لون العسل وخلايا سداسية، لمخبز حلويات طبيعي.', en: 'Honey colours and hexagon cells, for a natural bakery.' },
    scheme: 'light',
    palette: { bg: '#FBF3E4', surface: '#FFFAF0', ink: '#3A2A12', muted: '#7A6544', accent: '#C27A0E', accent2: '#8A6B3B', line: '#EAD9B8', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'harmattan' },
    decor: ['grain', 'honeycomb'],
  },
  {
    slug: 'linen', profile: 'boutique',
    name: { ar: 'كتّان', en: 'Linen' },
    blurb: { ar: 'بيج الكتّان وأخضر باهت وصور داخل أقواس، لملابس من خيوط طبيعية.', en: 'Linen beige, faded green and arched photos, for clothes made of natural fibres.' },
    scheme: 'light',
    palette: { bg: '#F1EEE7', surface: '#FAF8F3', ink: '#2E2B26', muted: '#706A60', accent: '#8A6E4B', accent2: '#A7B39A', line: '#DFDAD0', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'work-sans', displayAr: 'amiri', bodyAr: 'mada' },
    decor: ['grain', 'divider-leaf'],
  },
  {
    slug: 'harvest', profile: 'restaurant',
    name: { ar: 'حصاد', en: 'Harvest' },
    blurb: { ar: 'طين وبنّي ترابي وأخضر حقلي، مطعم من المزرعة إلى المائدة: صورة في قوس، قائمة دافئة، وأوراق خفيفة.', en: 'Clay, earth brown and field green, a farm-to-table restaurant: a photo in an arch, a warm menu and light leaves.' },
    scheme: 'light',
    palette: { bg: '#F3EFE4', surface: '#FBF8F0', ink: '#2B2A1E', muted: '#625F4C', accent: '#8A5A2B', accent2: '#6B8E4E', line: '#DEDACB', onAccent: '#FFFFFF' },
    fonts: { display: 'newsreader', body: 'outfit', displayAr: 'markazi-text', bodyAr: 'mada' },
    layout: { offer: 'menu', gallery: 'masonry' },
    decor: ['leaves', 'divider-leaf'],
  },
  {
    slug: 'botanica', profile: 'perfume',
    name: { ar: 'نبات', en: 'Botanica' },
    blurb: { ar: 'أخضر مريمية ونحاسي على ورق نباتي، عطور من الزهر والعشب: صورة بجانب العنوان، عطور في بطاقات، وخطوات التقطير.', en: 'Sage and copper on botanical paper, perfumes of flower and herb: a photo beside the headline, perfumes in cards and the distilling steps.' },
    scheme: 'light',
    palette: { bg: '#EEF0E8', surface: '#FFFFFF', ink: '#263027', muted: '#5B665C', accent: '#4F6F52', accent2: '#C08B5C', line: '#DCE0D3', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'outfit', displayAr: 'el-messiri', bodyAr: 'mada' },
    layout: { hero: 'split', offer: 'cards', process: 'steps' },
    decor: ['leaves', 'grain'],
  },
  {
    slug: 'lodge', profile: 'hotel',
    name: { ar: 'نُزُل الغابة', en: 'Lodge' },
    blurb: { ar: 'لحاء الشجر وأخضر الطحلب وورق خشن، نُزُل بين الأشجار: صورة كاملة، غرف في بطاقات، وجدار صور.', en: 'Tree bark, moss green and rough paper, a lodge among the trees: a full-screen photo, rooms in cards and a wall of photos.' },
    scheme: 'light',
    palette: { bg: '#F2EDE3', surface: '#FBF7F0', ink: '#2A2620', muted: '#665E52', accent: '#6E5A3C', accent2: '#7E9F6B', line: '#E0D8CA', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'work-sans', displayAr: 'aref-ruqaa', bodyAr: 'mada' },
    layout: { hero: 'fullbleed', offer: 'cards', gallery: 'masonry' },
    decor: ['grain', 'divider-leaf'],
  },
  {
    slug: 'seedling', profile: 'academy',
    name: { ar: 'بذرة', en: 'Seedling' },
    blurb: { ar: 'أخضر نبتة وأصفر شمسي على ورق فاتح، مدرسة في الطبيعة: صورة في قوس، دورات في بطاقات، وموجات ناعمة.', en: 'Sprout green and sunshine yellow on pale paper, a school in nature: a photo in an arch, courses in cards and soft waves.' },
    scheme: 'light',
    palette: { bg: '#F4F2E9', surface: '#FFFFFF', ink: '#23301F', muted: '#5A6852', accent: '#3F7D4E', accent2: '#E0A100', line: '#DFE3D2', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'outfit', displayAr: 'el-messiri', bodyAr: 'tajawal' },
    layout: { offer: 'cards', process: 'steps' },
    decor: ['leaves', 'divider-wave'],
  },
  {
    slug: 'retreat', profile: 'gym',
    name: { ar: 'خلوة', en: 'Retreat' },
    blurb: { ar: 'رمل وبنّي سيينا وأخضر زيتوني، خلوة يوغا وتأمل: صورة في قوس، برنامج اليوم بخط زمني، وورق محبّب.', en: 'Sand, sienna and olive, a yoga and meditation retreat: a photo in an arch, the day\'s programme as a timeline and grainy paper.' },
    scheme: 'light',
    palette: { bg: '#F1ECE4', surface: '#FFFFFF', ink: '#2E2722', muted: '#6B6058', accent: '#A0522D', accent2: '#8A9A5B', line: '#E2D9CD', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'outfit', displayAr: 'aref-ruqaa', bodyAr: 'harmattan' },
    layout: { schedule: 'timeline' },
    decor: ['grain', 'divider-leaf'],
  },
  {
    slug: 'earthwork', profile: 'construction',
    name: { ar: 'حجر وتراب', en: 'Earthwork' },
    blurb: { ar: 'حجر وطين وأخضر، بنّاء يعمل بالمواد المحلية: صورة بجانب العنوان، أعمال في جدار، ومراحل البناء بخطوات.', en: 'Stone, clay and green, a builder working with local materials: a photo beside the headline, work on a wall and the building stages in steps.' },
    scheme: 'light',
    palette: { bg: '#EDE8DD', surface: '#F7F4EC', ink: '#2A2721', muted: '#625C50', accent: '#7A5C3E', accent2: '#5E7D4A', line: '#DAD3C3', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-serif-display', body: 'dm-sans', displayAr: 'reem-kufi', bodyAr: 'harmattan' },
    layout: { hero: 'split', offer: 'cards', gallery: 'masonry', process: 'steps' },
    decor: ['grain', 'leaves'],
  },
];
