import type { DesignInput } from './input';

// Pixel: stepped borders, a limited palette and pixel type for headings and
// labels; the body stays in a readable face.
export const pixel: DesignInput[] = [
  {
    slug: 'arcade-cafe', profile: 'cafe',
    name: { ar: 'مقهى البكسل', en: 'Pixel café' },
    blurb: { ar: 'كحلي ليلي وأصفر وأحمر، مقهى ألعاب بقلوب حياة وصناديق حوار.', en: 'Night navy, yellow and red, a game café with life hearts and dialogue boxes.' },
    scheme: 'dark',
    palette: { bg: '#2B2D5C', surface: '#363970', ink: '#F8F4E3', muted: '#BDB9D6', accent: '#FFD23F', accent2: '#E4405F', line: '#14152E', onAccent: '#2B2D5C' },
    fonts: { display: 'press-start-2p', body: 'nunito', displayAr: 'handjet', bodyAr: 'tajawal' },
    decor: ['grid'],
  },
  {
    slug: 'quest', profile: 'app',
    name: { ar: 'مهمّة', en: 'Quest' },
    blurb: { ar: 'أخضر غابة وبني وذهبي، تطبيق عادات يحوّل يومك إلى مهمات ومستويات.', en: 'Forest green, brown and gold, a habit app that turns your day into quests and levels.' },
    scheme: 'dark',
    palette: { bg: '#1E3A2B', surface: '#284A37', ink: '#F3F0D8', muted: '#B9C2A6', accent: '#F7C948', accent2: '#E26D3D', line: '#0E1E15', onAccent: '#1E3A2B' },
    fonts: { display: 'silkscreen', body: 'nunito', displayAr: 'handjet', bodyAr: 'tajawal' },
    layout: { hero: 'device' },
  },
  {
    slug: 'sprite', profile: 'software',
    name: { ar: 'سبرايت', en: 'Sprite' },
    blurb: { ar: 'أبيض ورقي وأزرق NES وأحمر، أداة مطورين تشرح نفسها كدليل لعبة.', en: 'Paper white, NES blue and red, a developer tool that explains itself like a game manual.' },
    scheme: 'light',
    palette: { bg: '#F4F1E8', surface: '#FFFFFF', ink: '#1A1C2C', muted: '#4F5168', accent: '#3B5DC9', accent2: '#B13E53', line: '#1A1C2C', onAccent: '#FFFFFF' },
    fonts: { display: 'press-start-2p', body: 'ibm-plex-sans', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic', accent: 'vt323' },
    layout: { hero: 'centered' },
  },
  {
    slug: 'level-up', profile: 'academy',
    name: { ar: 'المستوى التالي', en: 'Level up' },
    blurb: { ar: 'بنفسجي وأخضر نيون، أكاديمية برمجة ألعاب للأطفال بشارات وخبرات.', en: 'Purple and neon green, a game-coding academy for kids with badges and XP.' },
    scheme: 'dark',
    palette: { bg: '#29174A', surface: '#36215E', ink: '#F4EEFF', muted: '#C2B4DE', accent: '#38E07B', accent2: '#FF77A8', line: '#140A26', onAccent: '#0B2414' },
    fonts: { display: 'press-start-2p', body: 'nunito', displayAr: 'handjet', bodyAr: 'baloo-bhaijaan-2' },
    layout: { pricing: 'pricing', process: 'steps' },
  },
  {
    slug: 'lan-party', profile: 'conference',
    name: { ar: 'بطولة', en: 'LAN party' },
    blurb: { ar: 'أسود وأخضر شاشة وأحمر، بطولة ألعاب إلكترونية بلوحة نتائج بكسلية.', en: 'Black, screen green and red, an esports tournament with a pixel scoreboard.' },
    scheme: 'dark',
    palette: { bg: '#0B0D0B', surface: '#161A16', ink: '#E8FFE8', muted: '#9DB89D', accent: '#39FF6A', accent2: '#FF3B3B', line: '#000000', onAccent: '#031A08' },
    fonts: { display: 'press-start-2p', body: 'ibm-plex-sans', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic', accent: 'vt323' },
    layout: { schedule: 'timeline', stats: 'big' },
    decor: ['scanlines'],
  },
  {
    slug: 'eight-bit', profile: 'agency',
    name: { ar: '٨ بت', en: '8-bit' },
    blurb: { ar: 'أصفر وأسود وأزرق، استوديو تصميم ألعاب مستقل بأعمال في إطارات بكسل.', en: 'Yellow, black and blue, an indie game-design studio with work in pixel frames.' },
    scheme: 'light',
    palette: { bg: '#FFE45E', surface: '#FFF3A8', ink: '#111111', muted: '#4A4320', accent: '#2C4BFF', accent2: '#FF3D3D', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'press-start-2p', body: 'space-grotesk', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'type', gallery: 'gallery' },
  },
  {
    slug: 'marquee-sign', profile: 'signage',
    name: { ar: 'شاشة LED', en: 'LED board' },
    blurb: { ar: 'أسود وأحمر LED وكهرماني، مصنع شاشات إعلانية بنقاط مضيئة.', en: 'Black, LED red and amber, a maker of advertising screens made of glowing dots.' },
    scheme: 'dark',
    palette: { bg: '#100808', surface: '#1E1010', ink: '#FFEDE0', muted: '#C9A799', accent: '#FF4D2E', accent2: '#FFB020', line: '#000000', onAccent: '#1A0500' },
    fonts: { display: 'silkscreen', body: 'inter', displayAr: 'handjet', bodyAr: 'cairo', accent: 'vt323' },
    layout: { gallery: 'gallery' },
    decor: ['glow'],
  },
  {
    slug: 'candy-crush', profile: 'sweets',
    name: { ar: 'حلوى بكسل', en: 'Candy pixels' },
    blurb: { ar: 'وردي وتركوازي وأصفر، محل حلويات بقطع مربعة كمستويات لعبة ألغاز.', en: 'Pink, turquoise and yellow, a sweet shop with square treats like puzzle-game levels.' },
    scheme: 'light',
    palette: { bg: '#FFE6F0', surface: '#FFF6FA', ink: '#3A1030', muted: '#704A62', accent: '#E8288A', accent2: '#2EC4B6', line: '#3A1030', onAccent: '#FFFFFF' },
    fonts: { display: 'silkscreen', body: 'nunito', displayAr: 'handjet', bodyAr: 'baloo-bhaijaan-2' },
    layout: { offer: 'menu' },
  },
  {
    slug: 'boss-fight', profile: 'gym',
    name: { ar: 'الزعيم', en: 'Boss fight' },
    blurb: { ar: 'أحمر قانٍ وأسود وأصفر، نادي ملاكمة بشريط طاقة وجولات.', en: 'Crimson, black and yellow, a boxing club with a health bar and rounds.' },
    scheme: 'dark',
    palette: { bg: '#1A0B0B', surface: '#2A1212', ink: '#FFF0E6', muted: '#C9A396', accent: '#FFD23F', accent2: '#E4262E', line: '#000000', onAccent: '#1A0B0B' },
    fonts: { display: 'press-start-2p', body: 'archivo', displayAr: 'handjet', bodyAr: 'cairo' },
    layout: { pricing: 'pricing', stats: 'big' },
  },
  {
    slug: 'diner-8bit', profile: 'restaurant',
    name: { ar: 'مطعم البكسل', en: 'Pixel diner' },
    blurb: { ar: 'أحمر طماطم وكريمي وأخضر، مطعم برغر بقائمة كشاشة اختيار في لعبة.', en: 'Tomato red, cream and green, a burger diner with a menu like a game\'s select screen.' },
    scheme: 'light',
    palette: { bg: '#FFF4E0', surface: '#FFFFFF', ink: '#2A1508', muted: '#6B5240', accent: '#D7342A', accent2: '#3E9C4B', line: '#2A1508', onAccent: '#FFFFFF' },
    fonts: { display: 'press-start-2p', body: 'nunito', displayAr: 'handjet', bodyAr: 'tajawal' },
    layout: { offer: 'menu', hero: 'split' },
  },
  {
    slug: 'harvest-moon', profile: 'farm',
    name: { ar: 'موسم الحصاد', en: 'Harvest' },
    blurb: { ar: 'أخضر عشبي وبني تربة وأصفر قمح، مزرعة عائلية كلعبة زراعة لطيفة.', en: 'Grass green, soil brown and wheat yellow, a family farm like a cosy farming game.' },
    scheme: 'light',
    palette: { bg: '#E9F5D0', surface: '#F7FCEB', ink: '#2B2410', muted: '#5F5638', accent: '#7A4A1E', accent2: '#F2C230', line: '#2B2410', onAccent: '#FFFFFF' },
    fonts: { display: 'silkscreen', body: 'nunito', displayAr: 'handjet', bodyAr: 'tajawal' },
    layout: { gallery: 'gallery', hero: 'collage' },
  },
  {
    slug: 'blocks', profile: 'construction',
    name: { ar: 'مكعبات', en: 'Blocks' },
    blurb: { ar: 'أصفر تحذيري ورمادي وأزرق سماء، شركة مقاولات تبني بالمكعبات كلعبة بناء.', en: 'Hazard yellow, grey and sky blue, a contractor that builds in blocks like a building game.' },
    scheme: 'light',
    palette: { bg: '#E8F1FB', surface: '#FFFFFF', ink: '#1C232B', muted: '#505B66', accent: '#F5B400', accent2: '#5B6672', line: '#1C232B', onAccent: '#1C232B' },
    fonts: { display: 'press-start-2p', body: 'archivo', displayAr: 'handjet', bodyAr: 'cairo' },
    layout: { process: 'steps', gallery: 'gallery' },
  },
];
