import type { DesignInput } from './input';

export const playful: DesignInput[] = [
  {
    slug: 'candy', profile: 'sweets',
    name: { ar: 'حلوى', en: 'Candy' },
    blurb: { ar: 'وردي وأصفر ونعناعي، قصاصات ملونة وحدود سميكة وصورة داخل فقاعة.', en: 'Pink, yellow and mint, confetti, thick outlines and a photo inside a blob.' },
    scheme: 'light',
    palette: { bg: '#FFF4E8', surface: '#FFFFFF', ink: '#2B1B17', muted: '#6E5650', accent: '#FF5C8A', accent2: '#FFC93C', line: '#2B1B17', onAccent: '#2B1B17' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'lemonada', bodyAr: 'baloo-bhaijaan-2' },
    decor: ['confetti', 'divider-wave', 'sparkles'],
  },
  {
    slug: 'kids', profile: 'academy',
    name: { ar: 'صغار', en: 'Kids' },
    blurb: { ar: 'أزرق ووردي فاقعان وأشكال مرحة، لأكاديمية أطفال تحب الضجيج الجميل.', en: 'Bright blue and pink with cheerful shapes, for a kids\' academy that loves happy noise.' },
    scheme: 'light',
    palette: { bg: '#FFFBEA', surface: '#FFFFFF', ink: '#1E2A4A', muted: '#5B6584', accent: '#3A86FF', accent2: '#FF006E', line: '#1E2A4A', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'baloo-bhaijaan-2', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'collage' },
    decor: ['confetti', 'divider-wave'],
  },
  {
    slug: 'juicy', profile: 'cafe',
    name: { ar: 'عصير', en: 'Juicy' },
    blurb: { ar: 'برتقالي وأخضر وملصقات مائلة، كبار عصائر صيفي على الشاطئ.', en: 'Orange, green and tilted stickers, like a summer juice bar by the beach.' },
    scheme: 'light',
    palette: { bg: '#FFF1E0', surface: '#FFFFFF', ink: '#2D1E12', muted: '#6F5A47', accent: '#FF7A00', accent2: '#2BB673', line: '#2D1E12', onAccent: '#2D1E12' },
    fonts: { display: 'lilita-one', body: 'nunito', displayAr: 'marhey', bodyAr: 'tajawal' },
    decor: ['sparkles', 'divider-wave'],
  },
  {
    slug: 'pop', profile: 'app',
    name: { ar: 'بوب', en: 'Pop' },
    blurb: { ar: 'بنفسجي وأصفر وأيقونات في فقاعات، تطبيق ودود يبتسم لك.', en: 'Purple and yellow with icons in bubbles, a friendly app that smiles back.' },
    scheme: 'light',
    palette: { bg: '#F3EDFF', surface: '#FFFFFF', ink: '#1B1035', muted: '#5D5277', accent: '#7B2FF7', accent2: '#FFD43B', line: '#1B1035', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro' },
    layout: { hero: 'device', contact: 'center' },
    decor: ['confetti', 'icons'],
  },
  {
    slug: 'wavy', profile: 'hotel',
    name: { ar: 'موج', en: 'Wavy' },
    blurb: { ar: 'تركواز ومرجاني وأمواج تفصل الأقسام، لمنتجع بحري مرح.', en: 'Turquoise, coral and waves between sections, for a cheerful beach resort.' },
    scheme: 'light',
    palette: { bg: '#EFFBFA', surface: '#FFFFFF', ink: '#10363A', muted: '#4E6E70', accent: '#FF6F59', accent2: '#1FB5AC', line: '#10363A', onAccent: '#10363A' },
    fonts: { display: 'nunito', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    decor: ['divider-wave', 'sparkles'],
  },
  {
    slug: 'sticker', profile: 'signage',
    name: { ar: 'ملصق', en: 'Sticker' },
    blurb: { ar: 'أحمر وأصفر وأسود وبطاقات كالملصقات المائلة، لورشة طباعة ستيكرات.', en: 'Red, yellow and black with cards like tilted stickers, for a sticker print shop.' },
    scheme: 'light',
    palette: { bg: '#FFFDF2', surface: '#FFFFFF', ink: '#111111', muted: '#555555', accent: '#FF3B30', accent2: '#FFD60A', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'lalezar', bodyAr: 'tajawal' },
    layout: { nav: 'bar', hero: 'poster' },
    decor: ['sparkles'],
  },
];
