import type { DesignInput } from './input';

export const playful: DesignInput[] = [
  {
    slug: 'candy', profile: 'sweets',
    name: { ar: 'حلوى', en: 'Candy' },
    blurb: { ar: 'وردي وأصفر ونعناعي، قصاصات ملونة وحدود سميكة وصورة داخل فقاعة.', en: 'Pink, yellow and mint, confetti, thick outlines and a photo inside a blob.' },
    scheme: 'light',
    palette: { bg: '#FFF4E8', surface: '#FFFFFF', ink: '#2B1B17', muted: '#6E5650', accent: '#FF5C8A', accent2: '#FFC93C', line: '#2B1B17', onAccent: '#2B1B17' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'lemonada', bodyAr: 'baloo-bhaijaan-2' },
    decor: ['confetti', 'divider-wave', 'sparkles'],
  },
  {
    slug: 'kids', profile: 'academy',
    name: { ar: 'صغار', en: 'Kids' },
    blurb: { ar: 'أزرق ووردي فاقعان وأشكال مرحة، لأكاديمية أطفال تحب الضجيج الجميل.', en: 'Bright blue and pink with cheerful shapes, for a kids\' academy that loves happy noise.' },
    scheme: 'light',
    palette: { bg: '#FFFBEA', surface: '#FFFFFF', ink: '#1E2A4A', muted: '#5B6584', accent: '#3A86FF', accent2: '#FF006E', line: '#1E2A4A', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'baloo-bhaijaan-2', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'collage' },
    decor: ['confetti', 'divider-wave'],
  },
  {
    slug: 'juicy', profile: 'cafe',
    name: { ar: 'عصير', en: 'Juicy' },
    blurb: { ar: 'برتقالي وأخضر وملصقات مائلة، كبار عصائر صيفي على الشاطئ.', en: 'Orange, green and tilted stickers, like a summer juice bar by the beach.' },
    scheme: 'light',
    palette: { bg: '#FFF1E0', surface: '#FFFFFF', ink: '#2D1E12', muted: '#6F5A47', accent: '#FF7A00', accent2: '#2BB673', line: '#2D1E12', onAccent: '#2D1E12' },
    fonts: { display: 'lilita-one', body: 'nunito', displayAr: 'marhey', bodyAr: 'tajawal' },
    decor: ['sparkles', 'divider-wave'],
  },
  {
    slug: 'pop', profile: 'app',
    name: { ar: 'بوب', en: 'Pop' },
    blurb: { ar: 'بنفسجي وأصفر وأيقونات في فقاعات، تطبيق ودود يبتسم لك.', en: 'Purple and yellow with icons in bubbles, a friendly app that smiles back.' },
    scheme: 'light',
    palette: { bg: '#F3EDFF', surface: '#FFFFFF', ink: '#1B1035', muted: '#5D5277', accent: '#7B2FF7', accent2: '#FFD43B', line: '#1B1035', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro' },
    layout: { hero: 'device', contact: 'center' },
    decor: ['confetti', 'icons'],
  },
  {
    slug: 'wavy', profile: 'hotel',
    name: { ar: 'موج', en: 'Wavy' },
    blurb: { ar: 'تركواز ومرجاني وأمواج تفصل الأقسام، لمنتجع بحري مرح.', en: 'Turquoise, coral and waves between sections, for a cheerful beach resort.' },
    scheme: 'light',
    palette: { bg: '#EFFBFA', surface: '#FFFFFF', ink: '#10363A', muted: '#4E6E70', accent: '#FF6F59', accent2: '#1FB5AC', line: '#10363A', onAccent: '#10363A' },
    fonts: { display: 'nunito', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    decor: ['divider-wave', 'sparkles'],
  },
  {
    slug: 'sticker', profile: 'signage',
    name: { ar: 'ملصق', en: 'Sticker' },
    blurb: { ar: 'أحمر وأصفر وأسود وبطاقات كالملصقات المائلة، لورشة طباعة ستيكرات.', en: 'Red, yellow and black with cards like tilted stickers, for a sticker print shop.' },
    scheme: 'light',
    palette: { bg: '#FFFDF2', surface: '#FFFFFF', ink: '#111111', muted: '#555555', accent: '#FF3B30', accent2: '#FFD60A', line: '#111111', onAccent: '#FFFFFF' },
    fonts: { display: 'bricolage-grotesque', body: 'dm-sans', displayAr: 'lalezar', bodyAr: 'tajawal' },
    layout: { nav: 'bar', hero: 'poster' },
    decor: ['sparkles'],
  },
  {
    slug: 'yum', profile: 'restaurant',
    name: { ar: 'لذيذ', en: 'Yum' },
    blurb: { ar: 'كريمي وبرتقالي فاقع وأخضر، مطعم برغر مبهج: صور متراكبة مائلة، بطاقات أطباق مستديرة، وقصاصات ملونة.', en: 'Cream, loud orange and green, a cheerful burger joint: tilted stacked photos, rounded dish cards and colourful confetti.' },
    scheme: 'light',
    palette: { bg: '#FFF6E5', surface: '#FFFFFF', ink: '#2D1B12', muted: '#6E5546', accent: '#F2541B', accent2: '#2EB872', line: '#F6E3C6', onAccent: '#FFFFFF' },
    fonts: { display: 'bungee', body: 'nunito', displayAr: 'lalezar', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'collage', offer: 'cards', gallery: 'gallery' },
    decor: ['confetti', 'divider-zigzag'],
  },
  {
    slug: 'barnyard', profile: 'farm',
    name: { ar: 'حظيرة', en: 'Barnyard' },
    blurb: { ar: 'أخضر عشبي وأصفر شمسي، مزرعة يحبها الصغار: صورة مستديرة الزوايا، منتجات في بطاقات، وموجات بين الأقسام.', en: 'Grass green and sunshine yellow, a farm children love: a round-cornered photo, produce in cards and waves between sections.' },
    scheme: 'light',
    palette: { bg: '#F1FBEF', surface: '#FFFFFF', ink: '#1E3320', muted: '#546B55', accent: '#2F8F3E', accent2: '#FFC93C', line: '#DDEFD9', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'nunito', displayAr: 'baloo-bhaijaan-2', bodyAr: 'tajawal' },
    layout: { offer: 'cards', process: 'steps' },
    decor: ['sparkles', 'divider-wave'],
  },
  {
    slug: 'smiles', profile: 'clinic',
    name: { ar: 'ابتسامات', en: 'Smiles' },
    blurb: { ar: 'سماوي فاتح ووردي وأزرق، عيادة أسنان للأطفال لا تخيف أحدًا: أيقونات مرحة، خطوات بسيطة، وباقات واضحة.', en: 'Light sky, pink and blue, a children\'s dentist that scares nobody: playful icons, simple steps and clear plans.' },
    scheme: 'light',
    palette: { bg: '#EEF7FF', surface: '#FFFFFF', ink: '#12304A', muted: '#4E6A82', accent: '#FF6B9A', accent2: '#3AB0FF', line: '#D7E8F7', onAccent: '#2A0A16' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { offer: 'cards', process: 'steps' },
    decor: ['sparkles', 'divider-wave', 'icons'],
  },
  {
    slug: 'toybox', profile: 'boutique',
    name: { ar: 'صندوق الألعاب', en: 'Toybox' },
    blurb: { ar: 'بنفسجي وبرتقالي على كريمي، محل أطفال كعلبة ألوان: صور متراكبة، قطع في شبكة بينتو، وقصاصات في كل مكان.', en: 'Purple and orange on cream, a children\'s shop like a box of crayons: stacked photos, pieces in a bento grid and confetti everywhere.' },
    scheme: 'light',
    palette: { bg: '#FFF8EC', surface: '#FFFFFF', ink: '#2B1E3A', muted: '#6A5C78', accent: '#7B5CFF', accent2: '#FF9F1C', line: '#F2E6D2', onAccent: '#FFFFFF' },
    fonts: { display: 'lilita-one', body: 'nunito', displayAr: 'marhey', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'collage', offer: 'bento', extra: 'cards' },
    decor: ['confetti', 'sparkles'],
  },
  {
    slug: 'bounce', profile: 'gym',
    name: { ar: 'قفزة', en: 'Bounce' },
    blurb: { ar: 'وردي فاتح وفوشي وفيروزي، صالة حركة ورقص للصغار: عنوان في المنتصف، جدول الحصص بخط زمني، وقصاصات.', en: 'Light pink, fuchsia and turquoise, a movement and dance studio for kids: a centred headline, the class schedule as a timeline and confetti.' },
    scheme: 'light',
    palette: { bg: '#FFF1F5', surface: '#FFFFFF', ink: '#3A1030', muted: '#7A4F6C', accent: '#E83F6F', accent2: '#2EC4B6', line: '#F6D9E3', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'dm-sans', displayAr: 'lalezar', bodyAr: 'readex-pro' },
    layout: { hero: 'centered', offer: 'cards', schedule: 'timeline' },
    decor: ['confetti', 'divider-wave'],
  },
  {
    slug: 'jolly', profile: 'agency',
    name: { ar: 'مرح', en: 'Jolly' },
    blurb: { ar: 'أصفر ليموني وأزرق صافٍ، وكالة تأخذ العمل بجدية والشكل بخفة: عنوان كالملصق، أعمال في جدار، وبريق صغير.', en: 'Lemon yellow and clear blue, an agency serious about work and light about looks: a poster headline, work on a wall and small sparkles.' },
    scheme: 'light',
    palette: { bg: '#FFFBEA', surface: '#FFFFFF', ink: '#1F1F1F', muted: '#5F5B4E', accent: '#2F6BFF', accent2: '#FFC300', line: '#F0E8C8', onAccent: '#FFFFFF' },
    fonts: { display: 'baloo-2', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'tajawal' },
    layout: { nav: 'bar', hero: 'poster', gallery: 'masonry', process: 'steps' },
    decor: ['sparkles', 'confetti'],
  },
];
