import type { DesignInput } from './input';

export const retro: DesignInput[] = [
  {
    slug: 'groovy', profile: 'cafe',
    name: { ar: 'سبعينات', en: 'Groovy' },
    blurb: { ar: 'برتقالي وخردلي وبني وأشرطة قوس قزح، بخط منتفخ من السبعينات.', en: 'Orange, mustard and brown with rainbow stripes and a puffy seventies face.' },
    scheme: 'light',
    palette: { bg: '#F6E7C8', surface: '#FFF4DE', ink: '#3A1C0B', muted: '#7A5A3F', accent: '#E8590C', accent2: '#F2A900', line: '#3A1C0B', onAccent: '#FFF4DE' },
    fonts: { display: 'shrikhand', body: 'work-sans', displayAr: 'lalezar', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'menu' },
    decor: ['seventies', 'stripes', 'divider-wave'],
  },
  {
    slug: 'synth', profile: 'gym',
    name: { ar: 'سينث', en: 'Synth' },
    blurb: { ar: 'شمس الثمانينات المخططة وشبكة نيون وردية وسماوية، كشريط فيديو قديم.', en: 'A striped eighties sun and a pink-and-cyan neon grid, like an old VHS tape.' },
    scheme: 'dark',
    palette: { bg: '#12052B', surface: '#1D0B40', ink: '#FFE9FF', muted: '#C9A7E8', accent: '#FF2E97', accent2: '#00E5FF', line: '#3A1A6B', onAccent: '#12052B' },
    fonts: { display: 'righteous', body: 'rajdhani', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro' },
    layout: { hero: 'centered', contact: 'center' },
    decor: ['synth', 'sun', 'scanlines'],
  },
  {
    slug: 'desktop-98', profile: 'software',
    name: { ar: 'سطح المكتب ٩٨', en: 'Desktop 98' },
    blurb: { ar: 'نوافذ رمادية بأشرطة عنوان زرقاء وأزرار بارزة، كحاسوب التسعينات.', en: 'Grey windows with blue title bars and bevelled buttons, like a nineties PC.' },
    scheme: 'light',
    palette: { bg: '#008080', surface: '#C0C0C0', ink: '#000000', muted: '#303030', accent: '#000080', accent2: '#FFFFFF', line: '#808080', onAccent: '#FFFFFF' },
    fonts: { display: 'vt323', body: 'space-mono', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'split', about: 'columns', contact: 'form', footer: 'simple' },
    decor: ['win98'],
  },
  {
    slug: 'memphis', profile: 'agency',
    name: { ar: 'ممفيس', en: 'Memphis' },
    blurb: { ar: 'وردي وتركواز ونقاط وخطوط متعرجة، بروح تصميم ممفيس في الثمانينات.', en: 'Pink, turquoise, dots and squiggles, in the spirit of eighties Memphis design.' },
    scheme: 'light',
    palette: { bg: '#FFF7EC', surface: '#FFFFFF', ink: '#1A1A1A', muted: '#555555', accent: '#FF5E8E', accent2: '#29C4C4', line: '#1A1A1A', onAccent: '#1A1A1A' },
    fonts: { display: 'bungee', body: 'dm-sans', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'collage' },
    decor: ['memphis', 'confetti'],
  },
  {
    slug: 'roadside', profile: 'garage',
    name: { ar: 'كراج الطريق', en: 'Roadside' },
    blurb: { ar: 'مربعات حمراء وبيضاء وتركواز معدني، ورشة ككراج على طريق سفر من الخمسينات: عنوان كالملصق وقائمة أسعار كلوحة الخدمات.', en: 'Red-and-white checks and chrome turquoise, a workshop like a fifties roadside garage: a poster headline and a price list like a service board.' },
    scheme: 'light',
    palette: { bg: '#FFF8EE', surface: '#FFFFFF', ink: '#1C1C1C', muted: '#5A5A5A', accent: '#D62828', accent2: '#00A6A6', line: '#1C1C1C', onAccent: '#FFFFFF' },
    fonts: { display: 'lilita-one', body: 'nunito', displayAr: 'rakkas', bodyAr: 'tajawal' },
    layout: { hero: 'poster', offer: 'menu' },
    decor: ['diner'],
  },
  {
    slug: 'star-arcade', profile: 'stars',
    name: { ar: 'أركيد النجوم', en: 'Star Arcade' },
    blurb: { ar: 'خط بكسلي وأخضر نيون وخطوط مسح، نادي فلك على شاشة أركيد قديمة: الليالي في جدول كقائمة أعلى النقاط.', en: 'Pixel type, neon green and scanlines, an astronomy club on an old arcade screen: the nights in a table like a high-score list.' },
    scheme: 'dark',
    palette: { bg: '#0B0B1F', surface: '#15153A', ink: '#F7F7FF', muted: '#A3A3D6', accent: '#39FF14', accent2: '#FF3EA5', line: '#2A2A66', onAccent: '#0B0B1F' },
    fonts: { display: 'press-start-2p', body: 'chakra-petch', displayAr: 'handjet', bodyAr: 'readex-pro' },
    layout: { hero: 'centered', extra: 'cards', schedule: 'table', contact: 'center' },
    decor: ['arcade', 'scanlines'],
  },
  {
    slug: 'soda', profile: 'sweets',
    name: { ar: 'نافورة الصودا', en: 'Soda Fountain' },
    blurb: { ar: 'كريمي وأحمر كرزي وأخضر نعناعي، محل مثلّجات من الستينات: خطوط مائلة ملونة، بطاقات حلوى، وموجات.', en: 'Cream, cherry red and mint, a sixties ice-cream parlour: coloured diagonal stripes, sweet cards and waves.' },
    scheme: 'light',
    palette: { bg: '#FFF4E6', surface: '#FFFFFF', ink: '#3A1D1D', muted: '#7A5555', accent: '#E63946', accent2: '#2A9D8F', line: '#F3DCC6', onAccent: '#FFFFFF' },
    fonts: { display: 'righteous', body: 'nunito', displayAr: 'lemonada', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'cards' },
    decor: ['stripes', 'divider-wave'],
  },
  {
    slug: 'instant', profile: 'photographer',
    name: { ar: 'فوري', en: 'Instant' },
    blurb: { ar: 'ورق مصفرّ وبرتقالي غروب وفيروزي، مختبر صور من السبعينات: صور فورية متراكبة، جدار أعمال، وباقات ملونة.', en: 'Yellowed paper, sunset orange and teal, a seventies photo lab: stacked instant prints, a wall of work and colourful packages.' },
    scheme: 'light',
    palette: { bg: '#F2EDE4', surface: '#FFFFFF', ink: '#222222', muted: '#5E5850', accent: '#E76F51', accent2: '#2A9D8F', line: '#DED6C8', onAccent: '#1F0D06' },
    fonts: { display: 'righteous', body: 'work-sans', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'collage', gallery: 'masonry' },
    decor: ['seventies', 'divider-wave'],
  },
  {
    slug: 'motel', profile: 'hotel',
    name: { ar: 'موتيل', en: 'Motel' },
    blurb: { ar: 'رملي ووردي أحمر وفيروزي، موتيل على طريق صحراوي: شمس مخططة خلف عنوان كالملصق، وغرف في بطاقات.', en: 'Sand, pinkish red and teal, a motel on a desert road: a striped sun behind a poster headline and rooms in cards.' },
    scheme: 'light',
    palette: { bg: '#F6E3C5', surface: '#FFF3E0', ink: '#2B1B12', muted: '#6E5440', accent: '#C23B4E', accent2: '#00798C', line: '#E6CCA6', onAccent: '#FFFFFF' },
    fonts: { display: 'lilita-one', body: 'work-sans', displayAr: 'lalezar', bodyAr: 'mada' },
    layout: { offer: 'cards', gallery: 'gallery' },
    decor: ['sun', 'stripes'],
  },
  {
    slug: 'cassette', profile: 'music',
    name: { ar: 'كاسيت', en: 'Cassette' },
    blurb: { ar: 'كريمي وبنفسجي وأصفر بأشكال ممفيس، مدرسة موسيقى بشريط من التسعينات: صور متراكبة، أشكال مرحة، وبطاقات دروس ملونة.', en: 'Cream, purple and yellow with Memphis shapes, a music school with a nineties mixtape: stacked photos, playful shapes and colourful lesson cards.' },
    scheme: 'light',
    palette: { bg: '#FDF6EC', surface: '#FFFFFF', ink: '#1E1B4B', muted: '#57537A', accent: '#7C3AED', accent2: '#FACC15', line: '#EDE3F7', onAccent: '#FFFFFF' },
    fonts: { display: 'righteous', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro' },
    layout: { hero: 'collage', offer: 'cards', process: 'steps' },
    decor: ['memphis', 'confetti'],
  },
  {
    slug: 'wavelength', profile: 'app',
    name: { ar: 'موجة', en: 'Wavelength' },
    blurb: { ar: 'بنفسجي ليلي ووردي نيون وسماوي، تطبيق بروح الثمانينات: شمس مخططة وشبكة أفق، هاتفان، وخطوط مسح.', en: 'Night purple, neon pink and cyan, an app with an eighties soul: a striped sun and horizon grid, two phones and scan lines.' },
    scheme: 'dark',
    palette: { bg: '#140A2E', surface: '#1E1142', ink: '#F6EEFF', muted: '#B3A3D6', accent: '#FF3EA5', accent2: '#3DF2FF', line: '#2D1B5C', onAccent: '#140A2E' },
    fonts: { display: 'audiowide', body: 'rajdhani', displayAr: 'handjet', bodyAr: 'readex-pro' },
    layout: { hero: 'device', offer: 'cards' },
    decor: ['synth', 'sun', 'scanlines'],
  },
  {
    slug: 'sundown', profile: 'realestate',
    name: { ar: 'غروب', en: 'Sundown' },
    blurb: { ar: 'وردي فاتح ومرجاني وفيروزي، عقارات على شاطئ الثمانينات: شمس مخططة، عنوان في المنتصف، وعروض في بطاقات.', en: 'Light pink, coral and turquoise, property on an eighties beachfront: a striped sun, a centred headline and listings in cards.' },
    scheme: 'light',
    palette: { bg: '#FFF0F3', surface: '#FFFFFF', ink: '#2B1838', muted: '#6C5A78', accent: '#FF5C8A', accent2: '#00A3AE', line: '#F6D7E0', onAccent: '#2A0A16' },
    fonts: { display: 'bungee', body: 'nunito', displayAr: 'reem-kufi-fun', bodyAr: 'tajawal' },
    layout: { hero: 'centered', offer: 'cards', extra: 'list' },
    decor: ['sun', 'stripes'],
  },
];
