import type { DesignInput } from './input';

export const retro: DesignInput[] = [
  {
    slug: 'groovy', profile: 'cafe',
    name: { ar: 'سبعينات', en: 'Groovy' },
    blurb: { ar: 'برتقالي وخردلي وبني وأشرطة قوس قزح، بخط منتفخ من السبعينات.', en: 'Orange, mustard and brown with rainbow stripes and a puffy seventies face.' },
    scheme: 'light',
    palette: { bg: '#F6E7C8', surface: '#FFF4DE', ink: '#3A1C0B', muted: '#7A5A3F', accent: '#E8590C', accent2: '#F2A900', line: '#3A1C0B', onAccent: '#FFF4DE' },
    fonts: { display: 'shrikhand', body: 'work-sans', displayAr: 'lalezar', bodyAr: 'tajawal' },
    layout: { hero: 'split', offer: 'menu' },
    decor: ['seventies', 'stripes', 'divider-wave'],
  },
  {
    slug: 'synth', profile: 'gym',
    name: { ar: 'سينث', en: 'Synth' },
    blurb: { ar: 'شمس الثمانينات المخططة وشبكة نيون وردية وسماوية، كشريط فيديو قديم.', en: 'A striped eighties sun and a pink-and-cyan neon grid, like an old VHS tape.' },
    scheme: 'dark',
    palette: { bg: '#12052B', surface: '#1D0B40', ink: '#FFE9FF', muted: '#C9A7E8', accent: '#FF2E97', accent2: '#00E5FF', line: '#3A1A6B', onAccent: '#12052B' },
    fonts: { display: 'righteous', body: 'rajdhani', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro' },
    layout: { hero: 'centered', contact: 'center' },
    decor: ['synth', 'sun', 'scanlines'],
  },
  {
    slug: 'desktop-98', profile: 'software',
    name: { ar: 'سطح المكتب ٩٨', en: 'Desktop 98' },
    blurb: { ar: 'نوافذ رمادية بأشرطة عنوان زرقاء وأزرار بارزة، كحاسوب التسعينات.', en: 'Grey windows with blue title bars and bevelled buttons, like a nineties PC.' },
    scheme: 'light',
    palette: { bg: '#008080', surface: '#C0C0C0', ink: '#000000', muted: '#303030', accent: '#000080', accent2: '#FFFFFF', line: '#808080', onAccent: '#FFFFFF' },
    fonts: { display: 'vt323', body: 'space-mono', displayAr: 'handjet', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'split', about: 'columns', contact: 'form', footer: 'simple' },
    decor: ['win98'],
  },
  {
    slug: 'memphis', profile: 'agency',
    name: { ar: 'ممفيس', en: 'Memphis' },
    blurb: { ar: 'وردي وتركواز ونقاط وخطوط متعرجة، بروح تصميم ممفيس في الثمانينات.', en: 'Pink, turquoise, dots and squiggles, in the spirit of eighties Memphis design.' },
    scheme: 'light',
    palette: { bg: '#FFF7EC', surface: '#FFFFFF', ink: '#1A1A1A', muted: '#555555', accent: '#FF5E8E', accent2: '#29C4C4', line: '#1A1A1A', onAccent: '#1A1A1A' },
    fonts: { display: 'bungee', body: 'dm-sans', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { hero: 'collage' },
    decor: ['memphis', 'confetti'],
  },
  {
    slug: 'diner', profile: 'restaurant',
    name: { ar: 'داينر', en: 'Diner' },
    blurb: { ar: 'مربعات حمراء وبيضاء وتركواز معدني، كمطعم أمريكي من الخمسينات.', en: 'Red-and-white checks and chrome turquoise, like a fifties American diner.' },
    scheme: 'light',
    palette: { bg: '#FFF8EE', surface: '#FFFFFF', ink: '#1C1C1C', muted: '#5A5A5A', accent: '#D62828', accent2: '#00A6A6', line: '#1C1C1C', onAccent: '#FFFFFF' },
    fonts: { display: 'lilita-one', body: 'nunito', displayAr: 'rakkas', bodyAr: 'tajawal' },
    layout: { hero: 'poster', offer: 'menu' },
    decor: ['diner'],
  },
  {
    slug: 'arcade', profile: 'conference',
    name: { ar: 'أركيد', en: 'Arcade' },
    blurb: { ar: 'خط بكسلي وأخضر نيون وخطوط مسح، كشاشة لعبة أركيد قديمة.', en: 'Pixel type, neon green and scanlines, like an old arcade cabinet screen.' },
    scheme: 'dark',
    palette: { bg: '#0B0B1F', surface: '#15153A', ink: '#F7F7FF', muted: '#A3A3D6', accent: '#39FF14', accent2: '#FF3EA5', line: '#2A2A66', onAccent: '#0B0B1F' },
    fonts: { display: 'press-start-2p', body: 'chakra-petch', displayAr: 'handjet', bodyAr: 'readex-pro' },
    layout: { hero: 'centered', extra: 'cards', schedule: 'table', contact: 'center' },
    decor: ['arcade', 'scanlines'],
  },
];
