import type { DesignInput } from './input';

// Skeuo: real materials built in CSS. `--material` picks the page surface
// (wood, leather, paper, linen, slate or felt); the palette tints it.
export const skeuo: DesignInput[] = [
  {
    slug: 'watchmaker', profile: 'boutique',
    name: { ar: 'ساعاتي', en: 'Watchmaker' },
    blurb: { ar: 'خشب جوز ونحاس لامع وعاجي، ساعاتي في السوق القديم منذ ١٩٦٨.', en: 'Walnut, polished brass and ivory, a watchmaker in the old market since 1968.' },
    scheme: 'dark',
    palette: { bg: '#4A2E1A', surface: '#F3E9D6', ink: '#F6E8CC', muted: '#D9BF94', accent: '#D4A94E', accent2: '#8E2A1E', line: '#2E1C0F', onAccent: '#2E1C0F' },
    fonts: { display: 'playfair-display', body: 'lora', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    css: 'html { --material: var(--wood); }',
  },
  {
    slug: 'chambers-leather', profile: 'law',
    name: { ar: 'مكتب جلدي', en: 'Leather desk' },
    blurb: { ar: 'جلد أخضر داكن بخياطة ذهبية وورق كريمي، مكتب محاماة عريق.', en: 'Dark green leather with gold stitching and cream paper, a long-established law office.' },
    scheme: 'dark',
    palette: { bg: '#1F3A2C', surface: '#F2EAD8', ink: '#F1E7CF', muted: '#C9BE9F', accent: '#CFA44A', accent2: '#7A2B22', line: '#11231A', onAccent: '#1A1206' },
    fonts: { display: 'libre-caslon-display', body: 'libre-caslon-text', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { process: 'steps' },
    css: 'html { --material: var(--leather); }',
  },
  {
    slug: 'trattoria', profile: 'restaurant',
    name: { ar: 'مطعم الحارة', en: 'Trattoria' },
    blurb: { ar: 'مفرش قماشي أحمر وخشب وورق قائمة مطبوع، مطعم عائلي دافئ.', en: 'A red cloth tablecloth, wood and a printed paper menu, a warm family restaurant.' },
    scheme: 'light',
    palette: { bg: '#EFE3CC', surface: '#FFFBF1', ink: '#2E1C12', muted: '#5F4B3C', accent: '#A8322A', accent2: '#3E6B3A', line: '#C9B48F', onAccent: '#FFFFFF' },
    fonts: { display: 'young-serif', body: 'lora', displayAr: 'mirza', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu' },
    css: 'html { --material: var(--paper); }',
  },
  {
    slug: 'coffee-mill', profile: 'cafe',
    name: { ar: 'مطحنة', en: 'Coffee mill' },
    blurb: { ar: 'خشب داكن ونحاس وأكياس خيش، مقهى بمطحنة قديمة تعمل يدويًا.', en: 'Dark wood, copper and burlap sacks, a café with an old hand-turned mill.' },
    scheme: 'dark',
    palette: { bg: '#3B2416', surface: '#EFE2CC', ink: '#F5E6CF', muted: '#D2B691', accent: '#C9803E', accent2: '#6E8B4E', line: '#24150C', onAccent: '#1E0F05' },
    fonts: { display: 'dm-serif-display', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { offer: 'menu', hero: 'split' },
    css: 'html { --material: var(--wood); }',
  },
  {
    slug: 'orchard', profile: 'farm',
    name: { ar: 'بستان', en: 'Orchard' },
    blurb: { ar: 'قماش كتان وخشب صناديق وأخضر زيتي، مزرعة فواكه تبيع بالصندوق.', en: 'Linen cloth, crate wood and olive green, a fruit farm that sells by the crate.' },
    scheme: 'light',
    palette: { bg: '#E8E0CC', surface: '#FBF7EC', ink: '#2A2716', muted: '#5D5839', accent: '#6A7D2E', accent2: '#B4572E', line: '#BFB28E', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'lora', displayAr: 'mirza', bodyAr: 'noto-naskh-arabic' },
    layout: { gallery: 'gallery' },
    css: 'html { --material: var(--linen); }',
  },
  {
    slug: 'blueprint-desk', profile: 'construction',
    name: { ar: 'طاولة المهندس', en: 'Drafting table' },
    blurb: { ar: 'لوح أزرق ومسطرة نحاسية وورق مخطط، شركة مقاولات تعرض أعمالها على طاولة الرسم.', en: 'A blue board, a brass ruler and drawing paper, a contractor showing its work on the drafting table.' },
    scheme: 'dark',
    palette: { bg: '#1D3557', surface: '#F1EFE7', ink: '#EEF3FA', muted: '#B3C2D6', accent: '#E0B54C', accent2: '#E85D3F', line: '#0F1F36', onAccent: '#1A1405' },
    fonts: { display: 'oswald', body: 'source-serif-4', displayAr: 'kufam', bodyAr: 'noto-naskh-arabic', accent: 'ibm-plex-mono' },
    layout: { process: 'steps' },
    css: 'html { --material: var(--slate); }',
  },
  {
    slug: 'workshop', profile: 'signage',
    name: { ar: 'ورشة', en: 'Workshop' },
    blurb: { ar: 'لوح خشبي محفور ولافتات نحاسية بمسامير، ورشة يافطات يدوية.', en: 'A carved wooden board and riveted brass plates, a hand-made sign workshop.' },
    scheme: 'dark',
    palette: { bg: '#43291A', surface: '#EADBC0', ink: '#F7E7CB', muted: '#D4B892', accent: '#D9A441', accent2: '#3F6E6A', line: '#271609', onAccent: '#271609' },
    fonts: { display: 'rye', body: 'lora', displayAr: 'rakkas', bodyAr: 'noto-naskh-arabic' },
    layout: { gallery: 'gallery' },
    css: 'html { --material: var(--wood); }',
  },
  {
    slug: 'leather-album', profile: 'photographer',
    name: { ar: 'ألبوم', en: 'Album' },
    blurb: { ar: 'غلاف جلدي بني وصور مطبوعة بزوايا ذهبية، مصور أعراس وعائلات.', en: 'A brown leather cover and prints held by gold photo corners, a wedding and family photographer.' },
    scheme: 'dark',
    palette: { bg: '#3A2418', surface: '#F4ECDC', ink: '#F4E5CD', muted: '#CDB394', accent: '#C9A14D', accent2: '#8C3B2E', line: '#22140B', onAccent: '#22140B' },
    fonts: { display: 'cormorant-garamond', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { gallery: 'masonry', hero: 'framed' },
    css: 'html { --material: var(--leather); }',
  },
  {
    slug: 'grand-hotel', profile: 'hotel',
    name: { ar: 'الفندق الكبير', en: 'Grand hotel' },
    blurb: { ar: 'خشب ماهوغني ومفاتيح نحاسية وجرس الاستقبال، فندق عريق بروح المئوية.', en: 'Mahogany, brass keys and the reception bell, a grand old hotel with a century\'s spirit.' },
    scheme: 'dark',
    palette: { bg: '#3E1A14', surface: '#F3E7D3', ink: '#F7E6D0', muted: '#D6B49A', accent: '#D8AE5A', accent2: '#2F5A4B', line: '#240D09', onAccent: '#240D09' },
    fonts: { display: 'cinzel', body: 'eb-garamond', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'fullbleed' },
    css: 'html { --material: var(--wood); }',
  },
  {
    slug: 'tailor-felt', profile: 'academy',
    name: { ar: 'خيّاط', en: 'Tailor' },
    blurb: { ar: 'جوخ رمادي وشريط قياس أصفر وأزرار نحاسية، مدرسة لتعليم الخياطة والتفصيل.', en: 'Grey wool felt, a yellow tape measure and brass buttons, a school of tailoring and dressmaking.' },
    scheme: 'dark',
    palette: { bg: '#3A3D40', surface: '#EFEAE0', ink: '#F2EFE8', muted: '#BDB8AE', accent: '#E8C34A', accent2: '#9E3B32', line: '#232527', onAccent: '#1E1A08' },
    fonts: { display: 'playfair-display', body: 'lora', displayAr: 'amiri', bodyAr: 'noto-naskh-arabic' },
    layout: { process: 'steps' },
    css: 'html { --material: var(--felt); }',
  },
  {
    slug: 'invitation-box', profile: 'wedding',
    name: { ar: 'صندوق الدعوة', en: 'Keepsake box' },
    blurb: { ar: 'ورق قطني بحواف ممزقة وختم شمع أحمر وشريط حرير، دعوة زفاف.', en: 'Cotton paper with torn edges, a red wax seal and a silk ribbon, a wedding invitation.' },
    scheme: 'light',
    palette: { bg: '#EFE6D6', surface: '#FFFCF5', ink: '#33231D', muted: '#65544A', accent: '#9E2B2B', accent2: '#B79A62', line: '#D4C3A6', onAccent: '#FFFFFF' },
    fonts: { display: 'great-vibes', body: 'cormorant-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { schedule: 'timeline', hero: 'centered' },
    css: 'html { --material: var(--paper); }',
  },
  {
    slug: 'apothecary', profile: 'perfume',
    name: { ar: 'عطّار', en: 'Apothecary' },
    blurb: { ar: 'رفوف خشبية وزجاج عنبري وملصقات ورقية، عطّار يركّب الزيوت بيده.', en: 'Wooden shelves, amber glass and paper labels, a perfumer who blends oils by hand.' },
    scheme: 'dark',
    palette: { bg: '#2E2016', surface: '#F2E6CF', ink: '#F4E4C8', muted: '#CDB28E', accent: '#D69A3A', accent2: '#5E7A4A', line: '#1A110A', onAccent: '#1A110A' },
    fonts: { display: 'im-fell-english', body: 'eb-garamond', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { offer: 'cards' },
    css: 'html { --material: var(--wood); }',
  },
];
