import type { DesignInput } from './input';

// Soft UI (neumorphism): page and cards share one colour; shapes rise out of
// it or sink into it with two opposite shadows. Mostly pale, two dark.
export const soft: DesignInput[] = [
  {
    slug: 'breath', profile: 'app',
    name: { ar: 'نَفَس', en: 'Breath' },
    blurb: { ar: 'رمادي مزرق وأزرق هادئ، تطبيق تأمل بمقبض دائري ينبض بإيقاع التنفس.', en: 'Bluish grey and a calm blue, a meditation app with a round dial that pulses with the breath.' },
    scheme: 'light',
    palette: { bg: '#E4E9EF', surface: '#E4E9EF', ink: '#2B3646', muted: '#55606F', accent: '#3D6BA8', accent2: '#8FB3DD', line: '#CCD3DC', onAccent: '#FFFFFF' },
    fonts: { display: 'nunito', body: 'nunito', displayAr: 'almarai', bodyAr: 'almarai' },
    layout: { hero: 'device' },
  },
  {
    slug: 'soft-care', profile: 'clinic',
    name: { ar: 'رعاية', en: 'Care' },
    blurb: { ar: 'أخضر نعناعي باهت وأخضر عميق، عيادة هادئة بأزرار وحقول محفورة في السطح.', en: 'Pale mint and a deep green, a quiet clinic with buttons and fields pressed into the surface.' },
    scheme: 'light',
    palette: { bg: '#E3ECE8', surface: '#E3ECE8', ink: '#203630', muted: '#4D615B', accent: '#2E7D66', accent2: '#9CCBB9', line: '#CAD8D2', onAccent: '#FFFFFF' },
    fonts: { display: 'outfit', body: 'outfit', displayAr: 'tajawal', bodyAr: 'tajawal' },
  },
  {
    slug: 'soft-pulse', profile: 'gym',
    name: { ar: 'نبض', en: 'Pulse' },
    blurb: { ar: 'رمادي فحمي ناعم وأخضر ليموني، نادٍ رياضي بأرقام في مقابض كساعة لياقة.', en: 'Soft charcoal and lime, a gym with numbers in dials like a fitness watch.' },
    scheme: 'dark',
    palette: { bg: '#2A2D33', surface: '#2A2D33', ink: '#EEF0F3', muted: '#A7ADB7', accent: '#C6F432', accent2: '#5AC8FA', line: '#363A41', onAccent: '#1A2006' },
    fonts: { display: 'archivo', body: 'inter', displayAr: 'cairo', bodyAr: 'cairo' },
    layout: { stats: 'big', pricing: 'pricing' },
  },
  {
    slug: 'powder-mist', profile: 'perfume',
    name: { ar: 'ضباب', en: 'Mist' },
    blurb: { ar: 'وردي بودرة وبرقوقي، عطور ناعمة كالضباب على سطح من الحرير.', en: 'Powder pink and plum, perfumes as soft as mist on a silk surface.' },
    scheme: 'light',
    palette: { bg: '#F1E6E9', surface: '#F1E6E9', ink: '#3F2532', muted: '#6E5560', accent: '#8C3E63', accent2: '#E2B8C6', line: '#DFCED4', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant-garamond', body: 'dm-sans', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'centered' },
  },
  {
    slug: 'spa-stay', profile: 'hotel',
    name: { ar: 'استجمام', en: 'Unwind' },
    blurb: { ar: 'رملي فاتح وبني دافئ، منتجع صحي هادئ تبرز عناصره من السطح كالحجر المصقول.', en: 'Pale sand and warm brown, a quiet spa resort whose shapes rise from the surface like polished stone.' },
    scheme: 'light',
    palette: { bg: '#ECE6DE', surface: '#ECE6DE', ink: '#352B21', muted: '#625548', accent: '#8A5A34', accent2: '#CDB79B', line: '#D9D0C4', onAccent: '#FFFFFF' },
    fonts: { display: 'fraunces', body: 'outfit', displayAr: 'el-messiri', bodyAr: 'readex-pro' },
    layout: { hero: 'fullbleed' },
  },
  {
    slug: 'soft-counsel', profile: 'law',
    name: { ar: 'مشورة', en: 'Counsel' },
    blurb: { ar: 'رمادي فضي وكحلي، مكتب محاماة هادئ ومتزن بلا زخرفة زائدة.', en: 'Silver grey and navy, a calm, balanced law office with no excess ornament.' },
    scheme: 'light',
    palette: { bg: '#E6E8EC', surface: '#E6E8EC', ink: '#1E2635', muted: '#4F5869', accent: '#24375E', accent2: '#A9B4C8', line: '#CFD3DA', onAccent: '#FFFFFF' },
    fonts: { display: 'libre-baskerville', body: 'source-serif-4', displayAr: 'noto-naskh-arabic', bodyAr: 'noto-naskh-arabic' },
    layout: { process: 'steps', contact: 'split' },
  },
  {
    slug: 'console', profile: 'software',
    name: { ar: 'تحكّم', en: 'Console' },
    blurb: { ar: 'رمادي كحلي داكن وسماوي، منصة سحابية لوحتها مفاتيح ومقابض بارزة.', en: 'Dark navy grey and sky blue, a cloud platform whose panel is made of raised switches and dials.' },
    scheme: 'dark',
    palette: { bg: '#262B36', surface: '#262B36', ink: '#ECEFF5', muted: '#A3ABBB', accent: '#5AB8FF', accent2: '#9C8CFF', line: '#323846', onAccent: '#061423' },
    fonts: { display: 'sora', body: 'inter', displayAr: 'readex-pro', bodyAr: 'ibm-plex-sans-arabic', accent: 'jetbrains-mono' },
    layout: { hero: 'centered', stats: 'big' },
  },
  {
    slug: 'nest', profile: 'realestate',
    name: { ar: 'عُش', en: 'Nest' },
    blurb: { ar: 'عاجي دافئ وزيتوني، شقق سكنية تُعرض في بطاقات ناعمة كأنها مصبوبة من الجبس.', en: 'Warm ivory and olive, homes shown in soft cards that look cast from plaster.' },
    scheme: 'light',
    palette: { bg: '#EDEAE2', surface: '#EDEAE2', ink: '#2C2E24', muted: '#5C5F50', accent: '#5E6B3A', accent2: '#C9C3A6', line: '#D9D5C9', onAccent: '#FFFFFF' },
    fonts: { display: 'manrope', body: 'manrope', displayAr: 'fustat', bodyAr: 'fustat' },
    layout: { offer: 'cards', hero: 'split' },
  },
  {
    slug: 'study', profile: 'academy',
    name: { ar: 'مذاكرة', en: 'Study' },
    blurb: { ar: 'أزرق سماوي باهت وبرتقالي، منصة دروس خصوصية هادئة تساعد على التركيز.', en: 'Pale sky blue and orange, a calm tutoring platform that helps you focus.' },
    scheme: 'light',
    palette: { bg: '#E5ECF3', surface: '#E5ECF3', ink: '#1F2D3D', muted: '#4E5D6E', accent: '#C4561E', accent2: '#9BBBDA', line: '#CDD7E2', onAccent: '#FFFFFF' },
    fonts: { display: 'lexend', body: 'lexend', displayAr: 'zain', bodyAr: 'zain' },
    layout: { pricing: 'pricing' },
  },
  {
    slug: 'latte', profile: 'cafe',
    name: { ar: 'لاتيه', en: 'Latte' },
    blurb: { ar: 'بيج الحليب وبني الإسبريسو، مقهى هادئ تبدو أكوابه وأزراره منحوتة في الخزف.', en: 'Milk beige and espresso brown, a quiet café whose cups and buttons look carved from porcelain.' },
    scheme: 'light',
    palette: { bg: '#EFE7DD', surface: '#EFE7DD', ink: '#36271C', muted: '#665547', accent: '#6F4A30', accent2: '#D7BFA4', line: '#DCD1C4', onAccent: '#FFFFFF' },
    fonts: { display: 'dm-serif-display', body: 'dm-sans', displayAr: 'markazi-text', bodyAr: 'readex-pro' },
    layout: { offer: 'menu' },
  },
  {
    slug: 'lens', profile: 'photographer',
    name: { ar: 'عدسة', en: 'Lens' },
    blurb: { ar: 'رمادي فضي كجسم الكاميرا وأحمر زر التصوير، صور في إطارات محفورة.', en: 'Camera-body silver grey and a shutter-button red, photos in pressed frames.' },
    scheme: 'light',
    palette: { bg: '#E7E7E9', surface: '#E7E7E9', ink: '#202024', muted: '#55555C', accent: '#C2372B', accent2: '#B4B4BB', line: '#D1D1D5', onAccent: '#FFFFFF' },
    fonts: { display: 'space-grotesk', body: 'inter', displayAr: 'kufam', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { gallery: 'gallery', hero: 'framed' },
  },
  {
    slug: 'vows', profile: 'wedding',
    name: { ar: 'عهد', en: 'Vows' },
    blurb: { ar: 'عاجي لؤلؤي ووردي خوخي، دعوة زفاف ناعمة كالورق المنقوش البارز.', en: 'Pearl ivory and peach pink, a wedding invitation as soft as embossed paper.' },
    scheme: 'light',
    palette: { bg: '#F0EAE6', surface: '#F0EAE6', ink: '#3A2B27', muted: '#69584F', accent: '#A34F4A', accent2: '#E6C3B6', line: '#DED4CE', onAccent: '#FFFFFF' },
    fonts: { display: 'cormorant', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'centered', schedule: 'timeline' },
  },
];
