import type { DesignInput } from './input';

export const vintage: DesignInput[] = [
  {
    slug: 'old-souq', profile: 'farm',
    name: { ar: 'السوق القديم', en: 'Old Souq' },
    blurb: { ar: 'ورق معتّق وختم دائري وبطاقات كالتذاكر، كدكان في سوق قديم.', en: 'Aged paper, a round stamp and ticket cards, like a stall in an old market.' },
    scheme: 'light',
    palette: { bg: '#EFE4CD', surface: '#F7EEDC', ink: '#3B2A1E', muted: '#6E5A47', accent: '#A33B20', accent2: '#2F5D50', line: '#CDB894', onAccent: '#F7EEDC' },
    fonts: { display: 'rye', body: 'old-standard-tt', displayAr: 'rakkas', bodyAr: 'amiri' },
    layout: { contact: 'card' },
    decor: ['grain', 'stamp', 'divider-dots'],
  },
  {
    slug: 'press', profile: 'bookshop',
    name: { ar: 'المطبعة', en: 'Press' },
    blurb: { ar: 'أحمر طباعة وأزرق حبر وآلة كاتبة، مكتبة لها مطبعة حروفها: عنوان كالملصق، العناوين في قائمة، والأمسيات في أعمدة.', en: 'Printer\'s red, ink blue and a typewriter, a bookshop with its own letterpress: a poster headline, the titles in a list and the evenings in columns.' },
    scheme: 'light',
    palette: { bg: '#F1EBDD', surface: '#FAF6EC', ink: '#1F1D1A', muted: '#5E5A52', accent: '#C1272D', accent2: '#1F3A5F', line: '#CFC5B0', onAccent: '#FAF6EC' },
    fonts: { display: 'abril-fatface', body: 'old-standard-tt', displayAr: 'katibeh', bodyAr: 'noto-naskh-arabic', accent: 'special-elite' },
    layout: { nav: 'bar', hero: 'poster', offer: 'list', contact: 'split', footer: 'columns' },
    decor: ['grain', 'divider-dots'],
  },
  {
    slug: 'tarab-1948', profile: 'music',
    name: { ar: 'طرب ١٩٤٨', en: 'Tarab 1948' },
    blurb: { ar: 'بني محمّص وخردلي وخط قوطي، مدرسة موسيقى كلافتة مسرح من الأربعينيات: عنوان في إطار، الدروس في قائمة منقّطة، واقتباس واحد في كل مرة.', en: 'Roasted brown, mustard and blackletter, a music school like a 1940s concert-hall sign: a framed headline, lessons in a dotted list and one quote at a time.' },
    scheme: 'dark',
    palette: { bg: '#2B1D14', surface: '#382619', ink: '#F3E6CF', muted: '#C2AD8E', accent: '#D9A441', accent2: '#B5452B', line: '#5A4130', onAccent: '#2B1D14' },
    fonts: { display: 'unifrakturmaguntia', body: 'old-standard-tt', displayAr: 'blaka', bodyAr: 'amiri' },
    layout: { hero: 'framed', offer: 'menu', quotes: 'single' },
    decor: ['grain', 'stamp'],
  },
  {
    slug: 'attar', profile: 'perfume',
    name: { ar: 'العطّار', en: 'Attar' },
    blurb: { ar: 'أخضر صيدلية قديمة وملصقات زجاجات، كرفوف عطّار في سوق القدس.', en: 'Old apothecary green and bottle labels, like a perfumer\'s shelves in a Jerusalem souq.' },
    scheme: 'light',
    palette: { bg: '#E9E2CF', surface: '#F4EFE1', ink: '#2E2A1F', muted: '#6B6350', accent: '#3E5E3B', accent2: '#8B5A2B', line: '#C9BE9E', onAccent: '#F4EFE1' },
    fonts: { display: 'im-fell-english', body: 'old-standard-tt', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { nav: 'bar', hero: 'split' },
    decor: ['grain', 'divider-dots'],
  },
  {
    slug: 'postcard', profile: 'travel',
    name: { ar: 'بطاقة بريدية', en: 'Postcard' },
    blurb: { ar: 'أحمر البريد وأزرق الطيران وأختام، مكتب سفر كبطاقة أُرسلت من بعيد قبل خمسين عامًا.', en: 'Postal red, airmail blue and postmarks, a travel agency like a card sent from abroad fifty years ago.' },
    scheme: 'light',
    palette: { bg: '#F3EBDD', surface: '#FFF9EE', ink: '#263544', muted: '#5E6B76', accent: '#C8553D', accent2: '#3A7CA5', line: '#D8CCB6', onAccent: '#FFF9EE' },
    fonts: { display: 'abril-fatface', body: 'lora', displayAr: 'lalezar', bodyAr: 'noto-naskh-arabic', accent: 'special-elite' },
    layout: { nav: 'bar', hero: 'collage', contact: 'card' },
    decor: ['grain', 'stamp', 'airmail'],
  },
  {
    slug: 'darkroom', profile: 'photographer',
    name: { ar: 'الغرفة المظلمة', en: 'Darkroom' },
    blurb: { ar: 'سيبيا داكنة وحبيبات فيلم وإطار، كمعرض صور في غرفة تحميض.', en: 'Dark sepia, film grain and a frame, like a print show in a developing room.' },
    scheme: 'dark',
    palette: { bg: '#1A1714', surface: '#24201C', ink: '#EDE3D1', muted: '#A69A87', accent: '#C9A66B', accent2: '#8F3B2B', line: '#3A342D', onAccent: '#1A1714' },
    fonts: { display: 'playfair-display-sc', body: 'eb-garamond', displayAr: 'katibeh', bodyAr: 'amiri' },
    layout: { hero: 'framed', gallery: 'masonry', pricing: 'table', quotes: 'single', contact: 'center' },
    decor: ['grain'],
  },
  {
    slug: 'est-1985', profile: 'garage',
    name: { ar: 'منذ ١٩٨٥', en: 'Est. 1985' },
    blurb: { ar: 'ورق معتّق وأحمر دموي وفيروزي باهت، كلافتة كراج عائلي مرسومة باليد: ختم دائري، قائمة أسعار منقّطة، وصور سيارات قديمة.', en: 'Aged paper, oxblood and faded teal, like the hand-painted sign of a family garage: a round stamp, a dotted price list and photos of old cars.' },
    scheme: 'light',
    palette: { bg: '#EFE3C8', surface: '#F6ECD6', ink: '#2C2016', muted: '#6B5640', accent: '#8E2B1E', accent2: '#2F5E54', line: '#D8C6A3', onAccent: '#F6ECD6' },
    fonts: { display: 'abril-fatface', body: 'lora', displayAr: 'jomhuria', bodyAr: 'noto-naskh-arabic' },
    layout: { nav: 'bar', hero: 'split', offer: 'menu', contact: 'split' },
    decor: ['grain', 'stamp', 'divider-dots'],
  },
  {
    slug: 'shoppe', profile: 'sweets',
    name: { ar: 'دكّان الحلو', en: 'Shoppe' },
    blurb: { ar: 'أحمر الحلوى وكراميل على ورق قديم، كواجهة محل سكاكر من الخمسينات: صور متراكبة، بطاقات بأختام، وشهادة زبون واحدة.', en: 'Candy red and caramel on old paper, like a fifties sweet-shop window: stacked photos, stamped cards and one customer\'s word at a time.' },
    scheme: 'light',
    palette: { bg: '#F3E6D3', surface: '#FBF3E6', ink: '#3B1F1A', muted: '#73574A', accent: '#B23A48', accent2: '#E0A43A', line: '#E0CBAE', onAccent: '#FFF8EE' },
    fonts: { display: 'rye', body: 'lora', displayAr: 'lalezar', bodyAr: 'amiri' },
    layout: { hero: 'collage', offer: 'cards', quotes: 'single' },
    decor: ['grain', 'stamp'],
  },
  {
    slug: 'tailor', profile: 'boutique',
    name: { ar: 'خيّاط', en: 'Tailor' },
    blurb: { ar: 'زيتوني داكن ونحاسي وحروف آلة كاتبة، كدفتر طلبات عند خيّاط الحارة: قوائم مرقّمة وجدول مقاسات بخطوط.', en: 'Dark olive, copper and typewriter labels, like the order book of a neighbourhood tailor: numbered lists and a ruled table of fittings.' },
    scheme: 'light',
    palette: { bg: '#E8E0CF', surface: '#F2ECDF', ink: '#262019', muted: '#5F5546', accent: '#3E4A3D', accent2: '#9C6B3C', line: '#D2C5AC', onAccent: '#F5EFE2' },
    fonts: { display: 'old-standard-tt', body: 'old-standard-tt', displayAr: 'katibeh', bodyAr: 'amiri', accent: 'special-elite' },
    layout: { nav: 'bar', hero: 'split', offer: 'list', extra: 'table' },
    decor: ['grain', 'divider-dots'],
  },
  {
    slug: 'copybook', profile: 'academy',
    name: { ar: 'كرّاسة', en: 'Copybook' },
    blurb: { ar: 'حبر أزرق وأحمر تصحيح على ورق مدرسي مصفرّ، كدفتر مدرسة قديم: إطار حول العنوان، أعمدة نصية، وخطوات مرقّمة.', en: 'Blue ink and correcting red on yellowed school paper, like an old exercise book: a framed headline, text in columns and numbered steps.' },
    scheme: 'light',
    palette: { bg: '#ECE4D0', surface: '#F5EFE0', ink: '#1F2A33', muted: '#55606A', accent: '#1F4E79', accent2: '#B5482F', line: '#D5CAB0', onAccent: '#FFFFFF' },
    fonts: { display: 'im-fell-english', body: 'eb-garamond', displayAr: 'mirza', bodyAr: 'noto-naskh-arabic' },
    layout: { hero: 'framed', about: 'columns', offer: 'cards', process: 'steps' },
    decor: ['grain', 'stamp'],
  },
  {
    slug: 'joinery', profile: 'construction',
    name: { ar: 'منجرة', en: 'Joinery' },
    blurb: { ar: 'خشب داكن وعسلي وأخضر طحلبي، كورشة نجارة قديمة: حروف كبيرة مطبوعة، صور الأعمال في شبكة، وخطوات العمل كقائمة.', en: 'Dark wood, honey and moss green, like an old joinery workshop: big printed capitals, work photos in a grid and the steps of the job as a list.' },
    scheme: 'dark',
    palette: { bg: '#2A2118', surface: '#342A20', ink: '#F0E5CF', muted: '#BBA98A', accent: '#D08C3E', accent2: '#8DA36E', line: '#463829', onAccent: '#1F170F' },
    fonts: { display: 'playfair-display-sc', body: 'old-standard-tt', displayAr: 'rakkas', bodyAr: 'amiri' },
    layout: { hero: 'centered', offer: 'cards', process: 'list', gallery: 'gallery' },
    decor: ['grain', 'stamp'],
  },
  {
    slug: 'vernissage', profile: 'gallery',
    name: { ar: 'افتتاح', en: 'Vernissage' },
    blurb: { ar: 'صدئي وأخضر زيتوني على ورق دافئ، كدعوة افتتاح أُرسلت بالبريد: حافة ظرف مخططة، برنامج الشهر على خط زمني، وصور في جدار.', en: 'Rust and olive on warm paper, like an opening invitation sent by post: a striped envelope edge, the month\'s programme on a timeline and a wall of photos.' },
    scheme: 'light',
    palette: { bg: '#F2E8D8', surface: '#FAF4EA', ink: '#3A2A22', muted: '#6F5C4E', accent: '#9B4D3A', accent2: '#6D7F5C', line: '#E0D0B8', onAccent: '#FFFFFF' },
    fonts: { display: 'im-fell-english', body: 'lora', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { nav: 'center', hero: 'framed', schedule: 'timeline', gallery: 'masonry', contact: 'card' },
    decor: ['grain', 'airmail', 'divider-dots'],
  },
];
