import type { DesignInput } from './input';

export const vintage: DesignInput[] = [
  {
    slug: 'old-souq', profile: 'farm',
    name: { ar: 'السوق القديم', en: 'Old Souq' },
    blurb: { ar: 'ورق معتّق وختم دائري وبطاقات كالتذاكر، كدكان في سوق قديم.', en: 'Aged paper, a round stamp and ticket cards, like a stall in an old market.' },
    scheme: 'light',
    palette: { bg: '#EFE4CD', surface: '#F7EEDC', ink: '#3B2A1E', muted: '#6E5A47', accent: '#A33B20', accent2: '#2F5D50', line: '#CDB894', onAccent: '#F7EEDC' },
    fonts: { display: 'rye', body: 'old-standard-tt', displayAr: 'rakkas', bodyAr: 'amiri' },
    layout: { contact: 'card' },
    decor: ['grain', 'stamp', 'divider-dots'],
  },
  {
    slug: 'press', profile: 'signage',
    name: { ar: 'المطبعة', en: 'Press' },
    blurb: { ar: 'أحمر طباعة وأزرق حبر وآلة كاتبة، كملصق خرج للتو من مطبعة الحروف.', en: 'Printer\'s red, ink blue and a typewriter, like a poster fresh off a letterpress.' },
    scheme: 'light',
    palette: { bg: '#F1EBDD', surface: '#FAF6EC', ink: '#1F1D1A', muted: '#5E5A52', accent: '#C1272D', accent2: '#1F3A5F', line: '#CFC5B0', onAccent: '#FAF6EC' },
    fonts: { display: 'abril-fatface', body: 'old-standard-tt', displayAr: 'katibeh', bodyAr: 'noto-naskh-arabic', accent: 'special-elite' },
    layout: { nav: 'bar', hero: 'poster', offer: 'list', contact: 'split', footer: 'columns' },
    decor: ['grain', 'divider-dots'],
  },
  {
    slug: 'qahwa-1948', profile: 'cafe',
    name: { ar: 'قهوة ١٩٤٨', en: 'Qahwa 1948' },
    blurb: { ar: 'بني محمّص وخردلي وخط قوطي، كلافتة مقهى من أربعينيات القرن الماضي.', en: 'Roasted brown, mustard and blackletter, like a 1940s coffee-house sign.' },
    scheme: 'dark',
    palette: { bg: '#2B1D14', surface: '#382619', ink: '#F3E6CF', muted: '#C2AD8E', accent: '#D9A441', accent2: '#B5452B', line: '#5A4130', onAccent: '#2B1D14' },
    fonts: { display: 'unifrakturmaguntia', body: 'old-standard-tt', displayAr: 'blaka', bodyAr: 'amiri' },
    layout: { hero: 'framed', offer: 'menu', quotes: 'single' },
    decor: ['grain', 'stamp'],
  },
  {
    slug: 'attar', profile: 'perfume',
    name: { ar: 'العطّار', en: 'Attar' },
    blurb: { ar: 'أخضر صيدلية قديمة وملصقات زجاجات، كرفوف عطّار في سوق القدس.', en: 'Old apothecary green and bottle labels, like a perfumer\'s shelves in a Jerusalem souq.' },
    scheme: 'light',
    palette: { bg: '#E9E2CF', surface: '#F4EFE1', ink: '#2E2A1F', muted: '#6B6350', accent: '#3E5E3B', accent2: '#8B5A2B', line: '#C9BE9E', onAccent: '#F4EFE1' },
    fonts: { display: 'im-fell-english', body: 'old-standard-tt', displayAr: 'aref-ruqaa', bodyAr: 'amiri' },
    layout: { nav: 'bar', hero: 'split' },
    decor: ['grain', 'divider-dots'],
  },
  {
    slug: 'postcard', profile: 'hotel',
    name: { ar: 'بطاقة بريدية', en: 'Postcard' },
    blurb: { ar: 'أحمر البريد وأزرق الطيران وأختام، كبطاقة أُرسلت من شاطئ قبل خمسين عامًا.', en: 'Postal red, airmail blue and postmarks, like a card sent from the coast fifty years ago.' },
    scheme: 'light',
    palette: { bg: '#F3EBDD', surface: '#FFF9EE', ink: '#263544', muted: '#5E6B76', accent: '#C8553D', accent2: '#3A7CA5', line: '#D8CCB6', onAccent: '#FFF9EE' },
    fonts: { display: 'abril-fatface', body: 'lora', displayAr: 'lalezar', bodyAr: 'noto-naskh-arabic', accent: 'special-elite' },
    layout: { nav: 'bar', hero: 'collage', contact: 'card' },
    decor: ['grain', 'stamp', 'airmail'],
  },
  {
    slug: 'darkroom', profile: 'photographer',
    name: { ar: 'الغرفة المظلمة', en: 'Darkroom' },
    blurb: { ar: 'سيبيا داكنة وحبيبات فيلم وإطار، كمعرض صور في غرفة تحميض.', en: 'Dark sepia, film grain and a frame, like a print show in a developing room.' },
    scheme: 'dark',
    palette: { bg: '#1A1714', surface: '#24201C', ink: '#EDE3D1', muted: '#A69A87', accent: '#C9A66B', accent2: '#8F3B2B', line: '#3A342D', onAccent: '#1A1714' },
    fonts: { display: 'playfair-display-sc', body: 'eb-garamond', displayAr: 'katibeh', bodyAr: 'amiri' },
    layout: { hero: 'framed', gallery: 'masonry', pricing: 'table', quotes: 'single', contact: 'center' },
    decor: ['grain'],
  },
];
