import type { DesignInput } from './input';

// Y2K: chrome headings, glossy candy buttons, bubbles and twinkling stars on
// iridescent pastels, or the same on black.
export const y2k: DesignInput[] = [
  {
    slug: 'glossy', profile: 'boutique',
    name: { ar: 'لامِعة', en: 'Glossy' },
    blurb: { ar: 'وردي ساخن وسماوي وفضي، بوتيك أزياء يعيد مجموعة سنة ٢٠٠٠.', en: 'Hot pink, cyan and silver, a fashion boutique bringing back the 2000 collection.' },
    scheme: 'light',
    palette: { bg: '#FFE3F3', surface: '#FFF6FB', ink: '#3A0D57', muted: '#6E4A82', accent: '#FF3EA5', accent2: '#00D5E8', line: '#F4C6E2', onAccent: '#2A0018' },
    fonts: { display: 'righteous', body: 'nunito', displayAr: 'lemonada', bodyAr: 'baloo-bhaijaan-2' },
    decor: ['sparkles'],
  },
  {
    slug: 'body-mist', profile: 'perfume',
    name: { ar: 'رذاذ', en: 'Body mist' },
    blurb: { ar: 'ليلكي ووردي قزحي، رذاذ عطري بزجاجات كالحلوى وفقاعات لامعة.', en: 'Lilac and iridescent pink, body mists in candy bottles and shiny bubbles.' },
    scheme: 'light',
    palette: { bg: '#F1E6FF', surface: '#FBF7FF', ink: '#3B1260', muted: '#6B4E88', accent: '#B34DFF', accent2: '#FF8BD1', line: '#E0CFF5', onAccent: '#FFFFFF' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'lemonada', bodyAr: 'readex-pro' },
    layout: { hero: 'split' },
    decor: ['sparkles'],
  },
  {
    slug: 'bubblegum', profile: 'sweets',
    name: { ar: 'علكة', en: 'Bubblegum' },
    blurb: { ar: 'وردي علكة وأزرق ثلجي، محل حلوى وآيس كريم بفقاعات وكروم.', en: 'Bubblegum pink and icy blue, a sweet and ice-cream shop with bubbles and chrome.' },
    scheme: 'light',
    palette: { bg: '#FFE8F2', surface: '#FFF8FB', ink: '#4A0F35', muted: '#7A4E68', accent: '#FF4FA0', accent2: '#8FE7FF', line: '#F6CCDE', onAccent: '#2B0016' },
    fonts: { display: 'shrikhand', body: 'nunito', displayAr: 'marhey', bodyAr: 'baloo-bhaijaan-2' },
    layout: { hero: 'collage', offer: 'menu' },
    decor: ['sparkles', 'confetti'],
  },
  {
    slug: 'digicam', profile: 'photographer',
    name: { ar: 'كاميرا رقمية', en: 'Digicam' },
    blurb: { ar: 'فضي ووردي وتاريخ برتقالي في الزاوية، مصورة بأسلوب الكاميرات الرقمية الأولى.', en: 'Silver, pink and an orange date stamp in the corner, a photographer in the style of early digital cameras.' },
    scheme: 'light',
    palette: { bg: '#EEF0F5', surface: '#FFFFFF', ink: '#22163A', muted: '#5C5470', accent: '#E93D9A', accent2: '#FF9A3C', line: '#D9DCE5', onAccent: '#FFFFFF' },
    fonts: { display: 'audiowide', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro', accent: 'vt323' },
    layout: { gallery: 'masonry', hero: 'framed' },
  },
  {
    slug: 'flip-phone', profile: 'app',
    name: { ar: 'هاتف قلاب', en: 'Flip phone' },
    blurb: { ar: 'أسود لامع ووردي وسماوي نيون، تطبيق محادثة يستعيد هواتف ٢٠٠٣.', en: 'Glossy black with neon pink and cyan, a chat app that recalls the phones of 2003.' },
    scheme: 'dark',
    palette: { bg: '#0B0612', surface: '#170D22', ink: '#FCEFFF', muted: '#B9A3C8', accent: '#FF4FD8', accent2: '#3DF5FF', line: '#2A1B3A', onAccent: '#24001E' },
    fonts: { display: 'audiowide', body: 'inter', displayAr: 'lalezar', bodyAr: 'readex-pro' },
    layout: { hero: 'device' },
    decor: ['sparkles', 'glow'],
  },
  {
    slug: 'sweet-sixteen', profile: 'wedding',
    name: { ar: 'حفلة لامعة', en: 'Sparkle party' },
    blurb: { ar: 'وردي وفضي وأزرق سماوي، منظم حفلات خطوبة وتخرج بكرات ديسكو ولمعان.', en: 'Pink, silver and sky blue, an engagement and graduation party planner with disco balls and glitter.' },
    scheme: 'light',
    palette: { bg: '#FDE9F7', surface: '#FFF8FD', ink: '#3E1145', muted: '#714E78', accent: '#D93BB5', accent2: '#A7E4FF', line: '#F2CDE8', onAccent: '#FFFFFF' },
    fonts: { display: 'righteous', body: 'nunito', displayAr: 'lemonada', bodyAr: 'baloo-bhaijaan-2' },
    layout: { schedule: 'timeline' },
    decor: ['sparkles', 'confetti'],
  },
  {
    slug: 'smoothie', profile: 'cafe',
    name: { ar: 'سموذي', en: 'Smoothie' },
    blurb: { ar: 'برتقالي مانجا ووردي وأخضر ليموني، كشك عصائر بأكواب لامعة كالبلاستيك.', en: 'Mango orange, pink and lime, a juice kiosk with cups as glossy as plastic.' },
    scheme: 'light',
    palette: { bg: '#FFF1DE', surface: '#FFFAF2', ink: '#3D1A08', muted: '#735643', accent: '#FF5E8A', accent2: '#B8F23A', line: '#F5DDBF', onAccent: '#2A000C' },
    fonts: { display: 'fredoka', body: 'nunito', displayAr: 'marhey', bodyAr: 'tajawal' },
    layout: { offer: 'menu', hero: 'arch' },
    decor: ['sparkles'],
  },
  {
    slug: 'aerobics', profile: 'gym',
    name: { ar: 'إيروبيك', en: 'Aerobics' },
    blurb: { ar: 'سماوي ووردي نيون وفضي، صالة رقص ولياقة بطاقة الألفية.', en: 'Cyan, neon pink and silver, a dance-fitness studio with millennium energy.' },
    scheme: 'dark',
    palette: { bg: '#0A0F24', surface: '#141A36', ink: '#F0F6FF', muted: '#A8B2D6', accent: '#2EF2FF', accent2: '#FF3EA5', line: '#232B50', onAccent: '#00191C' },
    fonts: { display: 'bungee', body: 'inter', displayAr: 'lalezar', bodyAr: 'cairo' },
    layout: { pricing: 'pricing', hero: 'fullbleed' },
    decor: ['glow'],
  },
  {
    slug: 'chrome-studio', profile: 'agency',
    name: { ar: 'كروم', en: 'Chrome' },
    blurb: { ar: 'فضي سائل وأسود ووردي، استوديو تصميم بعناوين كالمعدن المصهور.', en: 'Liquid silver, black and pink, a design studio with headings like molten metal.' },
    scheme: 'dark',
    palette: { bg: '#0C0C10', surface: '#18181F', ink: '#F4F4F8', muted: '#A8A8B5', accent: '#FF5CC8', accent2: '#C8CCD6', line: '#26262F', onAccent: '#2A0020' },
    fonts: { display: 'unbounded', body: 'inter', displayAr: 'blaka', bodyAr: 'ibm-plex-sans-arabic' },
    layout: { hero: 'type', gallery: 'masonry' },
    decor: ['sparkles'],
  },
  {
    slug: 'mixtape', profile: 'conference',
    name: { ar: 'شريط', en: 'Mixtape' },
    blurb: { ar: 'بنفسجي وأزرق قزحي ووردي، حفلة موسيقى بوب بتذاكر لامعة.', en: 'Purple, iridescent blue and pink, a pop concert with shiny tickets.' },
    scheme: 'light',
    palette: { bg: '#E9E6FF', surface: '#F8F7FF', ink: '#24104F', muted: '#5D4F86', accent: '#7B2FF7', accent2: '#FF6EC7', line: '#D7D1F7', onAccent: '#FFFFFF' },
    fonts: { display: 'righteous', body: 'dm-sans', displayAr: 'lemonada', bodyAr: 'readex-pro' },
    decor: ['sparkles'],
  },
  {
    slug: 'sticker-print', profile: 'signage',
    name: { ar: 'ملصقات', en: 'Stickers' },
    blurb: { ar: 'سماوي ووردي وأصفر هولوغرامي، مطبعة ملصقات ويافطات لامعة.', en: 'Cyan, pink and holographic yellow, a print shop for glossy stickers and signs.' },
    scheme: 'light',
    palette: { bg: '#E3FBFF', surface: '#F7FEFF', ink: '#0F2A44', muted: '#4A6478', accent: '#E83E9C', accent2: '#FFE14D', line: '#C5EEF5', onAccent: '#FFFFFF' },
    fonts: { display: 'bungee', body: 'nunito', displayAr: 'reem-kufi-fun', bodyAr: 'tajawal' },
    layout: { gallery: 'masonry' },
    decor: ['sparkles'],
  },
  {
    slug: 'dial-up', profile: 'academy',
    name: { ar: 'اتصال', en: 'Dial-up' },
    blurb: { ar: 'أزرق ويندوز وأخضر ليموني وفضي، دورات تصميم ويب بروح الإنترنت الأولى.', en: 'Windows blue, lime and silver, web-design courses in the spirit of the early internet.' },
    scheme: 'light',
    palette: { bg: '#E6F0FF', surface: '#F7FAFF', ink: '#0E2350', muted: '#4D5F86', accent: '#1F5FFF', accent2: '#B6FF3B', line: '#CFDDF7', onAccent: '#FFFFFF' },
    fonts: { display: 'audiowide', body: 'dm-sans', displayAr: 'reem-kufi-fun', bodyAr: 'readex-pro', accent: 'vt323' },
    layout: { pricing: 'pricing', process: 'steps' },
    decor: ['sparkles'],
  },
];
